--liquibase formatted sql

--changeset vocab-dev:008-seed-common-words
-- Batch 1: Common BEGINNER verbs
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'run',N'/rʌn/',N'chạy',N'verb',N'I run every morning.',N'Tôi chạy bộ mỗi buổi sáng.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'eat',N'/iːt/',N'ăn',N'verb',N'We eat dinner at 7 PM.',N'Chúng tôi ăn tối lúc 7 giờ.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'drink',N'/drɪŋk/',N'uống',N'verb',N'She drinks coffee every day.',N'Cô ấy uống cà phê mỗi ngày.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'sleep',N'/sliːp/',N'ngủ',N'verb',N'I sleep 8 hours a night.',N'Tôi ngủ 8 tiếng một đêm.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'work',N'/wɜːrk/',N'làm việc',N'verb',N'He works at a hospital.',N'Anh ấy làm việc ở bệnh viện.',N'BEGINNER',N'Work');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'play',N'/pleɪ/',N'chơi',N'verb',N'Children play in the park.',N'Trẻ em chơi trong công viên.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'walk',N'/wɔːk/',N'đi bộ',N'verb',N'I walk to school every day.',N'Tôi đi bộ đến trường mỗi ngày.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'talk',N'/tɔːk/',N'nói chuyện',N'verb',N'They talk on the phone.',N'Họ nói chuyện qua điện thoại.',N'BEGINNER',N'Communication');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'see',N'/siː/',N'nhìn thấy',N'verb',N'I can see the mountains.',N'Tôi có thể nhìn thấy những ngọn núi.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'go',N'/ɡoʊ/',N'đi',N'verb',N'Let''s go to the cinema.',N'Hãy đi xem phim nhé.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'come',N'/kʌm/',N'đến, tới',N'verb',N'Please come here.',N'Xin hãy đến đây.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'think',N'/θɪŋk/',N'nghĩ, suy nghĩ',N'verb',N'I think it is a good idea.',N'Tôi nghĩ đó là một ý tưởng hay.',N'BEGINNER',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'know',N'/noʊ/',N'biết',N'verb',N'Do you know the answer?',N'Bạn có biết câu trả lời không?',N'BEGINNER',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'want',N'/wɒnt/',N'muốn',N'verb',N'I want a cup of tea.',N'Tôi muốn một tách trà.',N'BEGINNER',N'Emotions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'give',N'/ɡɪv/',N'cho, tặng',N'verb',N'Give me your hand.',N'Đưa tay cho tôi.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'get',N'/ɡet/',N'lấy, nhận được',N'verb',N'I need to get some water.',N'Tôi cần lấy một ít nước.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'make',N'/meɪk/',N'làm, tạo ra',N'verb',N'She makes delicious cakes.',N'Cô ấy làm bánh ngon tuyệt.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'take',N'/teɪk/',N'lấy, mang theo',N'verb',N'Take an umbrella with you.',N'Mang theo ô theo.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'love',N'/lʌv/',N'yêu, yêu thích',N'verb',N'I love my family.',N'Tôi yêu gia đình mình.',N'BEGINNER',N'Emotions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'like',N'/laɪk/',N'thích',N'verb',N'I like chocolate ice cream.',N'Tôi thích kem sô-cô-la.',N'BEGINNER',N'Emotions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'need',N'/niːd/',N'cần',N'verb',N'I need help with this task.',N'Tôi cần giúp đỡ với nhiệm vụ này.',N'BEGINNER',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'say',N'/seɪ/',N'nói',N'verb',N'What did she say?',N'Cô ấy nói gì vậy?',N'BEGINNER',N'Communication');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'tell',N'/tel/',N'nói, kể',N'verb',N'Tell me a story.',N'Kể tôi nghe một câu chuyện.',N'BEGINNER',N'Communication');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'ask',N'/ɑːsk/',N'hỏi',N'verb',N'Can I ask you a question?',N'Tôi có thể hỏi bạn một câu không?',N'BEGINNER',N'Communication');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'write',N'/raɪt/',N'viết',N'verb',N'I write in my diary every night.',N'Tôi viết nhật ký mỗi đêm.',N'BEGINNER',N'Education');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'read',N'/riːd/',N'đọc',N'verb',N'I read books in my free time.',N'Tôi đọc sách vào thời gian rảnh.',N'BEGINNER',N'Education');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'buy',N'/baɪ/',N'mua',N'verb',N'I want to buy a new phone.',N'Tôi muốn mua điện thoại mới.',N'BEGINNER',N'Shopping');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'call',N'/kɔːl/',N'gọi điện, gọi',N'verb',N'I will call you tomorrow.',N'Tôi sẽ gọi cho bạn vào ngày mai.',N'BEGINNER',N'Communication');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'help',N'/help/',N'giúp đỡ',N'verb',N'Can you help me?',N'Bạn có thể giúp tôi không?',N'BEGINNER',N'Social');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'use',N'/juːz/',N'sử dụng',N'verb',N'I use my phone every day.',N'Tôi sử dụng điện thoại mỗi ngày.',N'BEGINNER',N'Actions');

-- Common BEGINNER nouns
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'time',N'/taɪm/',N'thời gian',N'noun',N'Time is very precious.',N'Thời gian rất quý giá.',N'BEGINNER',N'Time');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'year',N'/jɪər/',N'năm',N'noun',N'She is ten years old.',N'Cô bé 10 tuổi.',N'BEGINNER',N'Time');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'day',N'/deɪ/',N'ngày',N'noun',N'I work five days a week.',N'Tôi làm việc năm ngày một tuần.',N'BEGINNER',N'Time');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'week',N'/wiːk/',N'tuần',N'noun',N'I exercise three times a week.',N'Tôi tập thể dục ba lần một tuần.',N'BEGINNER',N'Time');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'month',N'/mʌnθ/',N'tháng',N'noun',N'There are twelve months in a year.',N'Có mười hai tháng trong một năm.',N'BEGINNER',N'Time');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'morning',N'/ˈmɔːr.nɪŋ/',N'buổi sáng',N'noun',N'Good morning everyone.',N'Chào buổi sáng mọi người.',N'BEGINNER',N'Time');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'evening',N'/ˈiːv.nɪŋ/',N'buổi tối',N'noun',N'I relax in the evening.',N'Tôi thư giãn vào buổi tối.',N'BEGINNER',N'Time');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'man',N'/mæn/',N'đàn ông, nam giới',N'noun',N'The man is very tall.',N'Người đàn ông rất cao.',N'BEGINNER',N'People');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'woman',N'/ˈwʊm.ən/',N'phụ nữ',N'noun',N'The woman is a doctor.',N'Người phụ nữ là bác sĩ.',N'BEGINNER',N'People');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'child',N'/tʃaɪld/',N'đứa trẻ',N'noun',N'Every child deserves education.',N'Mọi đứa trẻ đều xứng đáng được học.',N'BEGINNER',N'People');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'family',N'/ˈfæm.ɪ.li/',N'gia đình',N'noun',N'My family is very close.',N'Gia đình tôi rất gắn bó.',N'BEGINNER',N'People');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'city',N'/ˈsɪt.i/',N'thành phố',N'noun',N'Ho Chi Minh City is very big.',N'Thành phố Hồ Chí Minh rất lớn.',N'BEGINNER',N'Places');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'country',N'/ˈkʌn.tri/',N'đất nước, quốc gia',N'noun',N'Vietnam is a beautiful country.',N'Việt Nam là một đất nước đẹp.',N'BEGINNER',N'Places');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'food',N'/fuːd/',N'thức ăn',N'noun',N'Vietnamese food is delicious.',N'Thức ăn Việt Nam rất ngon.',N'BEGINNER',N'Food');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'money',N'/ˈmʌn.i/',N'tiền',N'noun',N'I need more money.',N'Tôi cần nhiều tiền hơn.',N'BEGINNER',N'Business');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'job',N'/dʒɒb/',N'công việc, nghề nghiệp',N'noun',N'She has a great job.',N'Cô ấy có công việc tốt.',N'BEGINNER',N'Work');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'home',N'/hoʊm/',N'nhà, quê hương',N'noun',N'There is no place like home.',N'Không nơi nào như ở nhà.',N'BEGINNER',N'Places');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'hand',N'/hænd/',N'bàn tay',N'noun',N'She raised her hand.',N'Cô ấy giơ tay.',N'BEGINNER',N'Body');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'eye',N'/aɪ/',N'mắt',N'noun',N'She has blue eyes.',N'Cô ấy có đôi mắt xanh.',N'BEGINNER',N'Body');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'face',N'/feɪs/',N'khuôn mặt',N'noun',N'She has a kind face.',N'Cô ấy có khuôn mặt nhân hậu.',N'BEGINNER',N'Body');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'heart',N'/hɑːrt/',N'trái tim',N'noun',N'Exercise is good for your heart.',N'Tập thể dục tốt cho tim bạn.',N'BEGINNER',N'Body');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'life',N'/laɪf/',N'cuộc sống, sinh mệnh',N'noun',N'Life is full of surprises.',N'Cuộc sống đầy bất ngờ.',N'BEGINNER',N'General');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'world',N'/wɜːrld/',N'thế giới',N'noun',N'The world is changing fast.',N'Thế giới đang thay đổi nhanh chóng.',N'BEGINNER',N'General');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'door',N'/dɔːr/',N'cánh cửa',N'noun',N'Please close the door.',N'Xin hãy đóng cửa lại.',N'BEGINNER',N'Places');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'car',N'/kɑːr/',N'xe ô tô',N'noun',N'I drive my car to work.',N'Tôi lái xe đi làm.',N'BEGINNER',N'Transport');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'phone',N'/foʊn/',N'điện thoại',N'noun',N'My phone battery is low.',N'Pin điện thoại của tôi yếu rồi.',N'BEGINNER',N'Technology');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'table',N'/ˈteɪ.bəl/',N'cái bàn',N'noun',N'Put the books on the table.',N'Đặt sách lên bàn.',N'BEGINNER',N'Home');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'chair',N'/tʃeər/',N'cái ghế',N'noun',N'Sit on the chair please.',N'Xin hãy ngồi vào ghế.',N'BEGINNER',N'Home');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'bag',N'/bæɡ/',N'cái túi',N'noun',N'I carry a bag to school.',N'Tôi mang túi đến trường.',N'BEGINNER',N'Shopping');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'shirt',N'/ʃɜːrt/',N'áo sơ mi',N'noun',N'He wears a white shirt.',N'Anh ấy mặc áo sơ mi trắng.',N'BEGINNER',N'Clothing');

-- Common BEGINNER adjectives
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'good',N'/ɡʊd/',N'tốt',N'adjective',N'This is a good book.',N'Đây là một cuốn sách hay.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'bad',N'/bæd/',N'xấu, tệ',N'adjective',N'This is a bad idea.',N'Đây là một ý tưởng tệ.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'big',N'/bɪɡ/',N'lớn, to',N'adjective',N'An elephant is very big.',N'Con voi rất to.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'small',N'/smɔːl/',N'nhỏ',N'adjective',N'A mouse is very small.',N'Con chuột rất nhỏ.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'old',N'/oʊld/',N'già, cũ',N'adjective',N'This is an old building.',N'Đây là một tòa nhà cũ.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'young',N'/jʌŋ/',N'trẻ, trẻ tuổi',N'adjective',N'She looks very young.',N'Cô ấy trông rất trẻ.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'hot',N'/hɒt/',N'nóng',N'adjective',N'The weather is very hot today.',N'Thời tiết hôm nay rất nóng.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'cold',N'/koʊld/',N'lạnh',N'adjective',N'It is cold in winter.',N'Mùa đông rất lạnh.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'fast',N'/fæst/',N'nhanh',N'adjective',N'He is a fast runner.',N'Anh ấy là người chạy nhanh.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'slow',N'/sloʊ/',N'chậm',N'adjective',N'The turtle is very slow.',N'Con rùa rất chậm.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'easy',N'/ˈiː.zi/',N'dễ dàng',N'adjective',N'This test is easy.',N'Bài kiểm tra này dễ.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'hard',N'/hɑːrd/',N'khó, cứng',N'adjective',N'The exam is very hard.',N'Kỳ thi rất khó.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'clean',N'/kliːn/',N'sạch sẽ',N'adjective',N'Keep your room clean.',N'Hãy giữ phòng sạch sẽ.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'dirty',N'/ˈdɜːr.ti/',N'bẩn',N'adjective',N'The floor is dirty.',N'Sàn nhà bẩn.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'tall',N'/tɔːl/',N'cao',N'adjective',N'My brother is very tall.',N'Anh trai tôi rất cao.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'short',N'/ʃɔːrt/',N'thấp, ngắn',N'adjective',N'She has short hair.',N'Cô ấy có tóc ngắn.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'rich',N'/rɪtʃ/',N'giàu có',N'adjective',N'He is a very rich man.',N'Ông ấy là người rất giàu.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'poor',N'/pʊər/',N'nghèo',N'adjective',N'They help poor children.',N'Họ giúp đỡ trẻ em nghèo.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'tired',N'/ˈtaɪərd/',N'mệt mỏi',N'adjective',N'I feel tired after work.',N'Tôi cảm thấy mệt sau khi làm việc.',N'BEGINNER',N'Emotions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'hungry',N'/ˈhʌŋ.ɡri/',N'đói',N'adjective',N'I am very hungry.',N'Tôi rất đói.',N'BEGINNER',N'Emotions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'busy',N'/ˈbɪz.i/',N'bận rộn',N'adjective',N'I am busy today.',N'Hôm nay tôi bận.',N'BEGINNER',N'Work');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'free',N'/friː/',N'tự do, miễn phí',N'adjective',N'Are you free tomorrow?',N'Bạn rảnh vào ngày mai không?',N'BEGINNER',N'General');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'true',N'/truː/',N'đúng, thật',N'adjective',N'Is that true?',N'Điều đó có đúng không?',N'BEGINNER',N'General');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'strong',N'/strɒŋ/',N'mạnh mẽ',N'adjective',N'He is very strong.',N'Anh ấy rất mạnh.',N'BEGINNER',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'sick',N'/sɪk/',N'ốm, bệnh',N'adjective',N'I feel sick today.',N'Hôm nay tôi cảm thấy không khỏe.',N'BEGINNER',N'Health');

-- INTERMEDIATE verbs
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'achieve',N'/əˈtʃiːv/',N'đạt được, thành tựu',N'verb',N'She achieved her dream.',N'Cô ấy đã đạt được ước mơ.',N'INTERMEDIATE',N'Achievement');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'allow',N'/əˈlaʊ/',N'cho phép',N'verb',N'Smoking is not allowed here.',N'Không được phép hút thuốc ở đây.',N'INTERMEDIATE',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'apply',N'/əˈplaɪ/',N'nộp đơn, áp dụng',N'verb',N'I want to apply for this job.',N'Tôi muốn nộp đơn xin việc này.',N'INTERMEDIATE',N'Work');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'avoid',N'/əˈvɔɪd/',N'tránh, né tránh',N'verb',N'You should avoid junk food.',N'Bạn nên tránh đồ ăn nhanh.',N'INTERMEDIATE',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'compare',N'/kəmˈpeər/',N'so sánh',N'verb',N'Let''s compare the two options.',N'Hãy so sánh hai lựa chọn.',N'INTERMEDIATE',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'connect',N'/kəˈnekt/',N'kết nối',N'verb',N'Connect your phone to WiFi.',N'Kết nối điện thoại vào WiFi.',N'INTERMEDIATE',N'Technology');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'contain',N'/kənˈteɪn/',N'chứa đựng',N'verb',N'This box contains books.',N'Hộp này chứa sách.',N'INTERMEDIATE',N'General');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'control',N'/kənˈtroʊl/',N'kiểm soát, điều khiển',N'verb',N'You need to control your emotions.',N'Bạn cần kiểm soát cảm xúc.',N'INTERMEDIATE',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'decide',N'/dɪˈsaɪd/',N'quyết định',N'verb',N'I need to decide quickly.',N'Tôi cần quyết định nhanh.',N'INTERMEDIATE',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'describe',N'/dɪˈskraɪb/',N'mô tả',N'verb',N'Describe what you see.',N'Hãy mô tả những gì bạn nhìn thấy.',N'INTERMEDIATE',N'Communication');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'discuss',N'/dɪˈskʌs/',N'thảo luận',N'verb',N'Let''s discuss this problem.',N'Hãy thảo luận về vấn đề này.',N'INTERMEDIATE',N'Communication');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'explain',N'/ɪkˈspleɪn/',N'giải thích',N'verb',N'Can you explain this to me?',N'Bạn có thể giải thích điều này cho tôi không?',N'INTERMEDIATE',N'Communication');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'focus',N'/ˈfoʊ.kəs/',N'tập trung',N'verb',N'Focus on your studies.',N'Tập trung vào việc học.',N'INTERMEDIATE',N'Education');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'improve',N'/ɪmˈpruːv/',N'cải thiện, tiến bộ',N'verb',N'Practice will improve your skills.',N'Luyện tập sẽ cải thiện kỹ năng.',N'INTERMEDIATE',N'Achievement');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'increase',N'/ɪnˈkriːs/',N'tăng, tăng lên',N'verb',N'Prices have increased this year.',N'Giá cả đã tăng năm nay.',N'INTERMEDIATE',N'Business');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'introduce',N'/ˌɪn.trəˈdjuːs/',N'giới thiệu',N'verb',N'Let me introduce my friend.',N'Cho phép tôi giới thiệu người bạn của mình.',N'INTERMEDIATE',N'Social');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'manage',N'/ˈmæn.ɪdʒ/',N'quản lý, xoay sở',N'verb',N'She manages a large team.',N'Cô ấy quản lý một nhóm lớn.',N'INTERMEDIATE',N'Work');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'mention',N'/ˈmen.ʃən/',N'đề cập, nhắc đến',N'verb',N'He mentioned the problem.',N'Anh ấy đề cập đến vấn đề.',N'INTERMEDIATE',N'Communication');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'offer',N'/ˈɒf.ər/',N'đề nghị, cung cấp',N'verb',N'They offered me a job.',N'Họ đề nghị cho tôi một công việc.',N'INTERMEDIATE',N'Social');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'organize',N'/ˈɔːr.ɡə.naɪz/',N'tổ chức, sắp xếp',N'verb',N'She organized the event well.',N'Cô ấy tổ chức sự kiện tốt.',N'INTERMEDIATE',N'Work');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'prepare',N'/prɪˈpeər/',N'chuẩn bị',N'verb',N'Prepare for the exam.',N'Hãy chuẩn bị cho kỳ thi.',N'INTERMEDIATE',N'Education');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'prevent',N'/prɪˈvent/',N'ngăn chặn, phòng ngừa',N'verb',N'Exercise prevents many diseases.',N'Tập thể dục ngăn ngừa nhiều bệnh.',N'INTERMEDIATE',N'Health');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'produce',N'/prəˈdjuːs/',N'sản xuất, tạo ra',N'verb',N'The factory produces 1000 cars a day.',N'Nhà máy sản xuất 1000 xe mỗi ngày.',N'INTERMEDIATE',N'Business');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'protect',N'/prəˈtekt/',N'bảo vệ',N'verb',N'We must protect the environment.',N'Chúng ta phải bảo vệ môi trường.',N'INTERMEDIATE',N'Nature');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'reduce',N'/rɪˈdjuːs/',N'giảm, giảm bớt',N'verb',N'We need to reduce pollution.',N'Chúng ta cần giảm ô nhiễm.',N'INTERMEDIATE',N'Nature');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'support',N'/səˈpɔːrt/',N'hỗ trợ, ủng hộ',N'verb',N'Thank you for your support.',N'Cảm ơn bạn vì sự ủng hộ.',N'INTERMEDIATE',N'Social');

-- INTERMEDIATE nouns
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'ability',N'/əˈbɪl.ɪ.ti/',N'khả năng, năng lực',N'noun',N'She has the ability to lead.',N'Cô ấy có khả năng lãnh đạo.',N'INTERMEDIATE',N'Character');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'advice',N'/ədˈvaɪs/',N'lời khuyên',N'noun',N'Thank you for your advice.',N'Cảm ơn bạn về lời khuyên.',N'INTERMEDIATE',N'Social');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'choice',N'/tʃɔɪs/',N'sự lựa chọn',N'noun',N'You have to make a choice.',N'Bạn phải đưa ra sự lựa chọn.',N'INTERMEDIATE',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'community',N'/kəˈmjuː.nɪ.ti/',N'cộng đồng',N'noun',N'We live in a friendly community.',N'Chúng tôi sống trong một cộng đồng thân thiện.',N'INTERMEDIATE',N'Social');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'culture',N'/ˈkʌl.tʃər/',N'văn hóa',N'noun',N'I love Vietnamese culture.',N'Tôi yêu văn hóa Việt Nam.',N'INTERMEDIATE',N'Social');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'experience',N'/ɪkˈspɪər.i.əns/',N'kinh nghiệm, trải nghiệm',N'noun',N'She has 5 years of experience.',N'Cô ấy có 5 năm kinh nghiệm.',N'INTERMEDIATE',N'Work');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'government',N'/ˈɡʌv.ən.mənt/',N'chính phủ',N'noun',N'The government made a new law.',N'Chính phủ ban hành luật mới.',N'INTERMEDIATE',N'Politics');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'health',N'/helθ/',N'sức khỏe',N'noun',N'Health is the greatest wealth.',N'Sức khỏe là tài sản lớn nhất.',N'INTERMEDIATE',N'Health');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'knowledge',N'/ˈnɒl.ɪdʒ/',N'kiến thức',N'noun',N'Knowledge is power.',N'Kiến thức là sức mạnh.',N'INTERMEDIATE',N'Education');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'language',N'/ˈlæŋ.ɡwɪdʒ/',N'ngôn ngữ',N'noun',N'English is a global language.',N'Tiếng Anh là ngôn ngữ toàn cầu.',N'INTERMEDIATE',N'Language');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'memory',N'/ˈmem.ər.i/',N'trí nhớ, ký ức',N'noun',N'I have a good memory.',N'Tôi có trí nhớ tốt.',N'INTERMEDIATE',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'problem',N'/ˈprɒb.ləm/',N'vấn đề, bài toán',N'noun',N'Every problem has a solution.',N'Mọi vấn đề đều có giải pháp.',N'INTERMEDIATE',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'research',N'/ˈriː.sɜːtʃ/',N'nghiên cứu',N'noun',N'She does cancer research.',N'Cô ấy nghiên cứu ung thư.',N'INTERMEDIATE',N'Education');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'skill',N'/skɪl/',N'kỹ năng',N'noun',N'Communication is an important skill.',N'Giao tiếp là kỹ năng quan trọng.',N'INTERMEDIATE',N'Work');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'society',N'/səˈsaɪ.ɪ.ti/',N'xã hội',N'noun',N'Education is important for society.',N'Giáo dục quan trọng với xã hội.',N'INTERMEDIATE',N'Social');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'technology',N'/tekˈnɒl.ə.dʒi/',N'công nghệ',N'noun',N'Technology changes our lives.',N'Công nghệ thay đổi cuộc sống chúng ta.',N'INTERMEDIATE',N'Technology');

-- INTERMEDIATE adjectives
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'accurate',N'/ˈæk.jʊ.rɪt/',N'chính xác',N'adjective',N'The report must be accurate.',N'Báo cáo phải chính xác.',N'INTERMEDIATE',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'active',N'/ˈæk.tɪv/',N'năng động, tích cực',N'adjective',N'She is very active.',N'Cô ấy rất năng động.',N'INTERMEDIATE',N'Character');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'careful',N'/ˈkeər.fəl/',N'cẩn thận',N'adjective',N'Be careful on the road.',N'Hãy cẩn thận trên đường.',N'INTERMEDIATE',N'Character');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'clever',N'/ˈklev.ər/',N'thông minh, nhanh trí',N'adjective',N'She is a very clever student.',N'Cô ấy là học sinh rất thông minh.',N'INTERMEDIATE',N'Character');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'creative',N'/kriˈeɪ.tɪv/',N'sáng tạo',N'adjective',N'He is a creative designer.',N'Anh ấy là nhà thiết kế sáng tạo.',N'INTERMEDIATE',N'Character');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'curious',N'/ˈkjʊə.ri.əs/',N'tò mò',N'adjective',N'Children are naturally curious.',N'Trẻ em tự nhiên hay tò mò.',N'INTERMEDIATE',N'Character');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'dangerous',N'/ˈdeɪn.dʒər.əs/',N'nguy hiểm',N'adjective',N'Driving too fast is dangerous.',N'Lái xe quá nhanh rất nguy hiểm.',N'INTERMEDIATE',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'efficient',N'/ɪˈfɪʃ.ənt/',N'hiệu quả, hiệu năng',N'adjective',N'We need efficient solutions.',N'Chúng ta cần các giải pháp hiệu quả.',N'INTERMEDIATE',N'Work');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'excellent',N'/ˈek.sɪ.lənt/',N'xuất sắc, tuyệt vời',N'adjective',N'She did an excellent job.',N'Cô ấy đã làm xuất sắc.',N'INTERMEDIATE',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'flexible',N'/ˈflek.sɪ.bəl/',N'linh hoạt, dẻo dai',N'adjective',N'A flexible schedule helps me.',N'Lịch trình linh hoạt giúp ích cho tôi.',N'INTERMEDIATE',N'Work');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'honest',N'/ˈɒn.ɪst/',N'trung thực',N'adjective',N'Always be honest.',N'Hãy luôn trung thực.',N'INTERMEDIATE',N'Character');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'patient',N'/ˈpeɪ.ʃənt/',N'kiên nhẫn',N'adjective',N'Be patient and you will succeed.',N'Hãy kiên nhẫn và bạn sẽ thành công.',N'INTERMEDIATE',N'Character');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'polite',N'/pəˈlaɪt/',N'lịch sự',N'adjective',N'Always be polite to others.',N'Hãy luôn lịch sự với người khác.',N'INTERMEDIATE',N'Character');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'popular',N'/ˈpɒp.jʊ.lər/',N'phổ biến, nổi tiếng',N'adjective',N'This song is very popular.',N'Bài hát này rất phổ biến.',N'INTERMEDIATE',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'successful',N'/səkˈses.fəl/',N'thành công',N'adjective',N'She is a successful businesswoman.',N'Cô ấy là một nữ doanh nhân thành công.',N'INTERMEDIATE',N'Achievement');

-- ADVANCED verbs
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'anticipate',N'/ænˈtɪs.ɪ.peɪt/',N'dự đoán, mong chờ',N'verb',N'We anticipate high demand.',N'Chúng tôi dự đoán nhu cầu cao.',N'ADVANCED',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'contemplate',N'/ˈkɒn.tem.pleɪt/',N'suy ngẫm, chiêm nghiệm',N'verb',N'He contemplated his future.',N'Anh ấy suy ngẫm về tương lai.',N'ADVANCED',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'demonstrate',N'/ˈdem.ən.streɪt/',N'chứng minh, biểu diễn',N'verb',N'She demonstrated great courage.',N'Cô ấy đã chứng minh sự dũng cảm.',N'ADVANCED',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'distinguish',N'/dɪˈstɪŋ.ɡwɪʃ/',N'phân biệt',N'verb',N'Can you distinguish the two?',N'Bạn có thể phân biệt hai cái đó không?',N'ADVANCED',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'eliminate',N'/ɪˈlɪm.ɪ.neɪt/',N'loại bỏ, triệt tiêu',N'verb',N'We need to eliminate waste.',N'Chúng ta cần loại bỏ lãng phí.',N'ADVANCED',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'emphasize',N'/ˈem.fə.saɪz/',N'nhấn mạnh',N'verb',N'I want to emphasize this point.',N'Tôi muốn nhấn mạnh điểm này.',N'ADVANCED',N'Communication');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'establish',N'/ɪˈstæb.lɪʃ/',N'thiết lập, thành lập',N'verb',N'They established a new company.',N'Họ thành lập một công ty mới.',N'ADVANCED',N'Business');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'evaluate',N'/ɪˈvæl.ju.eɪt/',N'đánh giá',N'verb',N'Please evaluate the results.',N'Xin hãy đánh giá kết quả.',N'ADVANCED',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'facilitate',N'/fəˈsɪl.ɪ.teɪt/',N'tạo điều kiện, hỗ trợ',N'verb',N'Technology facilitates communication.',N'Công nghệ tạo điều kiện cho giao tiếp.',N'ADVANCED',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'implement',N'/ˈɪm.plɪ.ment/',N'triển khai, thực hiện',N'verb',N'They implemented a new system.',N'Họ triển khai một hệ thống mới.',N'ADVANCED',N'Work');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'manipulate',N'/məˈnɪp.jʊ.leɪt/',N'thao túng, điều khiển',N'verb',N'He tried to manipulate the data.',N'Anh ấy cố gắng thao túng dữ liệu.',N'ADVANCED',N'Actions');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'perceive',N'/pəˈsiːv/',N'nhận thức, cảm nhận',N'verb',N'How do you perceive this situation?',N'Bạn nhận thức tình huống này như thế nào?',N'ADVANCED',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'preserve',N'/prɪˈzɜːrv/',N'bảo tồn, gìn giữ',N'verb',N'We must preserve our traditions.',N'Chúng ta phải bảo tồn truyền thống.',N'ADVANCED',N'Culture');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'stimulate',N'/ˈstɪm.jʊ.leɪt/',N'kích thích, thúc đẩy',N'verb',N'Music stimulates the brain.',N'Âm nhạc kích thích não bộ.',N'ADVANCED',N'Health');

-- ADVANCED nouns
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'ambition',N'/æmˈbɪʃ.ən/',N'tham vọng, khát vọng',N'noun',N'His ambition is to be a doctor.',N'Tham vọng của anh ấy là trở thành bác sĩ.',N'ADVANCED',N'Character');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'consequence',N'/ˈkɒn.sɪ.kwəns/',N'hậu quả, kết quả',N'noun',N'Think about the consequences.',N'Hãy nghĩ về hậu quả.',N'ADVANCED',N'Thinking');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'controversy',N'/ˈkɒn.trə.vɜː.si/',N'tranh cãi, luận chiến',N'noun',N'This topic causes a lot of controversy.',N'Chủ đề này gây ra nhiều tranh cãi.',N'ADVANCED',N'Social');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'endeavor',N'/ɪnˈdev.ər/',N'nỗ lực, cố gắng',N'noun',N'His every endeavor ends in success.',N'Mọi nỗ lực của anh ấy đều thành công.',N'ADVANCED',N'Achievement');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'hypothesis',N'/haɪˈpɒθ.ɪ.sɪs/',N'giả thuyết',N'noun',N'The scientist tested her hypothesis.',N'Nhà khoa học kiểm tra giả thuyết.',N'ADVANCED',N'Education');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'integrity',N'/ɪnˈteɡ.rɪ.ti/',N'chính trực, liêm chính',N'noun',N'He is known for his integrity.',N'Anh ấy nổi tiếng vì tính chính trực.',N'ADVANCED',N'Character');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'phenomenon',N'/fɪˈnɒm.ɪ.nən/',N'hiện tượng',N'noun',N'Social media is a global phenomenon.',N'Mạng xã hội là hiện tượng toàn cầu.',N'ADVANCED',N'General');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'priority',N'/praɪˈɒr.ɪ.ti/',N'ưu tiên',N'noun',N'Health should be your priority.',N'Sức khỏe nên là ưu tiên của bạn.',N'ADVANCED',N'Thinking');

-- ADVANCED adjectives
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'comprehensive',N'/ˌkɒm.prɪˈhen.sɪv/',N'toàn diện, đầy đủ',N'adjective',N'We need a comprehensive plan.',N'Chúng ta cần một kế hoạch toàn diện.',N'ADVANCED',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'controversial',N'/ˌkɒn.trəˈvɜː.ʃəl/',N'gây tranh cãi',N'adjective',N'It is a controversial decision.',N'Đó là một quyết định gây tranh cãi.',N'ADVANCED',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'excessive',N'/ɪkˈses.ɪv/',N'quá mức, thái quá',N'adjective',N'Excessive stress is harmful.',N'Căng thẳng quá mức thì có hại.',N'ADVANCED',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'explicit',N'/ɪkˈsplɪs.ɪt/',N'rõ ràng, tường minh',N'adjective',N'Give explicit instructions.',N'Hãy đưa ra hướng dẫn rõ ràng.',N'ADVANCED',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'profound',N'/prəˈfaʊnd/',N'sâu sắc, thâm thúy',N'adjective',N'She made a profound statement.',N'Cô ấy đưa ra một tuyên bố sâu sắc.',N'ADVANCED',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'substantial',N'/səbˈstæn.ʃəl/',N'đáng kể, quan trọng',N'adjective',N'There is a substantial difference.',N'Có một sự khác biệt đáng kể.',N'ADVANCED',N'Descriptive');
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, example_sentence, example_translation, difficulty, category) VALUES (N'sustainable',N'/səˈsteɪ.nə.bəl/',N'bền vững',N'adjective',N'We need sustainable energy.',N'Chúng ta cần năng lượng bền vững.',N'ADVANCED',N'Nature');

--rollback DELETE FROM words WHERE word IN ('run','eat','drink','sleep','work','play','walk','talk','see','go','come','think','know','want','give','get','make','take','love','like','need','say','tell','ask','write','read','buy','call','help','use','time','year','day','week','month','morning','evening','man','woman','child','family','city','country','food','money','job','home','hand','eye','face','heart','life','world','door','car','phone','table','chair','bag','shirt','good','bad','big','small','old','young','hot','cold','fast','slow','easy','hard','clean','dirty','tall','short','rich','poor','tired','hungry','busy','free','true','strong','sick','achieve','allow','apply','avoid','compare','connect','contain','control','decide','describe','discuss','explain','focus','improve','increase','introduce','manage','mention','offer','organize','prepare','prevent','produce','protect','reduce','support','ability','advice','choice','community','culture','experience','government','health','knowledge','language','memory','problem','research','skill','society','technology','accurate','active','careful','clever','creative','curious','dangerous','efficient','excellent','flexible','honest','patient','polite','popular','successful','anticipate','contemplate','demonstrate','distinguish','eliminate','emphasize','establish','evaluate','facilitate','implement','manipulate','perceive','preserve','stimulate','ambition','consequence','controversy','endeavor','hypothesis','integrity','phenomenon','priority','comprehensive','controversial','excessive','explicit','profound','substantial','sustainable');
