--liquibase formatted sql

--changeset vocab:009-seed-words-batch2
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.example_sentence, v.example_translation
FROM (VALUES
-- BEGINNER: Home & Daily Life
(N'door', N'/dɔːr/', N'cái cửa', N'noun', N'BEGINNER', N'Please close the door.', N'Làm ơn đóng cửa lại.'),
(N'window', N'/ˈwɪndoʊ/', N'cửa sổ', N'noun', N'BEGINNER', N'Open the window for fresh air.', N'Mở cửa sổ để lấy không khí trong lành.'),
(N'chair', N'/tʃer/', N'cái ghế', N'noun', N'BEGINNER', N'Sit on the chair.', N'Ngồi vào ghế đi.'),
(N'table', N'/ˈteɪbəl/', N'cái bàn', N'noun', N'BEGINNER', N'Put it on the table.', N'Đặt nó lên bàn.'),
(N'bed', N'/bed/', N'cái giường', N'noun', N'BEGINNER', N'I sleep in my bed every night.', N'Tôi ngủ trên giường mỗi đêm.'),
(N'floor', N'/flɔːr/', N'sàn nhà', N'noun', N'BEGINNER', N'The floor is clean.', N'Sàn nhà sạch sẽ.'),
(N'wall', N'/wɔːl/', N'bức tường', N'noun', N'BEGINNER', N'Hang the picture on the wall.', N'Treo bức tranh lên tường.'),
(N'roof', N'/ruːf/', N'mái nhà', N'noun', N'BEGINNER', N'The roof protects us from rain.', N'Mái nhà bảo vệ chúng ta khỏi mưa.'),
(N'kitchen', N'/ˈkɪtʃɪn/', N'nhà bếp', N'noun', N'BEGINNER', N'She cooks in the kitchen.', N'Cô ấy nấu ăn trong bếp.'),
(N'bathroom', N'/ˈbæθruːm/', N'phòng tắm', N'noun', N'BEGINNER', N'The bathroom is upstairs.', N'Phòng tắm ở trên lầu.'),
(N'bedroom', N'/ˈbedruːm/', N'phòng ngủ', N'noun', N'BEGINNER', N'My bedroom is small but cozy.', N'Phòng ngủ của tôi nhỏ nhưng ấm cúng.'),
(N'living room', N'/ˈlɪvɪŋ ruːm/', N'phòng khách', N'noun', N'BEGINNER', N'We watch TV in the living room.', N'Chúng tôi xem TV trong phòng khách.'),
(N'garden', N'/ˈɡɑːrdən/', N'khu vườn', N'noun', N'BEGINNER', N'She grows flowers in the garden.', N'Cô ấy trồng hoa trong vườn.'),
(N'key', N'/kiː/', N'chìa khóa', N'noun', N'BEGINNER', N'Do you have the key?', N'Bạn có chìa khóa không?'),
(N'lamp', N'/læmp/', N'đèn', N'noun', N'BEGINNER', N'Turn on the lamp please.', N'Bật đèn lên đi.'),
(N'mirror', N'/ˈmɪrər/', N'gương', N'noun', N'BEGINNER', N'Look in the mirror.', N'Nhìn vào gương đi.'),
(N'towel', N'/ˈtaʊəl/', N'khăn tắm', N'noun', N'BEGINNER', N'Use this towel to dry off.', N'Dùng khăn này để lau khô người.'),
(N'soap', N'/soʊp/', N'xà phòng', N'noun', N'BEGINNER', N'Wash your hands with soap.', N'Rửa tay với xà phòng.'),
(N'brush', N'/brʌʃ/', N'bàn chải', N'noun', N'BEGINNER', N'Use a brush to clean your teeth.', N'Dùng bàn chải để đánh răng.'),
(N'comb', N'/koʊm/', N'cái lược', N'noun', N'BEGINNER', N'She combed her hair.', N'Cô ấy chải tóc.'),
-- BEGINNER: Food & Drinks
(N'bread', N'/bred/', N'bánh mì', N'noun', N'BEGINNER', N'I eat bread for breakfast.', N'Tôi ăn bánh mì cho bữa sáng.'),
(N'rice', N'/raɪs/', N'cơm / gạo', N'noun', N'BEGINNER', N'Rice is a staple food in Vietnam.', N'Cơm là thức ăn chủ yếu ở Việt Nam.'),
(N'egg', N'/eɡ/', N'quả trứng', N'noun', N'BEGINNER', N'I had two eggs for breakfast.', N'Tôi ăn hai quả trứng cho bữa sáng.'),
(N'meat', N'/miːt/', N'thịt', N'noun', N'BEGINNER', N'Do you like to eat meat?', N'Bạn có thích ăn thịt không?'),
(N'fish', N'/fɪʃ/', N'cá', N'noun', N'BEGINNER', N'We had fish for dinner.', N'Chúng tôi ăn cá cho bữa tối.'),
(N'vegetable', N'/ˈvedʒtəbəl/', N'rau củ', N'noun', N'BEGINNER', N'Eat more vegetables for health.', N'Ăn nhiều rau để tốt cho sức khỏe.'),
(N'fruit', N'/fruːt/', N'trái cây', N'noun', N'BEGINNER', N'Fruit is good for you.', N'Trái cây rất tốt cho bạn.'),
(N'milk', N'/mɪlk/', N'sữa', N'noun', N'BEGINNER', N'Children should drink milk daily.', N'Trẻ em nên uống sữa hàng ngày.'),
(N'juice', N'/dʒuːs/', N'nước ép', N'noun', N'BEGINNER', N'I drink orange juice every morning.', N'Tôi uống nước cam mỗi sáng.'),
(N'sugar', N'/ˈʃʊɡər/', N'đường', N'noun', N'BEGINNER', N'Add some sugar to the tea.', N'Thêm đường vào trà.'),
(N'salt', N'/sɔːlt/', N'muối', N'noun', N'BEGINNER', N'This soup needs more salt.', N'Canh này cần thêm muối.'),
(N'oil', N'/ɔɪl/', N'dầu ăn', N'noun', N'BEGINNER', N'Fry with a little oil.', N'Chiên với một ít dầu.'),
(N'butter', N'/ˈbʌtər/', N'bơ', N'noun', N'BEGINNER', N'Spread butter on the bread.', N'Phết bơ lên bánh mì.'),
(N'cheese', N'/tʃiːz/', N'phô mai', N'noun', N'BEGINNER', N'I like cheese on my pizza.', N'Tôi thích phô mai trên bánh pizza.'),
(N'soup', N'/suːp/', N'súp / canh', N'noun', N'BEGINNER', N'The soup is hot.', N'Canh đang nóng.'),
(N'noodle', N'/ˈnuːdəl/', N'mì / bún', N'noun', N'BEGINNER', N'Noodle soup is popular in Asia.', N'Súp mì rất phổ biến ở châu Á.'),
(N'cake', N'/keɪk/', N'bánh ngọt', N'noun', N'BEGINNER', N'She baked a birthday cake.', N'Cô ấy làm bánh sinh nhật.'),
(N'cookie', N'/ˈkʊki/', N'bánh quy', N'noun', N'BEGINNER', N'The cookies smell amazing.', N'Bánh quy có mùi thơm tuyệt vời.'),
(N'chocolate', N'/ˈtʃɒklət/', N'sô cô la', N'noun', N'BEGINNER', N'She loves chocolate ice cream.', N'Cô ấy thích kem sô cô la.'),
(N'candy', N'/ˈkændi/', N'kẹo', N'noun', N'BEGINNER', N'Don''t eat too much candy.', N'Đừng ăn quá nhiều kẹo.'),
-- BEGINNER: Verbs (Actions)
(N'eat', N'/iːt/', N'ăn', N'verb', N'BEGINNER', N'I eat three meals a day.', N'Tôi ăn ba bữa một ngày.'),
(N'drink', N'/drɪŋk/', N'uống', N'verb', N'BEGINNER', N'Drink plenty of water.', N'Uống nhiều nước vào.'),
(N'sleep', N'/sliːp/', N'ngủ', N'verb', N'BEGINNER', N'I sleep eight hours a night.', N'Tôi ngủ tám tiếng một đêm.'),
(N'wake', N'/weɪk/', N'thức dậy', N'verb', N'BEGINNER', N'I wake up at 6 every morning.', N'Tôi thức dậy lúc 6 giờ mỗi sáng.'),
(N'cook', N'/kʊk/', N'nấu ăn', N'verb', N'BEGINNER', N'My mother cooks delicious food.', N'Mẹ tôi nấu đồ ăn ngon.'),
(N'clean', N'/kliːn/', N'dọn dẹp / sạch', N'verb', N'BEGINNER', N'Clean your room every day.', N'Dọn dẹp phòng mỗi ngày.'),
(N'wash', N'/wɒʃ/', N'rửa / giặt', N'verb', N'BEGINNER', N'Wash your hands before eating.', N'Rửa tay trước khi ăn.'),
(N'open', N'/ˈoʊpən/', N'mở', N'verb', N'BEGINNER', N'Open the box carefully.', N'Mở hộp cẩn thận.'),
(N'close', N'/kloʊz/', N'đóng', N'verb', N'BEGINNER', N'Close the door please.', N'Làm ơn đóng cửa lại.'),
(N'buy', N'/baɪ/', N'mua', N'verb', N'BEGINNER', N'I need to buy some groceries.', N'Tôi cần mua một số đồ ăn.'),
(N'sell', N'/sel/', N'bán', N'verb', N'BEGINNER', N'They sell fresh vegetables here.', N'Họ bán rau tươi ở đây.'),
(N'pay', N'/peɪ/', N'trả tiền', N'verb', N'BEGINNER', N'How much do I need to pay?', N'Tôi cần trả bao nhiêu tiền?'),
(N'carry', N'/ˈkæri/', N'mang / vác', N'verb', N'BEGINNER', N'Can you carry this bag?', N'Bạn có thể mang túi này không?'),
(N'give', N'/ɡɪv/', N'đưa / tặng', N'verb', N'BEGINNER', N'Give me a pen please.', N'Đưa cho tôi cây bút đi.'),
(N'take', N'/teɪk/', N'lấy / cầm', N'verb', N'BEGINNER', N'Take the umbrella with you.', N'Mang ô theo đi.'),
(N'put', N'/pʊt/', N'đặt', N'verb', N'BEGINNER', N'Put the book on the shelf.', N'Đặt quyển sách lên kệ.'),
(N'find', N'/faɪnd/', N'tìm thấy', N'verb', N'BEGINNER', N'I cannot find my keys.', N'Tôi không thể tìm thấy chìa khóa.'),
(N'lose', N'/luːz/', N'mất / thua', N'verb', N'BEGINNER', N'Don''t lose your ticket.', N'Đừng đánh mất vé của bạn.'),
(N'use', N'/juːz/', N'sử dụng', N'verb', N'BEGINNER', N'Use this pen to write.', N'Dùng bút này để viết.'),
(N'need', N'/niːd/', N'cần', N'verb', N'BEGINNER', N'I need help with this.', N'Tôi cần giúp đỡ với điều này.'),
-- BEGINNER: Numbers & Time
(N'minute', N'/ˈmɪnɪt/', N'phút', N'noun', N'BEGINNER', N'Wait a minute please.', N'Chờ một phút.'),
(N'hour', N'/aʊər/', N'giờ', N'noun', N'BEGINNER', N'The meeting lasts one hour.', N'Cuộc họp kéo dài một giờ.'),
(N'week', N'/wiːk/', N'tuần', N'noun', N'BEGINNER', N'See you next week.', N'Hẹn gặp lại tuần sau.'),
(N'month', N'/mʌnθ/', N'tháng', N'noun', N'BEGINNER', N'January is the first month.', N'Tháng Giêng là tháng đầu tiên.'),
(N'year', N'/jɪr/', N'năm', N'noun', N'BEGINNER', N'Happy New Year!', N'Chúc Mừng Năm Mới!'),
(N'morning', N'/ˈmɔːrnɪŋ/', N'buổi sáng', N'noun', N'BEGINNER', N'Good morning everyone!', N'Chào buổi sáng mọi người!'),
(N'afternoon', N'/ˌæftərˈnuːn/', N'buổi chiều', N'noun', N'BEGINNER', N'We meet in the afternoon.', N'Chúng ta gặp nhau vào buổi chiều.'),
(N'evening', N'/ˈiːvnɪŋ/', N'buổi tối (sớm)', N'noun', N'BEGINNER', N'Good evening sir.', N'Chào buổi tối thưa ông.'),
(N'night', N'/naɪt/', N'ban đêm', N'noun', N'BEGINNER', N'The stars shine at night.', N'Các vì sao tỏa sáng vào ban đêm.'),
(N'today', N'/təˈdeɪ/', N'hôm nay', N'adverb', N'BEGINNER', N'What day is today?', N'Hôm nay là thứ mấy?'),
(N'yesterday', N'/ˈjestərdeɪ/', N'hôm qua', N'adverb', N'BEGINNER', N'I was sick yesterday.', N'Hôm qua tôi bị bệnh.'),
(N'tomorrow', N'/təˈmɒroʊ/', N'ngày mai', N'adverb', N'BEGINNER', N'See you tomorrow.', N'Gặp bạn ngày mai.'),
-- BEGINNER: Body Parts
(N'head', N'/hed/', N'đầu', N'noun', N'BEGINNER', N'Shake your head for no.', N'Lắc đầu nghĩa là không.'),
(N'face', N'/feɪs/', N'khuôn mặt', N'noun', N'BEGINNER', N'Wash your face every morning.', N'Rửa mặt mỗi buổi sáng.'),
(N'eye', N'/aɪ/', N'mắt', N'noun', N'BEGINNER', N'Her eyes are blue.', N'Mắt cô ấy màu xanh.'),
(N'nose', N'/noʊz/', N'mũi', N'noun', N'BEGINNER', N'My nose is running.', N'Tôi đang bị chảy mũi.'),
(N'mouth', N'/maʊθ/', N'miệng', N'noun', N'BEGINNER', N'Open your mouth wide.', N'Há miệng ra.'),
(N'ear', N'/ɪr/', N'tai', N'noun', N'BEGINNER', N'He has good ears for music.', N'Anh ấy có tai âm nhạc tốt.'),
(N'tooth', N'/tuːθ/', N'răng', N'noun', N'BEGINNER', N'Brush your teeth twice a day.', N'Đánh răng hai lần mỗi ngày.'),
(N'hair', N'/her/', N'tóc', N'noun', N'BEGINNER', N'She has long black hair.', N'Cô ấy có mái tóc dài đen.'),
(N'neck', N'/nek/', N'cổ', N'noun', N'BEGINNER', N'She wore a necklace around her neck.', N'Cô ấy đeo vòng cổ quanh cổ.'),
(N'shoulder', N'/ˈʃoʊldər/', N'vai', N'noun', N'BEGINNER', N'He tapped her on the shoulder.', N'Anh ấy vỗ vai cô ấy.'),
(N'arm', N'/ɑːrm/', N'cánh tay', N'noun', N'BEGINNER', N'She broke her arm.', N'Cô ấy bị gãy tay.'),
(N'hand', N'/hænd/', N'bàn tay', N'noun', N'BEGINNER', N'Give me your hand.', N'Đưa tay cho tôi.'),
(N'finger', N'/ˈfɪŋɡər/', N'ngón tay', N'noun', N'BEGINNER', N'She hurt her finger.', N'Cô ấy bị đau ngón tay.'),
(N'leg', N'/leɡ/', N'chân (cả cẳng)', N'noun', N'BEGINNER', N'He has strong legs.', N'Anh ấy có đôi chân khỏe.'),
(N'foot', N'/fʊt/', N'bàn chân', N'noun', N'BEGINNER', N'My foot hurts.', N'Bàn chân tôi đau.'),
(N'back', N'/bæk/', N'lưng', N'noun', N'BEGINNER', N'My back is sore from sitting.', N'Lưng tôi đau vì ngồi nhiều.'),
(N'stomach', N'/ˈstʌmək/', N'bụng / dạ dày', N'noun', N'BEGINNER', N'I have a stomachache.', N'Tôi bị đau bụng.'),
(N'heart', N'/hɑːrt/', N'trái tim', N'noun', N'BEGINNER', N'Exercise is good for your heart.', N'Tập thể dục tốt cho tim bạn.'),
(N'blood', N'/blʌd/', N'máu', N'noun', N'BEGINNER', N'Blood carries oxygen through the body.', N'Máu vận chuyển oxy qua cơ thể.'),
(N'skin', N'/skɪn/', N'da', N'noun', N'BEGINNER', N'Protect your skin from the sun.', N'Bảo vệ da khỏi ánh nắng mặt trời.'),
-- BEGINNER: Adjectives
(N'big', N'/bɪɡ/', N'to lớn', N'adjective', N'BEGINNER', N'That is a big dog.', N'Đó là một con chó to.'),
(N'small', N'/smɔːl/', N'nhỏ bé', N'adjective', N'BEGINNER', N'She lives in a small house.', N'Cô ấy sống trong một ngôi nhà nhỏ.'),
(N'long', N'/lɔːŋ/', N'dài', N'adjective', N'BEGINNER', N'The road is very long.', N'Con đường rất dài.'),
(N'short', N'/ʃɔːrt/', N'ngắn / thấp', N'adjective', N'BEGINNER', N'She has short hair.', N'Cô ấy có mái tóc ngắn.'),
(N'tall', N'/tɔːl/', N'cao', N'adjective', N'BEGINNER', N'He is very tall.', N'Anh ấy rất cao.'),
(N'wide', N'/waɪd/', N'rộng', N'adjective', N'BEGINNER', N'The street is wide.', N'Con phố rộng.'),
(N'narrow', N'/ˈnæroʊ/', N'hẹp', N'adjective', N'BEGINNER', N'The path is very narrow.', N'Con đường rất hẹp.'),
(N'heavy', N'/ˈhevi/', N'nặng', N'adjective', N'BEGINNER', N'This bag is too heavy.', N'Cái túi này quá nặng.'),
(N'light', N'/laɪt/', N'nhẹ / sáng', N'adjective', N'BEGINNER', N'The feather is very light.', N'Cái lông rất nhẹ.'),
(N'fast', N'/fæst/', N'nhanh', N'adjective', N'BEGINNER', N'He is a fast runner.', N'Anh ấy chạy rất nhanh.'),
(N'slow', N'/sloʊ/', N'chậm', N'adjective', N'BEGINNER', N'The turtle moves slow.', N'Con rùa di chuyển chậm.'),
(N'hard', N'/hɑːrd/', N'cứng / khó', N'adjective', N'BEGINNER', N'This math problem is hard.', N'Bài toán này khó.'),
(N'soft', N'/sɒft/', N'mềm', N'adjective', N'BEGINNER', N'The pillow is very soft.', N'Cái gối rất mềm.'),
(N'full', N'/fʊl/', N'đầy / no', N'adjective', N'BEGINNER', N'I am full. Thank you.', N'Tôi no rồi. Cảm ơn.'),
(N'empty', N'/ˈempti/', N'trống rỗng', N'adjective', N'BEGINNER', N'The glass is empty.', N'Cái ly trống rỗng.'),
(N'clean', N'/kliːn/', N'sạch', N'adjective', N'BEGINNER', N'The room is clean now.', N'Phòng đã sạch rồi.'),
(N'dirty', N'/ˈdɜːrti/', N'bẩn', N'adjective', N'BEGINNER', N'Your hands are dirty.', N'Tay bạn bẩn đấy.'),
(N'wet', N'/wet/', N'ướt', N'adjective', N'BEGINNER', N'My clothes are wet.', N'Quần áo tôi bị ướt.'),
(N'dry', N'/draɪ/', N'khô', N'adjective', N'BEGINNER', N'Keep the cookies dry.', N'Giữ bánh quy khô ráo.'),
(N'round', N'/raʊnd/', N'tròn', N'adjective', N'BEGINNER', N'The earth is round.', N'Trái đất hình tròn.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('door','window','chair','table','bed','floor','wall','roof','kitchen','bathroom','bedroom','living room','garden','key','lamp','mirror','towel','soap','brush','comb','bread','rice','egg','meat','fish','vegetable','fruit','milk','juice','sugar','salt','oil','butter','cheese','soup','noodle','cake','cookie','chocolate','candy','eat','drink','sleep','wake','cook','clean','wash','open','close','buy','sell','pay','carry','give','take','put','find','lose','use','need','minute','hour','week','month','year','morning','afternoon','evening','night','today','yesterday','tomorrow','head','face','eye','nose','mouth','ear','tooth','hair','neck','shoulder','arm','hand','finger','leg','foot','back','stomach','heart','blood','skin','big','small','long','short','tall','wide','narrow','heavy','light','fast','slow','hard','soft','full','empty','clean','dirty','wet','dry','round');
