--liquibase formatted sql

--changeset vocab:010-seed-words-batch3
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.example_sentence, v.example_translation
FROM (VALUES
-- BEGINNER: School & Learning
(N'school', N'/skuːl/', N'trường học', N'noun', N'BEGINNER', N'She goes to school by bus.', N'Cô ấy đi học bằng xe buýt.'),
(N'class', N'/klæs/', N'lớp học', N'noun', N'BEGINNER', N'The class starts at 8 am.', N'Lớp học bắt đầu lúc 8 giờ sáng.'),
(N'teacher', N'/ˈtiːtʃər/', N'giáo viên', N'noun', N'BEGINNER', N'The teacher is kind and patient.', N'Giáo viên tốt bụng và kiên nhẫn.'),
(N'student', N'/ˈstuːdənt/', N'học sinh', N'noun', N'BEGINNER', N'The student studies hard.', N'Học sinh học chăm chỉ.'),
(N'lesson', N'/ˈlesən/', N'bài học', N'noun', N'BEGINNER', N'The lesson was very interesting.', N'Bài học rất thú vị.'),
(N'homework', N'/ˈhoʊmwɜːrk/', N'bài tập về nhà', N'noun', N'BEGINNER', N'I finished my homework early.', N'Tôi hoàn thành bài tập sớm.'),
(N'exam', N'/ɪɡˈzæm/', N'kỳ thi', N'noun', N'BEGINNER', N'I have an exam tomorrow.', N'Ngày mai tôi có bài thi.'),
(N'answer', N'/ˈænsər/', N'câu trả lời', N'noun', N'BEGINNER', N'What is the answer?', N'Câu trả lời là gì?'),
(N'question', N'/ˈkwestʃən/', N'câu hỏi', N'noun', N'BEGINNER', N'Do you have any questions?', N'Bạn có câu hỏi nào không?'),
(N'pen', N'/pen/', N'cây bút bi', N'noun', N'BEGINNER', N'Write with a pen.', N'Viết bằng bút bi.'),
(N'pencil', N'/ˈpensəl/', N'bút chì', N'noun', N'BEGINNER', N'Draw with a pencil first.', N'Vẽ bằng bút chì trước.'),
(N'book', N'/bʊk/', N'cuốn sách', N'noun', N'BEGINNER', N'I love reading books.', N'Tôi thích đọc sách.'),
(N'notebook', N'/ˈnoʊtbʊk/', N'vở / sổ tay', N'noun', N'BEGINNER', N'Write notes in your notebook.', N'Ghi chú vào vở.'),
(N'ruler', N'/ˈruːlər/', N'thước kẻ', N'noun', N'BEGINNER', N'Use a ruler to draw straight lines.', N'Dùng thước để vẽ đường thẳng.'),
(N'eraser', N'/ɪˈreɪzər/', N'cục tẩy', N'noun', N'BEGINNER', N'Can I borrow your eraser?', N'Tôi có thể mượn cục tẩy của bạn không?'),
(N'bag', N'/bæɡ/', N'cái túi', N'noun', N'BEGINNER', N'Put your books in the bag.', N'Cho sách vào túi.'),
(N'library', N'/ˈlaɪbreri/', N'thư viện', N'noun', N'BEGINNER', N'I study at the library.', N'Tôi học ở thư viện.'),
(N'read', N'/riːd/', N'đọc', N'verb', N'BEGINNER', N'Read the instructions carefully.', N'Đọc hướng dẫn cẩn thận.'),
(N'write', N'/raɪt/', N'viết', N'verb', N'BEGINNER', N'Write your name here.', N'Viết tên bạn vào đây.'),
(N'draw', N'/drɔː/', N'vẽ', N'verb', N'BEGINNER', N'She likes to draw pictures.', N'Cô ấy thích vẽ tranh.'),
-- BEGINNER: Transportation
(N'car', N'/kɑːr/', N'xe ô tô', N'noun', N'BEGINNER', N'He drives a red car.', N'Anh ấy lái xe ô tô màu đỏ.'),
(N'bus', N'/bʌs/', N'xe buýt', N'noun', N'BEGINNER', N'Take the bus to school.', N'Đi xe buýt đến trường.'),
(N'train', N'/treɪn/', N'tàu hỏa', N'noun', N'BEGINNER', N'The train is on time.', N'Tàu hỏa đúng giờ.'),
(N'plane', N'/pleɪn/', N'máy bay', N'noun', N'BEGINNER', N'The plane takes off at noon.', N'Máy bay cất cánh lúc trưa.'),
(N'ship', N'/ʃɪp/', N'tàu thủy', N'noun', N'BEGINNER', N'The ship sails across the ocean.', N'Con tàu đi qua đại dương.'),
(N'bike', N'/baɪk/', N'xe đạp', N'noun', N'BEGINNER', N'I ride my bike to work.', N'Tôi đạp xe đi làm.'),
(N'motorcycle', N'/ˈmoʊtərsaɪkəl/', N'xe máy', N'noun', N'BEGINNER', N'He bought a new motorcycle.', N'Anh ấy mua xe máy mới.'),
(N'road', N'/roʊd/', N'con đường', N'noun', N'BEGINNER', N'The road is wet after the rain.', N'Đường ướt sau mưa.'),
(N'street', N'/striːt/', N'phố / đường phố', N'noun', N'BEGINNER', N'She walks down the street.', N'Cô ấy đi bộ trên phố.'),
(N'bridge', N'/brɪdʒ/', N'cầu', N'noun', N'BEGINNER', N'We crossed the bridge.', N'Chúng tôi đã qua cầu.'),
(N'station', N'/ˈsteɪʃən/', N'nhà ga / bến', N'noun', N'BEGINNER', N'The bus station is nearby.', N'Bến xe buýt ở gần đây.'),
(N'airport', N'/ˈerpɔːrt/', N'sân bay', N'noun', N'BEGINNER', N'We arrived at the airport early.', N'Chúng tôi đến sân bay sớm.'),
(N'taxi', N'/ˈtæksi/', N'xe taxi', N'noun', N'BEGINNER', N'Call a taxi for me please.', N'Gọi taxi cho tôi nhé.'),
(N'drive', N'/draɪv/', N'lái xe', N'verb', N'BEGINNER', N'Can you drive me home?', N'Bạn có thể lái xe đưa tôi về nhà không?'),
(N'ride', N'/raɪd/', N'cưỡi / đi (xe)', N'verb', N'BEGINNER', N'Do you know how to ride a bike?', N'Bạn có biết đi xe đạp không?'),
(N'walk', N'/wɔːk/', N'đi bộ', N'verb', N'BEGINNER', N'Let''s walk to the park.', N'Hãy đi bộ đến công viên.'),
(N'run', N'/rʌn/', N'chạy', N'verb', N'BEGINNER', N'He runs every morning.', N'Anh ấy chạy bộ mỗi sáng.'),
(N'fly', N'/flaɪ/', N'bay', N'verb', N'BEGINNER', N'Birds can fly high.', N'Chim có thể bay cao.'),
(N'arrive', N'/əˈraɪv/', N'đến nơi', N'verb', N'BEGINNER', N'We arrived at the hotel.', N'Chúng tôi đã đến khách sạn.'),
(N'leave', N'/liːv/', N'rời đi', N'verb', N'BEGINNER', N'What time do we leave?', N'Chúng ta rời đi lúc mấy giờ?'),
-- BEGINNER: Nature
(N'sun', N'/sʌn/', N'mặt trời', N'noun', N'BEGINNER', N'The sun is shining brightly.', N'Mặt trời đang tỏa sáng rực rỡ.'),
(N'moon', N'/muːn/', N'mặt trăng', N'noun', N'BEGINNER', N'The full moon is beautiful.', N'Trăng tròn thật đẹp.'),
(N'star', N'/stɑːr/', N'ngôi sao', N'noun', N'BEGINNER', N'Count the stars in the sky.', N'Đếm các ngôi sao trên bầu trời.'),
(N'sky', N'/skaɪ/', N'bầu trời', N'noun', N'BEGINNER', N'The sky is blue today.', N'Bầu trời hôm nay trong xanh.'),
(N'cloud', N'/klaʊd/', N'đám mây', N'noun', N'BEGINNER', N'Dark clouds are coming.', N'Những đám mây đen đang đến.'),
(N'rain', N'/reɪn/', N'mưa', N'noun', N'BEGINNER', N'The rain is heavy today.', N'Hôm nay mưa to.'),
(N'snow', N'/snoʊ/', N'tuyết', N'noun', N'BEGINNER', N'Children love playing in the snow.', N'Trẻ em thích chơi trong tuyết.'),
(N'wind', N'/wɪnd/', N'gió', N'noun', N'BEGINNER', N'The wind is blowing hard.', N'Gió đang thổi mạnh.'),
(N'river', N'/ˈrɪvər/', N'con sông', N'noun', N'BEGINNER', N'The river is long and wide.', N'Con sông dài và rộng.'),
(N'lake', N'/leɪk/', N'cái hồ', N'noun', N'BEGINNER', N'We swam in the lake.', N'Chúng tôi bơi trong hồ.'),
(N'sea', N'/siː/', N'biển', N'noun', N'BEGINNER', N'The sea is calm today.', N'Biển hôm nay yên lặng.'),
(N'mountain', N'/ˈmaʊntən/', N'ngọn núi', N'noun', N'BEGINNER', N'The mountain is covered in snow.', N'Ngọn núi phủ đầy tuyết.'),
(N'forest', N'/ˈfɒrɪst/', N'rừng', N'noun', N'BEGINNER', N'We went hiking in the forest.', N'Chúng tôi đi bộ trong rừng.'),
(N'tree', N'/triː/', N'cái cây', N'noun', N'BEGINNER', N'The tree provides shade.', N'Cây tạo bóng mát.'),
(N'flower', N'/ˈflaʊər/', N'bông hoa', N'noun', N'BEGINNER', N'She picked a beautiful flower.', N'Cô ấy hái một bông hoa đẹp.'),
(N'grass', N'/ɡræs/', N'cỏ', N'noun', N'BEGINNER', N'The grass is green after rain.', N'Cỏ xanh sau mưa.'),
(N'animal', N'/ˈænɪməl/', N'con vật', N'noun', N'BEGINNER', N'What is your favorite animal?', N'Con vật yêu thích của bạn là gì?'),
(N'bird', N'/bɜːrd/', N'con chim', N'noun', N'BEGINNER', N'The bird sings every morning.', N'Con chim hót mỗi buổi sáng.'),
(N'dog', N'/dɒɡ/', N'con chó', N'noun', N'BEGINNER', N'My dog is very friendly.', N'Con chó của tôi rất thân thiện.'),
(N'cat', N'/kæt/', N'con mèo', N'noun', N'BEGINNER', N'The cat is sleeping on the sofa.', N'Con mèo đang ngủ trên sofa.'),
-- INTERMEDIATE: Business & Work
(N'meeting', N'/ˈmiːtɪŋ/', N'cuộc họp', N'noun', N'INTERMEDIATE', N'We have a meeting at 9 am.', N'Chúng tôi có cuộc họp lúc 9 giờ sáng.'),
(N'deadline', N'/ˈdedlaɪn/', N'thời hạn chót', N'noun', N'INTERMEDIATE', N'The deadline is next Friday.', N'Thời hạn chót là thứ Sáu tuần tới.'),
(N'project', N'/ˈprɒdʒekt/', N'dự án', N'noun', N'INTERMEDIATE', N'The project is on schedule.', N'Dự án đang tiến độ.'),
(N'budget', N'/ˈbʌdʒɪt/', N'ngân sách', N'noun', N'INTERMEDIATE', N'We need to stay within budget.', N'Chúng ta cần giữ trong ngân sách.'),
(N'profit', N'/ˈprɒfɪt/', N'lợi nhuận', N'noun', N'INTERMEDIATE', N'The company made a big profit.', N'Công ty kiếm được nhiều lợi nhuận.'),
(N'loss', N'/lɒs/', N'tổn thất / lỗ', N'noun', N'INTERMEDIATE', N'The company suffered a loss.', N'Công ty bị thua lỗ.'),
(N'contract', N'/ˈkɒntrækt/', N'hợp đồng', N'noun', N'INTERMEDIATE', N'Sign the contract before starting.', N'Ký hợp đồng trước khi bắt đầu.'),
(N'client', N'/ˈklaɪənt/', N'khách hàng', N'noun', N'INTERMEDIATE', N'The client is satisfied with our work.', N'Khách hàng hài lòng với công việc của chúng tôi.'),
(N'colleague', N'/ˈkɒliːɡ/', N'đồng nghiệp', N'noun', N'INTERMEDIATE', N'My colleague helped me finish the report.', N'Đồng nghiệp giúp tôi hoàn thành báo cáo.'),
(N'promotion', N'/prəˈmoʊʃən/', N'sự thăng chức', N'noun', N'INTERMEDIATE', N'She received a promotion last month.', N'Cô ấy được thăng chức tháng trước.'),
(N'salary', N'/ˈsæləri/', N'lương tháng', N'noun', N'INTERMEDIATE', N'His salary increased this year.', N'Lương của anh ấy tăng năm nay.'),
(N'bonus', N'/ˈboʊnəs/', N'tiền thưởng', N'noun', N'INTERMEDIATE', N'Employees received a year-end bonus.', N'Nhân viên nhận thưởng cuối năm.'),
(N'interview', N'/ˈɪntərvjuː/', N'phỏng vấn', N'noun', N'INTERMEDIATE', N'I have a job interview tomorrow.', N'Ngày mai tôi có buổi phỏng vấn xin việc.'),
(N'resume', N'/ˈrezjuːmeɪ/', N'hồ sơ xin việc', N'noun', N'INTERMEDIATE', N'Send your resume to HR.', N'Gửi hồ sơ của bạn cho bộ phận nhân sự.'),
(N'experience', N'/ɪkˈspɪəriəns/', N'kinh nghiệm', N'noun', N'INTERMEDIATE', N'She has five years of experience.', N'Cô ấy có năm năm kinh nghiệm.'),
(N'skill', N'/skɪl/', N'kỹ năng', N'noun', N'INTERMEDIATE', N'Communication is an important skill.', N'Giao tiếp là kỹ năng quan trọng.'),
(N'leadership', N'/ˈliːdərʃɪp/', N'khả năng lãnh đạo', N'noun', N'INTERMEDIATE', N'Good leadership inspires others.', N'Khả năng lãnh đạo tốt truyền cảm hứng cho người khác.'),
(N'teamwork', N'/ˈtiːmwɜːrk/', N'làm việc nhóm', N'noun', N'INTERMEDIATE', N'Teamwork makes projects successful.', N'Làm việc nhóm giúp dự án thành công.'),
(N'strategy', N'/ˈstrætədʒi/', N'chiến lược', N'noun', N'INTERMEDIATE', N'We need a better strategy.', N'Chúng ta cần chiến lược tốt hơn.'),
(N'achieve', N'/əˈtʃiːv/', N'đạt được', N'verb', N'INTERMEDIATE', N'Work hard to achieve your goals.', N'Hãy làm việc chăm chỉ để đạt mục tiêu.'),
-- INTERMEDIATE: Technology
(N'software', N'/ˈsɒftweər/', N'phần mềm', N'noun', N'INTERMEDIATE', N'Download the latest software.', N'Tải phần mềm mới nhất.'),
(N'hardware', N'/ˈhɑːrdweər/', N'phần cứng', N'noun', N'INTERMEDIATE', N'The hardware needs an upgrade.', N'Phần cứng cần được nâng cấp.'),
(N'network', N'/ˈnetwɜːrk/', N'mạng lưới', N'noun', N'INTERMEDIATE', N'The network is down today.', N'Mạng hôm nay bị lỗi.'),
(N'password', N'/ˈpæswɜːrd/', N'mật khẩu', N'noun', N'INTERMEDIATE', N'Change your password regularly.', N'Thay đổi mật khẩu thường xuyên.'),
(N'database', N'/ˈdeɪtəbeɪs/', N'cơ sở dữ liệu', N'noun', N'INTERMEDIATE', N'The database stores all records.', N'Cơ sở dữ liệu lưu trữ tất cả hồ sơ.'),
(N'algorithm', N'/ˈælɡərɪðəm/', N'thuật toán', N'noun', N'INTERMEDIATE', N'The algorithm sorts data quickly.', N'Thuật toán sắp xếp dữ liệu nhanh chóng.'),
(N'device', N'/dɪˈvaɪs/', N'thiết bị', N'noun', N'INTERMEDIATE', N'This device is easy to use.', N'Thiết bị này dễ sử dụng.'),
(N'application', N'/ˌæplɪˈkeɪʃən/', N'ứng dụng', N'noun', N'INTERMEDIATE', N'Download the application on your phone.', N'Tải ứng dụng trên điện thoại của bạn.'),
(N'update', N'/ˈʌpdeɪt/', N'cập nhật', N'verb', N'INTERMEDIATE', N'Please update your software.', N'Hãy cập nhật phần mềm của bạn.'),
(N'connect', N'/kəˈnekt/', N'kết nối', N'verb', N'INTERMEDIATE', N'Connect to the WiFi network.', N'Kết nối vào mạng WiFi.'),
(N'upload', N'/ˈʌploʊd/', N'tải lên', N'verb', N'INTERMEDIATE', N'Upload the photos to the cloud.', N'Tải ảnh lên đám mây.'),
(N'download', N'/ˈdaʊnloʊd/', N'tải xuống', N'verb', N'INTERMEDIATE', N'Download the file to your computer.', N'Tải file về máy tính của bạn.'),
(N'install', N'/ɪnˈstɔːl/', N'cài đặt', N'verb', N'INTERMEDIATE', N'Install the program before use.', N'Cài đặt chương trình trước khi sử dụng.'),
(N'digital', N'/ˈdɪdʒɪtəl/', N'kỹ thuật số', N'adjective', N'INTERMEDIATE', N'We live in a digital world.', N'Chúng ta sống trong thế giới kỹ thuật số.'),
(N'virtual', N'/ˈvɜːrtʃuəl/', N'ảo / trực tuyến', N'adjective', N'INTERMEDIATE', N'Virtual meetings are common now.', N'Họp trực tuyến rất phổ biến hiện nay.'),
(N'wireless', N'/ˈwaɪərləs/', N'không dây', N'adjective', N'INTERMEDIATE', N'The wireless connection is fast.', N'Kết nối không dây nhanh.'),
(N'efficient', N'/ɪˈfɪʃənt/', N'hiệu quả', N'adjective', N'INTERMEDIATE', N'The new system is more efficient.', N'Hệ thống mới hiệu quả hơn.'),
(N'compatible', N'/kəmˈpætəbəl/', N'tương thích', N'adjective', N'INTERMEDIATE', N'Is this compatible with Windows?', N'Cái này có tương thích với Windows không?'),
-- INTERMEDIATE: Health
(N'medicine', N'/ˈmedɪsən/', N'thuốc', N'noun', N'INTERMEDIATE', N'Take this medicine after meals.', N'Uống thuốc này sau bữa ăn.'),
(N'hospital', N'/ˈhɒspɪtəl/', N'bệnh viện', N'noun', N'INTERMEDIATE', N'She was taken to the hospital.', N'Cô ấy được đưa vào bệnh viện.'),
(N'doctor', N'/ˈdɒktər/', N'bác sĩ', N'noun', N'INTERMEDIATE', N'The doctor will see you now.', N'Bác sĩ sẽ khám cho bạn bây giờ.'),
(N'nurse', N'/nɜːrs/', N'y tá', N'noun', N'INTERMEDIATE', N'The nurse is very helpful.', N'Y tá rất nhiệt tình.'),
(N'patient', N'/ˈpeɪʃənt/', N'bệnh nhân / kiên nhẫn', N'noun', N'INTERMEDIATE', N'The patient needs rest.', N'Bệnh nhân cần nghỉ ngơi.'),
(N'symptom', N'/ˈsɪmptəm/', N'triệu chứng', N'noun', N'INTERMEDIATE', N'Describe your symptoms please.', N'Mô tả triệu chứng của bạn đi.'),
(N'treatment', N'/ˈtriːtmənt/', N'phương pháp điều trị', N'noun', N'INTERMEDIATE', N'The treatment is working well.', N'Điều trị đang hiệu quả.'),
(N'surgery', N'/ˈsɜːrdʒəri/', N'phẫu thuật', N'noun', N'INTERMEDIATE', N'The surgery was successful.', N'Cuộc phẫu thuật thành công.'),
(N'prescription', N'/prɪˈskrɪpʃən/', N'đơn thuốc', N'noun', N'INTERMEDIATE', N'Take this prescription to the pharmacy.', N'Mang đơn thuốc này đến nhà thuốc.'),
(N'allergy', N'/ˈælədʒi/', N'dị ứng', N'noun', N'INTERMEDIATE', N'She has a peanut allergy.', N'Cô ấy bị dị ứng đậu phộng.'),
(N'fever', N'/ˈfiːvər/', N'sốt', N'noun', N'INTERMEDIATE', N'He has a high fever.', N'Anh ấy sốt cao.'),
(N'headache', N'/ˈhedeɪk/', N'đau đầu', N'noun', N'INTERMEDIATE', N'I have a terrible headache.', N'Tôi bị đau đầu khủng khiếp.'),
(N'infection', N'/ɪnˈfekʃən/', N'nhiễm trùng', N'noun', N'INTERMEDIATE', N'The wound has an infection.', N'Vết thương bị nhiễm trùng.'),
(N'prevent', N'/prɪˈvent/', N'ngăn chặn', N'verb', N'INTERMEDIATE', N'Exercise helps prevent disease.', N'Tập thể dục giúp ngăn ngừa bệnh tật.'),
(N'diagnose', N'/ˈdaɪəɡnoʊz/', N'chẩn đoán', N'verb', N'INTERMEDIATE', N'The doctor diagnosed a cold.', N'Bác sĩ chẩn đoán là cảm lạnh.'),
(N'recover', N'/rɪˈkʌvər/', N'hồi phục', N'verb', N'INTERMEDIATE', N'She recovered quickly from the flu.', N'Cô ấy hồi phục nhanh sau cúm.'),
(N'healthy', N'/ˈhelθi/', N'khỏe mạnh', N'adjective', N'INTERMEDIATE', N'Eat healthy food every day.', N'Ăn thức ăn lành mạnh mỗi ngày.'),
(N'painful', N'/ˈpeɪnfəl/', N'đau đớn', N'adjective', N'INTERMEDIATE', N'The injury was very painful.', N'Chấn thương rất đau.'),
(N'chronic', N'/ˈkrɒnɪk/', N'mãn tính', N'adjective', N'INTERMEDIATE', N'She has a chronic back problem.', N'Cô ấy bị đau lưng mãn tính.'),
(N'immune', N'/ɪˈmjuːn/', N'miễn dịch', N'adjective', N'INTERMEDIATE', N'A strong immune system fights disease.', N'Hệ miễn dịch mạnh chống lại bệnh tật.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('school','class','teacher','student','lesson','homework','exam','answer','question','pen','pencil','book','notebook','ruler','eraser','bag','library','read','write','draw','car','bus','train','plane','ship','bike','motorcycle','road','street','bridge','station','airport','taxi','drive','ride','walk','run','fly','arrive','leave','sun','moon','star','sky','cloud','rain','snow','wind','river','lake','sea','mountain','forest','tree','flower','grass','animal','bird','dog','cat','meeting','deadline','project','budget','profit','loss','contract','client','colleague','promotion','salary','bonus','interview','resume','experience','skill','leadership','teamwork','strategy','achieve','software','hardware','network','password','database','algorithm','device','application','update','connect','upload','download','install','digital','virtual','wireless','efficient','compatible','medicine','hospital','doctor','nurse','patient','symptom','treatment','surgery','prescription','allergy','fever','headache','infection','prevent','diagnose','recover','healthy','painful','chronic','immune');
