--liquibase formatted sql

--changeset vocab:012-seed-words-batch5
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.example_sentence, v.example_translation
FROM (VALUES
-- BEGINNER: Colors & Shapes
(N'color', N'/ˈkʌlər/', N'màu sắc', N'noun', N'BEGINNER', N'What is your favorite color?', N'Màu sắc yêu thích của bạn là gì?'),
(N'red', N'/red/', N'màu đỏ', N'adjective', N'BEGINNER', N'She wore a red dress.', N'Cô ấy mặc váy đỏ.'),
(N'blue', N'/bluː/', N'màu xanh dương', N'adjective', N'BEGINNER', N'The sky is blue.', N'Bầu trời màu xanh.'),
(N'green', N'/ɡriːn/', N'màu xanh lá', N'adjective', N'BEGINNER', N'The leaves are green.', N'Lá cây màu xanh.'),
(N'yellow', N'/ˈjeloʊ/', N'màu vàng', N'adjective', N'BEGINNER', N'The sun looks yellow.', N'Mặt trời trông màu vàng.'),
(N'white', N'/waɪt/', N'màu trắng', N'adjective', N'BEGINNER', N'Snow is white.', N'Tuyết màu trắng.'),
(N'black', N'/blæk/', N'màu đen', N'adjective', N'BEGINNER', N'The cat is black.', N'Con mèo màu đen.'),
(N'orange', N'/ˈɒrɪndʒ/', N'màu cam', N'adjective', N'BEGINNER', N'She painted the wall orange.', N'Cô ấy sơn tường màu cam.'),
(N'purple', N'/ˈpɜːrpəl/', N'màu tím', N'adjective', N'BEGINNER', N'She likes purple flowers.', N'Cô ấy thích hoa tím.'),
(N'pink', N'/pɪŋk/', N'màu hồng', N'adjective', N'BEGINNER', N'The baby wore a pink hat.', N'Em bé đội mũ hồng.'),
(N'brown', N'/braʊn/', N'màu nâu', N'adjective', N'BEGINNER', N'He has brown eyes.', N'Anh ấy có đôi mắt nâu.'),
(N'gray', N'/ɡreɪ/', N'màu xám', N'adjective', N'BEGINNER', N'The sky looks gray today.', N'Bầu trời hôm nay trông xám xịt.'),
(N'circle', N'/ˈsɜːrkəl/', N'hình tròn', N'noun', N'BEGINNER', N'Draw a circle on the paper.', N'Vẽ hình tròn trên giấy.'),
(N'square', N'/skwer/', N'hình vuông', N'noun', N'BEGINNER', N'The table is square.', N'Cái bàn hình vuông.'),
(N'triangle', N'/ˈtraɪæŋɡəl/', N'hình tam giác', N'noun', N'BEGINNER', N'A triangle has three sides.', N'Tam giác có ba cạnh.'),
(N'rectangle', N'/ˈrektæŋɡəl/', N'hình chữ nhật', N'noun', N'BEGINNER', N'The door is a rectangle.', N'Cái cửa hình chữ nhật.'),
-- BEGINNER: Feelings & Basic Expressions
(N'happy', N'/ˈhæpi/', N'vui / hạnh phúc', N'adjective', N'BEGINNER', N'She is very happy today.', N'Cô ấy rất vui hôm nay.'),
(N'sad', N'/sæd/', N'buồn', N'adjective', N'BEGINNER', N'He looks sad.', N'Anh ấy trông có vẻ buồn.'),
(N'angry', N'/ˈæŋɡri/', N'tức giận', N'adjective', N'BEGINNER', N'Don''t get angry easily.', N'Đừng dễ tức giận.'),
(N'tired', N'/ˈtaɪərd/', N'mệt mỏi', N'adjective', N'BEGINNER', N'I feel tired after work.', N'Tôi cảm thấy mệt sau giờ làm.'),
(N'hungry', N'/ˈhʌŋɡri/', N'đói', N'adjective', N'BEGINNER', N'I am hungry, let''s eat.', N'Tôi đói rồi, ăn thôi.'),
(N'thirsty', N'/ˈθɜːrsti/', N'khát nước', N'adjective', N'BEGINNER', N'I''m thirsty. Give me water.', N'Tôi khát. Cho tôi nước.'),
(N'scared', N'/skerd/', N'sợ hãi', N'adjective', N'BEGINNER', N'She was scared of the dark.', N'Cô ấy sợ bóng tối.'),
(N'excited', N'/ɪkˈsaɪtɪd/', N'hào hứng / phấn khích', N'adjective', N'BEGINNER', N'The children are excited about the trip.', N'Bọn trẻ rất hào hứng về chuyến đi.'),
(N'bored', N'/bɔːrd/', N'chán', N'adjective', N'BEGINNER', N'I feel bored at home.', N'Tôi cảm thấy chán ở nhà.'),
(N'surprised', N'/sərˈpraɪzd/', N'ngạc nhiên', N'adjective', N'BEGINNER', N'I was surprised by the news.', N'Tôi ngạc nhiên vì tin tức đó.'),
-- BEGINNER: Clothes
(N'shirt', N'/ʃɜːrt/', N'áo sơ mi', N'noun', N'BEGINNER', N'He wore a white shirt.', N'Anh ấy mặc áo sơ mi trắng.'),
(N'pants', N'/pænts/', N'quần dài', N'noun', N'BEGINNER', N'Buy new pants for the event.', N'Mua quần dài mới cho sự kiện.'),
(N'dress', N'/dres/', N'váy đầm', N'noun', N'BEGINNER', N'She wore a beautiful dress.', N'Cô ấy mặc váy đẹp.'),
(N'skirt', N'/skɜːrt/', N'váy ngắn', N'noun', N'BEGINNER', N'She wore a blue skirt.', N'Cô ấy mặc váy xanh.'),
(N'jacket', N'/ˈdʒækɪt/', N'áo khoác', N'noun', N'BEGINNER', N'Wear a jacket in cold weather.', N'Mặc áo khoác khi trời lạnh.'),
(N'shoes', N'/ʃuːz/', N'đôi giày', N'noun', N'BEGINNER', N'Tie your shoes tightly.', N'Buộc dây giày chặt vào.'),
(N'socks', N'/sɒks/', N'tất / vớ', N'noun', N'BEGINNER', N'Put on clean socks.', N'Mang tất sạch vào.'),
(N'hat', N'/hæt/', N'cái mũ', N'noun', N'BEGINNER', N'Wear a hat in the sun.', N'Đội mũ khi ra nắng.'),
(N'gloves', N'/ɡlʌvz/', N'găng tay', N'noun', N'BEGINNER', N'Wear gloves in winter.', N'Mang găng tay vào mùa đông.'),
(N'scarf', N'/skɑːrf/', N'khăn quàng cổ', N'noun', N'BEGINNER', N'Wrap the scarf around your neck.', N'Quàng khăn quanh cổ.'),
(N'glasses', N'/ˈɡlæsɪz/', N'kính mắt', N'noun', N'BEGINNER', N'He wears glasses to read.', N'Anh ấy đeo kính để đọc.'),
(N'wear', N'/wer/', N'mặc / đeo', N'verb', N'BEGINNER', N'What should I wear today?', N'Hôm nay tôi nên mặc gì?'),
-- INTERMEDIATE: Society & Culture
(N'community', N'/kəˈmjuːnɪti/', N'cộng đồng', N'noun', N'INTERMEDIATE', N'Help your local community.', N'Giúp đỡ cộng đồng địa phương của bạn.'),
(N'society', N'/səˈsaɪəti/', N'xã hội', N'noun', N'INTERMEDIATE', N'Education benefits society.', N'Giáo dục có lợi cho xã hội.'),
(N'population', N'/ˌpɒpjʊˈleɪʃən/', N'dân số', N'noun', N'INTERMEDIATE', N'The city has a large population.', N'Thành phố có dân số đông.'),
(N'generation', N'/ˌdʒenəˈreɪʃən/', N'thế hệ', N'noun', N'INTERMEDIATE', N'The next generation will face challenges.', N'Thế hệ tiếp theo sẽ đối mặt với thách thức.'),
(N'diversity', N'/daɪˈvɜːrsɪti/', N'sự đa dạng', N'noun', N'INTERMEDIATE', N'Diversity makes teams stronger.', N'Sự đa dạng làm cho đội nhóm mạnh hơn.'),
(N'equality', N'/ɪˈkwɒlɪti/', N'sự bình đẳng', N'noun', N'INTERMEDIATE', N'Fight for equality and justice.', N'Đấu tranh cho bình đẳng và công lý.'),
(N'freedom', N'/ˈfriːdəm/', N'sự tự do', N'noun', N'INTERMEDIATE', N'Freedom of speech is important.', N'Tự do ngôn luận rất quan trọng.'),
(N'democracy', N'/dɪˈmɒkrəsi/', N'nền dân chủ', N'noun', N'INTERMEDIATE', N'Democracy gives power to the people.', N'Dân chủ trao quyền cho người dân.'),
(N'government', N'/ˈɡʌvərnmənt/', N'chính phủ', N'noun', N'INTERMEDIATE', N'The government passed a new law.', N'Chính phủ đã thông qua luật mới.'),
(N'policy', N'/ˈpɒlɪsi/', N'chính sách', N'noun', N'INTERMEDIATE', N'Review the company''s policy.', N'Xem lại chính sách của công ty.'),
(N'election', N'/ɪˈlekʃən/', N'cuộc bầu cử', N'noun', N'INTERMEDIATE', N'The election is in November.', N'Cuộc bầu cử vào tháng Mười Một.'),
(N'campaign', N'/kæmˈpeɪn/', N'chiến dịch', N'noun', N'INTERMEDIATE', N'He ran a successful campaign.', N'Anh ấy thực hiện chiến dịch thành công.'),
(N'protest', N'/ˈproʊtest/', N'cuộc biểu tình', N'noun', N'INTERMEDIATE', N'The protest was peaceful.', N'Cuộc biểu tình diễn ra hòa bình.'),
(N'debate', N'/dɪˈbeɪt/', N'cuộc tranh luận', N'noun', N'INTERMEDIATE', N'The debate lasted for hours.', N'Cuộc tranh luận kéo dài nhiều giờ.'),
(N'influence', N'/ˈɪnfluəns/', N'ảnh hưởng', N'noun', N'INTERMEDIATE', N'Social media has a great influence.', N'Mạng xã hội có ảnh hưởng lớn.'),
(N'impact', N'/ˈɪmpækt/', N'tác động', N'noun', N'INTERMEDIATE', N'The decision had a huge impact.', N'Quyết định đó có tác động lớn.'),
(N'challenge', N'/ˈtʃælɪndʒ/', N'thách thức', N'noun', N'INTERMEDIATE', N'Every challenge is an opportunity.', N'Mỗi thách thức là một cơ hội.'),
(N'opportunity', N'/ˌɒpəˈtjuːnɪti/', N'cơ hội', N'noun', N'INTERMEDIATE', N'Seize every opportunity you get.', N'Nắm bắt mọi cơ hội bạn có.'),
(N'consequence', N'/ˈkɒnsɪkwəns/', N'hậu quả', N'noun', N'INTERMEDIATE', N'Think about the consequences first.', N'Hãy suy nghĩ về hậu quả trước.'),
(N'resolve', N'/rɪˈzɒlv/', N'giải quyết / quyết tâm', N'verb', N'INTERMEDIATE', N'Resolve conflicts calmly.', N'Giải quyết xung đột một cách bình tĩnh.'),
-- ADVANCED: Law & Justice
(N'legislation', N'/ˌledʒɪsˈleɪʃən/', N'pháp luật / lập pháp', N'noun', N'ADVANCED', N'New legislation was introduced.', N'Luật mới đã được đưa ra.'),
(N'constitution', N'/ˌkɒnstɪˈtjuːʃən/', N'hiến pháp', N'noun', N'ADVANCED', N'The constitution protects citizens'' rights.', N'Hiến pháp bảo vệ quyền công dân.'),
(N'litigation', N'/ˌlɪtɪˈɡeɪʃən/', N'kiện tụng', N'noun', N'ADVANCED', N'The company faces litigation.', N'Công ty đối mặt với kiện tụng.'),
(N'verdict', N'/ˈvɜːrdɪkt/', N'phán quyết', N'noun', N'ADVANCED', N'The jury delivered a verdict.', N'Bồi thẩm đoàn đưa ra phán quyết.'),
(N'prosecution', N'/ˌprɒsɪˈkjuːʃən/', N'việc truy tố', N'noun', N'ADVANCED', N'The prosecution presented evidence.', N'Bên công tố trình bày bằng chứng.'),
(N'defendant', N'/dɪˈfendənt/', N'bị cáo', N'noun', N'ADVANCED', N'The defendant pleaded not guilty.', N'Bị cáo nhận tội không phạm.'),
(N'testimony', N'/ˈtestɪməni/', N'lời khai / nhân chứng', N'noun', N'ADVANCED', N'Her testimony was crucial.', N'Lời khai của cô ấy rất quan trọng.'),
(N'amendment', N'/əˈmendmənt/', N'tu chính án / sửa đổi', N'noun', N'ADVANCED', N'The amendment changed the law.', N'Tu chính án đã thay đổi luật.'),
(N'arbitration', N'/ˌɑːrbɪˈtreɪʃən/', N'trọng tài phân xử', N'noun', N'ADVANCED', N'Settle the dispute through arbitration.', N'Giải quyết tranh chấp qua trọng tài.'),
(N'sanction', N'/ˈsæŋkʃən/', N'biện pháp trừng phạt', N'noun', N'ADVANCED', N'Economic sanctions were imposed.', N'Các biện pháp trừng phạt kinh tế đã được áp đặt.'),
-- ADVANCED: Philosophy & Abstract
(N'consciousness', N'/ˈkɒnʃəsnəs/', N'ý thức', N'noun', N'ADVANCED', N'Consciousness defines human experience.', N'Ý thức xác định trải nghiệm con người.'),
(N'perception', N'/pərˈsepʃən/', N'nhận thức / cảm nhận', N'noun', N'ADVANCED', N'Perception shapes our reality.', N'Nhận thức định hình thực tế của chúng ta.'),
(N'ideology', N'/ˌaɪdiˈɒlədʒi/', N'hệ tư tưởng', N'noun', N'ADVANCED', N'Political ideology divides people.', N'Hệ tư tưởng chính trị chia rẽ con người.'),
(N'morality', N'/məˈræləti/', N'đạo đức', N'noun', N'ADVANCED', N'Morality guides our choices.', N'Đạo đức hướng dẫn các lựa chọn của chúng ta.'),
(N'abstraction', N'/æbˈstrækʃən/', N'sự trừu tượng', N'noun', N'ADVANCED', N'Philosophy deals with abstraction.', N'Triết học xử lý sự trừu tượng.'),
(N'sovereignty', N'/ˈsɒvrənti/', N'chủ quyền', N'noun', N'ADVANCED', N'National sovereignty must be respected.', N'Chủ quyền quốc gia phải được tôn trọng.'),
(N'hegemony', N'/hɪˈdʒeməni/', N'quyền bá chủ', N'noun', N'ADVANCED', N'The country seeks hegemony.', N'Đất nước đó tìm kiếm quyền bá chủ.'),
(N'rhetoric', N'/ˈretərɪk/', N'tu từ học / lời lẽ hoa mỹ', N'noun', N'ADVANCED', N'Political rhetoric can be misleading.', N'Lời lẽ hoa mỹ chính trị có thể gây hiểu lầm.'),
(N'paradox', N'/ˈpærədɒks/', N'nghịch lý', N'noun', N'ADVANCED', N'This situation is a paradox.', N'Tình huống này là một nghịch lý.'),
(N'nuance', N'/ˈnjuːɑːns/', N'sắc thái tinh tế', N'noun', N'ADVANCED', N'Understanding nuance is important.', N'Hiểu được sắc thái tinh tế rất quan trọng.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('color','red','blue','green','yellow','white','black','orange','purple','pink','brown','gray','circle','square','triangle','rectangle','happy','sad','angry','tired','hungry','thirsty','scared','excited','bored','surprised','shirt','pants','dress','skirt','jacket','shoes','socks','hat','gloves','scarf','glasses','wear','community','society','population','generation','diversity','equality','freedom','democracy','government','policy','election','campaign','protest','debate','influence','impact','challenge','opportunity','consequence','resolve','legislation','constitution','litigation','verdict','prosecution','defendant','testimony','amendment','arbitration','sanction','consciousness','perception','ideology','morality','abstraction','sovereignty','hegemony','rhetoric','paradox','nuance');
