--liquibase formatted sql

--changeset vocab:013-seed-words-batch6
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.example_sentence, v.example_translation
FROM (VALUES
-- BEGINNER: Family & People
(N'family', N'/ˈfæməli/', N'gia đình', N'noun', N'BEGINNER', N'My family is very important to me.', N'Gia đình rất quan trọng với tôi.'),
(N'parent', N'/ˈperənt/', N'phụ huynh', N'noun', N'BEGINNER', N'My parents work hard.', N'Bố mẹ tôi làm việc chăm chỉ.'),
(N'father', N'/ˈfɑːðər/', N'cha / bố', N'noun', N'BEGINNER', N'My father is a doctor.', N'Bố tôi là bác sĩ.'),
(N'mother', N'/ˈmʌðər/', N'mẹ', N'noun', N'BEGINNER', N'My mother cooks well.', N'Mẹ tôi nấu ăn giỏi.'),
(N'brother', N'/ˈbrʌðər/', N'anh / em trai', N'noun', N'BEGINNER', N'My brother is older than me.', N'Anh trai tôi lớn hơn tôi.'),
(N'sister', N'/ˈsɪstər/', N'chị / em gái', N'noun', N'BEGINNER', N'My sister lives abroad.', N'Chị tôi sống ở nước ngoài.'),
(N'son', N'/sʌn/', N'con trai', N'noun', N'BEGINNER', N'They have one son.', N'Họ có một đứa con trai.'),
(N'daughter', N'/ˈdɔːtər/', N'con gái', N'noun', N'BEGINNER', N'Their daughter is very smart.', N'Con gái họ rất thông minh.'),
(N'husband', N'/ˈhʌzbənd/', N'chồng', N'noun', N'BEGINNER', N'Her husband is very kind.', N'Chồng cô ấy rất tốt bụng.'),
(N'wife', N'/waɪf/', N'vợ', N'noun', N'BEGINNER', N'His wife is a teacher.', N'Vợ anh ấy là giáo viên.'),
(N'grandfather', N'/ˈɡrændfɑːðər/', N'ông nội / ông ngoại', N'noun', N'BEGINNER', N'My grandfather tells great stories.', N'Ông tôi kể chuyện rất hay.'),
(N'grandmother', N'/ˈɡrændmʌðər/', N'bà nội / bà ngoại', N'noun', N'BEGINNER', N'My grandmother makes delicious food.', N'Bà tôi nấu đồ ăn rất ngon.'),
(N'uncle', N'/ˈʌŋkəl/', N'chú / cậu / bác (trai)', N'noun', N'BEGINNER', N'My uncle lives in the city.', N'Chú tôi sống ở thành phố.'),
(N'aunt', N'/ænt/', N'cô / dì / bác (gái)', N'noun', N'BEGINNER', N'My aunt is very funny.', N'Cô tôi rất vui tính.'),
(N'cousin', N'/ˈkʌzən/', N'anh chị em họ', N'noun', N'BEGINNER', N'My cousin visits every summer.', N'Anh họ tôi thăm mỗi mùa hè.'),
(N'friend', N'/frend/', N'bạn bè', N'noun', N'BEGINNER', N'She is my best friend.', N'Cô ấy là bạn thân nhất của tôi.'),
(N'neighbor', N'/ˈneɪbər/', N'hàng xóm', N'noun', N'BEGINNER', N'My neighbor is very friendly.', N'Hàng xóm tôi rất thân thiện.'),
(N'person', N'/ˈpɜːrsən/', N'người', N'noun', N'BEGINNER', N'She is a kind person.', N'Cô ấy là người tốt bụng.'),
(N'man', N'/mæn/', N'đàn ông / người đàn ông', N'noun', N'BEGINNER', N'The man is reading a book.', N'Người đàn ông đang đọc sách.'),
(N'woman', N'/ˈwʊmən/', N'phụ nữ / người phụ nữ', N'noun', N'BEGINNER', N'The woman is a teacher.', N'Người phụ nữ là giáo viên.'),
(N'child', N'/tʃaɪld/', N'đứa trẻ', N'noun', N'BEGINNER', N'The child is playing outside.', N'Đứa trẻ đang chơi ngoài sân.'),
(N'baby', N'/ˈbeɪbi/', N'em bé', N'noun', N'BEGINNER', N'The baby is sleeping.', N'Em bé đang ngủ.'),
(N'boy', N'/bɔɪ/', N'cậu bé', N'noun', N'BEGINNER', N'The boy runs fast.', N'Cậu bé chạy nhanh.'),
(N'girl', N'/ɡɜːrl/', N'cô bé', N'noun', N'BEGINNER', N'The girl loves dancing.', N'Cô bé thích nhảy.'),
-- BEGINNER: Actions (verbs)
(N'talk', N'/tɔːk/', N'nói chuyện', N'verb', N'BEGINNER', N'Talk to me honestly.', N'Hãy nói chuyện thật thà với tôi.'),
(N'listen', N'/ˈlɪsən/', N'lắng nghe', N'verb', N'BEGINNER', N'Please listen carefully.', N'Hãy lắng nghe cẩn thận.'),
(N'look', N'/lʊk/', N'nhìn / trông', N'verb', N'BEGINNER', N'Look at the board.', N'Nhìn lên bảng.'),
(N'see', N'/siː/', N'nhìn thấy', N'verb', N'BEGINNER', N'I can see the mountains.', N'Tôi có thể thấy những ngọn núi.'),
(N'hear', N'/hɪr/', N'nghe', N'verb', N'BEGINNER', N'Can you hear the music?', N'Bạn có nghe thấy âm nhạc không?'),
(N'think', N'/θɪŋk/', N'suy nghĩ', N'verb', N'BEGINNER', N'Think before you speak.', N'Hãy suy nghĩ trước khi nói.'),
(N'know', N'/noʊ/', N'biết', N'verb', N'BEGINNER', N'Do you know the answer?', N'Bạn có biết câu trả lời không?'),
(N'want', N'/wɒnt/', N'muốn', N'verb', N'BEGINNER', N'What do you want to eat?', N'Bạn muốn ăn gì?'),
(N'like', N'/laɪk/', N'thích', N'verb', N'BEGINNER', N'I like playing football.', N'Tôi thích chơi bóng đá.'),
(N'love', N'/lʌv/', N'yêu', N'verb', N'BEGINNER', N'I love my family.', N'Tôi yêu gia đình tôi.'),
(N'hate', N'/heɪt/', N'ghét', N'verb', N'BEGINNER', N'I hate being late.', N'Tôi ghét bị trễ.'),
(N'feel', N'/fiːl/', N'cảm thấy', N'verb', N'BEGINNER', N'How do you feel today?', N'Hôm nay bạn cảm thấy thế nào?'),
(N'try', N'/traɪ/', N'thử / cố gắng', N'verb', N'BEGINNER', N'Try your best every day.', N'Hãy cố gắng hết sức mỗi ngày.'),
(N'start', N'/stɑːrt/', N'bắt đầu', N'verb', N'BEGINNER', N'Start the project now.', N'Bắt đầu dự án ngay bây giờ.'),
(N'stop', N'/stɒp/', N'dừng lại', N'verb', N'BEGINNER', N'Stop the car here.', N'Dừng xe ở đây.'),
(N'wait', N'/weɪt/', N'chờ đợi', N'verb', N'BEGINNER', N'Wait for me please.', N'Hãy chờ tôi.'),
(N'help', N'/help/', N'giúp đỡ', N'verb', N'BEGINNER', N'Can you help me?', N'Bạn có thể giúp tôi không?'),
(N'work', N'/wɜːrk/', N'làm việc', N'verb', N'BEGINNER', N'She works at a bank.', N'Cô ấy làm việc ở ngân hàng.'),
(N'play', N'/pleɪ/', N'chơi', N'verb', N'BEGINNER', N'Children love to play.', N'Trẻ em thích chơi.'),
(N'study', N'/ˈstʌdi/', N'học tập', N'verb', N'BEGINNER', N'Study hard to pass the exam.', N'Học chăm để qua bài thi.'),
-- INTERMEDIATE: Art & Entertainment
(N'performance', N'/pərˈfɔːrməns/', N'buổi biểu diễn', N'noun', N'INTERMEDIATE', N'The performance was outstanding.', N'Buổi biểu diễn rất xuất sắc.'),
(N'exhibition', N'/ˌeksɪˈbɪʃən/', N'triển lãm', N'noun', N'INTERMEDIATE', N'Visit the art exhibition downtown.', N'Thăm triển lãm nghệ thuật ở trung tâm.'),
(N'orchestra', N'/ˈɔːrkɪstrə/', N'dàn nhạc', N'noun', N'INTERMEDIATE', N'The orchestra played beautifully.', N'Dàn nhạc chơi rất hay.'),
(N'sculpture', N'/ˈskʌlptʃər/', N'điêu khắc / tượng điêu khắc', N'noun', N'INTERMEDIATE', N'The sculpture is hundreds of years old.', N'Bức tượng điêu khắc đã hàng trăm năm tuổi.'),
(N'photography', N'/fəˈtɒɡrəfi/', N'nhiếp ảnh', N'noun', N'INTERMEDIATE', N'Photography is her hobby.', N'Nhiếp ảnh là sở thích của cô ấy.'),
(N'literature', N'/ˈlɪtrətʃər/', N'văn học', N'noun', N'INTERMEDIATE', N'She studies English literature.', N'Cô ấy học văn học tiếng Anh.'),
(N'novel', N'/ˈnɒvəl/', N'tiểu thuyết', N'noun', N'INTERMEDIATE', N'I''m reading a historical novel.', N'Tôi đang đọc tiểu thuyết lịch sử.'),
(N'poetry', N'/ˈpoʊɪtri/', N'thơ ca', N'noun', N'INTERMEDIATE', N'Poetry expresses deep emotions.', N'Thơ ca thể hiện cảm xúc sâu sắc.'),
(N'musician', N'/mjuˈzɪʃən/', N'nhạc sĩ', N'noun', N'INTERMEDIATE', N'The musician plays guitar well.', N'Nhạc sĩ chơi guitar rất hay.'),
(N'actress', N'/ˈæktrɪs/', N'nữ diễn viên', N'noun', N'INTERMEDIATE', N'She is a famous actress.', N'Cô ấy là nữ diễn viên nổi tiếng.'),
(N'director', N'/dɪˈrektər/', N'đạo diễn / giám đốc', N'noun', N'INTERMEDIATE', N'The director won an award.', N'Đạo diễn đã nhận giải thưởng.'),
(N'audience', N'/ˈɔːdiəns/', N'khán giả', N'noun', N'INTERMEDIATE', N'The audience applauded loudly.', N'Khán giả vỗ tay to.'),
(N'critic', N'/ˈkrɪtɪk/', N'nhà phê bình', N'noun', N'INTERMEDIATE', N'The movie received good reviews from critics.', N'Bộ phim nhận được đánh giá tốt từ các nhà phê bình.'),
(N'entertain', N'/ˌentərˈteɪn/', N'giải trí', N'verb', N'INTERMEDIATE', N'The show entertains people of all ages.', N'Chương trình giải trí cho mọi lứa tuổi.'),
(N'inspire', N'/ɪnˈspaɪər/', N'truyền cảm hứng', N'verb', N'INTERMEDIATE', N'The teacher inspired her students.', N'Giáo viên truyền cảm hứng cho học sinh.'),
(N'creative', N'/kriˈeɪtɪv/', N'sáng tạo', N'adjective', N'INTERMEDIATE', N'She is a very creative person.', N'Cô ấy là người rất sáng tạo.'),
(N'artistic', N'/ɑːrˈtɪstɪk/', N'có tính nghệ thuật', N'adjective', N'INTERMEDIATE', N'The design is very artistic.', N'Thiết kế rất có tính nghệ thuật.'),
-- ADVANCED: Economics
(N'inflation', N'/ɪnˈfleɪʃən/', N'lạm phát', N'noun', N'ADVANCED', N'Inflation affects purchasing power.', N'Lạm phát ảnh hưởng đến sức mua.'),
(N'recession', N'/rɪˈseʃən/', N'suy thoái kinh tế', N'noun', N'ADVANCED', N'The country entered a recession.', N'Đất nước bước vào giai đoạn suy thoái.'),
(N'gross domestic product', N'/ɡroʊs dəˈmestɪk ˈprɒdʌkt/', N'tổng sản phẩm quốc nội', N'noun', N'ADVANCED', N'The GDP grew by 3 percent.', N'GDP tăng 3 phần trăm.'),
(N'monopoly', N'/məˈnɒpəli/', N'độc quyền', N'noun', N'ADVANCED', N'The company has a monopoly.', N'Công ty đang độc quyền.'),
(N'commodity', N'/kəˈmɒdɪti/', N'hàng hóa', N'noun', N'ADVANCED', N'Oil is a valuable commodity.', N'Dầu mỏ là hàng hóa có giá trị.'),
(N'depreciation', N'/dɪˌpriːʃiˈeɪʃən/', N'khấu hao / giảm giá trị', N'noun', N'ADVANCED', N'Asset depreciation affects profits.', N'Khấu hao tài sản ảnh hưởng đến lợi nhuận.'),
(N'subsidy', N'/ˈsʌbsɪdi/', N'trợ cấp', N'noun', N'ADVANCED', N'The government provides farming subsidies.', N'Chính phủ cung cấp trợ cấp nông nghiệp.'),
(N'fiscal', N'/ˈfɪskəl/', N'thuộc tài chính / tài khóa', N'adjective', N'ADVANCED', N'The fiscal year ends in December.', N'Năm tài khóa kết thúc vào tháng Mười Hai.'),
(N'monetary', N'/ˈmʌnɪteri/', N'thuộc tiền tệ', N'adjective', N'ADVANCED', N'The central bank sets monetary policy.', N'Ngân hàng trung ương đặt ra chính sách tiền tệ.'),
(N'austerity', N'/ɒˈsterɪti/', N'khắc khổ / thắt chặt chi tiêu', N'noun', N'ADVANCED', N'Austerity measures cut spending.', N'Các biện pháp thắt lưng buộc bụng cắt giảm chi tiêu.'),
-- ADVANCED: Science & Medicine
(N'metabolism', N'/məˈtæbəlɪzəm/', N'quá trình trao đổi chất', N'noun', N'ADVANCED', N'Exercise boosts your metabolism.', N'Tập thể dục thúc đẩy quá trình trao đổi chất.'),
(N'genome', N'/ˈdʒiːnoʊm/', N'bộ gen', N'noun', N'ADVANCED', N'Scientists mapped the human genome.', N'Các nhà khoa học đã lập bản đồ bộ gen người.'),
(N'neuroscience', N'/ˈnjʊəroʊsaɪəns/', N'khoa học thần kinh', N'noun', N'ADVANCED', N'Neuroscience studies the brain.', N'Khoa học thần kinh nghiên cứu não bộ.'),
(N'pathogen', N'/ˈpæθədʒən/', N'mầm bệnh', N'noun', N'ADVANCED', N'The pathogen spreads through contact.', N'Mầm bệnh lây qua tiếp xúc.'),
(N'catalyst', N'/ˈkætəlɪst/', N'chất xúc tác', N'noun', N'ADVANCED', N'The catalyst speeds up the reaction.', N'Chất xúc tác tăng tốc phản ứng.'),
(N'phenomenon', N'/fɪˈnɒmɪnən/', N'hiện tượng', N'noun', N'ADVANCED', N'This is a rare natural phenomenon.', N'Đây là hiện tượng tự nhiên hiếm gặp.'),
(N'hypothesis', N'/haɪˈpɒθɪsɪs/', N'giả thuyết', N'noun', N'ADVANCED', N'Prove your hypothesis with data.', N'Chứng minh giả thuyết bằng dữ liệu.'),
(N'quantum', N'/ˈkwɒntəm/', N'lượng tử', N'adjective', N'ADVANCED', N'Quantum computing is revolutionary.', N'Máy tính lượng tử mang tính cách mạng.'),
(N'gravity', N'/ˈɡrævɪti/', N'trọng lực', N'noun', N'ADVANCED', N'Gravity keeps us on the ground.', N'Trọng lực giữ chúng ta ở mặt đất.'),
(N'entropy', N'/ˈentrəpi/', N'entropy / sự hỗn loạn nhiệt', N'noun', N'ADVANCED', N'Entropy increases over time.', N'Entropy tăng theo thời gian.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('family','parent','father','mother','brother','sister','son','daughter','husband','wife','grandfather','grandmother','uncle','aunt','cousin','friend','neighbor','person','man','woman','child','baby','boy','girl','talk','listen','look','see','hear','think','know','want','like','love','hate','feel','try','start','stop','wait','help','work','play','study','performance','exhibition','orchestra','sculpture','photography','literature','novel','poetry','musician','actress','director','audience','critic','entertain','inspire','creative','artistic','inflation','recession','gross domestic product','monopoly','commodity','depreciation','subsidy','fiscal','monetary','austerity','metabolism','genome','neuroscience','pathogen','catalyst','phenomenon','hypothesis','quantum','gravity','entropy');
