--liquibase formatted sql

--changeset vocab:018-seed-words-batch11
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.example_sentence, v.example_translation
FROM (VALUES
-- BEGINNER: Animals
(N'horse', N'/hɔːrs/', N'con ngựa', N'noun', N'BEGINNER', N'The horse runs very fast.', N'Con ngựa chạy rất nhanh.'),
(N'cow', N'/kaʊ/', N'con bò', N'noun', N'BEGINNER', N'The cow gives us milk.', N'Con bò cho chúng ta sữa.'),
(N'pig', N'/pɪɡ/', N'con lợn', N'noun', N'BEGINNER', N'The pig rolls in the mud.', N'Con lợn lăn trong bùn.'),
(N'chicken', N'/ˈtʃɪkɪn/', N'con gà', N'noun', N'BEGINNER', N'We raise chickens on the farm.', N'Chúng tôi nuôi gà ở nông trại.'),
(N'duck', N'/dʌk/', N'con vịt', N'noun', N'BEGINNER', N'The duck swims in the pond.', N'Con vịt bơi trong ao.'),
(N'rabbit', N'/ˈræbɪt/', N'con thỏ', N'noun', N'BEGINNER', N'The rabbit eats carrots.', N'Con thỏ ăn cà rốt.'),
(N'fish', N'/fɪʃ/', N'con cá', N'noun', N'BEGINNER', N'The fish swims in the tank.', N'Con cá bơi trong bể.'),
(N'tiger', N'/ˈtaɪɡər/', N'con hổ', N'noun', N'BEGINNER', N'The tiger is a powerful animal.', N'Con hổ là động vật mạnh mẽ.'),
(N'lion', N'/ˈlaɪən/', N'con sư tử', N'noun', N'BEGINNER', N'The lion is the king of the jungle.', N'Sư tử là vua của rừng rậm.'),
(N'elephant', N'/ˈelɪfənt/', N'con voi', N'noun', N'BEGINNER', N'Elephants have great memory.', N'Voi có trí nhớ tuyệt vời.'),
(N'monkey', N'/ˈmʌŋki/', N'con khỉ', N'noun', N'BEGINNER', N'The monkey climbs the tree.', N'Con khỉ leo cây.'),
(N'snake', N'/sneɪk/', N'con rắn', N'noun', N'BEGINNER', N'Be careful of snakes in the grass.', N'Cẩn thận rắn trong cỏ.'),
(N'frog', N'/frɒɡ/', N'con ếch', N'noun', N'BEGINNER', N'The frog jumps into the pond.', N'Con ếch nhảy xuống ao.'),
(N'butterfly', N'/ˈbʌtəflaɪ/', N'con bướm', N'noun', N'BEGINNER', N'The butterfly is very colorful.', N'Con bướm rất nhiều màu sắc.'),
(N'bee', N'/biː/', N'con ong', N'noun', N'BEGINNER', N'The bee makes honey.', N'Con ong làm mật.'),
(N'mouse', N'/maʊs/', N'con chuột', N'noun', N'BEGINNER', N'The mouse hides in the hole.', N'Con chuột trốn trong lỗ.'),
(N'bear', N'/ber/', N'con gấu', N'noun', N'BEGINNER', N'The bear sleeps in winter.', N'Con gấu ngủ đông.'),
(N'wolf', N'/wʊlf/', N'con sói', N'noun', N'BEGINNER', N'Wolves live in packs.', N'Sói sống thành bầy.'),
(N'deer', N'/dɪr/', N'con hươu', N'noun', N'BEGINNER', N'The deer runs through the forest.', N'Con hươu chạy qua rừng.'),
(N'whale', N'/weɪl/', N'con cá voi', N'noun', N'BEGINNER', N'Whales are the largest animals.', N'Cá voi là động vật lớn nhất.'),
-- BEGINNER: Vegetables & Fruits
(N'apple', N'/ˈæpəl/', N'quả táo', N'noun', N'BEGINNER', N'An apple a day keeps the doctor away.', N'Ăn một quả táo mỗi ngày không cần gặp bác sĩ.'),
(N'banana', N'/bəˈnɑːnə/', N'quả chuối', N'noun', N'BEGINNER', N'Monkeys love bananas.', N'Khỉ thích chuối.'),
(N'orange', N'/ˈɒrɪndʒ/', N'quả cam', N'noun', N'BEGINNER', N'I drink orange juice every morning.', N'Tôi uống nước cam mỗi sáng.'),
(N'grape', N'/ɡreɪp/', N'quả nho', N'noun', N'BEGINNER', N'Grapes are used to make wine.', N'Nho được dùng để làm rượu vang.'),
(N'mango', N'/ˈmæŋɡoʊ/', N'quả xoài', N'noun', N'BEGINNER', N'Mangoes are popular in Vietnam.', N'Xoài rất phổ biến ở Việt Nam.'),
(N'pineapple', N'/ˈpaɪnæpəl/', N'quả dứa', N'noun', N'BEGINNER', N'Pineapple is sweet and sour.', N'Dứa vừa ngọt vừa chua.'),
(N'watermelon', N'/ˈwɔːtərmelən/', N'quả dưa hấu', N'noun', N'BEGINNER', N'Watermelon is great in summer.', N'Dưa hấu rất ngon vào mùa hè.'),
(N'strawberry', N'/ˈstrɔːberi/', N'quả dâu tây', N'noun', N'BEGINNER', N'She loves strawberry jam.', N'Cô ấy thích mứt dâu tây.'),
(N'tomato', N'/təˈmeɪtoʊ/', N'quả cà chua', N'noun', N'BEGINNER', N'Tomatoes are used in many dishes.', N'Cà chua được dùng trong nhiều món.'),
(N'potato', N'/pəˈteɪtoʊ/', N'củ khoai tây', N'noun', N'BEGINNER', N'She made mashed potatoes.', N'Cô ấy làm khoai tây nghiền.'),
(N'carrot', N'/ˈkærət/', N'củ cà rốt', N'noun', N'BEGINNER', N'Carrots are good for your eyes.', N'Cà rốt tốt cho mắt.'),
(N'onion', N'/ˈʌnjən/', N'củ hành', N'noun', N'BEGINNER', N'Onions make me cry.', N'Hành làm tôi khóc.'),
(N'garlic', N'/ˈɡɑːrlɪk/', N'tỏi', N'noun', N'BEGINNER', N'Add garlic for flavor.', N'Thêm tỏi để tăng hương vị.'),
(N'corn', N'/kɔːrn/', N'bắp ngô', N'noun', N'BEGINNER', N'Corn grows tall in summer.', N'Ngô mọc cao vào mùa hè.'),
(N'mushroom', N'/ˈmʌʃruːm/', N'nấm', N'noun', N'BEGINNER', N'Add mushrooms to the soup.', N'Thêm nấm vào súp.'),
-- BEGINNER: Places in town
(N'city', N'/ˈsɪti/', N'thành phố', N'noun', N'BEGINNER', N'She moved to the city last year.', N'Cô ấy chuyển đến thành phố năm ngoái.'),
(N'town', N'/taʊn/', N'thị trấn', N'noun', N'BEGINNER', N'They live in a small town.', N'Họ sống ở thị trấn nhỏ.'),
(N'village', N'/ˈvɪlɪdʒ/', N'ngôi làng', N'noun', N'BEGINNER', N'She grew up in a village.', N'Cô ấy lớn lên ở làng.'),
(N'park', N'/pɑːrk/', N'công viên', N'noun', N'BEGINNER', N'Let''s take a walk in the park.', N'Hãy đi dạo trong công viên.'),
(N'market', N'/ˈmɑːrkɪt/', N'chợ', N'noun', N'BEGINNER', N'Buy fresh food at the market.', N'Mua thức ăn tươi ở chợ.'),
(N'store', N'/stɔːr/', N'cửa hàng', N'noun', N'BEGINNER', N'The store closes at 10 pm.', N'Cửa hàng đóng cửa lúc 10 giờ tối.'),
(N'restaurant', N'/ˈrestərɒnt/', N'nhà hàng', N'noun', N'BEGINNER', N'Let''s eat at the restaurant.', N'Hãy ăn ở nhà hàng.'),
(N'hospital', N'/ˈhɒspɪtəl/', N'bệnh viện', N'noun', N'BEGINNER', N'Take him to the hospital.', N'Đưa anh ấy đến bệnh viện.'),
(N'church', N'/tʃɜːrtʃ/', N'nhà thờ', N'noun', N'BEGINNER', N'They got married in the church.', N'Họ kết hôn trong nhà thờ.'),
(N'museum', N'/mjuˈziːəm/', N'bảo tàng', N'noun', N'BEGINNER', N'Visit the museum on Sunday.', N'Thăm bảo tàng vào chủ nhật.'),
(N'theater', N'/ˈθiːətər/', N'rạp hát', N'noun', N'BEGINNER', N'We watched a play at the theater.', N'Chúng tôi xem kịch ở rạp hát.'),
(N'cinema', N'/ˈsɪnəmə/', N'rạp chiếu phim', N'noun', N'BEGINNER', N'Let''s go to the cinema tonight.', N'Hãy đến rạp phim tối nay.'),
(N'office', N'/ˈɒfɪs/', N'văn phòng', N'noun', N'BEGINNER', N'I work at the office downtown.', N'Tôi làm việc ở văn phòng trung tâm thành phố.'),
(N'factory', N'/ˈfæktəri/', N'nhà máy', N'noun', N'BEGINNER', N'He works in a car factory.', N'Anh ấy làm việc ở nhà máy xe hơi.'),
(N'farm', N'/fɑːrm/', N'nông trại', N'noun', N'BEGINNER', N'They grow rice on the farm.', N'Họ trồng lúa ở nông trại.'),
(N'beach', N'/biːtʃ/', N'bãi biển', N'noun', N'BEGINNER', N'We played on the beach all day.', N'Chúng tôi chơi trên bãi biển cả ngày.'),
(N'hotel', N'/hoʊˈtel/', N'khách sạn', N'noun', N'BEGINNER', N'Book a hotel near the beach.', N'Đặt khách sạn gần bãi biển.'),
-- INTERMEDIATE: Phrasal Verbs (as vocabulary items)
(N'give up', N'/ɡɪv ʌp/', N'từ bỏ', N'verb', N'INTERMEDIATE', N'Never give up on your dreams.', N'Đừng bao giờ từ bỏ ước mơ.'),
(N'take off', N'/teɪk ɒf/', N'cất cánh / cởi ra', N'verb', N'INTERMEDIATE', N'The plane will take off at noon.', N'Máy bay sẽ cất cánh lúc trưa.'),
(N'put off', N'/pʊt ɒf/', N'hoãn lại', N'verb', N'INTERMEDIATE', N'Don''t put off what you can do today.', N'Đừng hoãn lại những gì bạn có thể làm hôm nay.'),
(N'look up', N'/lʊk ʌp/', N'tra cứu', N'verb', N'INTERMEDIATE', N'Look up the word in the dictionary.', N'Tra từ trong từ điển.'),
(N'find out', N'/faɪnd aʊt/', N'tìm ra / khám phá', N'verb', N'INTERMEDIATE', N'Find out the answer yourself.', N'Tự mình tìm ra câu trả lời.'),
(N'break down', N'/breɪk daʊn/', N'hỏng hóc / phân tích', N'verb', N'INTERMEDIATE', N'The car broke down on the highway.', N'Xe bị hỏng trên đường cao tốc.'),
(N'carry out', N'/kæri aʊt/', N'thực hiện', N'verb', N'INTERMEDIATE', N'Carry out the plan carefully.', N'Thực hiện kế hoạch cẩn thận.'),
(N'set up', N'/set ʌp/', N'thiết lập', N'verb', N'INTERMEDIATE', N'Set up a meeting with the team.', N'Thiết lập cuộc họp với nhóm.'),
(N'come up with', N'/kʌm ʌp wɪð/', N'nghĩ ra', N'verb', N'INTERMEDIATE', N'Come up with a new idea.', N'Nghĩ ra một ý tưởng mới.'),
(N'go through', N'/ɡoʊ θruː/', N'trải qua / xem xét', N'verb', N'INTERMEDIATE', N'Go through the report carefully.', N'Xem xét báo cáo cẩn thận.'),
-- INTERMEDIATE: Common Collocations
(N'appointment', N'/əˈpɔɪntmənt/', N'cuộc hẹn', N'noun', N'INTERMEDIATE', N'I have a doctor''s appointment.', N'Tôi có cuộc hẹn với bác sĩ.'),
(N'complaint', N'/kəmˈpleɪnt/', N'lời phàn nàn', N'noun', N'INTERMEDIATE', N'File a complaint with the manager.', N'Nộp đơn khiếu nại với quản lý.'),
(N'permission', N'/pərˈmɪʃən/', N'sự cho phép', N'noun', N'INTERMEDIATE', N'Ask for permission first.', N'Xin phép trước.'),
(N'evidence', N'/ˈevɪdəns/', N'bằng chứng', N'noun', N'INTERMEDIATE', N'The evidence proves his guilt.', N'Bằng chứng chứng minh anh ấy có tội.'),
(N'benefit', N'/ˈbenɪfɪt/', N'lợi ích', N'noun', N'INTERMEDIATE', N'Exercise has many health benefits.', N'Tập thể dục có nhiều lợi ích sức khỏe.'),
(N'advantage', N'/ədˈvɑːntɪdʒ/', N'lợi thế', N'noun', N'INTERMEDIATE', N'Use your advantages wisely.', N'Tận dụng lợi thế của bạn một cách khôn ngoan.'),
(N'disadvantage', N'/ˌdɪsədˈvɑːntɪdʒ/', N'bất lợi', N'noun', N'INTERMEDIATE', N'Every plan has its disadvantages.', N'Mọi kế hoạch đều có bất lợi.'),
(N'exception', N'/ɪkˈsepʃən/', N'ngoại lệ', N'noun', N'INTERMEDIATE', N'There is an exception to every rule.', N'Mọi quy tắc đều có ngoại lệ.'),
(N'effort', N'/ˈefərt/', N'nỗ lực', N'noun', N'INTERMEDIATE', N'Success requires a lot of effort.', N'Thành công đòi hỏi nhiều nỗ lực.'),
(N'aspect', N'/ˈæspekt/', N'khía cạnh', N'noun', N'INTERMEDIATE', N'Consider every aspect of the problem.', N'Xem xét mọi khía cạnh của vấn đề.'),
-- ADVANCED: Literary & Rhetoric
(N'allegory', N'/ˈæləɡɔːri/', N'ẩn dụ / ngụ ngôn', N'noun', N'ADVANCED', N'The novel is an allegory of war.', N'Cuốn tiểu thuyết là ẩn dụ của chiến tranh.'),
(N'metaphor', N'/ˈmetəfɔːr/', N'ẩn dụ (tu từ)', N'noun', N'ADVANCED', N'He used a powerful metaphor.', N'Anh ấy dùng ẩn dụ mạnh mẽ.'),
(N'simile', N'/ˈsɪmɪli/', N'so sánh (tu từ)', N'noun', N'ADVANCED', N'A simile compares using like or as.', N'So sánh dùng từ như hoặc giống như.'),
(N'irony', N'/ˈaɪrəni/', N'sự mỉa mai', N'noun', N'ADVANCED', N'There is a lot of irony in this situation.', N'Có nhiều sự mỉa mai trong tình huống này.'),
(N'satire', N'/ˈsætaɪər/', N'văn châm biếm', N'noun', N'ADVANCED', N'Political satire is popular.', N'Châm biếm chính trị rất phổ biến.'),
(N'narrative', N'/ˈnærətɪv/', N'câu chuyện / tường thuật', N'noun', N'ADVANCED', N'She told a compelling narrative.', N'Cô ấy kể một câu chuyện hấp dẫn.'),
(N'protagonist', N'/prəˈtæɡənɪst/', N'nhân vật chính', N'noun', N'ADVANCED', N'The protagonist faces many challenges.', N'Nhân vật chính đối mặt với nhiều thách thức.'),
(N'antagonist', N'/ænˈtæɡənɪst/', N'nhân vật phản diện', N'noun', N'ADVANCED', N'The antagonist is very cunning.', N'Nhân vật phản diện rất xảo quyệt.'),
(N'hyperbole', N'/haɪˈpɜːrbəli/', N'phóng đại (tu từ)', N'noun', N'ADVANCED', N'He used hyperbole to emphasize.', N'Anh ấy dùng phóng đại để nhấn mạnh.'),
(N'foreshadowing', N'/fɔːrˈʃædoʊɪŋ/', N'điềm báo trước', N'noun', N'ADVANCED', N'The dark clouds were foreshadowing.', N'Những đám mây tối là điềm báo trước.'),
-- ADVANCED: Architecture & Urban
(N'infrastructure', N'/ˈɪnfrəstrʌktʃər/', N'cơ sở hạ tầng', N'noun', N'ADVANCED', N'Improve the city infrastructure.', N'Cải thiện cơ sở hạ tầng thành phố.'),
(N'urbanization', N'/ˌɜːrbənɪˈzeɪʃən/', N'đô thị hóa', N'noun', N'ADVANCED', N'Urbanization is increasing rapidly.', N'Đô thị hóa đang tăng nhanh.'),
(N'architecture', N'/ˈɑːrkɪtektʃər/', N'kiến trúc', N'noun', N'ADVANCED', N'The building''s architecture is stunning.', N'Kiến trúc tòa nhà rất ấn tượng.'),
(N'facade', N'/fəˈsɑːd/', N'mặt tiền (tòa nhà)', N'noun', N'ADVANCED', N'The building has a beautiful facade.', N'Tòa nhà có mặt tiền đẹp.'),
(N'renovation', N'/ˌrenəˈveɪʃən/', N'việc cải tạo / sửa chữa', N'noun', N'ADVANCED', N'The renovation took six months.', N'Việc cải tạo mất sáu tháng.'),
(N'foundation', N'/faʊnˈdeɪʃən/', N'nền móng', N'noun', N'ADVANCED', N'Build a strong foundation first.', N'Xây nền móng vững chắc trước.'),
(N'metropolitan', N'/ˌmetrəˈpɒlɪtən/', N'thuộc đô thị lớn', N'adjective', N'ADVANCED', N'Tokyo is a metropolitan city.', N'Tokyo là thành phố đô thị lớn.'),
(N'municipal', N'/mjuˈnɪsɪpəl/', N'thuộc thành phố / địa phương', N'adjective', N'ADVANCED', N'Municipal services need improvement.', N'Dịch vụ thành phố cần cải thiện.'),
(N'zoning', N'/ˈzoʊnɪŋ/', N'quy hoạch (phân khu)', N'noun', N'ADVANCED', N'Zoning laws regulate land use.', N'Quy hoạch điều tiết việc sử dụng đất.'),
(N'suburb', N'/ˈsʌbɜːrb/', N'vùng ngoại ô', N'noun', N'ADVANCED', N'They moved to the suburbs.', N'Họ chuyển ra vùng ngoại ô.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('horse','cow','pig','chicken','duck','rabbit','fish','tiger','lion','elephant','monkey','snake','frog','butterfly','bee','mouse','bear','wolf','deer','whale','apple','banana','orange','grape','mango','pineapple','watermelon','strawberry','tomato','potato','carrot','onion','garlic','corn','mushroom','city','town','village','park','market','store','restaurant','hospital','church','museum','theater','cinema','office','factory','farm','beach','hotel','give up','take off','put off','look up','find out','break down','carry out','set up','come up with','go through','appointment','complaint','permission','evidence','benefit','advantage','disadvantage','exception','effort','aspect','allegory','metaphor','simile','irony','satire','narrative','protagonist','antagonist','hyperbole','foreshadowing','infrastructure','urbanization','architecture','facade','renovation','foundation','metropolitan','municipal','zoning','suburb');
