--liquibase formatted sql

--changeset vocab:024-seed-words-batch17
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.example_sentence, v.example_translation
FROM (VALUES
(N'absent', N'/ˈæbsənt/', N'vắng mặt', N'adjective', N'BEGINNER', N'He was absent from class today.', N'Anh ấy vắng mặt ở lớp hôm nay.'),
(N'abroad', N'/əˈbrɔːd/', N'ở nước ngoài', N'adverb', N'BEGINNER', N'She studied abroad for two years.', N'Cô ấy học ở nước ngoài hai năm.'),
(N'accident', N'/ˈæksɪdənt/', N'tai nạn', N'noun', N'BEGINNER', N'There was a car accident on the road.', N'Có một vụ tai nạn xe trên đường.'),
(N'account', N'/əˈkaʊnt/', N'tài khoản', N'noun', N'BEGINNER', N'Create an account to log in.', N'Tạo tài khoản để đăng nhập.'),
(N'ache', N'/eɪk/', N'đau âm ỉ', N'noun', N'BEGINNER', N'I have a toothache.', N'Tôi bị đau răng.'),
(N'address', N'/ˈædres/', N'địa chỉ', N'noun', N'BEGINNER', N'Write your address on the envelope.', N'Viết địa chỉ của bạn lên phong bì.'),
(N'adult', N'/ˈædʌlt/', N'người lớn', N'noun', N'BEGINNER', N'Only adults can vote.', N'Chỉ người lớn mới được bỏ phiếu.'),
(N'advice', N'/ədˈvaɪs/', N'lời khuyên', N'noun', N'BEGINNER', N'She gave me good advice.', N'Cô ấy cho tôi lời khuyên hay.'),
(N'afraid', N'/əˈfreɪd/', N'sợ hãi', N'adjective', N'BEGINNER', N'Don''t be afraid of failure.', N'Đừng sợ thất bại.'),
(N'age', N'/eɪdʒ/', N'tuổi / thời đại', N'noun', N'BEGINNER', N'What is your age?', N'Bạn bao nhiêu tuổi?'),
(N'agree', N'/əˈɡriː/', N'đồng ý', N'verb', N'BEGINNER', N'I agree with you.', N'Tôi đồng ý với bạn.'),
(N'ahead', N'/əˈhed/', N'phía trước / về phía trước', N'adverb', N'BEGINNER', N'Look ahead, not behind.', N'Hãy nhìn về phía trước, không phải phía sau.'),
(N'aim', N'/eɪm/', N'mục tiêu / nhắm vào', N'noun', N'BEGINNER', N'Aim high in life.', N'Hãy đặt mục tiêu cao trong cuộc sống.'),
(N'alarm', N'/əˈlɑːrm/', N'báo động / đồng hồ báo thức', N'noun', N'BEGINNER', N'Set the alarm for 6 am.', N'Đặt báo thức lúc 6 giờ sáng.'),
(N'allow', N'/əˈlaʊ/', N'cho phép', N'verb', N'BEGINNER', N'Are pets allowed here?', N'Thú cưng có được phép ở đây không?'),
(N'alone', N'/əˈloʊn/', N'một mình', N'adjective', N'BEGINNER', N'She lives alone.', N'Cô ấy sống một mình.'),
(N'amount', N'/əˈmaʊnt/', N'số lượng / tổng số', N'noun', N'BEGINNER', N'What is the total amount?', N'Tổng số là bao nhiêu?'),
(N'ancient', N'/ˈeɪnʃənt/', N'cổ đại', N'adjective', N'BEGINNER', N'Rome is an ancient city.', N'Rome là thành phố cổ đại.'),
(N'another', N'/əˈnʌðər/', N'một cái khác', N'adjective', N'BEGINNER', N'Give me another chance.', N'Cho tôi thêm một cơ hội nữa.'),
(N'apart', N'/əˈpɑːrt/', N'tách rời / xa nhau', N'adverb', N'BEGINNER', N'They live far apart.', N'Họ sống rất xa nhau.'),
(N'appear', N'/əˈpɪər/', N'xuất hiện', N'verb', N'BEGINNER', N'Stars appear at night.', N'Các ngôi sao xuất hiện vào ban đêm.'),
(N'apply', N'/əˈplaɪ/', N'áp dụng / nộp đơn', N'verb', N'BEGINNER', N'Apply for the job online.', N'Nộp đơn xin việc trực tuyến.'),
(N'approach', N'/əˈproʊtʃ/', N'tiếp cận / cách tiếp cận', N'verb', N'BEGINNER', N'Approach the problem calmly.', N'Tiếp cận vấn đề một cách bình tĩnh.'),
(N'area', N'/ˈeriə/', N'khu vực / diện tích', N'noun', N'BEGINNER', N'This area is very quiet.', N'Khu vực này rất yên tĩnh.'),
(N'argue', N'/ˈɑːrɡjuː/', N'tranh luận / cãi nhau', N'verb', N'BEGINNER', N'Don''t argue about small things.', N'Đừng cãi nhau về chuyện nhỏ.'),
(N'arise', N'/əˈraɪz/', N'nảy sinh / xuất hiện', N'verb', N'INTERMEDIATE', N'Problems may arise unexpectedly.', N'Vấn đề có thể nảy sinh bất ngờ.'),
(N'arrange', N'/əˈreɪndʒ/', N'sắp xếp', N'verb', N'BEGINNER', N'Arrange the books by title.', N'Sắp xếp sách theo tên.'),
(N'arrest', N'/əˈrest/', N'bắt giữ', N'verb', N'INTERMEDIATE', N'The police arrested the suspect.', N'Cảnh sát đã bắt giữ nghi phạm.'),
(N'article', N'/ˈɑːrtɪkəl/', N'bài viết / mạo từ', N'noun', N'BEGINNER', N'Read this news article.', N'Đọc bài báo này.'),
(N'assist', N'/əˈsɪst/', N'hỗ trợ', N'verb', N'INTERMEDIATE', N'Can you assist me with this?', N'Bạn có thể hỗ trợ tôi với điều này không?'),
(N'attach', N'/əˈtætʃ/', N'đính kèm', N'verb', N'BEGINNER', N'Attach the file to the email.', N'Đính kèm file vào email.'),
(N'attempt', N'/əˈtempt/', N'cố gắng / nỗ lực', N'noun', N'INTERMEDIATE', N'Make one more attempt.', N'Thử thêm một lần nữa.'),
(N'attend', N'/əˈtend/', N'tham dự', N'verb', N'BEGINNER', N'Attend the meeting on time.', N'Tham dự cuộc họp đúng giờ.'),
(N'attract', N'/əˈtrækt/', N'thu hút', N'verb', N'INTERMEDIATE', N'The city attracts many tourists.', N'Thành phố thu hút nhiều du khách.'),
(N'available', N'/əˈveɪləbəl/', N'có sẵn', N'adjective', N'BEGINNER', N'Is this seat available?', N'Ghế này có trống không?'),
(N'average', N'/ˈævərɪdʒ/', N'trung bình', N'adjective', N'BEGINNER', N'The average score is 75.', N'Điểm trung bình là 75.'),
(N'avoid', N'/əˈvɔɪd/', N'tránh né', N'verb', N'BEGINNER', N'Avoid eating junk food.', N'Tránh ăn đồ ăn vặt.'),
(N'aware', N'/əˈwer/', N'nhận thức được / biết', N'adjective', N'INTERMEDIATE', N'Be aware of your surroundings.', N'Hãy chú ý đến môi trường xung quanh.'),
(N'base', N'/beɪs/', N'cơ sở / nền tảng', N'noun', N'BEGINNER', N'Build a solid base.', N'Xây dựng nền tảng vững chắc.'),
(N'basic', N'/ˈbeɪsɪk/', N'cơ bản', N'adjective', N'BEGINNER', N'Learn the basic rules first.', N'Học các quy tắc cơ bản trước.'),
(N'basis', N'/ˈbeɪsɪs/', N'cơ sở', N'noun', N'INTERMEDIATE', N'On what basis did you decide?', N'Bạn quyết định trên cơ sở nào?'),
(N'beat', N'/biːt/', N'đánh bại / nhịp tim', N'verb', N'BEGINNER', N'Our team beat theirs.', N'Đội chúng tôi đánh bại họ.'),
(N'belong', N'/bɪˈlɒŋ/', N'thuộc về', N'verb', N'BEGINNER', N'This bag belongs to her.', N'Cái túi này thuộc về cô ấy.'),
(N'besides', N'/bɪˈsaɪdz/', N'ngoài ra', N'preposition', N'INTERMEDIATE', N'Besides work, she paints.', N'Ngoài công việc, cô ấy còn vẽ tranh.'),
(N'birth', N'/bɜːrθ/', N'sự ra đời / sinh', N'noun', N'BEGINNER', N'His birth was celebrated.', N'Ngày sinh của anh ấy được kỷ niệm.'),
(N'blame', N'/bleɪm/', N'đổ lỗi', N'verb', N'INTERMEDIATE', N'Don''t blame others for your problems.', N'Đừng đổ lỗi cho người khác vì vấn đề của bạn.'),
(N'bless', N'/bles/', N'ban phước', N'verb', N'BEGINNER', N'Bless you!', N'Chúc bạn mạnh khỏe!'),
(N'block', N'/blɒk/', N'khối / chặn', N'noun', N'BEGINNER', N'Walk two blocks north.', N'Đi hai khu nhà về phía bắc.'),
(N'blow', N'/bloʊ/', N'thổi', N'verb', N'BEGINNER', N'The wind blows from the north.', N'Gió thổi từ phía bắc.'),
(N'border', N'/ˈbɔːrdər/', N'biên giới', N'noun', N'INTERMEDIATE', N'Cross the border with your passport.', N'Qua biên giới với hộ chiếu của bạn.'),
(N'borrow', N'/ˈbɒroʊ/', N'mượn', N'verb', N'BEGINNER', N'Can I borrow your pen?', N'Tôi có thể mượn bút của bạn không?'),
(N'branch', N'/bræntʃ/', N'nhánh cây / chi nhánh', N'noun', N'BEGINNER', N'The bank has many branches.', N'Ngân hàng có nhiều chi nhánh.'),
(N'brief', N'/briːf/', N'ngắn gọn', N'adjective', N'INTERMEDIATE', N'Be brief in your answer.', N'Hãy trả lời ngắn gọn.'),
(N'bright', N'/braɪt/', N'sáng / thông minh', N'adjective', N'BEGINNER', N'She is a bright student.', N'Cô ấy là học sinh thông minh.'),
(N'broad', N'/brɔːd/', N'rộng lớn', N'adjective', N'INTERMEDIATE', N'He has a broad knowledge.', N'Anh ấy có kiến thức rộng lớn.'),
(N'broken', N'/ˈbroʊkən/', N'bị vỡ / hỏng', N'adjective', N'BEGINNER', N'The window is broken.', N'Cửa sổ bị vỡ.'),
(N'budget', N'/ˈbʌdʒɪt/', N'ngân sách', N'noun', N'INTERMEDIATE', N'Stay within the budget.', N'Giữ trong ngân sách.'),
(N'burden', N'/ˈbɜːrdən/', N'gánh nặng', N'noun', N'INTERMEDIATE', N'Share the burden with others.', N'Chia sẻ gánh nặng với người khác.'),
(N'capable', N'/ˈkeɪpəbəl/', N'có khả năng', N'adjective', N'INTERMEDIATE', N'She is capable of great things.', N'Cô ấy có khả năng làm những việc lớn.'),
(N'capture', N'/ˈkæptʃər/', N'nắm bắt / chụp lại', N'verb', N'INTERMEDIATE', N'Capture the moment on camera.', N'Chụp lại khoảnh khắc bằng máy ảnh.'),
(N'case', N'/keɪs/', N'trường hợp / vụ', N'noun', N'BEGINNER', N'In that case, let''s cancel.', N'Trong trường hợp đó, hãy hủy đi.'),
(N'cause', N'/kɔːz/', N'nguyên nhân / gây ra', N'noun', N'BEGINNER', N'What is the cause of the problem?', N'Nguyên nhân của vấn đề là gì?'),
(N'celebrate', N'/ˈselɪbreɪt/', N'kỷ niệm / ăn mừng', N'verb', N'BEGINNER', N'Let''s celebrate your success.', N'Hãy ăn mừng thành công của bạn.'),
(N'certain', N'/ˈsɜːrtən/', N'chắc chắn', N'adjective', N'BEGINNER', N'Are you certain about that?', N'Bạn có chắc chắn về điều đó không?'),
(N'chain', N'/tʃeɪn/', N'chuỗi / xích', N'noun', N'INTERMEDIATE', N'The chain of events was unexpected.', N'Chuỗi sự kiện thật bất ngờ.'),
(N'channel', N'/ˈtʃænəl/', N'kênh', N'noun', N'BEGINNER', N'Which channel do you watch?', N'Bạn xem kênh nào?'),
(N'chapter', N'/ˈtʃæptər/', N'chương (sách)', N'noun', N'BEGINNER', N'Read the first chapter tonight.', N'Đọc chương đầu tiên tối nay.'),
(N'charge', N'/tʃɑːrdʒ/', N'chi phí / buộc tội', N'noun', N'INTERMEDIATE', N'No extra charge for the service.', N'Không tính thêm phí cho dịch vụ.'),
(N'chart', N'/tʃɑːrt/', N'biểu đồ', N'noun', N'INTERMEDIATE', N'Show the data in a chart.', N'Hiển thị dữ liệu trong biểu đồ.'),
(N'citizen', N'/ˈsɪtɪzən/', N'công dân', N'noun', N'INTERMEDIATE', N'Every citizen has rights.', N'Mỗi công dân đều có quyền lợi.'),
(N'claim', N'/kleɪm/', N'yêu cầu / khẳng định', N'verb', N'INTERMEDIATE', N'He claims to be innocent.', N'Anh ấy khẳng định mình vô tội.'),
(N'closely', N'/ˈkloʊsli/', N'sát sao / cẩn thận', N'adverb', N'INTERMEDIATE', N'Watch closely.', N'Quan sát sát sao.'),
(N'collect', N'/kəˈlekt/', N'thu thập', N'verb', N'BEGINNER', N'Collect data for research.', N'Thu thập dữ liệu để nghiên cứu.'),
(N'combination', N'/ˌkɒmbɪˈneɪʃən/', N'sự kết hợp', N'noun', N'INTERMEDIATE', N'It''s a combination of skills.', N'Đó là sự kết hợp của các kỹ năng.'),
(N'commit', N'/kəˈmɪt/', N'cam kết / phạm (tội)', N'verb', N'INTERMEDIATE', N'Commit to your goals.', N'Cam kết với mục tiêu của bạn.'),
(N'common', N'/ˈkɒmən/', N'phổ biến / chung', N'adjective', N'BEGINNER', N'This is a common mistake.', N'Đây là lỗi phổ biến.'),
(N'compare', N'/kəmˈper/', N'so sánh', N'verb', N'BEGINNER', N'Compare prices before buying.', N'So sánh giá trước khi mua.'),
(N'complete', N'/kəmˈpliːt/', N'hoàn thành', N'verb', N'BEGINNER', N'Complete the task by noon.', N'Hoàn thành nhiệm vụ trước buổi trưa.'),
(N'concern', N'/kənˈsɜːrn/', N'mối lo ngại', N'noun', N'INTERMEDIATE', N'Express your concerns.', N'Hãy bày tỏ mối lo ngại.'),
(N'condition', N'/kənˈdɪʃən/', N'điều kiện / tình trạng', N'noun', N'INTERMEDIATE', N'The condition of the road is poor.', N'Tình trạng con đường rất kém.'),
(N'conduct', N'/ˈkɒndʌkt/', N'cách cư xử / tiến hành', N'noun', N'INTERMEDIATE', N'Professional conduct is expected.', N'Mọi người mong đợi cách cư xử chuyên nghiệp.'),
(N'consider', N'/kənˈsɪdər/', N'xem xét', N'verb', N'INTERMEDIATE', N'Consider all the options.', N'Hãy xem xét tất cả các lựa chọn.'),
(N'contact', N'/ˈkɒntækt/', N'liên hệ', N'verb', N'BEGINNER', N'Contact us for more info.', N'Liên hệ chúng tôi để biết thêm.'),
(N'context', N'/ˈkɒntekst/', N'ngữ cảnh / bối cảnh', N'noun', N'INTERMEDIATE', N'Read the word in context.', N'Đọc từ trong ngữ cảnh.'),
(N'contribute', N'/kənˈtrɪbjuːt/', N'đóng góp', N'verb', N'INTERMEDIATE', N'Contribute to the team effort.', N'Đóng góp vào nỗ lực của nhóm.'),
(N'copy', N'/ˈkɒpi/', N'bản sao / sao chép', N'noun', N'BEGINNER', N'Make a copy of the document.', N'Tạo bản sao của tài liệu.'),
(N'corner', N'/ˈkɔːrnər/', N'góc', N'noun', N'BEGINNER', N'Meet me at the corner.', N'Gặp tôi ở góc đường.'),
(N'correct', N'/kəˈrekt/', N'chính xác / đúng', N'adjective', N'BEGINNER', N'Is this the correct answer?', N'Đây có phải câu trả lời đúng không?'),
(N'cost', N'/kɒst/', N'chi phí', N'noun', N'BEGINNER', N'What is the cost of living?', N'Chi phí sinh hoạt là bao nhiêu?'),
(N'count', N'/kaʊnt/', N'đếm / tính đến', N'verb', N'BEGINNER', N'Count to ten.', N'Đếm đến mười.'),
(N'couple', N'/ˈkʌpəl/', N'cặp đôi / một vài', N'noun', N'BEGINNER', N'We need a couple more chairs.', N'Chúng ta cần thêm vài cái ghế nữa.'),
(N'cover', N'/ˈkʌvər/', N'che phủ / bao gồm', N'verb', N'BEGINNER', N'Cover the food with a lid.', N'Đậy thức ăn bằng nắp.'),
(N'create', N'/kriˈeɪt/', N'tạo ra', N'verb', N'BEGINNER', N'Create something new every day.', N'Tạo ra điều gì đó mới mỗi ngày.'),
(N'cross', N'/krɒs/', N'vượt qua / tức giận', N'verb', N'BEGINNER', N'Cross the street carefully.', N'Qua đường cẩn thận.'),
(N'crowd', N'/kraʊd/', N'đám đông', N'noun', N'BEGINNER', N'The crowd cheered loudly.', N'Đám đông歡呼 to.'),
(N'curious', N'/ˈkjʊəriəs/', N'tò mò', N'adjective', N'BEGINNER', N'Children are naturally curious.', N'Trẻ em tự nhiên tò mò.'),
(N'current', N'/ˈkɜːrənt/', N'hiện tại / dòng điện', N'adjective', N'INTERMEDIATE', N'The current situation is serious.', N'Tình hình hiện tại rất nghiêm trọng.'),
(N'custom', N'/ˈkʌstəm/', N'tục lệ / thói quen', N'noun', N'INTERMEDIATE', N'Respect local customs.', N'Tôn trọng phong tục địa phương.'),
(N'damage', N'/ˈdæmɪdʒ/', N'thiệt hại / làm hư hỏng', N'noun', N'INTERMEDIATE', N'The storm caused damage.', N'Cơn bão gây thiệt hại.'),
(N'deal', N'/diːl/', N'thỏa thuận / xử lý', N'noun', N'INTERMEDIATE', N'We made a good deal.', N'Chúng tôi đã đạt được thỏa thuận tốt.'),
(N'debate', N'/dɪˈbeɪt/', N'tranh luận', N'noun', N'INTERMEDIATE', N'The debate lasted two hours.', N'Cuộc tranh luận kéo dài hai tiếng.'),
(N'declare', N'/dɪˈkler/', N'tuyên bố', N'verb', N'INTERMEDIATE', N'Declare your income honestly.', N'Khai báo thu nhập thành thật.'),
(N'decrease', N'/dɪˈkriːs/', N'giảm', N'verb', N'INTERMEDIATE', N'Sales decreased this quarter.', N'Doanh số giảm trong quý này.'),
(N'defeat', N'/dɪˈfiːt/', N'đánh bại / thất bại', N'verb', N'INTERMEDIATE', N'They were defeated in the final.', N'Họ bị đánh bại ở vòng chung kết.'),
(N'define', N'/dɪˈfaɪn/', N'định nghĩa', N'verb', N'INTERMEDIATE', N'Define the key terms first.', N'Định nghĩa các thuật ngữ chính trước.'),
(N'delay', N'/dɪˈleɪ/', N'trì hoãn / sự chậm trễ', N'noun', N'INTERMEDIATE', N'The flight has a delay.', N'Chuyến bay bị trễ.'),
(N'deliver', N'/dɪˈlɪvər/', N'giao hàng / trình bày', N'verb', N'INTERMEDIATE', N'Deliver the package today.', N'Giao gói hàng hôm nay.'),
(N'deny', N'/dɪˈnaɪ/', N'phủ nhận', N'verb', N'INTERMEDIATE', N'He denied the accusation.', N'Anh ấy phủ nhận cáo buộc.'),
(N'deserve', N'/dɪˈzɜːrv/', N'xứng đáng', N'verb', N'INTERMEDIATE', N'You deserve the best.', N'Bạn xứng đáng được điều tốt nhất.'),
(N'design', N'/dɪˈzaɪn/', N'thiết kế', N'noun', N'BEGINNER', N'The design looks beautiful.', N'Thiết kế trông đẹp.'),
(N'destroy', N'/dɪˈstrɔɪ/', N'phá hủy', N'verb', N'INTERMEDIATE', N'Fire destroyed the building.', N'Lửa đã phá hủy tòa nhà.'),
(N'detail', N'/ˈdiːteɪl/', N'chi tiết', N'noun', N'BEGINNER', N'Pay attention to the details.', N'Chú ý đến chi tiết.'),
(N'differ', N'/ˈdɪfər/', N'khác nhau', N'verb', N'INTERMEDIATE', N'Our opinions differ.', N'Ý kiến chúng tôi khác nhau.'),
(N'direct', N'/daɪˈrekt/', N'trực tiếp / chỉ đạo', N'adjective', N'BEGINNER', N'Take the direct route.', N'Đi đường thẳng.'),
(N'disappear', N'/ˌdɪsəˈpɪər/', N'biến mất', N'verb', N'BEGINNER', N'The fog will disappear by noon.', N'Sương mù sẽ tan vào buổi trưa.'),
(N'discover', N'/dɪˈskʌvər/', N'khám phá / phát hiện', N'verb', N'BEGINNER', N'Discover new things every day.', N'Khám phá điều mới mỗi ngày.'),
(N'display', N'/dɪˈspleɪ/', N'hiển thị / trưng bày', N'verb', N'INTERMEDIATE', N'Display the artwork in the gallery.', N'Trưng bày tác phẩm trong phòng triển lãm.'),
(N'distance', N'/ˈdɪstəns/', N'khoảng cách', N'noun', N'BEGINNER', N'What is the distance to the city?', N'Khoảng cách đến thành phố là bao xa?'),
(N'doubt', N'/daʊt/', N'nghi ngờ', N'noun', N'INTERMEDIATE', N'I have no doubt about it.', N'Tôi không nghi ngờ gì về điều đó.'),
(N'drop', N'/drɒp/', N'rơi / giọt', N'verb', N'BEGINNER', N'Don''t drop the phone.', N'Đừng làm rơi điện thoại.'),
(N'due', N'/djuː/', N'đến hạn / phải trả', N'adjective', N'INTERMEDIATE', N'The report is due tomorrow.', N'Báo cáo đến hạn vào ngày mai.'),
(N'duty', N'/ˈdjuːti/', N'nghĩa vụ / nhiệm vụ', N'noun', N'INTERMEDIATE', N'It is my duty to help.', N'Giúp đỡ là nghĩa vụ của tôi.'),
(N'earn', N'/ɜːrn/', N'kiếm được', N'verb', N'BEGINNER', N'Earn money by working hard.', N'Kiếm tiền bằng cách làm việc chăm chỉ.'),
(N'educate', N'/ˈedʒʊkeɪt/', N'giáo dục', N'verb', N'BEGINNER', N'Educate yourself every day.', N'Tự giáo dục bản thân mỗi ngày.'),
(N'effect', N'/ɪˈfekt/', N'tác dụng / hiệu quả', N'noun', N'INTERMEDIATE', N'The medicine had no effect.', N'Thuốc không có tác dụng.'),
(N'emergency', N'/ɪˈmɜːrdʒənsi/', N'trường hợp khẩn cấp', N'noun', N'INTERMEDIATE', N'Call 113 in an emergency.', N'Gọi 113 trong trường hợp khẩn cấp.'),
(N'enable', N'/ɪˈneɪbəl/', N'cho phép / tạo điều kiện', N'verb', N'INTERMEDIATE', N'Technology enables remote work.', N'Công nghệ tạo điều kiện làm việc từ xa.'),
(N'encourage', N'/ɪnˈkɜːrɪdʒ/', N'khuyến khích', N'verb', N'INTERMEDIATE', N'Encourage others to do their best.', N'Khuyến khích người khác làm hết sức mình.'),
(N'energy', N'/ˈenədʒi/', N'năng lượng', N'noun', N'BEGINNER', N'Exercise gives you more energy.', N'Tập thể dục cho bạn thêm năng lượng.'),
(N'engage', N'/ɪnˈɡeɪdʒ/', N'tham gia / gắn kết', N'verb', N'INTERMEDIATE', N'Engage with your customers.', N'Gắn kết với khách hàng của bạn.'),
(N'enhance', N'/ɪnˈhɑːns/', N'tăng cường / cải thiện', N'verb', N'INTERMEDIATE', N'Enhance your skills daily.', N'Cải thiện kỹ năng mỗi ngày.'),
(N'ensure', N'/ɪnˈʃʊər/', N'đảm bảo', N'verb', N'INTERMEDIATE', N'Ensure quality in every product.', N'Đảm bảo chất lượng trong mọi sản phẩm.'),
(N'entire', N'/ɪnˈtaɪər/', N'toàn bộ', N'adjective', N'INTERMEDIATE', N'I read the entire book.', N'Tôi đọc toàn bộ cuốn sách.'),
(N'equal', N'/ˈiːkwəl/', N'bình đẳng / bằng nhau', N'adjective', N'BEGINNER', N'All people are equal.', N'Mọi người đều bình đẳng.'),
(N'establish', N'/ɪˈstæblɪʃ/', N'thành lập / thiết lập', N'verb', N'INTERMEDIATE', N'Establish rules from the start.', N'Thiết lập quy tắc từ đầu.'),
(N'even', N'/ˈiːvən/', N'thậm chí / bằng phẳng', N'adverb', N'BEGINNER', N'Even a child can do this.', N'Thậm chí một đứa trẻ cũng có thể làm điều này.'),
(N'event', N'/ɪˈvent/', N'sự kiện', N'noun', N'BEGINNER', N'The event starts at 7 pm.', N'Sự kiện bắt đầu lúc 7 giờ tối.'),
(N'eventually', N'/ɪˈventʃuəli/', N'cuối cùng', N'adverb', N'INTERMEDIATE', N'He eventually succeeded.', N'Cuối cùng anh ấy đã thành công.'),
(N'except', N'/ɪkˈsept/', N'ngoại trừ', N'preposition', N'BEGINNER', N'Everyone except me was there.', N'Mọi người ngoại trừ tôi đều có mặt.'),
(N'exist', N'/ɪɡˈzɪst/', N'tồn tại', N'verb', N'INTERMEDIATE', N'Does life exist on other planets?', N'Có sự sống tồn tại trên các hành tinh khác không?'),
(N'expand', N'/ɪkˈspænd/', N'mở rộng', N'verb', N'INTERMEDIATE', N'Expand your business globally.', N'Mở rộng kinh doanh toàn cầu.'),
(N'expect', N'/ɪkˈspekt/', N'mong đợi / kỳ vọng', N'verb', N'BEGINNER', N'I expect you to be on time.', N'Tôi kỳ vọng bạn đúng giờ.'),
(N'express', N'/ɪkˈspres/', N'thể hiện / bày tỏ', N'verb', N'INTERMEDIATE', N'Express yourself clearly.', N'Bày tỏ bản thân một cách rõ ràng.'),
(N'extend', N'/ɪkˈstend/', N'mở rộng / kéo dài', N'verb', N'INTERMEDIATE', N'Extend the deadline by one week.', N'Gia hạn thêm một tuần.'),
(N'extra', N'/ˈekstrə/', N'thêm / bổ sung', N'adjective', N'BEGINNER', N'Can I have extra sauce?', N'Cho tôi thêm nước sốt được không?'),
(N'factor', N'/ˈfæktər/', N'yếu tố', N'noun', N'INTERMEDIATE', N'Cost is an important factor.', N'Chi phí là yếu tố quan trọng.'),
(N'familiar', N'/fəˈmɪliər/', N'quen thuộc', N'adjective', N'INTERMEDIATE', N'Are you familiar with this topic?', N'Bạn có quen với chủ đề này không?'),
(N'feature', N'/ˈfiːtʃər/', N'tính năng / đặc điểm', N'noun', N'INTERMEDIATE', N'The best feature is the camera.', N'Tính năng tốt nhất là máy ảnh.'),
(N'field', N'/fiːld/', N'lĩnh vực / cánh đồng', N'noun', N'INTERMEDIATE', N'She works in the medical field.', N'Cô ấy làm việc trong lĩnh vực y tế.'),
(N'firm', N'/fɜːrm/', N'vững chắc / công ty', N'adjective', N'INTERMEDIATE', N'Be firm in your decisions.', N'Hãy kiên định trong các quyết định.'),
(N'follow', N'/ˈfɒloʊ/', N'theo / tuân theo', N'verb', N'BEGINNER', N'Follow the instructions.', N'Theo hướng dẫn.'),
(N'force', N'/fɔːrs/', N'lực / ép buộc', N'noun', N'INTERMEDIATE', N'Don''t force others to agree.', N'Đừng ép buộc người khác đồng ý.'),
(N'formal', N'/ˈfɔːrməl/', N'trang trọng / chính thức', N'adjective', N'INTERMEDIATE', N'Wear formal clothes to the interview.', N'Mặc quần áo trang trọng đến buổi phỏng vấn.'),
(N'form', N'/fɔːrm/', N'hình thức / biểu mẫu', N'noun', N'BEGINNER', N'Fill in the form completely.', N'Điền đầy đủ vào biểu mẫu.'),
(N'forward', N'/ˈfɔːrwərd/', N'tiến về phía trước', N'adverb', N'BEGINNER', N'Move forward with confidence.', N'Tiến về phía trước với sự tự tin.'),
(N'frequent', N'/ˈfriːkwənt/', N'thường xuyên', N'adjective', N'INTERMEDIATE', N'Make frequent visits to the doctor.', N'Thường xuyên đến gặp bác sĩ.'),
(N'function', N'/ˈfʌŋkʃən/', N'chức năng / hoạt động', N'noun', N'INTERMEDIATE', N'What is the function of this button?', N'Chức năng của nút này là gì?'),
(N'fund', N'/fʌnd/', N'quỹ / tài trợ', N'noun', N'INTERMEDIATE', N'Raise funds for charity.', N'Gây quỹ từ thiện.'),
(N'gap', N'/ɡæp/', N'khoảng cách / lỗ hổng', N'noun', N'INTERMEDIATE', N'Bridge the knowledge gap.', N'Thu hẹp khoảng cách kiến thức.'),
(N'gather', N'/ˈɡæðər/', N'tụ tập / thu thập', N'verb', N'INTERMEDIATE', N'Gather all the facts first.', N'Thu thập tất cả sự thật trước.'),
(N'global', N'/ˈɡloʊbəl/', N'toàn cầu', N'adjective', N'INTERMEDIATE', N'Climate change is a global issue.', N'Biến đổi khí hậu là vấn đề toàn cầu.'),
(N'grant', N'/ɡrænt/', N'trao / cấp phép', N'verb', N'INTERMEDIATE', N'The company granted a raise.', N'Công ty đã tăng lương.'),
(N'grave', N'/ɡreɪv/', N'nghiêm trọng / mộ', N'adjective', N'INTERMEDIATE', N'This is a grave situation.', N'Đây là tình huống nghiêm trọng.'),
(N'grow', N'/ɡroʊ/', N'lớn lên / phát triển', N'verb', N'BEGINNER', N'Children grow up so fast.', N'Trẻ em lớn lên rất nhanh.'),
(N'guarantee', N'/ˌɡærənˈtiː/', N'bảo đảm', N'verb', N'INTERMEDIATE', N'I guarantee the quality.', N'Tôi đảm bảo chất lượng.'),
(N'guide', N'/ɡaɪd/', N'hướng dẫn / người dẫn đường', N'noun', N'BEGINNER', N'Follow the guide.', N'Theo hướng dẫn viên.'),
(N'guilty', N'/ˈɡɪlti/', N'có tội', N'adjective', N'INTERMEDIATE', N'He was found guilty.', N'Anh ấy bị tuyên bố có tội.'),
(N'habit', N'/ˈhæbɪt/', N'thói quen', N'noun', N'BEGINNER', N'Develop good habits early.', N'Phát triển thói quen tốt sớm.'),
(N'happen', N'/ˈhæpən/', N'xảy ra', N'verb', N'BEGINNER', N'What happened last night?', N'Chuyện gì đã xảy ra tối qua?'),
(N'harm', N'/hɑːrm/', N'gây hại', N'verb', N'INTERMEDIATE', N'Smoking harms your health.', N'Hút thuốc gây hại cho sức khỏe.'),
(N'highlight', N'/ˈhaɪlaɪt/', N'nhấn mạnh / điểm nổi bật', N'verb', N'INTERMEDIATE', N'Highlight key information.', N'Nhấn mạnh thông tin quan trọng.'),
(N'host', N'/hoʊst/', N'chủ nhà / tổ chức', N'noun', N'INTERMEDIATE', N'She is the host of the show.', N'Cô ấy là người dẫn chương trình.'),
(N'identify', N'/aɪˈdentɪfaɪ/', N'xác định / nhận dạng', N'verb', N'INTERMEDIATE', N'Identify the main problem.', N'Xác định vấn đề chính.'),
(N'image', N'/ˈɪmɪdʒ/', N'hình ảnh', N'noun', N'BEGINNER', N'The image is very clear.', N'Hình ảnh rất rõ.'),
(N'income', N'/ˈɪnkʌm/', N'thu nhập', N'noun', N'INTERMEDIATE', N'Increase your income with skills.', N'Tăng thu nhập bằng kỹ năng.'),
(N'increase', N'/ɪnˈkriːs/', N'tăng lên', N'verb', N'BEGINNER', N'Increase your savings each month.', N'Tăng tiết kiệm mỗi tháng.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('absent','abroad','accident','account','ache','address','adult','advice','afraid','age','agree','ahead','aim','alarm','allow','alone','amount','ancient','another','apart','appear','apply','approach','area','argue','arise','arrange','arrest','article','assist','attach','attempt','attend','attract','available','average','avoid','aware','base','basic','basis','beat','belong','besides','birth','blame','bless','block','blow','border','borrow','branch','brief','bright','broad','broken','budget','burden','capable','capture','case','cause','celebrate','certain','chain','channel','chapter','charge','chart','citizen','claim','closely','collect','combination','commit','common','compare','complete','concern','condition','conduct','consider','contact','context','contribute','copy','corner','correct','cost','count','couple','cover','create','cross','crowd','curious','current','custom','damage','deal','debate','declare','decrease','defeat','define','delay','deliver','deny','deserve','design','destroy','detail','differ','direct','disappear','discover','display','distance','doubt','drop','due','duty','earn','educate','effect','emergency','enable','encourage','energy','engage','enhance','ensure','entire','equal','establish','even','event','eventually','except','exist','expand','expect','express','extend','extra','factor','familiar','feature','field','firm','follow','force','formal','form','forward','frequent','function','fund','gap','gather','global','grant','grave','grow','guarantee','guide','guilty','habit','happen','harm','highlight','host','identify','image','income','increase');
