--liquibase formatted sql

--changeset vocab:025-seed-words-batch18
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.example_sentence, v.example_translation
FROM (VALUES
-- Common words I-L
(N'indicate', N'/ˈɪndɪkeɪt/', N'chỉ ra / cho thấy', N'verb', N'INTERMEDIATE', N'The sign indicates the exit.', N'Biển báo chỉ ra lối thoát.'),
(N'individual', N'/ˌɪndɪˈvɪdʒuəl/', N'cá nhân', N'noun', N'INTERMEDIATE', N'Each individual has rights.', N'Mỗi cá nhân đều có quyền.'),
(N'influence', N'/ˈɪnfluəns/', N'ảnh hưởng', N'noun', N'INTERMEDIATE', N'Music has a big influence on mood.', N'Âm nhạc có ảnh hưởng lớn đến tâm trạng.'),
(N'inform', N'/ɪnˈfɔːrm/', N'thông báo', N'verb', N'BEGINNER', N'Inform the team about the change.', N'Thông báo cho nhóm về sự thay đổi.'),
(N'injury', N'/ˈɪndʒəri/', N'chấn thương', N'noun', N'BEGINNER', N'The injury healed after two weeks.', N'Vết thương lành sau hai tuần.'),
(N'innocent', N'/ˈɪnəsənt/', N'vô tội', N'adjective', N'INTERMEDIATE', N'She was found innocent.', N'Cô ấy được tuyên bố vô tội.'),
(N'instance', N'/ˈɪnstəns/', N'ví dụ / trường hợp', N'noun', N'INTERMEDIATE', N'In this instance, we made an exception.', N'Trong trường hợp này, chúng tôi đã ngoại lệ.'),
(N'instead', N'/ɪnˈsted/', N'thay vào đó', N'adverb', N'BEGINNER', N'Use butter instead of oil.', N'Dùng bơ thay vì dầu.'),
(N'intend', N'/ɪnˈtend/', N'dự định', N'verb', N'INTERMEDIATE', N'I intend to finish by Monday.', N'Tôi dự định hoàn thành vào thứ Hai.'),
(N'interest', N'/ˈɪntrəst/', N'sự quan tâm / lãi suất', N'noun', N'BEGINNER', N'She has a great interest in art.', N'Cô ấy rất quan tâm đến nghệ thuật.'),
(N'involve', N'/ɪnˈvɒlv/', N'liên quan đến', N'verb', N'INTERMEDIATE', N'The project involves many people.', N'Dự án liên quan đến nhiều người.'),
(N'issue', N'/ˈɪʃuː/', N'vấn đề / số phát hành', N'noun', N'INTERMEDIATE', N'Address the issue immediately.', N'Giải quyết vấn đề ngay lập tức.'),
(N'join', N'/dʒɔɪn/', N'tham gia', N'verb', N'BEGINNER', N'Join us for dinner tonight.', N'Tham gia ăn tối cùng chúng tôi tối nay.'),
(N'journey', N'/ˈdʒɜːrni/', N'cuộc hành trình', N'noun', N'BEGINNER', N'The journey took three hours.', N'Cuộc hành trình mất ba giờ.'),
(N'judge', N'/dʒʌdʒ/', N'phán xét / thẩm phán', N'verb', N'INTERMEDIATE', N'Don''t judge a book by its cover.', N'Đừng đánh giá qua vẻ ngoài.'),
(N'justice', N'/ˈdʒʌstɪs/', N'công lý', N'noun', N'INTERMEDIATE', N'Fight for justice and equality.', N'Đấu tranh vì công lý và bình đẳng.'),
(N'keen', N'/kiːn/', N'nhiệt tình / sắc bén', N'adjective', N'INTERMEDIATE', N'She is keen to learn new skills.', N'Cô ấy nhiệt tình học kỹ năng mới.'),
(N'key', N'/kiː/', N'chìa khóa / quan trọng', N'noun', N'BEGINNER', N'Communication is the key to success.', N'Giao tiếp là chìa khóa thành công.'),
(N'lack', N'/læk/', N'thiếu hụt', N'noun', N'INTERMEDIATE', N'A lack of sleep affects health.', N'Thiếu ngủ ảnh hưởng đến sức khỏe.'),
(N'launch', N'/lɔːntʃ/', N'ra mắt / khởi động', N'verb', N'INTERMEDIATE', N'They will launch the product next month.', N'Họ sẽ ra mắt sản phẩm tháng tới.'),
(N'layer', N'/ˈleɪər/', N'lớp', N'noun', N'INTERMEDIATE', N'Add another layer of paint.', N'Thêm một lớp sơn nữa.'),
(N'lead', N'/liːd/', N'dẫn đầu / lãnh đạo', N'verb', N'BEGINNER', N'She will lead the project.', N'Cô ấy sẽ dẫn đầu dự án.'),
(N'length', N'/leŋθ/', N'chiều dài', N'noun', N'BEGINNER', N'What is the length of the table?', N'Chiều dài của cái bàn là bao nhiêu?'),
(N'level', N'/ˈlevəl/', N'mức độ / cấp độ', N'noun', N'BEGINNER', N'Set the difficulty level.', N'Đặt cấp độ khó.'),
(N'likely', N'/ˈlaɪkli/', N'có khả năng', N'adjective', N'INTERMEDIATE', N'It is likely to rain today.', N'Hôm nay có khả năng mưa.'),
(N'limit', N'/ˈlɪmɪt/', N'giới hạn', N'noun', N'BEGINNER', N'There is a speed limit here.', N'Có giới hạn tốc độ ở đây.'),
(N'link', N'/lɪŋk/', N'liên kết', N'noun', N'BEGINNER', N'Click the link to open the page.', N'Nhấp liên kết để mở trang.'),
(N'local', N'/ˈloʊkəl/', N'địa phương', N'adjective', N'BEGINNER', N'Buy from local markets.', N'Mua hàng từ chợ địa phương.'),
(N'locate', N'/loʊˈkeɪt/', N'xác định vị trí', N'verb', N'INTERMEDIATE', N'Locate the nearest hospital.', N'Xác định bệnh viện gần nhất.'),
(N'loss', N'/lɒs/', N'sự mất mát / thua lỗ', N'noun', N'INTERMEDIATE', N'The company suffered a big loss.', N'Công ty chịu tổn thất lớn.'),
-- Common words M-N
(N'maintain', N'/meɪnˈteɪn/', N'duy trì', N'verb', N'INTERMEDIATE', N'Maintain a healthy lifestyle.', N'Duy trì lối sống lành mạnh.'),
(N'major', N'/ˈmeɪdʒər/', N'lớn / chuyên ngành', N'adjective', N'INTERMEDIATE', N'This is a major decision.', N'Đây là quyết định lớn.'),
(N'manner', N'/ˈmænər/', N'cách thức / thái độ', N'noun', N'INTERMEDIATE', N'Speak in a polite manner.', N'Nói chuyện theo cách lịch sự.'),
(N'matter', N'/ˈmætər/', N'vấn đề / quan trọng', N'noun', N'BEGINNER', N'It doesn''t matter what they think.', N'Họ nghĩ gì cũng không quan trọng.'),
(N'means', N'/miːnz/', N'phương tiện / nghĩa là', N'noun', N'INTERMEDIATE', N'Find the means to solve it.', N'Tìm phương tiện để giải quyết.'),
(N'mention', N'/ˈmenʃən/', N'đề cập', N'verb', N'INTERMEDIATE', N'Don''t forget to mention the date.', N'Đừng quên đề cập đến ngày tháng.'),
(N'method', N'/ˈmeθəd/', N'phương pháp', N'noun', N'INTERMEDIATE', N'Use the scientific method.', N'Sử dụng phương pháp khoa học.'),
(N'mind', N'/maɪnd/', N'tâm trí / để ý', N'noun', N'BEGINNER', N'Keep an open mind.', N'Hãy giữ tư duy cởi mở.'),
(N'minor', N'/ˈmaɪnər/', N'nhỏ / thứ yếu', N'adjective', N'INTERMEDIATE', N'It is only a minor issue.', N'Đó chỉ là vấn đề nhỏ.'),
(N'miss', N'/mɪs/', N'nhớ / bỏ lỡ', N'verb', N'BEGINNER', N'I miss my family a lot.', N'Tôi rất nhớ gia đình.'),
(N'model', N'/ˈmɒdəl/', N'mô hình / người mẫu', N'noun', N'INTERMEDIATE', N'This model shows the data clearly.', N'Mô hình này hiển thị dữ liệu rõ ràng.'),
(N'moment', N'/ˈmoʊmənt/', N'khoảnh khắc', N'noun', N'BEGINNER', N'Enjoy every moment of life.', N'Tận hưởng từng khoảnh khắc của cuộc sống.'),
(N'moreover', N'/mɔːrˈoʊvər/', N'hơn nữa', N'adverb', N'INTERMEDIATE', N'Moreover, the price is reasonable.', N'Hơn nữa, giá cả hợp lý.'),
(N'movement', N'/ˈmuːvmənt/', N'phong trào / chuyển động', N'noun', N'INTERMEDIATE', N'A social movement for change.', N'Phong trào xã hội vì sự thay đổi.'),
(N'mutual', N'/ˈmjuːtʃuəl/', N'lẫn nhau / chung', N'adjective', N'INTERMEDIATE', N'It was a mutual decision.', N'Đó là quyết định chung.'),
(N'narrow', N'/ˈnæroʊ/', N'hẹp / thu hẹp', N'adjective', N'BEGINNER', N'The road is very narrow here.', N'Con đường rất hẹp ở đây.'),
(N'natural', N'/ˈnætʃrəl/', N'tự nhiên', N'adjective', N'BEGINNER', N'Use natural ingredients.', N'Dùng nguyên liệu tự nhiên.'),
(N'necessary', N'/ˈnesəseri/', N'cần thiết', N'adjective', N'BEGINNER', N'Sleep is necessary for good health.', N'Ngủ là điều cần thiết cho sức khỏe tốt.'),
(N'negative', N'/ˈneɡətɪv/', N'tiêu cực', N'adjective', N'BEGINNER', N'Avoid negative thinking.', N'Tránh suy nghĩ tiêu cực.'),
(N'network', N'/ˈnetwɜːrk/', N'mạng lưới', N'noun', N'INTERMEDIATE', N'Build a strong professional network.', N'Xây dựng mạng lưới chuyên nghiệp mạnh.'),
(N'notice', N'/ˈnoʊtɪs/', N'chú ý / thông báo', N'verb', N'BEGINNER', N'Did you notice the change?', N'Bạn có nhận thấy sự thay đổi không?'),
(N'numerous', N'/ˈnjuːmərəs/', N'nhiều / vô số', N'adjective', N'INTERMEDIATE', N'There are numerous options available.', N'Có rất nhiều lựa chọn.'),
-- Common words O-P
(N'object', N'/ˈɒbdʒɪkt/', N'vật thể / phản đối', N'noun', N'BEGINNER', N'What is that object on the table?', N'Vật gì trên bàn vậy?'),
(N'observe', N'/əbˈzɜːrv/', N'quan sát', N'verb', N'INTERMEDIATE', N'Observe the students carefully.', N'Quan sát học sinh cẩn thận.'),
(N'obtain', N'/əbˈteɪn/', N'đạt được / có được', N'verb', N'INTERMEDIATE', N'Obtain permission before entering.', N'Xin phép trước khi vào.'),
(N'occur', N'/əˈkɜːr/', N'xảy ra', N'verb', N'INTERMEDIATE', N'Accidents occur when we least expect.', N'Tai nạn xảy ra khi chúng ta ít ngờ nhất.'),
(N'offer', N'/ˈɒfər/', N'đề nghị / cung cấp', N'verb', N'BEGINNER', N'She offered to help us.', N'Cô ấy đề nghị giúp chúng tôi.'),
(N'oppose', N'/əˈpoʊz/', N'phản đối', N'verb', N'INTERMEDIATE', N'Many people oppose the new law.', N'Nhiều người phản đối luật mới.'),
(N'option', N'/ˈɒpʃən/', N'lựa chọn', N'noun', N'INTERMEDIATE', N'You have two options to choose from.', N'Bạn có hai lựa chọn.'),
(N'outcome', N'/ˈaʊtkʌm/', N'kết quả / kết cục', N'noun', N'INTERMEDIATE', N'The outcome was better than expected.', N'Kết quả tốt hơn mong đợi.'),
(N'overcome', N'/ˌoʊvərˈkʌm/', N'vượt qua', N'verb', N'INTERMEDIATE', N'Overcome your fear step by step.', N'Vượt qua nỗi sợ từng bước một.'),
(N'pattern', N'/ˈpætərn/', N'mẫu / hoa văn', N'noun', N'INTERMEDIATE', N'I see a pattern in the data.', N'Tôi thấy một mẫu trong dữ liệu.'),
(N'percent', N'/pərˈsent/', N'phần trăm', N'noun', N'BEGINNER', N'Fifty percent of students passed.', N'Năm mươi phần trăm học sinh đậu.'),
(N'perform', N'/pərˈfɔːrm/', N'thực hiện / biểu diễn', N'verb', N'INTERMEDIATE', N'The team performed well today.', N'Đội thực hiện tốt hôm nay.'),
(N'perhaps', N'/pərˈhæps/', N'có lẽ', N'adverb', N'BEGINNER', N'Perhaps we can meet tomorrow.', N'Có lẽ chúng ta có thể gặp ngày mai.'),
(N'permit', N'/pərˈmɪt/', N'cho phép', N'verb', N'INTERMEDIATE', N'Smoking is not permitted here.', N'Không được phép hút thuốc ở đây.'),
(N'physical', N'/ˈfɪzɪkəl/', N'thể chất / vật lý', N'adjective', N'INTERMEDIATE', N'Physical exercise is important.', N'Tập thể dục rất quan trọng.'),
(N'position', N'/pəˈzɪʃən/', N'vị trí / chức vụ', N'noun', N'INTERMEDIATE', N'She holds a high position.', N'Cô ấy giữ chức vụ cao.'),
(N'positive', N'/ˈpɒzɪtɪv/', N'tích cực', N'adjective', N'BEGINNER', N'Stay positive in hard times.', N'Hãy tích cực trong thời gian khó khăn.'),
(N'possible', N'/ˈpɒsɪbəl/', N'có thể', N'adjective', N'BEGINNER', N'Everything is possible with effort.', N'Mọi thứ đều có thể với nỗ lực.'),
(N'potential', N'/pəˈtenʃəl/', N'tiềm năng', N'noun', N'INTERMEDIATE', N'She has great potential.', N'Cô ấy có tiềm năng lớn.'),
(N'prepare', N'/prɪˈpeər/', N'chuẩn bị', N'verb', N'BEGINNER', N'Prepare for the interview.', N'Chuẩn bị cho buổi phỏng vấn.'),
(N'present', N'/ˈprezənt/', N'hiện tại / quà tặng', N'noun', N'BEGINNER', N'Live in the present moment.', N'Sống trong khoảnh khắc hiện tại.'),
(N'prevent', N'/prɪˈvent/', N'ngăn ngừa', N'verb', N'INTERMEDIATE', N'Wash hands to prevent illness.', N'Rửa tay để ngăn ngừa bệnh tật.'),
(N'previous', N'/ˈpriːviəs/', N'trước đó', N'adjective', N'INTERMEDIATE', N'The previous version was better.', N'Phiên bản trước tốt hơn.'),
(N'primary', N'/ˈpraɪmeri/', N'chính / sơ cấp', N'adjective', N'INTERMEDIATE', N'The primary goal is to learn.', N'Mục tiêu chính là học hỏi.'),
(N'principle', N'/ˈprɪnsɪpəl/', N'nguyên tắc', N'noun', N'INTERMEDIATE', N'Stick to your principles.', N'Gắn bó với nguyên tắc của bạn.'),
(N'priority', N'/praɪˈɒrɪti/', N'ưu tiên', N'noun', N'INTERMEDIATE', N'Health should be your top priority.', N'Sức khỏe nên là ưu tiên hàng đầu.'),
(N'proceed', N'/prəˈsiːd/', N'tiến hành', N'verb', N'INTERMEDIATE', N'Proceed with the plan.', N'Tiến hành theo kế hoạch.'),
(N'process', N'/ˈprɒses/', N'quy trình / xử lý', N'noun', N'INTERMEDIATE', N'The hiring process takes two weeks.', N'Quy trình tuyển dụng mất hai tuần.'),
(N'produce', N'/prəˈdjuːs/', N'sản xuất', N'verb', N'INTERMEDIATE', N'The factory produces 1000 units daily.', N'Nhà máy sản xuất 1000 đơn vị mỗi ngày.'),
(N'progress', N'/ˈprɒɡres/', N'tiến bộ', N'noun', N'INTERMEDIATE', N'Track your progress every week.', N'Theo dõi tiến bộ mỗi tuần.'),
(N'proper', N'/ˈprɒpər/', N'đúng đắn / thích hợp', N'adjective', N'INTERMEDIATE', N'Follow the proper procedure.', N'Thực hiện đúng quy trình.'),
(N'protect', N'/prəˈtekt/', N'bảo vệ', N'verb', N'BEGINNER', N'Protect your skin from the sun.', N'Bảo vệ da khỏi ánh nắng.'),
(N'prove', N'/pruːv/', N'chứng minh', N'verb', N'INTERMEDIATE', N'Prove your point with evidence.', N'Chứng minh quan điểm bằng bằng chứng.'),
(N'provide', N'/prəˈvaɪd/', N'cung cấp', N'verb', N'INTERMEDIATE', N'The school provides free lunch.', N'Trường cung cấp bữa trưa miễn phí.'),
(N'publish', N'/ˈpʌblɪʃ/', N'xuất bản / công bố', N'verb', N'INTERMEDIATE', N'She will publish her first book.', N'Cô ấy sẽ xuất bản cuốn sách đầu tiên.'),
(N'purpose', N'/ˈpɜːrpəs/', N'mục đích', N'noun', N'INTERMEDIATE', N'Find your purpose in life.', N'Tìm mục đích của bạn trong cuộc sống.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('indicate','individual','influence','inform','injury','innocent','instance','instead','intend','interest','involve','issue','join','journey','judge','justice','keen','key','lack','launch','layer','lead','length','level','likely','limit','link','local','locate','loss','maintain','major','manner','matter','means','mention','method','mind','minor','miss','model','moment','moreover','movement','mutual','narrow','natural','necessary','negative','network','notice','numerous','object','observe','obtain','occur','offer','oppose','option','outcome','overcome','pattern','percent','perform','perhaps','permit','physical','position','positive','possible','potential','prepare','present','prevent','previous','primary','principle','priority','proceed','process','produce','progress','proper','protect','prove','provide','publish','purpose');
