--liquibase formatted sql

--changeset vocab:026-seed-words-batch19
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.example_sentence, v.example_translation
FROM (VALUES
-- Common words Q-R
(N'qualify', N'/ˈkwɒlɪfaɪ/', N'đủ điều kiện', N'verb', N'INTERMEDIATE', N'You must qualify for the position.', N'Bạn phải đủ điều kiện cho vị trí đó.'),
(N'quantity', N'/ˈkwɒntɪti/', N'số lượng', N'noun', N'INTERMEDIATE', N'Check the quantity before ordering.', N'Kiểm tra số lượng trước khi đặt hàng.'),
(N'question', N'/ˈkwestʃən/', N'câu hỏi', N'noun', N'BEGINNER', N'Ask questions if you don''t understand.', N'Hãy hỏi nếu bạn không hiểu.'),
(N'raise', N'/reɪz/', N'nâng lên / đặt ra', N'verb', N'BEGINNER', N'Raise your hand to answer.', N'Giơ tay để trả lời.'),
(N'range', N'/reɪndʒ/', N'phạm vi / dãy', N'noun', N'INTERMEDIATE', N'The price range is affordable.', N'Phạm vi giá cả phải chăng.'),
(N'rate', N'/reɪt/', N'tỷ lệ / đánh giá', N'noun', N'INTERMEDIATE', N'The success rate is high.', N'Tỷ lệ thành công cao.'),
(N'reach', N'/riːtʃ/', N'đạt tới / với tới', N'verb', N'BEGINNER', N'Reach for your dreams.', N'Vươn tới ước mơ của bạn.'),
(N'reaction', N'/riˈækʃən/', N'phản ứng', N'noun', N'INTERMEDIATE', N'His reaction surprised everyone.', N'Phản ứng của anh ấy làm mọi người ngạc nhiên.'),
(N'real', N'/riːl/', N'thực sự / thật', N'adjective', N'BEGINNER', N'Is this a real diamond?', N'Đây có phải kim cương thật không?'),
(N'realize', N'/ˈriːəlaɪz/', N'nhận ra', N'verb', N'INTERMEDIATE', N'I realized I made a mistake.', N'Tôi nhận ra mình đã mắc lỗi.'),
(N'reason', N'/ˈriːzən/', N'lý do / lý luận', N'noun', N'BEGINNER', N'What is the reason for your absence?', N'Lý do vắng mặt của bạn là gì?'),
(N'receive', N'/rɪˈsiːv/', N'nhận được', N'verb', N'BEGINNER', N'Did you receive my letter?', N'Bạn có nhận được thư của tôi không?'),
(N'recognize', N'/ˈrekəɡnaɪz/', N'nhận ra / công nhận', N'verb', N'INTERMEDIATE', N'I recognize that voice.', N'Tôi nhận ra giọng đó.'),
(N'recommend', N'/ˌrekəˈmend/', N'đề xuất / giới thiệu', N'verb', N'INTERMEDIATE', N'Can you recommend a good book?', N'Bạn có thể giới thiệu một cuốn sách hay không?'),
(N'reflect', N'/rɪˈflekt/', N'phản ánh / suy ngẫm', N'verb', N'INTERMEDIATE', N'Reflect on your decisions.', N'Suy ngẫm về các quyết định của bạn.'),
(N'regard', N'/rɪˈɡɑːrd/', N'liên quan đến / coi như', N'verb', N'INTERMEDIATE', N'With regard to your question...', N'Liên quan đến câu hỏi của bạn...'),
(N'relate', N'/rɪˈleɪt/', N'liên quan đến', N'verb', N'INTERMEDIATE', N'Can you relate to this experience?', N'Bạn có thể liên quan đến trải nghiệm này không?'),
(N'release', N'/rɪˈliːs/', N'phát hành / thả ra', N'verb', N'INTERMEDIATE', N'The company will release a new product.', N'Công ty sẽ phát hành sản phẩm mới.'),
(N'rely', N'/rɪˈlaɪ/', N'dựa vào / tin cậy', N'verb', N'INTERMEDIATE', N'You can rely on me.', N'Bạn có thể dựa vào tôi.'),
(N'remain', N'/rɪˈmeɪn/', N'vẫn còn / ở lại', N'verb', N'INTERMEDIATE', N'Remain calm in difficult situations.', N'Giữ bình tĩnh trong tình huống khó khăn.'),
(N'remove', N'/rɪˈmuːv/', N'loại bỏ', N'verb', N'BEGINNER', N'Remove the sticker from the bottle.', N'Gỡ nhãn dán khỏi chai.'),
(N'replace', N'/rɪˈpleɪs/', N'thay thế', N'verb', N'INTERMEDIATE', N'Replace the old battery.', N'Thay pin cũ.'),
(N'require', N'/rɪˈkwaɪər/', N'yêu cầu', N'verb', N'INTERMEDIATE', N'This task requires patience.', N'Công việc này đòi hỏi sự kiên nhẫn.'),
(N'resolve', N'/rɪˈzɒlv/', N'giải quyết', N'verb', N'INTERMEDIATE', N'Resolve the conflict peacefully.', N'Giải quyết xung đột một cách hòa bình.'),
(N'respond', N'/rɪˈspɒnd/', N'phản hồi / trả lời', N'verb', N'INTERMEDIATE', N'Please respond to my email.', N'Hãy phản hồi email của tôi.'),
(N'result', N'/rɪˈzʌlt/', N'kết quả', N'noun', N'BEGINNER', N'The result exceeded our expectations.', N'Kết quả vượt quá kỳ vọng của chúng tôi.'),
(N'retain', N'/rɪˈteɪn/', N'giữ lại', N'verb', N'INTERMEDIATE', N'Retain your customers with good service.', N'Giữ khách hàng bằng dịch vụ tốt.'),
(N'reveal', N'/rɪˈviːl/', N'tiết lộ', N'verb', N'INTERMEDIATE', N'She revealed the secret.', N'Cô ấy tiết lộ bí mật.'),
(N'review', N'/rɪˈvjuː/', N'xem lại / đánh giá', N'verb', N'INTERMEDIATE', N'Review your notes before the exam.', N'Xem lại ghi chú trước kỳ thi.'),
(N'risk', N'/rɪsk/', N'rủi ro', N'noun', N'INTERMEDIATE', N'Every business has risks.', N'Mọi doanh nghiệp đều có rủi ro.'),
(N'role', N'/roʊl/', N'vai trò', N'noun', N'INTERMEDIATE', N'What is your role in the team?', N'Vai trò của bạn trong nhóm là gì?'),
-- Common words S
(N'scale', N'/skeɪl/', N'quy mô / tỉ lệ', N'noun', N'INTERMEDIATE', N'The project is on a large scale.', N'Dự án có quy mô lớn.'),
(N'secure', N'/sɪˈkjʊər/', N'an toàn / đảm bảo', N'adjective', N'INTERMEDIATE', N'Make sure the door is secure.', N'Hãy chắc chắn cửa được an toàn.'),
(N'select', N'/sɪˈlekt/', N'lựa chọn / chọn lọc', N'verb', N'INTERMEDIATE', N'Select the best option.', N'Lựa chọn phương án tốt nhất.'),
(N'separate', N'/ˈseprət/', N'tách riêng', N'adjective', N'INTERMEDIATE', N'Keep the files in separate folders.', N'Giữ các tệp trong thư mục riêng biệt.'),
(N'series', N'/ˈsɪəriːz/', N'chuỗi / loạt', N'noun', N'INTERMEDIATE', N'A series of events followed.', N'Một loạt sự kiện diễn ra sau đó.'),
(N'settle', N'/ˈsetəl/', N'giải quyết / định cư', N'verb', N'INTERMEDIATE', N'Let''s settle this matter now.', N'Hãy giải quyết vấn đề này ngay bây giờ.'),
(N'severe', N'/sɪˈvɪər/', N'nghiêm trọng / khắc nghiệt', N'adjective', N'INTERMEDIATE', N'The storm caused severe damage.', N'Cơn bão gây thiệt hại nghiêm trọng.'),
(N'shift', N'/ʃɪft/', N'thay đổi / ca làm việc', N'verb', N'INTERMEDIATE', N'The focus shifted to digital media.', N'Trọng tâm đã chuyển sang truyền thông kỹ thuật số.'),
(N'significant', N'/sɪɡˈnɪfɪkənt/', N'đáng kể / quan trọng', N'adjective', N'INTERMEDIATE', N'There is a significant improvement.', N'Có sự cải thiện đáng kể.'),
(N'similar', N'/ˈsɪmɪlər/', N'tương tự', N'adjective', N'BEGINNER', N'Their opinions are similar.', N'Ý kiến của họ tương tự nhau.'),
(N'situation', N'/ˌsɪtʃuˈeɪʃən/', N'tình huống', N'noun', N'INTERMEDIATE', N'Handle the situation carefully.', N'Xử lý tình huống cẩn thận.'),
(N'skill', N'/skɪl/', N'kỹ năng', N'noun', N'BEGINNER', N'Develop your communication skills.', N'Phát triển kỹ năng giao tiếp.'),
(N'solve', N'/sɒlv/', N'giải quyết', N'verb', N'BEGINNER', N'Work together to solve problems.', N'Hợp tác để giải quyết vấn đề.'),
(N'source', N'/sɔːrs/', N'nguồn', N'noun', N'INTERMEDIATE', N'Water is the source of life.', N'Nước là nguồn sống.'),
(N'specific', N'/spɪˈsɪfɪk/', N'cụ thể', N'adjective', N'INTERMEDIATE', N'Be specific about your requirements.', N'Hãy cụ thể về yêu cầu của bạn.'),
(N'standard', N'/ˈstændərd/', N'tiêu chuẩn', N'noun', N'INTERMEDIATE', N'Meet the quality standard.', N'Đáp ứng tiêu chuẩn chất lượng.'),
(N'state', N'/steɪt/', N'trạng thái / tiểu bang', N'noun', N'BEGINNER', N'What is the current state of the project?', N'Trạng thái hiện tại của dự án là gì?'),
(N'strategy', N'/ˈstrætɪdʒi/', N'chiến lược', N'noun', N'INTERMEDIATE', N'Develop a clear strategy.', N'Phát triển chiến lược rõ ràng.'),
(N'strength', N'/streŋθ/', N'sức mạnh', N'noun', N'BEGINNER', N'Know your strengths and weaknesses.', N'Biết điểm mạnh và điểm yếu của bạn.'),
(N'structure', N'/ˈstrʌktʃər/', N'cấu trúc', N'noun', N'INTERMEDIATE', N'The structure of the essay is clear.', N'Cấu trúc của bài luận rõ ràng.'),
(N'subject', N'/ˈsʌbdʒɪkt/', N'chủ đề / môn học', N'noun', N'BEGINNER', N'Math is my favorite subject.', N'Toán là môn học yêu thích của tôi.'),
(N'succeed', N'/səkˈsiːd/', N'thành công', N'verb', N'BEGINNER', N'Work hard to succeed.', N'Làm việc chăm chỉ để thành công.'),
(N'suggest', N'/səˈdʒest/', N'đề nghị / gợi ý', N'verb', N'INTERMEDIATE', N'Can you suggest a solution?', N'Bạn có thể gợi ý giải pháp không?'),
(N'supply', N'/səˈplaɪ/', N'cung cấp / nguồn cung', N'verb', N'INTERMEDIATE', N'Supply and demand affect prices.', N'Cung và cầu ảnh hưởng đến giá cả.'),
(N'support', N'/səˈpɔːrt/', N'hỗ trợ', N'verb', N'BEGINNER', N'Support your local community.', N'Hỗ trợ cộng đồng địa phương của bạn.'),
(N'surface', N'/ˈsɜːrfɪs/', N'bề mặt', N'noun', N'BEGINNER', N'The surface of the table is smooth.', N'Bề mặt bàn nhẵn mịn.'),
(N'surround', N'/səˈraʊnd/', N'bao quanh', N'verb', N'INTERMEDIATE', N'Trees surround the house.', N'Cây cối bao quanh ngôi nhà.'),
(N'survey', N'/ˈsɜːrveɪ/', N'khảo sát', N'noun', N'INTERMEDIATE', N'Complete the survey online.', N'Hoàn thành khảo sát trực tuyến.'),
(N'survive', N'/səˈvaɪv/', N'sống sót / tồn tại', N'verb', N'INTERMEDIATE', N'Plants need water to survive.', N'Cây cần nước để sống sót.'),
(N'symbol', N'/ˈsɪmbəl/', N'biểu tượng', N'noun', N'INTERMEDIATE', N'The dove is a symbol of peace.', N'Chim bồ câu là biểu tượng của hòa bình.'),
(N'system', N'/ˈsɪstəm/', N'hệ thống', N'noun', N'INTERMEDIATE', N'The new system works efficiently.', N'Hệ thống mới hoạt động hiệu quả.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('qualify','quantity','question','raise','range','rate','reach','reaction','real','realize','reason','receive','recognize','recommend','reflect','regard','relate','release','rely','remain','remove','replace','require','resolve','respond','result','retain','reveal','review','risk','role','scale','secure','select','separate','series','settle','severe','shift','significant','similar','situation','skill','solve','source','specific','standard','state','strategy','strength','structure','subject','succeed','suggest','supply','support','surface','surround','survey','survive','symbol','system');
