--liquibase formatted sql

--changeset vocab:051-seed-words-batch44
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.example_sentence, v.example_translation
FROM (VALUES
(N'art', N'/ɑːrt/', N'nghệ thuật', N'noun', N'BEGINNER', N'She loves art and music.', N'Cô ấy yêu nghệ thuật và âm nhạc.'),
(N'ball', N'/bɔːl/', N'quả bóng', N'noun', N'BEGINNER', N'Kick the ball into the goal.', N'Đá bóng vào khung thành.'),
(N'board', N'/bɔːrd/', N'bảng / hội đồng', N'noun', N'BEGINNER', N'Write the answer on the board.', N'Viết câu trả lời lên bảng.'),
(N'boat', N'/boʊt/', N'con thuyền', N'noun', N'BEGINNER', N'We took a boat across the river.', N'Chúng tôi đi thuyền qua sông.'),
(N'body', N'/ˈbɒdi/', N'cơ thể', N'noun', N'BEGINNER', N'Exercise is good for your body.', N'Tập thể dục tốt cho cơ thể bạn.'),
(N'bone', N'/boʊn/', N'xương', N'noun', N'BEGINNER', N'The dog chewed on a bone.', N'Con chó gặm xương.'),
(N'brain', N'/breɪn/', N'não bộ', N'noun', N'BEGINNER', N'The brain controls all body functions.', N'Não bộ điều khiển mọi chức năng cơ thể.'),
(N'bug', N'/bʌɡ/', N'lỗi / con trùng', N'noun', N'BEGINNER', N'There is a bug in the code.', N'Có một lỗi trong mã.'),
(N'care', N'/kɛr/', N'sự chăm sóc', N'noun', N'BEGINNER', N'She takes care of her parents.', N'Cô ấy chăm sóc bố mẹ.'),
(N'center', N'/ˈsentər/', N'trung tâm', N'noun', N'BEGINNER', N'The library is in the center of town.', N'Thư viện ở trung tâm thị trấn.'),
(N'chance', N'/tʃæns/', N'cơ hội / khả năng', N'noun', N'BEGINNER', N'Give me one more chance.', N'Cho tôi thêm một cơ hội.'),
(N'chest', N'/tʃest/', N'ngực / hòm', N'noun', N'BEGINNER', N'He felt pain in his chest.', N'Anh ấy cảm thấy đau ở ngực.'),
(N'chip', N'/tʃɪp/', N'chip / mảnh vỡ', N'noun', N'INTERMEDIATE', N'The microchip stores all the data.', N'Con chip lưu trữ tất cả dữ liệu.'),
(N'code', N'/koʊd/', N'mã / mã lập trình', N'noun', N'BEGINNER', N'The developer writes clean code.', N'Lập trình viên viết mã sạch.'),
(N'command', N'/kəˈmænd/', N'lệnh / chỉ huy', N'noun', N'INTERMEDIATE', N'Type the command in the terminal.', N'Gõ lệnh vào terminal.'),
(N'comment', N'/ˈkɒment/', N'bình luận / nhận xét', N'noun', N'BEGINNER', N'Leave a comment below the post.', N'Để lại bình luận bên dưới bài đăng.'),
(N'competition', N'/ˌkɒmpɪˈtɪʃən/', N'cuộc thi / sự cạnh tranh', N'noun', N'INTERMEDIATE', N'The competition was very fierce.', N'Cuộc thi rất khốc liệt.'),
(N'concern', N'/kənˈsɜːrn/', N'mối lo ngại', N'noun', N'INTERMEDIATE', N'Safety is our main concern.', N'An toàn là mối lo ngại chính của chúng tôi.'),
(N'creativity', N'/ˌkriːeɪˈtɪvɪti/', N'sự sáng tạo', N'noun', N'INTERMEDIATE', N'Creativity is essential in design.', N'Sự sáng tạo rất cần thiết trong thiết kế.'),
(N'data', N'/ˈdeɪtə/', N'dữ liệu', N'noun', N'BEGINNER', N'We need more data to conclude.', N'Chúng ta cần thêm dữ liệu để kết luận.'),
(N'department', N'/dɪˈpɑːrtmənt/', N'phòng ban / khoa', N'noun', N'INTERMEDIATE', N'She works in the finance department.', N'Cô ấy làm việc ở phòng tài chính.'),
(N'desk', N'/desk/', N'bàn làm việc', N'noun', N'BEGINNER', N'Put the papers on my desk.', N'Đặt giấy tờ lên bàn làm việc của tôi.'),
(N'diet', N'/ˈdaɪət/', N'chế độ ăn uống', N'noun', N'BEGINNER', N'A balanced diet keeps you healthy.', N'Chế độ ăn cân bằng giúp bạn khỏe mạnh.'),
(N'disk', N'/dɪsk/', N'đĩa / ổ đĩa', N'noun', N'INTERMEDIATE', N'Save the file to the hard disk.', N'Lưu tệp vào ổ đĩa cứng.'),
(N'dust', N'/dʌst/', N'bụi', N'noun', N'BEGINNER', N'Wipe the dust off the shelf.', N'Lau bụi khỏi kệ.'),
(N'edge', N'/edʒ/', N'mép / cạnh / lợi thế', N'noun', N'INTERMEDIATE', N'Stand at the edge of the cliff.', N'Đứng ở mép vách đá.'),
(N'era', N'/ˈɪərə/', N'kỷ nguyên / thời đại', N'noun', N'INTERMEDIATE', N'We live in the digital era.', N'Chúng ta sống trong kỷ nguyên số.'),
(N'expert', N'/ˈekspɜːrt/', N'chuyên gia', N'noun', N'INTERMEDIATE', N'Consult an expert before deciding.', N'Tham khảo chuyên gia trước khi quyết định.'),
(N'fact', N'/fækt/', N'sự thật / thực tế', N'noun', N'BEGINNER', N'That is an interesting fact.', N'Đó là một sự thật thú vị.'),
(N'faith', N'/feɪθ/', N'niềm tin / đức tin', N'noun', N'INTERMEDIATE', N'Keep faith in yourself.', N'Hãy tin tưởng vào bản thân.'),
(N'fame', N'/feɪm/', N'danh tiếng / tiếng tăm', N'noun', N'INTERMEDIATE', N'He achieved fame through hard work.', N'Anh ấy đạt được danh tiếng nhờ làm việc chăm chỉ.'),
(N'fear', N'/fɪr/', N'nỗi sợ hãi', N'noun', N'BEGINNER', N'Fear of failure stops many people.', N'Sợ thất bại cản trở nhiều người.'),
(N'fee', N'/fiː/', N'phí / lệ phí', N'noun', N'INTERMEDIATE', N'The tuition fee has increased.', N'Học phí đã tăng.'),
(N'file', N'/faɪl/', N'tệp / hồ sơ', N'noun', N'BEGINNER', N'Open the file on your computer.', N'Mở tệp trên máy tính của bạn.'),
(N'film', N'/fɪlm/', N'bộ phim / phim ảnh', N'noun', N'BEGINNER', N'I watched a film last night.', N'Tôi xem một bộ phim tối qua.'),
(N'flag', N'/flæɡ/', N'lá cờ', N'noun', N'BEGINNER', N'Wave the flag proudly.', N'Vẫy lá cờ một cách tự hào.'),
(N'flow', N'/floʊ/', N'dòng chảy', N'noun', N'INTERMEDIATE', N'The flow of information is constant.', N'Dòng chảy thông tin liên tục.'),
(N'format', N'/ˈfɔːrmæt/', N'định dạng', N'noun', N'INTERMEDIATE', N'Please save it in PDF format.', N'Hãy lưu nó ở định dạng PDF.'),
(N'frame', N'/freɪm/', N'khung / khung ảnh', N'noun', N'BEGINNER', N'Put the photo in a frame.', N'Đặt ảnh vào khung.'),
(N'fuel', N'/fjuːəl/', N'nhiên liệu', N'noun', N'INTERMEDIATE', N'The car needs fuel to run.', N'Xe cần nhiên liệu để chạy.'),
(N'gain', N'/ɡeɪn/', N'lợi ích / sự thu được', N'noun', N'INTERMEDIATE', N'The gain from investment is high.', N'Lợi nhuận từ đầu tư rất cao.'),
(N'gate', N'/ɡeɪt/', N'cổng', N'noun', N'BEGINNER', N'Close the gate when you leave.', N'Đóng cổng khi bạn rời đi.'),
(N'gift', N'/ɡɪft/', N'món quà / tài năng', N'noun', N'BEGINNER', N'She has a gift for music.', N'Cô ấy có tài năng âm nhạc.'),
(N'gold', N'/ɡoʊld/', N'vàng', N'noun', N'BEGINNER', N'Gold is a precious metal.', N'Vàng là kim loại quý.'),
(N'grid', N'/ɡrɪd/', N'lưới / mạng lưới', N'noun', N'INTERMEDIATE', N'The power grid supplies electricity.', N'Lưới điện cung cấp điện.'),
(N'hall', N'/hɔːl/', N'hành lang / hội trường', N'noun', N'BEGINNER', N'Meet me in the entrance hall.', N'Gặp tôi ở sảnh vào.'),
(N'harm', N'/hɑːrm/', N'tác hại / sự tổn thương', N'noun', N'INTERMEDIATE', N'Smoking causes harm to your health.', N'Hút thuốc gây hại cho sức khỏe.'),
(N'heat', N'/hiːt/', N'nhiệt / sức nóng', N'noun', N'BEGINNER', N'The heat of the sun warms the earth.', N'Sức nóng của mặt trời làm ấm trái đất.'),
(N'height', N'/haɪt/', N'chiều cao', N'noun', N'BEGINNER', N'What is your height?', N'Chiều cao của bạn là bao nhiêu?'),
(N'hint', N'/hɪnt/', N'gợi ý / manh mối', N'noun', N'BEGINNER', N'Give me a hint, please.', N'Cho tôi một gợi ý đi.'),
(N'history', N'/ˈhɪstəri/', N'lịch sử', N'noun', N'BEGINNER', N'History teaches us valuable lessons.', N'Lịch sử dạy chúng ta những bài học quý giá.'),
(N'hub', N'/hʌb/', N'trung tâm kết nối', N'noun', N'INTERMEDIATE', N'Singapore is a global business hub.', N'Singapore là trung tâm kinh doanh toàn cầu.'),
(N'icon', N'/ˈaɪkɒn/', N'biểu tượng', N'noun', N'BEGINNER', N'Click the icon to open the app.', N'Nhấp vào biểu tượng để mở ứng dụng.'),
(N'index', N'/ˈɪndeks/', N'chỉ số / mục lục', N'noun', N'INTERMEDIATE', N'Check the index at the back of the book.', N'Kiểm tra mục lục ở cuối sách.'),
(N'item', N'/ˈaɪtəm/', N'mục / khoản mục', N'noun', N'BEGINNER', N'Each item on the list is important.', N'Mỗi mục trong danh sách đều quan trọng.'),
(N'land', N'/lænd/', N'đất / đất liền', N'noun', N'BEGINNER', N'They bought a piece of land.', N'Họ mua một mảnh đất.'),
(N'law', N'/lɔː/', N'luật pháp', N'noun', N'BEGINNER', N'Everyone must follow the law.', N'Mọi người phải tuân theo pháp luật.'),
(N'leaf', N'/liːf/', N'chiếc lá', N'noun', N'BEGINNER', N'The leaf fell from the tree.', N'Chiếc lá rơi khỏi cây.'),
(N'line', N'/laɪn/', N'đường / hàng', N'noun', N'BEGINNER', N'Stand in line and wait.', N'Đứng xếp hàng và chờ.'),
(N'list', N'/lɪst/', N'danh sách', N'noun', N'BEGINNER', N'Make a list of things to buy.', N'Lập danh sách những thứ cần mua.'),
(N'load', N'/loʊd/', N'tải trọng / khối lượng', N'noun', N'INTERMEDIATE', N'The truck carries a heavy load.', N'Chiếc xe tải chở hàng nặng.'),
(N'loop', N'/luːp/', N'vòng lặp', N'noun', N'INTERMEDIATE', N'The code runs in an infinite loop.', N'Mã chạy trong vòng lặp vô hạn.'),
(N'luck', N'/lʌk/', N'may mắn', N'noun', N'BEGINNER', N'Good luck on your exam!', N'Chúc may mắn trong kỳ thi!'),
(N'map', N'/mæp/', N'bản đồ', N'noun', N'BEGINNER', N'Use a map to find the way.', N'Dùng bản đồ để tìm đường.'),
(N'math', N'/mæθ/', N'toán học', N'noun', N'BEGINNER', N'Math is her favorite subject.', N'Toán học là môn yêu thích của cô ấy.'),
(N'media', N'/ˈmiːdiə/', N'truyền thông / phương tiện', N'noun', N'INTERMEDIATE', N'Social media influences public opinion.', N'Mạng xã hội ảnh hưởng đến dư luận.'),
(N'mesh', N'/meʃ/', N'lưới / mạng', N'noun', N'ADVANCED', N'The mesh network improves coverage.', N'Mạng lưới cải thiện phạm vi phủ sóng.'),
(N'mix', N'/mɪks/', N'hỗn hợp', N'noun', N'BEGINNER', N'Add the mix of spices.', N'Thêm hỗn hợp gia vị.'),
(N'mode', N'/moʊd/', N'chế độ / kiểu', N'noun', N'INTERMEDIATE', N'Switch to dark mode for comfort.', N'Chuyển sang chế độ tối để thoải mái.'),
(N'mood', N'/muːd/', N'tâm trạng', N'noun', N'BEGINNER', N'Music can change your mood.', N'Âm nhạc có thể thay đổi tâm trạng bạn.'),
(N'mud', N'/mʌd/', N'bùn', N'noun', N'BEGINNER', N'The kids played in the mud.', N'Bọn trẻ chơi trong bùn.'),
(N'myth', N'/mɪθ/', N'thần thoại / huyền thoại', N'noun', N'INTERMEDIATE', N'That is just a myth.', N'Đó chỉ là huyền thoại.'),
(N'nature', N'/ˈneɪtʃər/', N'thiên nhiên / bản chất', N'noun', N'BEGINNER', N'Spend time in nature to relax.', N'Dành thời gian trong thiên nhiên để thư giãn.'),
(N'news', N'/njuːz/', N'tin tức', N'noun', N'BEGINNER', N'I read the news every morning.', N'Tôi đọc tin tức mỗi sáng.'),
(N'niche', N'/niːʃ/', N'ngách / lĩnh vực cụ thể', N'noun', N'ADVANCED', N'Find your niche in the market.', N'Tìm ngách của bạn trên thị trường.'),
(N'node', N'/noʊd/', N'nút / điểm nút', N'noun', N'ADVANCED', N'Each node in the network is connected.', N'Mỗi nút trong mạng được kết nối.'),
(N'norm', N'/nɔːrm/', N'chuẩn mực / tiêu chuẩn', N'noun', N'INTERMEDIATE', N'Follow social norms to fit in.', N'Tuân theo chuẩn mực xã hội để hòa nhập.'),
(N'note', N'/noʊt/', N'ghi chú / lưu ý', N'noun', N'BEGINNER', N'Take notes during the lecture.', N'Ghi chú trong buổi giảng.'),
(N'oak', N'/oʊk/', N'cây sồi', N'noun', N'INTERMEDIATE', N'The oak tree lived for 200 years.', N'Cây sồi sống được 200 năm.'),
(N'output', N'/ˈaʊtpʊt/', N'đầu ra / sản lượng', N'noun', N'INTERMEDIATE', N'Increase the output of the factory.', N'Tăng sản lượng của nhà máy.'),
(N'pain', N'/peɪn/', N'cơn đau', N'noun', N'BEGINNER', N'She felt pain in her knee.', N'Cô ấy cảm thấy đau ở đầu gối.'),
(N'pair', N'/pɛr/', N'cặp đôi / cặp', N'noun', N'BEGINNER', N'I bought a new pair of shoes.', N'Tôi mua một đôi giày mới.'),
(N'part', N'/pɑːrt/', N'phần / bộ phận', N'noun', N'BEGINNER', N'This is the hardest part of the job.', N'Đây là phần khó nhất của công việc.'),
(N'path', N'/pæθ/', N'con đường / lối đi', N'noun', N'BEGINNER', N'Follow the path to the lake.', N'Đi theo con đường đến hồ.'),
(N'peace', N'/piːs/', N'hòa bình / sự bình yên', N'noun', N'BEGINNER', N'The world needs peace.', N'Thế giới cần hòa bình.'),
(N'peak', N'/piːk/', N'đỉnh / đỉnh điểm', N'noun', N'INTERMEDIATE', N'We reached the peak at noon.', N'Chúng tôi đến đỉnh vào buổi trưa.'),
(N'peer', N'/pɪr/', N'đồng nghiệp / bạn cùng trang lứa', N'noun', N'INTERMEDIATE', N'Learn from your peers.', N'Học hỏi từ những người đồng trang lứa.'),
(N'pill', N'/pɪl/', N'viên thuốc', N'noun', N'BEGINNER', N'Take one pill after each meal.', N'Uống một viên thuốc sau mỗi bữa ăn.'),
(N'plan', N'/plæn/', N'kế hoạch', N'noun', N'BEGINNER', N'We need a clear plan for success.', N'Chúng ta cần một kế hoạch rõ ràng để thành công.'),
(N'planet', N'/ˈplænɪt/', N'hành tinh', N'noun', N'BEGINNER', N'Earth is the only known planet with life.', N'Trái Đất là hành tinh duy nhất được biết có sự sống.'),
(N'plot', N'/plɒt/', N'cốt truyện / âm mưu', N'noun', N'INTERMEDIATE', N'The plot of the novel is complex.', N'Cốt truyện của cuốn tiểu thuyết phức tạp.'),
(N'point', N'/pɔɪnt/', N'điểm / quan điểm', N'noun', N'BEGINNER', N'What is the main point of the speech?', N'Điểm chính của bài phát biểu là gì?'),
(N'poll', N'/poʊl/', N'cuộc thăm dò / bỏ phiếu', N'noun', N'INTERMEDIATE', N'The poll shows 60% support.', N'Cuộc thăm dò cho thấy 60% ủng hộ.'),
(N'pond', N'/pɒnd/', N'ao', N'noun', N'BEGINNER', N'Ducks swim in the pond.', N'Vịt bơi trong ao.'),
(N'pool', N'/puːl/', N'hồ bơi / nguồn chung', N'noun', N'BEGINNER', N'The children swim in the pool.', N'Những đứa trẻ bơi trong hồ bơi.'),
(N'port', N'/pɔːrt/', N'cảng / cổng kết nối', N'noun', N'INTERMEDIATE', N'The ship arrived at the port.', N'Con tàu đến cảng.'),
(N'post', N'/poʊst/', N'bài đăng / cột mốc', N'noun', N'BEGINNER', N'She made a post on social media.', N'Cô ấy đăng một bài trên mạng xã hội.'),
(N'press', N'/pres/', N'báo chí / sức ép', N'noun', N'INTERMEDIATE', N'Freedom of the press is vital.', N'Tự do báo chí rất quan trọng.'),
(N'prize', N'/praɪz/', N'giải thưởng', N'noun', N'BEGINNER', N'She won first prize in the contest.', N'Cô ấy giành giải nhất trong cuộc thi.'),
(N'product', N'/ˈprɒdʌkt/', N'sản phẩm', N'noun', N'BEGINNER', N'The product is very popular.', N'Sản phẩm rất phổ biến.'),
(N'proof', N'/pruːf/', N'bằng chứng', N'noun', N'INTERMEDIATE', N'Show me the proof of your claim.', N'Cho tôi thấy bằng chứng về tuyên bố của bạn.'),
(N'quality', N'/ˈkwɒlɪti/', N'chất lượng', N'noun', N'BEGINNER', N'We guarantee high quality products.', N'Chúng tôi đảm bảo sản phẩm chất lượng cao.'),
(N'queue', N'/kjuː/', N'hàng đợi', N'noun', N'INTERMEDIATE', N'Join the queue at the counter.', N'Xếp hàng tại quầy.'),
(N'reality', N'/riˈæləti/', N'thực tế', N'noun', N'INTERMEDIATE', N'Face reality and move forward.', N'Đối mặt với thực tế và tiến về phía trước.'),
(N'record', N'/ˈrekərd/', N'hồ sơ / kỷ lục', N'noun', N'INTERMEDIATE', N'He broke the world record.', N'Anh ấy phá kỷ lục thế giới.'),
(N'region', N'/ˈriːdʒən/', N'vùng / khu vực', N'noun', N'INTERMEDIATE', N'This region has a warm climate.', N'Vùng này có khí hậu ấm áp.'),
(N'rent', N'/rent/', N'tiền thuê / tiền nhà', N'noun', N'BEGINNER', N'The rent is due on the first.', N'Tiền thuê nhà đến hạn vào ngày mồng một.'),
(N'report', N'/rɪˈpɔːrt/', N'báo cáo', N'noun', N'INTERMEDIATE', N'Submit your report by Friday.', N'Nộp báo cáo của bạn trước thứ Sáu.'),
(N'resource', N'/ˈriːsɔːrs/', N'tài nguyên / nguồn lực', N'noun', N'INTERMEDIATE', N'Manage your resources wisely.', N'Quản lý nguồn lực một cách khôn ngoan.'),
(N'route', N'/ruːt/', N'tuyến đường / lộ trình', N'noun', N'INTERMEDIATE', N'Take the fastest route.', N'Đi theo tuyến đường nhanh nhất.'),
(N'rule', N'/ruːl/', N'quy tắc / quy định', N'noun', N'BEGINNER', N'Follow the rules of the game.', N'Tuân theo quy tắc của trò chơi.'),
(N'scar', N'/skɑːr/', N'vết sẹo', N'noun', N'INTERMEDIATE', N'The scar faded over time.', N'Vết sẹo mờ dần theo thời gian.'),
(N'season', N'/ˈsiːzən/', N'mùa / mùa vụ', N'noun', N'BEGINNER', N'Spring is my favorite season.', N'Mùa xuân là mùa yêu thích của tôi.'),
(N'section', N'/ˈsekʃən/', N'phần / mục', N'noun', N'INTERMEDIATE', N'Read the first section carefully.', N'Đọc phần đầu tiên cẩn thận.'),
(N'self', N'/self/', N'bản thân', N'noun', N'INTERMEDIATE', N'Be true to your self.', N'Hãy trung thực với bản thân.'),
(N'service', N'/ˈsɜːrvɪs/', N'dịch vụ', N'noun', N'BEGINNER', N'The customer service is excellent.', N'Dịch vụ khách hàng rất xuất sắc.'),
(N'shape', N'/ʃeɪp/', N'hình dạng', N'noun', N'BEGINNER', N'What shape is that building?', N'Tòa nhà đó có hình dạng gì?'),
(N'share', N'/ʃɛr/', N'cổ phần / phần chia', N'noun', N'INTERMEDIATE', N'She owns a share of the company.', N'Cô ấy sở hữu cổ phần của công ty.'),
(N'shell', N'/ʃel/', N'vỏ sò / vỏ bọc', N'noun', N'BEGINNER', N'The turtle hides in its shell.', N'Con rùa ẩn vào trong vỏ của nó.'),
(N'sight', N'/saɪt/', N'tầm nhìn / cảnh quan', N'noun', N'INTERMEDIATE', N'The sight of the ocean was breathtaking.', N'Cảnh biển thật tuyệt vời.'),
(N'sign', N'/saɪn/', N'dấu hiệu / biển báo', N'noun', N'BEGINNER', N'This is a sign of progress.', N'Đây là dấu hiệu của sự tiến bộ.'),
(N'silk', N'/sɪlk/', N'lụa / tơ lụa', N'noun', N'INTERMEDIATE', N'This scarf is made of silk.', N'Chiếc khăn này được làm từ lụa.'),
(N'site', N'/saɪt/', N'địa điểm / trang web', N'noun', N'BEGINNER', N'The construction site is busy.', N'Công trình xây dựng rất bận rộn.'),
(N'size', N'/saɪz/', N'kích thước / cỡ', N'noun', N'BEGINNER', N'What size do you wear?', N'Bạn mặc cỡ bao nhiêu?'),
(N'soil', N'/sɔɪl/', N'đất / thổ nhưỡng', N'noun', N'INTERMEDIATE', N'Rich soil is needed for farming.', N'Đất màu mỡ cần thiết cho nông nghiệp.'),
(N'song', N'/sɒŋ/', N'bài hát', N'noun', N'BEGINNER', N'She sang a beautiful song.', N'Cô ấy hát một bài hát đẹp.'),
(N'soul', N'/soʊl/', N'linh hồn', N'noun', N'INTERMEDIATE', N'Music speaks to the soul.', N'Âm nhạc nói chuyện với linh hồn.'),
(N'space', N'/speɪs/', N'không gian / vũ trụ', N'noun', N'BEGINNER', N'There is enough space for everyone.', N'Có đủ không gian cho mọi người.'),
(N'speed', N'/spiːd/', N'tốc độ', N'noun', N'BEGINNER', N'The speed of light is constant.', N'Tốc độ ánh sáng là không đổi.'),
(N'spirit', N'/ˈspɪrɪt/', N'tinh thần / linh hồn', N'noun', N'INTERMEDIATE', N'Team spirit is essential for success.', N'Tinh thần đồng đội rất cần thiết để thành công.'),
(N'spot', N'/spɒt/', N'điểm / vị trí', N'noun', N'BEGINNER', N'This is a good spot for photos.', N'Đây là vị trí tốt để chụp ảnh.'),
(N'staff', N'/stæf/', N'nhân viên / đội ngũ', N'noun', N'INTERMEDIATE', N'The staff worked overtime.', N'Nhân viên làm thêm giờ.'),
(N'stage', N'/steɪdʒ/', N'giai đoạn / sân khấu', N'noun', N'INTERMEDIATE', N'We are in the final stage.', N'Chúng ta đang ở giai đoạn cuối.'),
(N'step', N'/step/', N'bước / bậc thang', N'noun', N'BEGINNER', N'Take it one step at a time.', N'Hãy làm từng bước một.'),
(N'story', N'/ˈstɔːri/', N'câu chuyện', N'noun', N'BEGINNER', N'Tell me a story.', N'Kể cho tôi nghe một câu chuyện.'),
(N'sum', N'/sʌm/', N'tổng số / tổng cộng', N'noun', N'INTERMEDIATE', N'The sum of all parts equals the whole.', N'Tổng của tất cả các phần bằng tổng thể.'),
(N'swap', N'/swɒp/', N'sự hoán đổi', N'noun', N'INTERMEDIATE', N'Let''s do a swap.', N'Hãy hoán đổi nào.'),
(N'talent', N'/ˈtælənt/', N'tài năng', N'noun', N'BEGINNER', N'She has a natural talent for art.', N'Cô ấy có tài năng thiên bẩm về nghệ thuật.'),
(N'target', N'/ˈtɑːrɡɪt/', N'mục tiêu / đích nhắm', N'noun', N'INTERMEDIATE', N'Set a clear target and work toward it.', N'Đặt mục tiêu rõ ràng và tiến tới nó.'),
(N'test', N'/test/', N'bài kiểm tra / thử nghiệm', N'noun', N'BEGINNER', N'Study hard for the test.', N'Học chăm chỉ cho bài kiểm tra.'),
(N'text', N'/tekst/', N'văn bản / tin nhắn', N'noun', N'BEGINNER', N'Send me a text when you arrive.', N'Nhắn tin cho tôi khi bạn đến.'),
(N'thought', N'/θɔːt/', N'suy nghĩ / ý nghĩ', N'noun', N'INTERMEDIATE', N'Share your thoughts with the group.', N'Chia sẻ suy nghĩ của bạn với nhóm.'),
(N'tier', N'/tɪr/', N'tầng / cấp bậc', N'noun', N'ADVANCED', N'The premium tier offers more features.', N'Cấp cao cấp cung cấp nhiều tính năng hơn.'),
(N'tip', N'/tɪp/', N'lời khuyên / tiền boa', N'noun', N'BEGINNER', N'Here is a useful tip for you.', N'Đây là một lời khuyên hữu ích cho bạn.'),
(N'title', N'/ˈtaɪtəl/', N'tiêu đề / danh hiệu', N'noun', N'BEGINNER', N'What is the title of the book?', N'Tiêu đề của cuốn sách là gì?'),
(N'toll', N'/toʊl/', N'phí cầu đường / cái giá', N'noun', N'INTERMEDIATE', N'The toll on the bridge is two dollars.', N'Phí cầu là hai đô la.'),
(N'tone', N'/toʊn/', N'giọng điệu / âm điệu', N'noun', N'INTERMEDIATE', N'Speak in a calm tone.', N'Nói bằng giọng điệu bình tĩnh.'),
(N'tour', N'/tʊr/', N'chuyến tham quan', N'noun', N'BEGINNER', N'We went on a tour of the city.', N'Chúng tôi đi tham quan thành phố.'),
(N'track', N'/træk/', N'đường ray / theo dõi', N'noun', N'INTERMEDIATE', N'Keep track of your progress.', N'Theo dõi tiến trình của bạn.'),
(N'trail', N'/treɪl/', N'đường mòn', N'noun', N'INTERMEDIATE', N'Hike along the forest trail.', N'Đi bộ dọc theo đường mòn rừng.'),
(N'trait', N'/treɪt/', N'đặc điểm / tính cách', N'noun', N'INTERMEDIATE', N'Honesty is a key trait.', N'Sự thành thật là đặc điểm quan trọng.'),
(N'tribe', N'/traɪb/', N'bộ lạc', N'noun', N'INTERMEDIATE', N'The tribe lived in the forest.', N'Bộ lạc sống trong rừng.'),
(N'trip', N'/trɪp/', N'chuyến đi', N'noun', N'BEGINNER', N'We planned a trip abroad.', N'Chúng tôi lên kế hoạch một chuyến đi nước ngoài.'),
(N'truck', N'/trʌk/', N'xe tải', N'noun', N'BEGINNER', N'The truck delivered the goods.', N'Xe tải đã giao hàng.'),
(N'truth', N'/truːθ/', N'sự thật', N'noun', N'BEGINNER', N'Always tell the truth.', N'Hãy luôn nói thật.'),
(N'tube', N'/tjuːb/', N'ống / đường ống', N'noun', N'BEGINNER', N'Squeeze the tube of toothpaste.', N'Bóp ống kem đánh răng.'),
(N'urge', N'/ɜːrdʒ/', N'sự thôi thúc / ham muốn', N'noun', N'INTERMEDIATE', N'Resist the urge to quit.', N'Kháng cự sự thôi thúc bỏ cuộc.'),
(N'vein', N'/veɪn/', N'tĩnh mạch / mạch máu', N'noun', N'INTERMEDIATE', N'Blood flows through the veins.', N'Máu chảy qua các tĩnh mạch.'),
(N'verb', N'/vɜːrb/', N'động từ', N'noun', N'BEGINNER', N'Run is an action verb.', N'Run là một động từ hành động.'),
(N'void', N'/vɔɪd/', N'khoảng trống / sự trống rỗng', N'noun', N'ADVANCED', N'There is a void in her life.', N'Có một khoảng trống trong cuộc sống của cô ấy.'),
(N'wage', N'/weɪdʒ/', N'tiền lương / tiền công', N'noun', N'INTERMEDIATE', N'The minimum wage was increased.', N'Lương tối thiểu đã được tăng.'),
(N'war', N'/wɔːr/', N'chiến tranh', N'noun', N'BEGINNER', N'War causes great suffering.', N'Chiến tranh gây ra nỗi đau khổ lớn.'),
(N'wave', N'/weɪv/', N'làn sóng / sóng', N'noun', N'BEGINNER', N'The wave hit the shore.', N'Làn sóng đập vào bờ.'),
(N'way', N'/weɪ/', N'cách / con đường', N'noun', N'BEGINNER', N'Is there a better way to solve this?', N'Có cách nào tốt hơn để giải quyết điều này không?'),
(N'weight', N'/weɪt/', N'cân nặng / trọng lượng', N'noun', N'BEGINNER', N'Check your weight regularly.', N'Kiểm tra cân nặng thường xuyên.'),
(N'width', N'/wɪdθ/', N'chiều rộng', N'noun', N'BEGINNER', N'Measure the width of the table.', N'Đo chiều rộng của cái bàn.'),
(N'wire', N'/waɪər/', N'dây điện / dây thép', N'noun', N'BEGINNER', N'The wire connects the two devices.', N'Dây kết nối hai thiết bị.'),
(N'wish', N'/wɪʃ/', N'điều ước / mong muốn', N'noun', N'BEGINNER', N'Make a wish before you blow the candles.', N'Ước một điều trước khi thổi nến.'),
(N'word', N'/wɜːrd/', N'từ / lời nói', N'noun', N'BEGINNER', N'Choose your words carefully.', N'Hãy chọn lời nói cẩn thận.'),
(N'yard', N'/jɑːrd/', N'sân / thước Anh', N'noun', N'BEGINNER', N'The kids play in the yard.', N'Bọn trẻ chơi trong sân.'),
(N'zone', N'/zoʊn/', N'khu vực / vùng', N'noun', N'INTERMEDIATE', N'Enter the restricted zone only with a pass.', N'Vào khu vực hạn chế chỉ với thẻ.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('art','ball','board','boat','body','bone','brain','bug','care','center','chance','chest','chip','code','command','comment','competition','concern','creativity','data','department','desk','diet','disk','dust','edge','era','expert','fact','faith','fame','fear','fee','file','film','flag','flow','format','frame','fuel','gain','gate','gift','gold','grid','hall','harm','heat','height','hint','history','hub','icon','index','item','land','law','leaf','line','list','load','loop','luck','map','math','media','mesh','mix','mode','mood','mud','myth','nature','news','niche','node','norm','note','oak','output','pain','pair','part','path','peace','peak','peer','pill','plan','planet','plot','point','poll','pond','pool','port','post','press','prize','product','proof','quality','queue','reality','record','region','rent','report','resource','route','rule','scar','season','section','self','service','shape','share','shell','sight','sign','silk','site','size','soil','song','soul','space','speed','spirit','spot','staff','stage','step','story','sum','swap','talent','target','test','text','thought','tier','tip','title','toll','tone','tour','track','trail','trait','tribe','trip','truck','truth','tube','urge','vein','verb','void','wage','war','wave','way','weight','width','wire','wish','word','yard','zone');
