--liquibase formatted sql

--changeset vocab:052-seed-words-batch45
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.example_sentence, v.example_translation
FROM (VALUES
-- Adjectives
(N'able', N'/ˈeɪbəl/', N'có khả năng', N'adjective', N'BEGINNER', N'She is able to speak three languages.', N'Cô ấy có khả năng nói ba thứ tiếng.'),
(N'acute', N'/əˈkjuːt/', N'cấp tính / nhạy bén', N'adjective', N'INTERMEDIATE', N'He has an acute sense of hearing.', N'Anh ấy có thính giác nhạy bén.'),
(N'alike', N'/əˈlaɪk/', N'giống nhau', N'adjective', N'BEGINNER', N'The twins look exactly alike.', N'Cặp song sinh trông giống hệt nhau.'),
(N'alive', N'/əˈlaɪv/', N'còn sống', N'adjective', N'BEGINNER', N'Keep the tradition alive.', N'Giữ truyền thống còn sống mãi.'),
(N'ample', N'/ˈæmpəl/', N'rộng rãi / dư dả', N'adjective', N'INTERMEDIATE', N'There is ample time to finish.', N'Có đủ thời gian để hoàn thành.'),
(N'awful', N'/ˈɔːfəl/', N'khủng khiếp / tệ hại', N'adjective', N'BEGINNER', N'The weather was awful today.', N'Thời tiết hôm nay thật tệ.'),
(N'bare', N'/bɛr/', N'trơ trụi / trần trụi', N'adjective', N'INTERMEDIATE', N'The tree was bare in winter.', N'Cây trơ trụi vào mùa đông.'),
(N'blunt', N'/blʌnt/', N'thẳng thắn / cùn', N'adjective', N'INTERMEDIATE', N'She was blunt about her opinion.', N'Cô ấy thẳng thắn về ý kiến của mình.'),
(N'bold', N'/boʊld/', N'dũng cảm / đậm nét', N'adjective', N'INTERMEDIATE', N'Make a bold decision.', N'Đưa ra quyết định dũng cảm.'),
(N'calm', N'/kɑːm/', N'bình tĩnh / yên lặng', N'adjective', N'BEGINNER', N'Stay calm during the storm.', N'Hãy bình tĩnh trong cơn bão.'),
(N'cheap', N'/tʃiːp/', N'rẻ / giá rẻ', N'adjective', N'BEGINNER', N'This restaurant is cheap and good.', N'Nhà hàng này rẻ và ngon.'),
(N'civil', N'/ˈsɪvəl/', N'dân sự / lịch sự', N'adjective', N'INTERMEDIATE', N'Civil rights are protected by law.', N'Quyền dân sự được bảo vệ bởi pháp luật.'),
(N'clear', N'/klɪr/', N'rõ ràng / trong suốt', N'adjective', N'BEGINNER', N'Give a clear explanation.', N'Đưa ra lời giải thích rõ ràng.'),
(N'coarse', N'/kɔːrs/', N'thô ráp / thô lỗ', N'adjective', N'ADVANCED', N'The fabric feels coarse.', N'Vải có cảm giác thô ráp.'),
(N'compact', N'/ˈkɒmpækt/', N'nhỏ gọn / chặt chẽ', N'adjective', N'INTERMEDIATE', N'A compact car is easy to park.', N'Xe nhỏ gọn dễ đỗ.'),
(N'concrete', N'/ˈkɒŋkriːt/', N'cụ thể / bê tông', N'adjective', N'INTERMEDIATE', N'Give a concrete example.', N'Cho một ví dụ cụ thể.'),
(N'damp', N'/dæmp/', N'ẩm ướt', N'adjective', N'INTERMEDIATE', N'The clothes are still damp.', N'Quần áo vẫn còn ẩm.'),
(N'decent', N'/ˈdiːsənt/', N'tử tế / đàng hoàng', N'adjective', N'INTERMEDIATE', N'She earns a decent salary.', N'Cô ấy kiếm được mức lương đàng hoàng.'),
(N'dense', N'/dens/', N'dày đặc / mật độ cao', N'adjective', N'INTERMEDIATE', N'The forest is very dense.', N'Khu rừng rất dày đặc.'),
(N'dull', N'/dʌl/', N'nhàm chán / tối tăm', N'adjective', N'BEGINNER', N'The lecture was dull.', N'Buổi giảng thật nhàm chán.'),
(N'durable', N'/ˈdjʊərəbəl/', N'bền bỉ / lâu bền', N'adjective', N'INTERMEDIATE', N'Buy durable materials.', N'Mua vật liệu bền bỉ.'),
(N'dynamic', N'/daɪˈnæmɪk/', N'năng động / linh hoạt', N'adjective', N'INTERMEDIATE', N'She is a dynamic leader.', N'Cô ấy là một nhà lãnh đạo năng động.'),
(N'eager', N'/ˈiːɡər/', N'háo hức / nhiệt tình', N'adjective', N'INTERMEDIATE', N'The students were eager to learn.', N'Học sinh háo hức được học.'),
(N'exact', N'/ɪɡˈzækt/', N'chính xác', N'adjective', N'INTERMEDIATE', N'What is the exact time?', N'Giờ chính xác là mấy giờ?'),
(N'fair', N'/fɛr/', N'công bằng / hội chợ', N'adjective', N'BEGINNER', N'Be fair to everyone.', N'Hãy công bằng với mọi người.'),
(N'faint', N'/feɪnt/', N'mờ nhạt / yếu ớt', N'adjective', N'INTERMEDIATE', N'There is a faint smell of flowers.', N'Có mùi hoa mờ nhạt.'),
(N'fake', N'/feɪk/', N'giả mạo / không thật', N'adjective', N'BEGINNER', N'This bag is a fake.', N'Túi này là hàng giả.'),
(N'fierce', N'/fɪrs/', N'dữ dội / mãnh liệt', N'adjective', N'INTERMEDIATE', N'The competition was fierce.', N'Cuộc cạnh tranh rất dữ dội.'),
(N'final', N'/ˈfaɪnəl/', N'cuối cùng / chung kết', N'adjective', N'BEGINNER', N'This is the final answer.', N'Đây là câu trả lời cuối cùng.'),
(N'flawed', N'/flɔːd/', N'có khuyết điểm', N'adjective', N'INTERMEDIATE', N'The plan was flawed from the start.', N'Kế hoạch có khuyết điểm ngay từ đầu.'),
(N'frail', N'/freɪl/', N'yếu ớt / mỏng manh', N'adjective', N'ADVANCED', N'The elderly woman was frail.', N'Người phụ nữ lớn tuổi rất yếu ớt.'),
(N'fresh', N'/freʃ/', N'tươi / mới mẻ', N'adjective', N'BEGINNER', N'Eat fresh vegetables daily.', N'Ăn rau tươi mỗi ngày.'),
(N'grim', N'/ɡrɪm/', N'u ám / nghiêm khắc', N'adjective', N'ADVANCED', N'The situation looks grim.', N'Tình hình trông u ám.'),
(N'harsh', N'/hɑːrʃ/', N'khắc nghiệt / gay gắt', N'adjective', N'INTERMEDIATE', N'The winter is harsh this year.', N'Mùa đông năm nay rất khắc nghiệt.'),
(N'hollow', N'/ˈhɒloʊ/', N'rỗng / trống rỗng', N'adjective', N'INTERMEDIATE', N'The tree trunk is hollow.', N'Thân cây rỗng.'),
(N'ideal', N'/aɪˈdiːəl/', N'lý tưởng', N'adjective', N'INTERMEDIATE', N'This is the ideal solution.', N'Đây là giải pháp lý tưởng.'),
(N'idle', N'/ˈaɪdəl/', N'nhàn rỗi / lãng phí', N'adjective', N'INTERMEDIATE', N'Do not let machines stay idle.', N'Đừng để máy móc nhàn rỗi.'),
(N'intact', N'/ɪnˈtækt/', N'nguyên vẹn', N'adjective', N'INTERMEDIATE', N'The building remained intact.', N'Tòa nhà vẫn còn nguyên vẹn.'),
(N'keen', N'/kiːn/', N'nhiệt tình / háo hức', N'adjective', N'INTERMEDIATE', N'She is keen to learn.', N'Cô ấy nhiệt tình muốn học.'),
(N'lean', N'/liːn/', N'gầy / tinh gọn', N'adjective', N'INTERMEDIATE', N'A lean body requires exercise.', N'Cơ thể gầy cần tập luyện.'),
(N'lively', N'/ˈlaɪvli/', N'sống động / vui tươi', N'adjective', N'BEGINNER', N'The market is very lively.', N'Chợ rất sống động.'),
(N'loose', N'/luːs/', N'lỏng lẻo / rộng', N'adjective', N'BEGINNER', N'The screw is loose.', N'Cái vít bị lỏng.'),
(N'lush', N'/lʌʃ/', N'xanh tươi / sum sê', N'adjective', N'INTERMEDIATE', N'The garden is lush and green.', N'Khu vườn xanh tươi và sum sê.'),
(N'massive', N'/ˈmæsɪv/', N'to lớn / đồ sộ', N'adjective', N'INTERMEDIATE', N'The company made a massive profit.', N'Công ty kiếm được lợi nhuận khổng lồ.'),
(N'mature', N'/məˈtʃʊər/', N'trưởng thành / chín chắn', N'adjective', N'INTERMEDIATE', N'He is mature for his age.', N'Anh ấy trưởng thành so với tuổi của mình.'),
(N'mild', N'/maɪld/', N'nhẹ nhàng / ôn hòa', N'adjective', N'INTERMEDIATE', N'The weather is mild this spring.', N'Thời tiết mùa xuân này ôn hòa.'),
(N'neat', N'/niːt/', N'gọn gàng / ngăn nắp', N'adjective', N'BEGINNER', N'Keep your desk neat.', N'Giữ bàn làm việc ngăn nắp.'),
(N'neutral', N'/ˈnjuːtrəl/', N'trung lập / trung tính', N'adjective', N'INTERMEDIATE', N'Switzerland remains neutral.', N'Thụy Sĩ vẫn giữ trung lập.'),
(N'noble', N'/ˈnoʊbəl/', N'cao quý / quý tộc', N'adjective', N'INTERMEDIATE', N'It was a noble gesture.', N'Đó là một cử chỉ cao quý.'),
(N'numb', N'/nʌm/', N'tê liệt / vô cảm', N'adjective', N'INTERMEDIATE', N'My fingers are numb from the cold.', N'Ngón tay tôi tê cứng vì lạnh.'),
(N'odd', N'/ɒd/', N'lẻ / kỳ lạ', N'adjective', N'BEGINNER', N'That is an odd number.', N'Đó là số lẻ.'),
(N'oral', N'/ˈɔːrəl/', N'bằng miệng / bằng lời', N'adjective', N'INTERMEDIATE', N'The oral exam was difficult.', N'Kỳ thi vấn đáp rất khó.'),
(N'pale', N'/peɪl/', N'nhợt nhạt / xanh xao', N'adjective', N'BEGINNER', N'She looks pale today.', N'Cô ấy trông xanh xao hôm nay.'),
(N'partial', N'/ˈpɑːrʃəl/', N'một phần / thiên vị', N'adjective', N'INTERMEDIATE', N'A partial solution is not enough.', N'Một giải pháp một phần là chưa đủ.'),
(N'passive', N'/ˈpæsɪv/', N'thụ động', N'adjective', N'INTERMEDIATE', N'Avoid passive behavior.', N'Tránh hành vi thụ động.'),
(N'precise', N'/prɪˈsaɪs/', N'chính xác / tỉ mỉ', N'adjective', N'INTERMEDIATE', N'Be precise in your measurements.', N'Hãy chính xác trong các phép đo của bạn.'),
(N'prime', N'/praɪm/', N'nguyên tố / tốt nhất', N'adjective', N'INTERMEDIATE', N'This is prime real estate.', N'Đây là bất động sản hạng nhất.'),
(N'prone', N'/proʊn/', N'dễ bị / có xu hướng', N'adjective', N'ADVANCED', N'He is prone to anxiety.', N'Anh ấy dễ bị lo lắng.'),
(N'proud', N'/praʊd/', N'tự hào', N'adjective', N'BEGINNER', N'I am proud of your achievement.', N'Tôi tự hào về thành tích của bạn.'),
(N'pure', N'/pjʊr/', N'thuần khiết / trong sáng', N'adjective', N'INTERMEDIATE', N'Drink pure water.', N'Uống nước tinh khiết.'),
(N'quick', N'/kwɪk/', N'nhanh chóng', N'adjective', N'BEGINNER', N'Give a quick answer.', N'Đưa ra câu trả lời nhanh.'),
(N'rare', N'/rɛr/', N'hiếm có', N'adjective', N'INTERMEDIATE', N'This is a rare opportunity.', N'Đây là cơ hội hiếm có.'),
(N'raw', N'/rɔː/', N'thô / sống / chưa xử lý', N'adjective', N'INTERMEDIATE', N'Raw data needs to be processed.', N'Dữ liệu thô cần được xử lý.'),
(N'remote', N'/rɪˈmoʊt/', N'xa xôi / từ xa', N'adjective', N'INTERMEDIATE', N'She works at a remote location.', N'Cô ấy làm việc ở địa điểm xa xôi.'),
(N'rigid', N'/ˈrɪdʒɪd/', N'cứng nhắc / cứng đờ', N'adjective', N'ADVANCED', N'Avoid rigid thinking.', N'Tránh tư duy cứng nhắc.'),
(N'rough', N'/rʌf/', N'thô ráp / khắc nghiệt', N'adjective', N'INTERMEDIATE', N'The road is rough and bumpy.', N'Con đường thô ráp và gập ghềnh.'),
(N'rural', N'/ˈrʊərəl/', N'nông thôn / vùng quê', N'adjective', N'INTERMEDIATE', N'She grew up in a rural area.', N'Cô ấy lớn lên ở vùng nông thôn.'),
(N'sacred', N'/ˈseɪkrɪd/', N'thiêng liêng / linh thiêng', N'adjective', N'INTERMEDIATE', N'The temple is a sacred place.', N'Ngôi đền là nơi thiêng liêng.'),
(N'scarce', N'/skɛrs/', N'khan hiếm', N'adjective', N'INTERMEDIATE', N'Clean water is scarce in the region.', N'Nước sạch khan hiếm ở khu vực này.'),
(N'shallow', N'/ˈʃæloʊ/', N'nông cạn / bề ngoài', N'adjective', N'INTERMEDIATE', N'The river is shallow here.', N'Sông nông ở đây.'),
(N'sharp', N'/ʃɑːrp/', N'sắc bén / nhọn', N'adjective', N'BEGINNER', N'Be careful with that sharp knife.', N'Cẩn thận với con dao sắc đó.'),
(N'sincere', N'/sɪnˈsɪr/', N'chân thành / thật lòng', N'adjective', N'INTERMEDIATE', N'She gave a sincere apology.', N'Cô ấy xin lỗi chân thành.'),
(N'slight', N'/slaɪt/', N'nhẹ / chút ít', N'adjective', N'INTERMEDIATE', N'There is a slight improvement.', N'Có sự cải thiện nhỏ.'),
(N'solid', N'/ˈsɒlɪd/', N'rắn chắc / vững chắc', N'adjective', N'INTERMEDIATE', N'Build a solid foundation.', N'Xây dựng nền tảng vững chắc.'),
(N'sparse', N'/spɑːrs/', N'thưa thớt / rải rác', N'adjective', N'ADVANCED', N'The population is sparse in this area.', N'Dân cư thưa thớt ở khu vực này.'),
(N'stable', N'/ˈsteɪbəl/', N'ổn định / vững vàng', N'adjective', N'INTERMEDIATE', N'Keep the economy stable.', N'Giữ nền kinh tế ổn định.'),
(N'static', N'/ˈstætɪk/', N'tĩnh / không đổi', N'adjective', N'ADVANCED', N'Avoid static thinking.', N'Tránh tư duy tĩnh.'),
(N'steady', N'/ˈstedi/', N'vững chắc / đều đặn', N'adjective', N'INTERMEDIATE', N'Keep a steady pace.', N'Giữ nhịp độ đều đặn.'),
(N'steep', N'/stiːp/', N'dốc / ngắt', N'adjective', N'INTERMEDIATE', N'The hill is very steep.', N'Ngọn đồi rất dốc.'),
(N'stiff', N'/stɪf/', N'cứng / cứng đờ', N'adjective', N'INTERMEDIATE', N'My neck is stiff from sleeping.', N'Cổ tôi cứng vì ngủ.'),
(N'swift', N'/swɪft/', N'nhanh chóng / mau lẹ', N'adjective', N'INTERMEDIATE', N'Take swift action.', N'Hành động nhanh chóng.'),
(N'tender', N'/ˈtendər/', N'mềm mại / âu yếm', N'adjective', N'INTERMEDIATE', N'The meat is very tender.', N'Thịt rất mềm.'),
(N'tense', N'/tens/', N'căng thẳng / thì (ngữ pháp)', N'adjective', N'INTERMEDIATE', N'The atmosphere was tense.', N'Bầu không khí rất căng thẳng.'),
(N'thin', N'/θɪn/', N'mỏng / gầy', N'adjective', N'BEGINNER', N'She is very thin.', N'Cô ấy rất gầy.'),
(N'tight', N'/taɪt/', N'chật / chặt', N'adjective', N'BEGINNER', N'These shoes are too tight.', N'Đôi giày này quá chật.'),
(N'timid', N'/ˈtɪmɪd/', N'nhút nhát / rụt rè', N'adjective', N'INTERMEDIATE', N'He was too timid to speak.', N'Anh ấy quá nhút nhát để nói.'),
(N'tough', N'/tʌf/', N'khó khăn / cứng rắn', N'adjective', N'INTERMEDIATE', N'It is a tough decision.', N'Đó là quyết định khó khăn.'),
(N'transparent', N'/trænsˈpærənt/', N'trong suốt / minh bạch', N'adjective', N'INTERMEDIATE', N'Be transparent about your goals.', N'Hãy minh bạch về mục tiêu của bạn.'),
(N'trivial', N'/ˈtrɪviəl/', N'tầm thường / không quan trọng', N'adjective', N'ADVANCED', N'Do not waste time on trivial matters.', N'Đừng lãng phí thời gian vào việc tầm thường.'),
(N'urban', N'/ˈɜːrbən/', N'đô thị / thành thị', N'adjective', N'INTERMEDIATE', N'Urban life is fast-paced.', N'Cuộc sống đô thị diễn ra nhanh chóng.'),
(N'vague', N'/veɪɡ/', N'mơ hồ / không rõ ràng', N'adjective', N'INTERMEDIATE', N'His answer was too vague.', N'Câu trả lời của anh ấy quá mơ hồ.'),
(N'vast', N'/vɑːst/', N'rộng lớn / mênh mông', N'adjective', N'INTERMEDIATE', N'The ocean is vast.', N'Đại dương thật mênh mông.'),
(N'vibrant', N'/ˈvaɪbrənt/', N'sôi động / rực rỡ', N'adjective', N'INTERMEDIATE', N'The city has a vibrant culture.', N'Thành phố có nền văn hóa sôi động.'),
(N'violent', N'/ˈvaɪələnt/', N'bạo lực / dữ dội', N'adjective', N'INTERMEDIATE', N'Avoid violent behavior.', N'Tránh hành vi bạo lực.'),
(N'vocal', N'/ˈvoʊkəl/', N'lên tiếng / thuộc giọng nói', N'adjective', N'INTERMEDIATE', N'She is vocal about her opinions.', N'Cô ấy lên tiếng về ý kiến của mình.'),
(N'weary', N'/ˈwɪri/', N'mệt mỏi / chán nản', N'adjective', N'INTERMEDIATE', N'He was weary after the long trip.', N'Anh ấy mệt mỏi sau chuyến đi dài.'),
(N'whole', N'/hoʊl/', N'toàn bộ / nguyên vẹn', N'adjective', N'BEGINNER', N'I spent the whole day studying.', N'Tôi dành cả ngày để học.'),
(N'wild', N'/waɪld/', N'hoang dã / điên cuồng', N'adjective', N'BEGINNER', N'Wild animals live in the forest.', N'Động vật hoang dã sống trong rừng.'),
(N'wise', N'/waɪz/', N'khôn ngoan', N'adjective', N'BEGINNER', N'It is wise to save money.', N'Tiết kiệm tiền là khôn ngoan.'),
(N'worthy', N'/ˈwɜːrði/', N'xứng đáng / có giá trị', N'adjective', N'INTERMEDIATE', N'He is worthy of trust.', N'Anh ấy xứng đáng được tin tưởng.'),
-- Common verbs
(N'absorb', N'/əbˈzɔːrb/', N'hấp thụ / tiếp thu', N'verb', N'INTERMEDIATE', N'Plants absorb sunlight to grow.', N'Cây hấp thụ ánh sáng mặt trời để phát triển.'),
(N'accelerate', N'/əkˈseləreɪt/', N'tăng tốc', N'verb', N'INTERMEDIATE', N'Accelerate the process.', N'Tăng tốc quá trình.'),
(N'accumulate', N'/əˈkjuːmjuleɪt/', N'tích lũy / tích góp', N'verb', N'INTERMEDIATE', N'Accumulate knowledge over time.', N'Tích lũy kiến thức theo thời gian.'),
(N'activate', N'/ˈæktɪveɪt/', N'kích hoạt', N'verb', N'INTERMEDIATE', N'Activate your account by email.', N'Kích hoạt tài khoản qua email.'),
(N'adjust', N'/əˈdʒʌst/', N'điều chỉnh / thích nghi', N'verb', N'INTERMEDIATE', N'Adjust the settings as needed.', N'Điều chỉnh cài đặt khi cần.'),
(N'admire', N'/ədˈmaɪər/', N'ngưỡng mộ / thán phục', N'verb', N'BEGINNER', N'I admire her courage.', N'Tôi ngưỡng mộ sự can đảm của cô ấy.'),
(N'approve', N'/əˈpruːv/', N'chấp thuận / phê duyệt', N'verb', N'INTERMEDIATE', N'The manager approved the proposal.', N'Người quản lý đã phê duyệt đề xuất.'),
(N'balance', N'/ˈbæləns/', N'cân bằng', N'verb', N'INTERMEDIATE', N'Balance work and personal life.', N'Cân bằng công việc và cuộc sống cá nhân.'),
(N'bind', N'/baɪnd/', N'ràng buộc / buộc lại', N'verb', N'INTERMEDIATE', N'This contract binds both parties.', N'Hợp đồng này ràng buộc cả hai bên.'),
(N'blend', N'/blend/', N'pha trộn / kết hợp', N'verb', N'INTERMEDIATE', N'Blend the ingredients together.', N'Trộn các nguyên liệu lại với nhau.'),
(N'boost', N'/buːst/', N'thúc đẩy / tăng cường', N'verb', N'INTERMEDIATE', N'Exercise boosts your energy.', N'Tập thể dục tăng cường năng lượng của bạn.'),
(N'breathe', N'/briːð/', N'thở', N'verb', N'BEGINNER', N'Breathe deeply to relax.', N'Hít thở sâu để thư giãn.'),
(N'build', N'/bɪld/', N'xây dựng / xây dựng', N'verb', N'BEGINNER', N'Build a better future.', N'Xây dựng một tương lai tốt đẹp hơn.'),
(N'burn', N'/bɜːrn/', N'đốt cháy / bỏng', N'verb', N'BEGINNER', N'Be careful not to burn yourself.', N'Cẩn thận đừng để bỏng.'),
(N'climb', N'/klaɪm/', N'leo trèo / trèo', N'verb', N'BEGINNER', N'Climb the mountain in summer.', N'Leo núi vào mùa hè.'),
(N'combine', N'/kəmˈbaɪn/', N'kết hợp', N'verb', N'INTERMEDIATE', N'Combine the two approaches.', N'Kết hợp hai phương pháp.'),
(N'compete', N'/kəmˈpiːt/', N'cạnh tranh / thi đấu', N'verb', N'INTERMEDIATE', N'We compete to improve ourselves.', N'Chúng ta cạnh tranh để cải thiện bản thân.'),
(N'compose', N'/kəmˈpoʊz/', N'soạn / tạo thành', N'verb', N'INTERMEDIATE', N'He composed a beautiful piece of music.', N'Anh ấy soạn một bản nhạc đẹp.'),
(N'cultivate', N'/ˈkʌltɪveɪt/', N'nuôi dưỡng / canh tác', N'verb', N'INTERMEDIATE', N'Cultivate good habits.', N'Nuôi dưỡng thói quen tốt.'),
(N'detect', N'/dɪˈtekt/', N'phát hiện / nhận ra', N'verb', N'INTERMEDIATE', N'The sensor can detect movement.', N'Cảm biến có thể phát hiện chuyển động.'),
(N'dive', N'/daɪv/', N'lặn / đâm đầu vào', N'verb', N'BEGINNER', N'Dive into the pool.', N'Lặn xuống hồ bơi.'),
(N'elect', N'/ɪˈlekt/', N'bầu chọn / lựa chọn', N'verb', N'INTERMEDIATE', N'Elect a new leader.', N'Bầu chọn nhà lãnh đạo mới.'),
(N'emerge', N'/ɪˈmɜːrdʒ/', N'nổi lên / xuất hiện', N'verb', N'INTERMEDIATE', N'New technologies emerge every year.', N'Công nghệ mới nổi lên mỗi năm.'),
(N'employ', N'/ɪmˈplɔɪ/', N'thuê / tuyển dụng', N'verb', N'INTERMEDIATE', N'The company employs 500 workers.', N'Công ty tuyển dụng 500 công nhân.'),
(N'evolve', N'/ɪˈvɒlv/', N'tiến hóa / phát triển', N'verb', N'INTERMEDIATE', N'Industries evolve with technology.', N'Các ngành công nghiệp phát triển cùng công nghệ.'),
(N'feed', N'/fiːd/', N'cho ăn / nuôi', N'verb', N'BEGINNER', N'Feed the animals in the morning.', N'Cho động vật ăn vào buổi sáng.'),
(N'filter', N'/ˈfɪltər/', N'lọc / lọc bỏ', N'verb', N'INTERMEDIATE', N'Filter the water before drinking.', N'Lọc nước trước khi uống.'),
(N'gain', N'/ɡeɪn/', N'đạt được / thu được', N'verb', N'INTERMEDIATE', N'Gain experience through practice.', N'Đạt được kinh nghiệm qua thực hành.'),
(N'heal', N'/hiːl/', N'chữa lành / hồi phục', N'verb', N'INTERMEDIATE', N'Time heals all wounds.', N'Thời gian chữa lành mọi vết thương.'),
(N'hide', N'/haɪd/', N'ẩn / giấu', N'verb', N'BEGINNER', N'Do not hide the truth.', N'Đừng giấu sự thật.'),
(N'hire', N'/haɪər/', N'thuê / tuyển dụng', N'verb', N'INTERMEDIATE', N'We will hire more staff next month.', N'Chúng tôi sẽ tuyển thêm nhân viên tháng tới.'),
(N'hunt', N'/hʌnt/', N'săn / tìm kiếm', N'verb', N'INTERMEDIATE', N'Hunt for the best opportunity.', N'Săn tìm cơ hội tốt nhất.'),
(N'hurt', N'/hɜːrt/', N'làm đau / tổn thương', N'verb', N'BEGINNER', N'Words can hurt people.', N'Lời nói có thể làm tổn thương người khác.'),
(N'include', N'/ɪnˈkluːd/', N'bao gồm', N'verb', N'BEGINNER', N'Include everyone in the plan.', N'Bao gồm mọi người trong kế hoạch.'),
(N'inherit', N'/ɪnˈherɪt/', N'thừa hưởng / kế thừa', N'verb', N'INTERMEDIATE', N'She inherited the family business.', N'Cô ấy thừa kế doanh nghiệp gia đình.'),
(N'interact', N'/ˌɪntərˈækt/', N'tương tác', N'verb', N'INTERMEDIATE', N'Interact with the community.', N'Tương tác với cộng đồng.'),
(N'keep', N'/kiːp/', N'giữ / duy trì', N'verb', N'BEGINNER', N'Keep trying no matter what.', N'Hãy tiếp tục cố gắng dù thế nào.'),
(N'label', N'/ˈleɪbəl/', N'dán nhãn / gán nhãn', N'verb', N'INTERMEDIATE', N'Label the files clearly.', N'Dán nhãn tệp rõ ràng.'),
(N'measure', N'/ˈmeʒər/', N'đo lường', N'verb', N'INTERMEDIATE', N'Measure the room before buying furniture.', N'Đo phòng trước khi mua nội thất.'),
(N'merge', N'/mɜːrdʒ/', N'hợp nhất / sáp nhập', N'verb', N'INTERMEDIATE', N'The two companies will merge.', N'Hai công ty sẽ sáp nhập.'),
(N'modify', N'/ˈmɒdɪfaɪ/', N'sửa đổi / điều chỉnh', N'verb', N'INTERMEDIATE', N'Modify the code to fix the bug.', N'Sửa đổi mã để sửa lỗi.'),
(N'monitor', N'/ˈmɒnɪtər/', N'theo dõi / giám sát', N'verb', N'INTERMEDIATE', N'Monitor your health regularly.', N'Theo dõi sức khỏe thường xuyên.'),
(N'notify', N'/ˈnoʊtɪfaɪ/', N'thông báo', N'verb', N'INTERMEDIATE', N'Notify all team members immediately.', N'Thông báo cho tất cả thành viên nhóm ngay lập tức.'),
(N'propose', N'/prəˈpoʊz/', N'đề xuất / cầu hôn', N'verb', N'INTERMEDIATE', N'Propose a solution to the problem.', N'Đề xuất giải pháp cho vấn đề.'),
(N'pull', N'/pʊl/', N'kéo', N'verb', N'BEGINNER', N'Pull the door to open it.', N'Kéo cửa để mở.'),
(N'push', N'/pʊʃ/', N'đẩy', N'verb', N'BEGINNER', N'Push the button to start.', N'Nhấn nút để bắt đầu.'),
(N'recruit', N'/rɪˈkruːt/', N'tuyển dụng', N'verb', N'INTERMEDIATE', N'Recruit talented people.', N'Tuyển dụng những người tài năng.'),
(N'represent', N'/ˌreprɪˈzent/', N'đại diện / thể hiện', N'verb', N'INTERMEDIATE', N'She represents the company abroad.', N'Cô ấy đại diện công ty ở nước ngoài.'),
(N'scan', N'/skæn/', N'quét / đọc nhanh', N'verb', N'INTERMEDIATE', N'Scan the document before sending.', N'Quét tài liệu trước khi gửi.'),
(N'schedule', N'/ˈʃedʒuːl/', N'lên lịch / sắp xếp', N'verb', N'INTERMEDIATE', N'Schedule a meeting for Monday.', N'Lên lịch họp vào thứ Hai.'),
(N'serve', N'/sɜːrv/', N'phục vụ', N'verb', N'BEGINNER', N'Serve the guests with care.', N'Phục vụ khách một cách chu đáo.'),
(N'sketch', N'/sketʃ/', N'phác thảo / vẽ phác', N'verb', N'INTERMEDIATE', N'Sketch your ideas on paper first.', N'Phác thảo ý tưởng của bạn trên giấy trước.'),
(N'sort', N'/sɔːrt/', N'sắp xếp / phân loại', N'verb', N'BEGINNER', N'Sort the files by date.', N'Sắp xếp tệp theo ngày.'),
(N'split', N'/splɪt/', N'chia đôi / tách ra', N'verb', N'INTERMEDIATE', N'Split the cost equally.', N'Chia đều chi phí.'),
(N'spread', N'/spred/', N'lan rộng / trải rộng', N'verb', N'INTERMEDIATE', N'Spread the news quickly.', N'Lan truyền tin tức nhanh chóng.'),
(N'stream', N'/striːm/', N'phát trực tuyến / chảy', N'verb', N'INTERMEDIATE', N'Stream the video online.', N'Phát video trực tuyến.'),
(N'stretch', N'/stretʃ/', N'kéo căng / giãn', N'verb', N'BEGINNER', N'Stretch before exercising.', N'Khởi động trước khi tập thể dục.'),
(N'submit', N'/səbˈmɪt/', N'nộp / đệ trình', N'verb', N'INTERMEDIATE', N'Submit your application online.', N'Nộp đơn trực tuyến của bạn.'),
(N'suffer', N'/ˈsʌfər/', N'chịu đựng / khổ sở', N'verb', N'INTERMEDIATE', N'No one should suffer in silence.', N'Không ai nên chịu đựng trong im lặng.'),
(N'switch', N'/swɪtʃ/', N'chuyển đổi', N'verb', N'BEGINNER', N'Switch off the lights.', N'Tắt đèn đi.'),
(N'tackle', N'/ˈtækəl/', N'giải quyết / đương đầu', N'verb', N'INTERMEDIATE', N'Tackle the problem head-on.', N'Giải quyết vấn đề trực tiếp.'),
(N'tap', N'/tæp/', N'nhấn / khai thác', N'verb', N'BEGINNER', N'Tap the screen to select.', N'Nhấn vào màn hình để chọn.'),
(N'trace', N'/treɪs/', N'theo dõi / vết', N'verb', N'INTERMEDIATE', N'Trace the origin of the problem.', N'Truy tìm nguồn gốc của vấn đề.'),
(N'trigger', N'/ˈtrɪɡər/', N'kích hoạt / gây ra', N'verb', N'INTERMEDIATE', N'Stress can trigger health problems.', N'Căng thẳng có thể gây ra vấn đề sức khỏe.'),
(N'upgrade', N'/ˈʌpɡreɪd/', N'nâng cấp', N'verb', N'INTERMEDIATE', N'Upgrade your software regularly.', N'Nâng cấp phần mềm thường xuyên.'),
(N'verify', N'/ˈverɪfaɪ/', N'xác minh / kiểm chứng', N'verb', N'INTERMEDIATE', N'Verify the information before sharing.', N'Xác minh thông tin trước khi chia sẻ.'),
(N'vote', N'/voʊt/', N'bỏ phiếu / biểu quyết', N'verb', N'BEGINNER', N'Vote for the best candidate.', N'Bỏ phiếu cho ứng cử viên tốt nhất.'),
(N'waste', N'/weɪst/', N'lãng phí', N'verb', N'BEGINNER', N'Do not waste water.', N'Đừng lãng phí nước.'),
(N'withdraw', N'/wɪðˈdrɔː/', N'rút tiền / rút lui', N'verb', N'INTERMEDIATE', N'Withdraw money from the ATM.', N'Rút tiền từ ATM.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('able','acute','alike','alive','ample','awful','bare','blunt','bold','calm','cheap','civil','clear','coarse','compact','concrete','damp','decent','dense','dull','durable','dynamic','eager','exact','fair','faint','fake','fierce','final','flawed','frail','fresh','grim','harsh','hollow','ideal','idle','intact','keen','lean','lively','loose','lush','massive','mature','mild','neat','neutral','noble','numb','odd','oral','pale','partial','passive','precise','prime','prone','proud','pure','quick','rare','raw','remote','rigid','rough','rural','sacred','scarce','shallow','sharp','sincere','slight','solid','sparse','stable','static','steady','steep','stiff','swift','tender','tense','thin','tight','timid','tough','transparent','trivial','urban','vague','vast','vibrant','violent','vocal','weary','whole','wild','wise','worthy','absorb','accelerate','accumulate','activate','adjust','admire','approve','balance','bind','blend','boost','breathe','build','burn','climb','combine','compete','compose','cultivate','detect','dive','elect','emerge','employ','evolve','feed','filter','gain','heal','hide','hire','hunt','hurt','include','inherit','interact','keep','label','measure','merge','modify','monitor','notify','propose','pull','push','recruit','represent','scan','schedule','serve','sketch','sort','split','spread','stream','stretch','submit','suffer','switch','tackle','tap','trace','trigger','upgrade','verify','vote','waste','withdraw');
