--liquibase formatted sql

--changeset vocab:053-seed-words-batch46
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.example_sentence, v.example_translation
FROM (VALUES
(N'air', N'/ɛr/', N'không khí / bầu trời', N'noun', N'BEGINNER', N'Fresh air is good for the lungs.', N'Không khí trong lành tốt cho phổi.'),
(N'bite', N'/baɪt/', N'cắn / miếng cắn', N'verb', N'BEGINNER', N'The dog might bite.', N'Con chó có thể cắn.'),
(N'cut', N'/kʌt/', N'cắt / giảm', N'verb', N'BEGINNER', N'Cut the paper into pieces.', N'Cắt tờ giấy thành từng mảnh.'),
(N'draw', N'/drɔː/', N'vẽ / kéo', N'verb', N'BEGINNER', N'She can draw very well.', N'Cô ấy có thể vẽ rất giỏi.'),
(N'fill', N'/fɪl/', N'lấp đầy / điền vào', N'verb', N'BEGINNER', N'Fill in the blanks.', N'Điền vào chỗ trống.'),
(N'flow', N'/floʊ/', N'chảy / lưu thông', N'verb', N'INTERMEDIATE', N'Water flows downhill.', N'Nước chảy xuống dốc.'),
(N'mix', N'/mɪks/', N'trộn / pha trộn', N'verb', N'BEGINNER', N'Mix the flour and water.', N'Trộn bột mì và nước.'),
(N'plan', N'/plæn/', N'lên kế hoạch', N'verb', N'BEGINNER', N'Plan your day the night before.', N'Lên kế hoạch cho ngày của bạn vào đêm trước.'),
(N'produce', N'/prəˈdjuːs/', N'sản xuất / tạo ra', N'verb', N'INTERMEDIATE', N'This factory produces cars.', N'Nhà máy này sản xuất xe hơi.'),
(N'report', N'/rɪˈpɔːrt/', N'báo cáo / tường thuật', N'verb', N'INTERMEDIATE', N'Report the incident to the manager.', N'Báo cáo sự cố cho người quản lý.'),
(N'roll', N'/roʊl/', N'lăn / cuộn', N'verb', N'BEGINNER', N'The ball rolled down the hill.', N'Quả bóng lăn xuống dốc.'),
(N'sign', N'/saɪn/', N'ký / ra hiệu', N'verb', N'BEGINNER', N'Sign the contract today.', N'Ký hợp đồng hôm nay.'),
(N'swap', N'/swɒp/', N'hoán đổi / trao đổi', N'verb', N'INTERMEDIATE', N'Swap your old phone for a new one.', N'Đổi điện thoại cũ lấy cái mới.'),
(N'test', N'/test/', N'kiểm tra / thử nghiệm', N'verb', N'BEGINNER', N'Test the product before launch.', N'Kiểm tra sản phẩm trước khi ra mắt.'),
(N'map', N'/mæp/', N'lập bản đồ / vạch ra', N'verb', N'INTERMEDIATE', N'Map out the project timeline.', N'Vạch ra dòng thời gian dự án.'),
(N'track', N'/træk/', N'theo dõi / bám sát', N'verb', N'INTERMEDIATE', N'Track your daily expenses.', N'Theo dõi chi tiêu hàng ngày của bạn.'),
(N'trim', N'/trɪm/', N'cắt tỉa / thu gọn', N'verb', N'INTERMEDIATE', N'Trim the budget to save costs.', N'Cắt giảm ngân sách để tiết kiệm chi phí.'),
(N'back up', N'/bæk ʌp/', N'sao lưu / hỗ trợ', N'verb', N'INTERMEDIATE', N'Back up your files every day.', N'Sao lưu tệp của bạn mỗi ngày.'),
(N'calm down', N'/kɑːm daʊn/', N'bình tĩnh lại', N'verb', N'BEGINNER', N'Calm down and breathe.', N'Bình tĩnh và hít thở.'),
(N'count on', N'/kaʊnt ɒn/', N'tin tưởng / trông cậy vào', N'verb', N'INTERMEDIATE', N'You can count on me.', N'Bạn có thể trông cậy vào tôi.'),
(N'cut off', N'/kʌt ɒf/', N'cắt đứt / ngắt', N'verb', N'INTERMEDIATE', N'The storm cut off the power.', N'Cơn bão đã cắt điện.'),
(N'get up', N'/ɡet ʌp/', N'thức dậy', N'verb', N'BEGINNER', N'Get up early every morning.', N'Thức dậy sớm mỗi sáng.'),
(N'log in', N'/lɒɡ ɪn/', N'đăng nhập', N'verb', N'BEGINNER', N'Log in with your username.', N'Đăng nhập bằng tên người dùng của bạn.'),
(N'log out', N'/lɒɡ aʊt/', N'đăng xuất', N'verb', N'BEGINNER', N'Log out when you are done.', N'Đăng xuất khi bạn hoàn thành.'),
(N'make out', N'/meɪk aʊt/', N'hiểu ra / nhận ra', N'verb', N'INTERMEDIATE', N'I could not make out what he said.', N'Tôi không thể hiểu những gì anh ấy nói.'),
(N'pass on', N'/pɑːs ɒn/', N'truyền lại / bỏ qua', N'verb', N'INTERMEDIATE', N'Pass on the knowledge to others.', N'Truyền lại kiến thức cho người khác.'),
(N'set off', N'/set ɒf/', N'khởi hành / kích hoạt', N'verb', N'INTERMEDIATE', N'We set off early in the morning.', N'Chúng tôi khởi hành sớm vào buổi sáng.'),
(N'show off', N'/ʃoʊ ɒf/', N'khoe khoang / phô trương', N'verb', N'BEGINNER', N'Stop showing off.', N'Hãy ngừng khoe khoang.'),
(N'sign up', N'/saɪn ʌp/', N'đăng ký', N'verb', N'BEGINNER', N'Sign up for the newsletter.', N'Đăng ký nhận bản tin.'),
(N'speak up', N'/spiːk ʌp/', N'lên tiếng / nói to hơn', N'verb', N'INTERMEDIATE', N'Speak up if you disagree.', N'Hãy lên tiếng nếu bạn không đồng ý.'),
(N'turn off', N'/tɜːrn ɒf/', N'tắt', N'verb', N'BEGINNER', N'Turn off the TV before sleeping.', N'Tắt TV trước khi ngủ.'),
(N'turn on', N'/tɜːrn ɒn/', N'bật', N'verb', N'BEGINNER', N'Turn on the light.', N'Bật đèn lên.'),
(N'use up', N'/juːz ʌp/', N'dùng hết', N'verb', N'BEGINNER', N'We used up all the ink.', N'Chúng ta đã dùng hết mực.'),
(N'give in', N'/ɡɪv ɪn/', N'nhượng bộ / đầu hàng', N'verb', N'INTERMEDIATE', N'Never give in to pressure.', N'Đừng bao giờ nhượng bộ áp lực.'),
(N'hang on', N'/hæŋ ɒn/', N'chờ đợi / bám chặt', N'verb', N'BEGINNER', N'Hang on, I will be right back.', N'Chờ tôi một chút, tôi sẽ quay lại ngay.'),
(N'keep on', N'/kiːp ɒn/', N'tiếp tục', N'verb', N'BEGINNER', N'Keep on trying.', N'Hãy tiếp tục cố gắng.'),
(N'let down', N'/let daʊn/', N'làm thất vọng', N'verb', N'INTERMEDIATE', N'Do not let down your team.', N'Đừng làm thất vọng nhóm của bạn.'),
(N'pick up', N'/pɪk ʌp/', N'nhặt lên / đón', N'verb', N'BEGINNER', N'Pick up the kids after school.', N'Đón bọn trẻ sau giờ học.'),
(N'run into', N'/rʌn ˈɪntu/', N'tình cờ gặp / gặp phải', N'verb', N'INTERMEDIATE', N'I ran into an old friend.', N'Tôi tình cờ gặp một người bạn cũ.'),
(N'act', N'/ækt/', N'hành động / đạo luật', N'verb', N'BEGINNER', N'Act quickly in an emergency.', N'Hành động nhanh trong tình huống khẩn cấp.'),
(N'admit', N'/ədˈmɪt/', N'thừa nhận / cho phép vào', N'verb', N'INTERMEDIATE', N'Admit your mistakes and learn.', N'Thừa nhận lỗi lầm và học hỏi.'),
(N'afford', N'/əˈfɔːrd/', N'đủ khả năng / có thể', N'verb', N'INTERMEDIATE', N'Can you afford the tuition?', N'Bạn có đủ khả năng trả học phí không?'),
(N'aim', N'/eɪm/', N'nhắm đến / mục tiêu', N'verb', N'INTERMEDIATE', N'Aim for excellence.', N'Hướng đến sự xuất sắc.'),
(N'anticipate', N'/ænˈtɪsɪpeɪt/', N'dự đoán / trông đợi', N'verb', N'ADVANCED', N'Anticipate problems before they arise.', N'Dự đoán vấn đề trước khi chúng xảy ra.'),
(N'borrow', N'/ˈbɒroʊ/', N'mượn', N'verb', N'BEGINNER', N'Can I borrow your pen?', N'Tôi có thể mượn bút của bạn không?'),
(N'break', N'/breɪk/', N'phá vỡ / nghỉ giải lao', N'verb', N'BEGINNER', N'Take a break every hour.', N'Nghỉ giải lao mỗi giờ.'),
(N'brush', N'/brʌʃ/', N'chải / bàn chải', N'verb', N'BEGINNER', N'Brush your teeth twice a day.', N'Đánh răng hai lần mỗi ngày.'),
(N'challenge', N'/ˈtʃælɪndʒ/', N'thách thức', N'verb', N'INTERMEDIATE', N'Challenge yourself every day.', N'Thách thức bản thân mỗi ngày.'),
(N'chase', N'/tʃeɪs/', N'đuổi theo / theo đuổi', N'verb', N'INTERMEDIATE', N'Chase your dreams relentlessly.', N'Theo đuổi ước mơ không mệt mỏi.'),
(N'check', N'/tʃek/', N'kiểm tra / xem lại', N'verb', N'BEGINNER', N'Check your work before submitting.', N'Kiểm tra bài làm trước khi nộp.'),
(N'cite', N'/saɪt/', N'trích dẫn', N'verb', N'INTERMEDIATE', N'Cite your sources in the essay.', N'Trích dẫn nguồn của bạn trong bài luận.'),
(N'claim', N'/kleɪm/', N'tuyên bố / yêu cầu', N'verb', N'INTERMEDIATE', N'Claim your reward now.', N'Nhận phần thưởng của bạn ngay bây giờ.'),
(N'collect', N'/kəˈlekt/', N'thu thập / sưu tầm', N'verb', N'BEGINNER', N'Collect data from the survey.', N'Thu thập dữ liệu từ cuộc khảo sát.'),
(N'cope', N'/koʊp/', N'đối phó / chịu đựng', N'verb', N'INTERMEDIATE', N'Cope with stress by exercising.', N'Đối phó với căng thẳng bằng cách tập thể dục.'),
(N'count', N'/kaʊnt/', N'đếm / tính', N'verb', N'BEGINNER', N'Count the number of items.', N'Đếm số lượng mặt hàng.'),
(N'delay', N'/dɪˈleɪ/', N'trì hoãn', N'verb', N'INTERMEDIATE', N'Do not delay important tasks.', N'Đừng trì hoãn những công việc quan trọng.'),
(N'display', N'/dɪˈspleɪ/', N'hiển thị / trưng bày', N'verb', N'INTERMEDIATE', N'Display the results clearly.', N'Hiển thị kết quả rõ ràng.'),
(N'divide', N'/dɪˈvaɪd/', N'chia / phân chia', N'verb', N'BEGINNER', N'Divide the work equally.', N'Chia công việc đồng đều.'),
(N'doubt', N'/daʊt/', N'nghi ngờ', N'verb', N'INTERMEDIATE', N'Do not doubt yourself.', N'Đừng nghi ngờ bản thân.'),
(N'drop', N'/drɒp/', N'thả / rơi / giảm', N'verb', N'BEGINNER', N'Drop the bag on the floor.', N'Đặt túi xuống sàn.'),
(N'earn', N'/ɜːrn/', N'kiếm / xứng đáng', N'verb', N'BEGINNER', N'Earn respect through hard work.', N'Kiếm sự tôn trọng qua làm việc chăm chỉ.'),
(N'edit', N'/ˈedɪt/', N'chỉnh sửa / biên tập', N'verb', N'BEGINNER', N'Edit the document before printing.', N'Chỉnh sửa tài liệu trước khi in.'),
(N'examine', N'/ɪɡˈzæmɪn/', N'kiểm tra / xem xét', N'verb', N'INTERMEDIATE', N'Examine the evidence carefully.', N'Xem xét bằng chứng cẩn thận.'),
(N'extend', N'/ɪkˈstend/', N'mở rộng / kéo dài', N'verb', N'INTERMEDIATE', N'Extend the deadline by a week.', N'Gia hạn thời hạn thêm một tuần.'),
(N'fix', N'/fɪks/', N'sửa chữa / cố định', N'verb', N'BEGINNER', N'Fix the broken window.', N'Sửa cửa sổ bị vỡ.'),
(N'focus', N'/ˈfoʊkəs/', N'tập trung', N'verb', N'INTERMEDIATE', N'Focus on what matters.', N'Tập trung vào những gì quan trọng.'),
(N'follow', N'/ˈfɒloʊ/', N'theo dõi / làm theo', N'verb', N'BEGINNER', N'Follow the instructions carefully.', N'Làm theo hướng dẫn cẩn thận.'),
(N'form', N'/fɔːrm/', N'hình thành / tạo ra', N'verb', N'INTERMEDIATE', N'Form good habits early.', N'Hình thành thói quen tốt sớm.'),
(N'gather', N'/ˈɡæðər/', N'tập hợp / thu thập', N'verb', N'INTERMEDIATE', N'Gather all the information first.', N'Thu thập tất cả thông tin trước.'),
(N'guess', N'/ɡes/', N'đoán', N'verb', N'BEGINNER', N'Guess the answer.', N'Đoán câu trả lời.'),
(N'handle', N'/ˈhændəl/', N'xử lý / cầm nắm', N'verb', N'INTERMEDIATE', N'Handle the situation carefully.', N'Xử lý tình huống cẩn thận.'),
(N'imagine', N'/ɪˈmædʒɪn/', N'tưởng tượng', N'verb', N'BEGINNER', N'Imagine a better world.', N'Hãy tưởng tượng một thế giới tốt đẹp hơn.'),
(N'link', N'/lɪŋk/', N'liên kết / kết nối', N'verb', N'INTERMEDIATE', N'Link the two ideas together.', N'Liên kết hai ý tưởng lại với nhau.'),
(N'list', N'/lɪst/', N'liệt kê', N'verb', N'BEGINNER', N'List all the requirements.', N'Liệt kê tất cả các yêu cầu.'),
(N'mark', N'/mɑːrk/', N'đánh dấu / chấm điểm', N'verb', N'BEGINNER', N'Mark the important pages.', N'Đánh dấu các trang quan trọng.'),
(N'match', N'/mætʃ/', N'khớp với / phù hợp', N'verb', N'BEGINNER', N'Match the words with the pictures.', N'Ghép từ với hình ảnh.'),
(N'mention', N'/ˈmenʃən/', N'đề cập / nhắc đến', N'verb', N'INTERMEDIATE', N'Mention your experience in the interview.', N'Đề cập đến kinh nghiệm của bạn trong buổi phỏng vấn.'),
(N'miss', N'/mɪs/', N'nhớ / bỏ lỡ', N'verb', N'BEGINNER', N'I miss my hometown.', N'Tôi nhớ quê hương.'),
(N'object', N'/əbˈdʒekt/', N'phản đối', N'verb', N'INTERMEDIATE', N'He objected to the new policy.', N'Anh ấy phản đối chính sách mới.'),
(N'observe', N'/əbˈzɜːrv/', N'quan sát / tuân thủ', N'verb', N'INTERMEDIATE', N'Observe the behavior of animals.', N'Quan sát hành vi của động vật.'),
(N'obtain', N'/əbˈteɪn/', N'có được / thu được', N'verb', N'INTERMEDIATE', N'Obtain permission before entering.', N'Xin phép trước khi vào.'),
(N'offer', N'/ˈɒfər/', N'đề nghị / cung cấp', N'verb', N'BEGINNER', N'Offer help when needed.', N'Hãy đề nghị giúp đỡ khi cần.'),
(N'order', N'/ˈɔːrdər/', N'đặt hàng / ra lệnh', N'verb', N'BEGINNER', N'Order the food online.', N'Đặt thức ăn trực tuyến.'),
(N'overcome', N'/ˌoʊvərˈkʌm/', N'vượt qua', N'verb', N'INTERMEDIATE', N'Overcome your fears.', N'Vượt qua nỗi sợ hãi của bạn.'),
(N'pass', N'/pɑːs/', N'vượt qua / đậu / đưa', N'verb', N'BEGINNER', N'Pass the test with a high score.', N'Vượt qua bài kiểm tra với điểm cao.'),
(N'persuade', N'/pərˈsweɪd/', N'thuyết phục', N'verb', N'INTERMEDIATE', N'Persuade them with good arguments.', N'Thuyết phục họ bằng lý lẽ tốt.'),
(N'possess', N'/pəˈzes/', N'sở hữu / có', N'verb', N'ADVANCED', N'Possess the skills needed.', N'Sở hữu những kỹ năng cần thiết.'),
(N'postpone', N'/poʊstˈpoʊn/', N'hoãn lại', N'verb', N'INTERMEDIATE', N'Postpone the meeting to tomorrow.', N'Hoãn cuộc họp sang ngày mai.'),
(N'predict', N'/prɪˈdɪkt/', N'dự đoán', N'verb', N'INTERMEDIATE', N'Predict the outcome of the match.', N'Dự đoán kết quả trận đấu.'),
(N'raise', N'/reɪz/', N'nâng cao / tăng lên', N'verb', N'BEGINNER', N'Raise your hand if you know.', N'Giơ tay lên nếu bạn biết.'),
(N'react', N'/riˈækt/', N'phản ứng', N'verb', N'INTERMEDIATE', N'React calmly in emergencies.', N'Phản ứng bình tĩnh trong tình huống khẩn cấp.'),
(N'receive', N'/rɪˈsiːv/', N'nhận / tiếp nhận', N'verb', N'BEGINNER', N'Receive the package at the door.', N'Nhận gói hàng tại cửa.'),
(N'record', N'/rɪˈkɔːrd/', N'ghi lại / thu âm', N'verb', N'INTERMEDIATE', N'Record the meeting for reference.', N'Ghi lại cuộc họp để tham khảo.'),
(N'recycle', N'/ˌriːˈsaɪkəl/', N'tái chế', N'verb', N'BEGINNER', N'Recycle plastic bottles.', N'Tái chế chai nhựa.'),
(N'refer', N'/rɪˈfɜːr/', N'tham khảo / đề cập', N'verb', N'INTERMEDIATE', N'Refer to the manual for help.', N'Tham khảo hướng dẫn để được giúp đỡ.'),
(N'regard', N'/rɪˈɡɑːrd/', N'coi là / liên quan đến', N'verb', N'INTERMEDIATE', N'Regard this as an opportunity.', N'Hãy coi đây là một cơ hội.'),
(N'rely', N'/rɪˈlaɪ/', N'phụ thuộc / dựa vào', N'verb', N'INTERMEDIATE', N'Do not rely on luck alone.', N'Đừng chỉ dựa vào may mắn.'),
(N'remind', N'/rɪˈmaɪnd/', N'nhắc nhở', N'verb', N'BEGINNER', N'Remind me about the meeting.', N'Nhắc tôi về cuộc họp.'),
(N'replace', N'/rɪˈpleɪs/', N'thay thế', N'verb', N'INTERMEDIATE', N'Replace the old parts.', N'Thay thế các bộ phận cũ.'),
(N'request', N'/rɪˈkwest/', N'yêu cầu / đề nghị', N'verb', N'INTERMEDIATE', N'Request additional time.', N'Yêu cầu thêm thời gian.'),
(N'respond', N'/rɪˈspɒnd/', N'phản hồi / trả lời', N'verb', N'INTERMEDIATE', N'Respond to emails promptly.', N'Phản hồi email kịp thời.'),
(N'ride', N'/raɪd/', N'cưỡi / đi', N'verb', N'BEGINNER', N'Ride a bicycle to school.', N'Đi xe đạp đến trường.'),
(N'rise', N'/raɪz/', N'tăng lên / mọc lên', N'verb', N'INTERMEDIATE', N'Prices rise every year.', N'Giá cả tăng mỗi năm.'),
(N'risk', N'/rɪsk/', N'mạo hiểm / liều', N'verb', N'INTERMEDIATE', N'Do not risk your health.', N'Đừng mạo hiểm với sức khỏe của bạn.'),
(N'seek', N'/siːk/', N'tìm kiếm / tìm', N'verb', N'INTERMEDIATE', N'Seek advice from experts.', N'Tìm kiếm lời khuyên từ chuyên gia.'),
(N'select', N'/sɪˈlekt/', N'chọn lọc / lựa chọn', N'verb', N'INTERMEDIATE', N'Select the best option.', N'Chọn lựa chọn tốt nhất.'),
(N'share', N'/ʃɛr/', N'chia sẻ', N'verb', N'BEGINNER', N'Share your ideas with the class.', N'Chia sẻ ý tưởng của bạn với lớp.'),
(N'shift', N'/ʃɪft/', N'thay đổi / chuyển', N'verb', N'INTERMEDIATE', N'Shift your focus to solutions.', N'Chuyển sự chú ý của bạn sang các giải pháp.'),
(N'signal', N'/ˈsɪɡnəl/', N'ra hiệu / báo hiệu', N'verb', N'INTERMEDIATE', N'Signal before turning.', N'Bật xi-nhan trước khi quẹo.'),
(N'slow', N'/sloʊ/', N'làm chậm lại / trì hoãn', N'verb', N'BEGINNER', N'Slow down at the intersection.', N'Giảm tốc độ tại ngã tư.'),
(N'store', N'/stɔːr/', N'lưu trữ', N'verb', N'BEGINNER', N'Store the data securely.', N'Lưu trữ dữ liệu an toàn.'),
(N'study', N'/ˈstʌdi/', N'học tập / nghiên cứu', N'verb', N'BEGINNER', N'Study hard for the exam.', N'Học chăm chỉ cho kỳ thi.'),
(N'teach', N'/tiːtʃ/', N'dạy học', N'verb', N'BEGINNER', N'Teach others what you know.', N'Dạy những gì bạn biết cho người khác.'),
(N'trust', N'/trʌst/', N'tin tưởng', N'verb', N'BEGINNER', N'Trust your instincts.', N'Hãy tin vào bản năng của bạn.'),
(N'turn', N'/tɜːrn/', N'quay / rẽ', N'verb', N'BEGINNER', N'Turn left at the corner.', N'Rẽ trái ở góc đường.'),
(N'vary', N'/ˈvɛri/', N'biến đổi / thay đổi', N'verb', N'INTERMEDIATE', N'Results vary depending on the method.', N'Kết quả thay đổi tùy thuộc vào phương pháp.'),
(N'visit', N'/ˈvɪzɪt/', N'thăm / ghé thăm', N'verb', N'BEGINNER', N'Visit your grandparents often.', N'Thường xuyên thăm ông bà.'),
(N'welcome', N'/ˈwelkəm/', N'chào đón', N'verb', N'BEGINNER', N'Welcome the new students.', N'Chào đón học sinh mới.'),
(N'wonder', N'/ˈwʌndər/', N'tự hỏi / kỳ diệu', N'verb', N'BEGINNER', N'I wonder what will happen next.', N'Tôi tự hỏi chuyện gì sẽ xảy ra tiếp theo.'),
(N'worry', N'/ˈwʌri/', N'lo lắng', N'verb', N'BEGINNER', N'Do not worry about the future.', N'Đừng lo lắng về tương lai.'),
(N'write', N'/raɪt/', N'viết', N'verb', N'BEGINNER', N'Write your name on the top.', N'Viết tên bạn lên trên cùng.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('air','bite','cut','draw','fill','flow','mix','plan','produce','report','roll','sign','swap','test','map','track','trim','back up','calm down','count on','cut off','get up','log in','log out','make out','pass on','set off','show off','sign up','speak up','turn off','turn on','use up','give in','hang on','keep on','let down','pick up','run into','act','admit','afford','aim','anticipate','borrow','break','brush','challenge','chase','check','cite','claim','collect','cope','count','delay','display','divide','doubt','drop','earn','edit','examine','extend','fix','focus','follow','form','gather','guess','handle','imagine','link','list','mark','match','mention','miss','object','observe','obtain','offer','order','overcome','pass','persuade','possess','postpone','predict','raise','react','receive','record','recycle','refer','regard','rely','remind','replace','request','respond','ride','rise','risk','seek','select','share','shift','signal','slow','store','study','teach','trust','turn','vary','visit','welcome','wonder','worry','write');
