--liquibase formatted sql

--changeset vocab:055-fix-word-categories
-- Backfill category for all batch-seeded words

UPDATE words SET category = 'Actions' WHERE category IS NULL AND word IN ('eat', 'drink', 'sleep', 'wake', 'cook', 'clean', 'wash', 'open', 'close', 'buy', 'sell', 'pay', 'carry', 'give', 'take', 'put', 'find', 'lose', 'use', 'need', 'talk', 'listen', 'look', 'see', 'hear', 'think', 'know', 'want', 'like', 'love', 'hate', 'feel', 'try', 'start', 'stop', 'wait', 'help', 'work', 'play', 'study', 'accept', 'refuse', 'agree', 'disagree', 'suggest', 'recommend', 'request', 'demand', 'confirm', 'cancel');
UPDATE words SET category = 'Actions' WHERE category IS NULL AND word IN ('postpone', 'arrange', 'manage', 'control', 'handle', 'solve', 'develop', 'improve', 'maintain', 'achieve', 'come', 'go', 'make', 'do', 'get', 'have', 'say', 'tell', 'ask', 'answer', 'call', 'show', 'bring', 'send', 'receive', 'give up', 'take off', 'put off', 'look up', 'find out', 'break down', 'carry out', 'set up', 'come up with', 'go through', 'turn', 'change', 'choose', 'decide', 'forget', 'remember', 'understand', 'explain', 'meet', 'jump', 'sing', 'dance', 'laugh', 'cry', 'smile');
UPDATE words SET category = 'Actions' WHERE category IS NULL AND word IN ('anticipate', 'acknowledge', 'distinguish', 'evaluate', 'interpret', 'demonstrate', 'implement', 'incorporate', 'integrate', 'generate', 'transform', 'illustrate', 'examine', 'specify', 'justify', 'reduce', 'reuse', 'recycle', 'conserve', 'sustain', 'compost', 'solar energy', 'wind turbine', 'emission', 'degrade', 'accomplish', 'acquire', 'adapt', 'adopt', 'affect', 'allocate', 'alter', 'assess', 'assume', 'clarify', 'collaborate', 'communicate', 'compensate', 'concentrate', 'consent', 'coordinate', 'criticize', 'dedicate', 'differentiate', 'distribute', 'emphasize', 'exceed', 'execute', 'facilitate', 'maximize');
UPDATE words SET category = 'Actions' WHERE category IS NULL AND word IN ('minimize', 'motivate', 'negotiate', 'optimize', 'organize', 'overcome', 'prioritize', 'quantify', 'reinforce', 'simplify', 'summarize', 'validate', 'break out', 'bring about', 'bring up', 'call off', 'carry on', 'catch up', 'check in', 'check out', 'come across', 'cut back', 'deal with', 'figure out', 'get along', 'get away', 'go ahead', 'go over', 'grow up', 'hand in', 'hold on', 'keep up', 'look after', 'look forward to', 'look into', 'make up', 'move on', 'point out', 'pull off', 'run out', 'show up', 'take over', 'talk over', 'think over', 'throw away', 'turn down', 'work out');

UPDATE words SET category = 'Animals' WHERE category IS NULL AND word IN ('horse', 'cow', 'pig', 'chicken', 'duck', 'rabbit', 'fish', 'tiger', 'lion', 'elephant', 'monkey', 'snake', 'frog', 'butterfly', 'bee', 'mouse', 'bear', 'wolf', 'deer', 'whale', 'amphibian', 'antelope', 'bison', 'cheetah', 'chimpanzee', 'crab', 'crane', 'crocodile', 'dolphin', 'donkey', 'dragonfly', 'eagle', 'flamingo', 'fox', 'giraffe', 'gorilla', 'hippopotamus', 'jellyfish', 'kangaroo', 'leopard', 'lobster', 'lynx', 'moose', 'mosquito', 'octopus', 'ostrich', 'otter', 'owl', 'panda', 'parrot');
UPDATE words SET category = 'Animals' WHERE category IS NULL AND word IN ('penguin', 'python', 'rhinoceros', 'salmon', 'scorpion', 'seal', 'shark', 'sparrow', 'squirrel', 'stingray', 'tortoise', 'vulture', 'walrus', 'wasp', 'worm', 'zebra');

UPDATE words SET category = 'Body' WHERE category IS NULL AND word IN ('head', 'face', 'eye', 'nose', 'mouth', 'ear', 'tooth', 'hair', 'neck', 'shoulder', 'arm', 'hand', 'finger', 'leg', 'foot', 'back', 'stomach', 'heart', 'blood', 'skin', 'ankle', 'elbow', 'eyebrow', 'forehead', 'jaw', 'lung', 'palm', 'spine', 'temple', 'thumb', 'wrist');

UPDATE words SET category = 'Business' WHERE category IS NULL AND word IN ('meeting', 'deadline', 'project', 'budget', 'profit', 'loss', 'contract', 'client', 'colleague', 'promotion', 'salary', 'bonus', 'interview', 'resume', 'experience', 'skill', 'leadership', 'teamwork', 'strategy', 'achieve', 'bank', 'account', 'interest', 'investment', 'loan', 'debt', 'tax', 'insurance', 'mortgage', 'afford', 'inflation', 'recession', 'gross domestic product', 'monopoly', 'commodity', 'depreciation', 'subsidy', 'fiscal', 'monetary', 'austerity', 'hedge fund', 'derivatives', 'portfolio', 'liquidity', 'volatility', 'collateral', 'speculation', 'dividend', 'equity', 'amortize');
UPDATE words SET category = 'Business' WHERE category IS NULL AND word IN ('quarterly', 'revenue', 'overhead', 'stakeholder', 'benchmark', 'objective', 'proposal', 'agenda', 'collaborate', 'negotiate', 'allocate', 'prioritize', 'implement', 'streamline', 'outsource', 'oligopoly', 'duopoly', 'elasticity', 'macroeconomics', 'microeconomics', 'supply chain', 'market share', 'trade deficit', 'quantitative easing', 'stagflation', 'brand', 'target audience', 'advertising', 'social media', 'engagement', 'viral', 'content', 'platform', 'influencer', 'analytics', 'document', 'spreadsheet', 'invoice', 'receipt', 'minutes', 'signature', 'confidential', 'protocol', 'delegate', 'asset', 'audit', 'bond', 'capital', 'credit', 'currency');
UPDATE words SET category = 'Business' WHERE category IS NULL AND word IN ('deficit', 'expenditure', 'interest rate', 'invest', 'liability', 'shareholder', 'stock market', 'surplus', 'tariff', 'transaction', 'venture');

UPDATE words SET category = 'Character' WHERE category IS NULL AND word IN ('ambitious', 'determined', 'humble', 'reliable', 'flexible', 'adaptable', 'innovative', 'tolerant', 'diligent', 'straightforward');

UPDATE words SET category = 'Clothing' WHERE category IS NULL AND word IN ('shirt', 'pants', 'dress', 'skirt', 'jacket', 'shoes', 'socks', 'hat', 'gloves', 'scarf', 'glasses', 'wear', 'blouse', 'bracelet', 'cap', 'collar', 'costume', 'fabric', 'sleeve', 'sweater', 'uniform', 'zipper');

UPDATE words SET category = 'Communication' WHERE category IS NULL AND word IN ('communicate', 'negotiation', 'presentation', 'feedback', 'broadcast', 'translate', 'interpret', 'publish', 'journalism', 'editorial', 'persuade', 'convince', 'emphasize', 'summarize', 'verbal');

UPDATE words SET category = 'Culture' WHERE category IS NULL AND word IN ('community', 'society', 'population', 'generation', 'diversity', 'equality', 'freedom', 'democracy', 'government', 'policy', 'election', 'campaign', 'protest', 'debate', 'influence', 'impact', 'challenge', 'opportunity', 'consequence', 'resolve', 'abstract', 'aesthetic', 'canvas', 'choreography', 'classical', 'composer', 'exhibition', 'folk', 'gallery', 'genre', 'harmony', 'heritage', 'melody', 'mosaic', 'mural', 'orchestra', 'portrait', 'sculpture', 'symphony', 'theatrical');

UPDATE words SET category = 'Descriptive' WHERE category IS NULL AND word IN ('big', 'small', 'long', 'short', 'tall', 'wide', 'narrow', 'heavy', 'light', 'fast', 'slow', 'hard', 'soft', 'full', 'empty', 'clean', 'dirty', 'wet', 'dry', 'round', 'color', 'red', 'blue', 'green', 'yellow', 'white', 'black', 'orange', 'purple', 'pink', 'brown', 'gray', 'circle', 'square', 'triangle', 'rectangle', 'accurate', 'precise', 'relevant', 'significant', 'obvious', 'complex', 'comprehensive', 'sufficient', 'appropriate', 'effective', 'new', 'old', 'good', 'bad');
UPDATE words SET category = 'Descriptive' WHERE category IS NULL AND word IN ('great', 'beautiful', 'ugly', 'strong', 'weak', 'young', 'rich', 'poor', 'safe', 'dangerous', 'easy', 'difficult', 'important', 'interesting', 'boring', 'funny', 'vivid', 'subtle', 'remarkable', 'outstanding', 'spontaneous', 'deliberate', 'consistent', 'exceptional', 'genuine', 'profound', 'aggressive', 'ambitious', 'authentic', 'brilliant', 'cautious', 'constructive', 'controversial', 'convenient', 'cooperative', 'creative', 'critical', 'decisive', 'dedicated', 'demanding', 'dependable', 'efficient', 'eloquent', 'ethical', 'excessive', 'explicit', 'flexible', 'fundamental', 'idealistic', 'imaginative');
UPDATE words SET category = 'Descriptive' WHERE category IS NULL AND word IN ('innovative', 'insightful', 'logical', 'meticulous', 'modest', 'objective', 'outgoing', 'passionate', 'persistent', 'practical', 'proactive', 'productive', 'rational', 'reliable', 'resilient', 'resourceful', 'responsible', 'straightforward', 'systematic', 'versatile', 'amber', 'azure', 'beige', 'bronze', 'charcoal', 'crimson', 'ebony', 'emerald', 'fuchsia', 'ivory', 'lavender', 'maroon', 'mustard', 'navy', 'nude', 'olive', 'peach', 'scarlet', 'silver', 'teal', 'turquoise', 'violet');

UPDATE words SET category = 'Education' WHERE category IS NULL AND word IN ('school', 'class', 'teacher', 'student', 'lesson', 'homework', 'exam', 'answer', 'question', 'pen', 'pencil', 'book', 'notebook', 'ruler', 'eraser', 'bag', 'library', 'read', 'write', 'draw', 'university', 'graduate', 'degree', 'scholarship', 'lecture', 'seminar', 'thesis', 'research', 'knowledge', 'curriculum', 'paradigm', 'hypothesis', 'empirical', 'methodology', 'inference', 'synthesis', 'ambiguous', 'coherent', 'pragmatic', 'jurisdiction', 'listen', 'speak', 'repeat', 'spell', 'translate', 'practice', 'check', 'correct', 'mark', 'pass');
UPDATE words SET category = 'Education' WHERE category IS NULL AND word IN ('fail', 'academic', 'accreditation', 'assignment', 'campus', 'dean', 'dissertation', 'enroll', 'faculty', 'fellowship', 'grade', 'internship', 'literacy', 'mentor', 'module', 'orientation', 'plagiarism', 'portfolio', 'professor', 'syllabi', 'syllabus', 'tuition', 'undergraduate');

UPDATE words SET category = 'Emotions' WHERE category IS NULL AND word IN ('confident', 'anxious', 'grateful', 'frustrated', 'enthusiastic', 'optimistic', 'pessimistic', 'stubborn', 'generous', 'selfish', 'happy', 'sad', 'angry', 'tired', 'hungry', 'thirsty', 'scared', 'excited', 'bored', 'surprised', 'anxiety', 'compassion', 'confidence', 'contempt', 'crave', 'curiosity', 'depression', 'despair', 'determination', 'disgust', 'empathy', 'envy', 'euphoria', 'frustration', 'gratitude', 'grief', 'guilt', 'humility', 'jealousy', 'loneliness', 'melancholy', 'nostalgia', 'optimism', 'patience', 'pessimism', 'pride', 'regret', 'resentment', 'shame', 'sympathy');

UPDATE words SET category = 'Food' WHERE category IS NULL AND word IN ('bread', 'rice', 'egg', 'meat', 'fish', 'vegetable', 'fruit', 'milk', 'juice', 'sugar', 'salt', 'oil', 'butter', 'cheese', 'soup', 'noodle', 'cake', 'cookie', 'chocolate', 'candy', 'ingredient', 'recipe', 'cuisine', 'roast', 'marinate', 'simmer', 'bake', 'grill', 'seasoning', 'portion', 'vegetarian', 'organic', 'nutritious', 'calorie', 'protein', 'apple', 'banana', 'orange', 'grape', 'mango', 'pineapple', 'watermelon', 'strawberry', 'tomato', 'potato', 'carrot', 'onion', 'garlic', 'corn', 'mushroom');
UPDATE words SET category = 'Food' WHERE category IS NULL AND word IN ('boil', 'chop', 'fry', 'leftover', 'marinade', 'pastry', 'steam', 'topping', 'asparagus', 'avocado', 'broccoli', 'bruschetta', 'cabbage', 'cauliflower', 'celery', 'cinnamon', 'clove', 'coconut', 'croissant', 'cucumber', 'cumin', 'eggplant', 'ginger', 'lemon', 'lettuce', 'lime', 'oat', 'olive', 'papaya', 'parsley', 'peach', 'pear', 'plum', 'pomegranate', 'pumpkin', 'raspberry', 'rosemary', 'sage', 'shrimp', 'spinach', 'squash', 'thyme', 'tofu', 'tuna', 'turnip', 'walnut', 'wheat', 'yogurt', 'zucchini', 'espresso');
UPDATE words SET category = 'Food' WHERE category IS NULL AND word IN ('herbal tea');

UPDATE words SET category = 'General' WHERE category IS NULL AND word IN ('environment', 'pollution', 'climate', 'recycling', 'sustainability', 'renewable', 'carbon', 'wildlife', 'ecosystem', 'contaminate', 'legislation', 'constitution', 'litigation', 'verdict', 'prosecution', 'defendant', 'testimony', 'amendment', 'arbitration', 'sanction', 'metabolism', 'genome', 'neuroscience', 'pathogen', 'catalyst', 'phenomenon', 'hypothesis', 'quantum', 'gravity', 'entropy', 'number', 'count', 'add', 'subtract', 'multiply', 'divide', 'half', 'quarter', 'double', 'total', 'sport', 'football', 'basketball', 'swimming', 'tennis', 'team', 'game', 'win', 'lose', 'score');
UPDATE words SET category = 'General' WHERE category IS NULL AND word IN ('practice', 'exercise', 'gym', 'race', 'match', 'success', 'failure', 'progress', 'solution', 'problem', 'decision', 'effort', 'attitude', 'behavior', 'habit', 'principle', 'value', 'goal', 'dream', 'hope', 'trust', 'respect', 'responsibility', 'patience', 'courage', 'appointment', 'complaint', 'permission', 'evidence', 'benefit', 'advantage', 'disadvantage', 'exception', 'aspect', 'with', 'without', 'between', 'among', 'during', 'before', 'after', 'because', 'although', 'therefore', 'however', 'furthermore', 'by heart', 'once in a while', 'all of a sudden', 'at first glance');
UPDATE words SET category = 'General' WHERE category IS NULL AND word IN ('in the long run', 'on the contrary', 'in terms of', 'take into account', 'as a result', 'in other words', 'experiment', 'theory', 'observation', 'analysis', 'conclusion', 'variable', 'laboratory', 'molecule', 'atom', 'determinism', 'existentialism', 'nihilism', 'epistemology', 'ontology', 'dialectic', 'utilitarian', 'empiricism', 'rationalism', 'phenomenology', 'who', 'what', 'where', 'when', 'why', 'how', 'how much', 'how many', 'which', 'whose', 'volleyball', 'badminton', 'boxing', 'cycling', 'marathon', 'goalkeeper', 'championship', 'tournament', 'athlete', 'coach', 'attorney', 'bail', 'ballot', 'ban', 'candidate');
UPDATE words SET category = 'General' WHERE category IS NULL AND word IN ('clause', 'council', 'court', 'enforce', 'federal', 'penalty', 'plaintiff', 'regulate', 'senator', 'witness', 'cardio', 'endurance', 'flexibility', 'interval', 'jogging', 'meditation', 'muscle', 'referee', 'stamina', 'trophy', 'warm-up', 'workout', 'yoga', 'agility', 'analyze', 'anomaly', 'asteroid', 'bacteria', 'cell', 'chemical', 'chromosome', 'compound', 'condense', 'density', 'DNA', 'element', 'evolution', 'fossil', 'friction', 'gene', 'laser', 'magnetic', 'membrane', 'microscope', 'neutron', 'nucleus', 'orbit', 'organism', 'particle', 'photosynthesis');
UPDATE words SET category = 'General' WHERE category IS NULL AND word IN ('plasma', 'polymer', 'probe', 'proton', 'radiation', 'reaction', 'relativity', 'research', 'specimen', 'telescope', 'thermometer', 'velocity', 'virus', 'wavelength', 'abundance', 'achievement', 'ambition', 'appearance', 'authority', 'awareness', 'belief', 'capability', 'character', 'circumstance', 'consciousness', 'consequence', 'credibility', 'discipline', 'diversity', 'efficiency', 'expertise', 'fairness', 'foundation', 'imagination', 'impact', 'independence', 'integrity', 'knowledge', 'leadership', 'mindset', 'momentum', 'motivation', 'objectivity', 'opportunity', 'ownership', 'perspective', 'reputation', 'sacrifice', 'self-discipline', 'transparency');
UPDATE words SET category = 'General' WHERE category IS NULL AND word IN ('uncertainty', 'unity', 'urgency', 'vulnerability', 'willpower', 'by contrast', 'for instance', 'in addition', 'in conclusion', 'in spite of', 'not only but also', 'on the other hand', 'such as', 'that is to say', 'to begin with', 'with regard to', 'alarm', 'apartment', 'appliance', 'attic', 'backyard', 'basement', 'bin', 'blanket', 'blind', 'bowl', 'cabinet', 'candle', 'carpet', 'ceiling', 'closet', 'couch', 'counter', 'curtain', 'cushion', 'drawer', 'driveway', 'fence', 'fireplace', 'floor', 'faucet', 'garage', 'hallway', 'lamp', 'laundry', 'lawn', 'mattress', 'microwave', 'mirror', 'mop');
UPDATE words SET category = 'General' WHERE category IS NULL AND word IN ('nail', 'outlet', 'pantry', 'pillow', 'plumber', 'porch', 'railing', 'renovation', 'rooftop', 'shelf', 'shovel', 'sink', 'socket', 'sofa', 'stairs', 'wardrobe', 'circular', 'cubic', 'cylindrical', 'diagonal', 'dimension', 'geometric', 'hexagon', 'horizontal', 'oval', 'parallel', 'pentagon', 'perpendicular', 'prism', 'sphere', 'symmetry', 'trapezoid', 'vertical', 'calculate', 'decimal', 'denominator', 'equation', 'fraction', 'geometry', 'integer', 'numerator', 'percentage', 'probability', 'statistics', 'theorem', 'trigonometry', 'aberrant', 'abide', 'abridge', 'abstain');
UPDATE words SET category = 'General' WHERE category IS NULL AND word IN ('acrimony', 'adroit', 'affable', 'alleviate', 'aloof', 'ambiguous', 'ameliorate', 'amiable', 'anomalous', 'antipathy', 'apprehension', 'apt', 'arduous', 'articulate', 'ascertain', 'astute', 'atrocity', 'audacious', 'augment', 'avert', 'benevolent', 'brevity', 'candor', 'circumspect', 'cogent', 'compel', 'complicit', 'convoluted', 'covet', 'cynical', 'daunt', 'debilitating', 'deceive', 'decipher', 'deference', 'denigrate', 'denounce', 'despondent', 'detrimental', 'devoid', 'diligent', 'discern', 'disdain', 'diverge', 'dubious', 'elicit', 'accomplish', 'afternoon', 'airport', 'autumn');
UPDATE words SET category = 'General' WHERE category IS NULL AND word IN ('bakery', 'balcony', 'bank', 'bedroom', 'bicycle', 'birthday', 'borrow', 'bottle', 'breakfast', 'bridge', 'building', 'bus', 'button', 'calendar', 'camera', 'canteen', 'card', 'careful', 'carry', 'cash', 'catch', 'change', 'chat', 'child', 'choose', 'cinema', 'city', 'clean', 'clever', 'close', 'clothes', 'cloud', 'cold', 'color', 'come', 'company', 'cook', 'corner', 'cost', 'country', 'cup', 'customer', 'dark', 'daughter', 'decide');

UPDATE words SET category = 'Health' WHERE category IS NULL AND word IN ('medicine', 'hospital', 'doctor', 'nurse', 'patient', 'symptom', 'treatment', 'surgery', 'prescription', 'allergy', 'fever', 'headache', 'infection', 'prevent', 'diagnose', 'recover', 'healthy', 'painful', 'chronic', 'immune', 'diagnosis', 'prognosis', 'rehabilitation', 'chromosome', 'antibody', 'vaccination', 'pathology', 'therapeutic', 'contagious', 'susceptible', 'cardiology', 'neurology', 'oncology', 'pediatrics', 'anesthesia', 'biopsy', 'chemotherapy', 'osteoporosis', 'hypertension', 'autoimmune', 'nutrition', 'vitamin', 'mineral', 'supplement', 'cardio', 'flexibility', 'stamina', 'posture', 'meditation', 'hydration');
UPDATE words SET category = 'Health' WHERE category IS NULL AND word IN ('ache', 'ambulance', 'antibiotic', 'bandage', 'blood pressure', 'capsule', 'clinic', 'disinfect', 'dizzy', 'dosage', 'exhaust', 'fracture', 'hygiene', 'injection', 'insomnia', 'nausea', 'obese', 'paramedic', 'rash', 'recovery', 'remedy', 'stitch', 'therapy', 'transplant', 'vaccine');

UPDATE words SET category = 'Home' WHERE category IS NULL AND word IN ('door', 'window', 'chair', 'table', 'bed', 'floor', 'wall', 'roof', 'kitchen', 'bathroom', 'bedroom', 'living room', 'garden', 'key', 'lamp', 'mirror', 'towel', 'soap', 'brush', 'comb', 'knife', 'fork', 'spoon', 'cup', 'plate', 'glass', 'bowl', 'pot', 'pan', 'scissors', 'hammer', 'nail', 'rope', 'string', 'tape');

UPDATE words SET category = 'Language' WHERE category IS NULL AND word IN ('linguistics', 'syntax', 'semantics', 'phonology', 'morphology', 'dialect', 'bilingual', 'fluent', 'eloquent', 'articulate', 'allegory', 'metaphor', 'simile', 'irony', 'satire', 'narrative', 'protagonist', 'antagonist', 'hyperbole', 'foreshadowing', 'pidgin', 'creole', 'register', 'pragmatics', 'euphemism', 'dysphemism', 'onomatopoeia', 'polysemy', 'morpheme', 'intonation');

UPDATE words SET category = 'Nature' WHERE category IS NULL AND word IN ('sun', 'moon', 'star', 'sky', 'cloud', 'rain', 'snow', 'wind', 'river', 'lake', 'sea', 'mountain', 'forest', 'tree', 'flower', 'grass', 'animal', 'bird', 'dog', 'cat', 'weather', 'temperature', 'hot', 'cold', 'warm', 'cool', 'spring', 'summer', 'autumn', 'winter', 'storm', 'thunder', 'lightning', 'foggy', 'sunny', 'cloudy', 'deforestation', 'biodiversity', 'greenhouse gas', 'ozone', 'fossil fuel', 'carbon footprint', 'reforestation', 'erosion', 'conservation', 'emission', 'mitigation', 'sequestration', 'biodegradable', 'ecological');
UPDATE words SET category = 'Nature' WHERE category IS NULL AND word IN ('biomass', 'geothermal', 'photovoltaic', 'net zero', 'carbon neutral', 'biodiversity hotspot', 'breeze', 'cliff', 'dew', 'drought', 'earthquake', 'fog', 'frost', 'glacier', 'harvest', 'hurricane', 'landscape', 'meadow', 'pebble', 'tide', 'tornado', 'valley', 'volcano', 'waterfall', 'algae', 'blossom', 'branch', 'cactus', 'compost', 'crop', 'fertilizer', 'fern', 'irrigation', 'moss', 'orchard', 'petal', 'pollen', 'root', 'seed', 'stem', 'vine', 'weed');

UPDATE words SET category = 'People' WHERE category IS NULL AND word IN ('family', 'parent', 'father', 'mother', 'brother', 'sister', 'son', 'daughter', 'husband', 'wife', 'grandfather', 'grandmother', 'uncle', 'aunt', 'cousin', 'friend', 'neighbor', 'person', 'man', 'woman', 'child', 'baby', 'boy', 'girl');

UPDATE words SET category = 'Places' WHERE category IS NULL AND word IN ('here', 'there', 'north', 'south', 'east', 'west', 'left', 'right', 'up', 'down', 'front', 'behind', 'inside', 'outside', 'near', 'far', 'city', 'town', 'village', 'park', 'market', 'store', 'restaurant', 'hospital', 'church', 'museum', 'theater', 'cinema', 'office', 'factory', 'farm', 'beach', 'hotel', 'infrastructure', 'urbanization', 'architecture', 'facade', 'renovation', 'foundation', 'metropolitan', 'municipal', 'zoning', 'suburb', 'Arctic', 'atlas', 'bay', 'canal', 'canyon', 'cape', 'continent');
UPDATE words SET category = 'Places' WHERE category IS NULL AND word IN ('coordinates', 'coral reef', 'delta', 'desert', 'equator', 'estuary', 'fjord', 'gulf', 'hemisphere', 'highland', 'inlet', 'isthmus', 'jungle', 'latitude', 'lava', 'longitude', 'marsh', 'mesa', 'monsoon', 'moor', 'oasis', 'peninsula', 'plain', 'plateau', 'polar', 'prairie', 'reef', 'ridge', 'savanna', 'slope', 'summit', 'swamp', 'terrain', 'tundra', 'wetland');

UPDATE words SET category = 'Politics' WHERE category IS NULL AND word IN ('bilateral', 'multilateral', 'embargo', 'extradition', 'annexation', 'intervention', 'veto', 'ceasefire', 'deterrence', 'geopolitical');

UPDATE words SET category = 'Social' WHERE category IS NULL AND word IN ('globalization', 'migration', 'refugee', 'diplomacy', 'treaty', 'sanctions', 'sovereignty', 'humanitarian', 'indigenous', 'proliferation', 'geopolitics', 'oligarchy', 'totalitarian', 'propaganda', 'censorship', 'imperialism', 'nationalism', 'capitalism', 'bureaucracy', 'coalition', 'ethnicity', 'prejudice', 'discrimination', 'stereotype', 'integration', 'marginalized', 'inclusive', 'empowerment', 'solidarity', 'civic', 'activism', 'advocate', 'bias', 'charity', 'class', 'community', 'conflict', 'corrupt', 'crisis', 'culture', 'democracy', 'dignity', 'diversity', 'equality', 'exploitation', 'freedom', 'gender', 'homeless', 'human rights', 'immigrant');
UPDATE words SET category = 'Social' WHERE category IS NULL AND word IN ('inequality', 'justice', 'minority', 'nonprofit', 'oppression', 'poverty', 'privilege', 'protest', 'racism', 'reform', 'segregation', 'tolerance', 'volunteer');

UPDATE words SET category = 'Technology' WHERE category IS NULL AND word IN ('software', 'hardware', 'network', 'password', 'database', 'algorithm', 'device', 'application', 'update', 'connect', 'upload', 'download', 'install', 'digital', 'virtual', 'wireless', 'efficient', 'compatible', 'performance', 'exhibition', 'orchestra', 'sculpture', 'photography', 'literature', 'novel', 'poetry', 'musician', 'actress', 'director', 'audience', 'critic', 'entertain', 'inspire', 'creative', 'artistic', 'artificial intelligence', 'machine learning', 'automation', 'blockchain', 'cybersecurity', 'augmented reality', 'nanotechnology', 'innovation', 'disruptive', 'prototype', 'computer', 'phone', 'internet', 'email', 'message');
UPDATE words SET category = 'Technology' WHERE category IS NULL AND word IN ('website', 'video', 'photo', 'screen', 'battery', 'charge', 'search', 'click', 'type', 'save', 'neural network', 'deep learning', 'natural language processing', 'reinforcement learning', 'overfitting', 'bias-variance tradeoff', 'hyperparameter', 'gradient descent', 'epoch', 'inference', 'bandwidth', 'browser', 'cache', 'cloud computing', 'coding', 'debug', 'encryption', 'firewall', 'framework', 'interface', 'kernel', 'malware', 'protocol', 'server');

UPDATE words SET category = 'Thinking' WHERE category IS NULL AND word IN ('consciousness', 'perception', 'ideology', 'morality', 'abstraction', 'sovereignty', 'hegemony', 'rhetoric', 'paradox', 'nuance', 'cognitive', 'subconscious', 'resilience', 'empathy', 'intuition', 'compulsive', 'irrational', 'procrastinate', 'obsession', 'introspection', 'neuroplasticity', 'cognitive bias', 'heuristic', 'metacognition', 'working memory', 'confirmation bias', 'unconscious bias', 'placebo effect', 'dopamine', 'serotonin');

UPDATE words SET category = 'Time' WHERE category IS NULL AND word IN ('minute', 'hour', 'week', 'month', 'year', 'morning', 'afternoon', 'evening', 'night', 'today', 'yesterday', 'tomorrow', 'second', 'soon', 'later', 'already', 'still', 'yet', 'again', 'always', 'never', 'usually', 'sometimes', 'rarely', 'recently', 'immediately', 'gradually', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');

UPDATE words SET category = 'Transport' WHERE category IS NULL AND word IN ('car', 'bus', 'train', 'plane', 'ship', 'bike', 'motorcycle', 'road', 'street', 'bridge', 'station', 'airport', 'taxi', 'drive', 'ride', 'walk', 'run', 'fly', 'arrive', 'leave');

UPDATE words SET category = 'Travel' WHERE category IS NULL AND word IN ('hotel', 'reservation', 'passport', 'visa', 'luggage', 'destination', 'tourism', 'tourist', 'currency', 'culture', 'tradition', 'landmark', 'souvenir', 'guided tour', 'accommodation', 'explore', 'discover', 'navigate', 'picturesque', 'exotic', 'abroad', 'airline', 'backpack', 'cruise', 'excursion', 'guidebook', 'itinerary', 'terminal');

UPDATE words SET category = 'Work' WHERE category IS NULL AND word IN ('delegate', 'accountability', 'transparency', 'integrity', 'initiative', 'scalable', 'sustainable', 'optimize', 'facilitate', 'leverage', 'doctor', 'nurse', 'engineer', 'lawyer', 'police officer', 'firefighter', 'chef', 'pilot', 'farmer', 'artist', 'singer', 'driver', 'soldier', 'dentist', 'accountant', 'programmer', 'architect', 'scientist', 'journalist', 'athlete', 'agenda', 'appraisal', 'bonus', 'colleague', 'contractor', 'freelance', 'hierarchy', 'layoff', 'overtime', 'payroll', 'probation', 'promotion', 'recruitment', 'resignation', 'retire');

