--liquibase formatted sql

--changeset vocab:055-seed-words-batch47
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.category, v.example_sentence, v.example_translation
FROM (VALUES
-- Shopping
(N'cart', N'/kɑːrt/', N'xe đẩy / giỏ hàng', N'noun', N'BEGINNER', N'Shopping', N'Put the items in the cart.', N'Đặt các mặt hàng vào giỏ hàng.'),
(N'checkout', N'/ˈtʃekaʊt/', N'thanh toán / quầy tính tiền', N'noun', N'BEGINNER', N'Shopping', N'Go to the checkout to pay.', N'Đến quầy thanh toán để trả tiền.'),
(N'discount', N'/ˈdɪskaʊnt/', N'giảm giá / chiết khấu', N'noun', N'BEGINNER', N'Shopping', N'The store offers a ten percent discount.', N'Cửa hàng giảm giá mười phần trăm.'),
(N'bargain', N'/ˈbɑːrɡɪn/', N'hàng giá rẻ / mặc cả', N'noun', N'INTERMEDIATE', N'Shopping', N'I found a great bargain at the market.', N'Tôi tìm được món hàng giá rẻ tốt ở chợ.'),
(N'purchase', N'/ˈpɜːrtʃəs/', N'mua / sự mua hàng', N'verb', N'INTERMEDIATE', N'Shopping', N'Purchase the ticket online in advance.', N'Mua vé trực tuyến trước.'),
(N'browse', N'/braʊz/', N'duyệt / xem hàng', N'verb', N'BEGINNER', N'Shopping', N'I like to browse shops on weekends.', N'Tôi thích đi xem hàng vào cuối tuần.'),
(N'delivery', N'/dɪˈlɪvəri/', N'giao hàng', N'noun', N'BEGINNER', N'Shopping', N'The delivery arrived the next day.', N'Hàng giao đến vào ngày hôm sau.'),
(N'exchange', N'/ɪksˈtʃeɪndʒ/', N'trao đổi / đổi hàng', N'verb', N'INTERMEDIATE', N'Shopping', N'Can I exchange this for a different size?', N'Tôi có thể đổi cái này lấy cỡ khác không?'),
(N'refund', N'/ˈriːfʌnd/', N'hoàn tiền', N'noun', N'INTERMEDIATE', N'Shopping', N'She asked for a refund on the broken item.', N'Cô ấy yêu cầu hoàn tiền cho mặt hàng bị hỏng.'),
(N'cashier', N'/kæˈʃɪər/', N'thu ngân', N'noun', N'BEGINNER', N'Shopping', N'Pay at the cashier before leaving.', N'Trả tiền cho thu ngân trước khi rời đi.'),
(N'warranty', N'/ˈwɒrənti/', N'bảo hành', N'noun', N'INTERMEDIATE', N'Shopping', N'The product comes with a one-year warranty.', N'Sản phẩm có bảo hành một năm.'),
(N'wallet', N'/ˈwɒlɪt/', N'ví tiền', N'noun', N'BEGINNER', N'Shopping', N'I left my wallet at home.', N'Tôi để quên ví ở nhà.'),
(N'sale', N'/seɪl/', N'đợt giảm giá / bán hàng', N'noun', N'BEGINNER', N'Shopping', N'The sale starts tomorrow morning.', N'Đợt giảm giá bắt đầu sáng mai.'),
-- Entertainment
(N'concert', N'/ˈkɒnsərt/', N'buổi hòa nhạc / ca nhạc', N'noun', N'BEGINNER', N'Entertainment', N'We attended a live concert last night.', N'Chúng tôi đi xem hòa nhạc trực tiếp tối qua.'),
(N'festival', N'/ˈfestɪvəl/', N'lễ hội', N'noun', N'BEGINNER', N'Entertainment', N'The music festival attracts thousands of visitors.', N'Lễ hội âm nhạc thu hút hàng nghìn du khách.'),
(N'episode', N'/ˈepɪsoʊd/', N'tập phim / sự kiện', N'noun', N'BEGINNER', N'Entertainment', N'I watched the latest episode last night.', N'Tôi xem tập mới nhất tối qua.'),
(N'cast', N'/kɑːst/', N'diễn viên / dàn diễn viên', N'noun', N'INTERMEDIATE', N'Entertainment', N'The cast of the film is very talented.', N'Dàn diễn viên của bộ phim rất tài năng.'),
(N'trailer', N'/ˈtreɪlər/', N'đoạn giới thiệu phim', N'noun', N'BEGINNER', N'Entertainment', N'The trailer made the film look exciting.', N'Đoạn giới thiệu khiến bộ phim trông hấp dẫn.'),
(N'subtitle', N'/ˈsʌbtaɪtəl/', N'phụ đề', N'noun', N'BEGINNER', N'Entertainment', N'Turn on the subtitles to understand better.', N'Bật phụ đề để hiểu rõ hơn.'),
(N'podcast', N'/ˈpɒdkɑːst/', N'podcast / chương trình âm thanh', N'noun', N'INTERMEDIATE', N'Entertainment', N'I listen to a podcast on my commute.', N'Tôi nghe podcast khi đi làm.'),
(N'album', N'/ˈælbəm/', N'album nhạc / album ảnh', N'noun', N'BEGINNER', N'Entertainment', N'Her new album became a hit.', N'Album mới của cô ấy trở thành hit.'),
(N'lyrics', N'/ˈlɪrɪks/', N'lời bài hát', N'noun', N'BEGINNER', N'Entertainment', N'The lyrics of this song are very meaningful.', N'Lời bài hát này rất có ý nghĩa.'),
(N'animation', N'/ˌænɪˈmeɪʃən/', N'hoạt hình', N'noun', N'BEGINNER', N'Entertainment', N'Children love watching animation films.', N'Trẻ em thích xem phim hoạt hình.'),
(N'scene', N'/siːn/', N'cảnh / bối cảnh', N'noun', N'INTERMEDIATE', N'Entertainment', N'The opening scene of the film is powerful.', N'Cảnh mở đầu của bộ phim rất ấn tượng.'),
-- Descriptive adjectives
(N'modern', N'/ˈmɒdərn/', N'hiện đại', N'adjective', N'BEGINNER', N'Descriptive', N'The office has a modern design.', N'Văn phòng có thiết kế hiện đại.'),
(N'traditional', N'/trəˈdɪʃənəl/', N'truyền thống', N'adjective', N'BEGINNER', N'Descriptive', N'We wore traditional costumes at the festival.', N'Chúng tôi mặc trang phục truyền thống tại lễ hội.'),
(N'ordinary', N'/ˈɔːrdɪneri/', N'bình thường / thông thường', N'adjective', N'BEGINNER', N'Descriptive', N'It was just an ordinary day.', N'Đó chỉ là một ngày bình thường.'),
(N'serious', N'/ˈsɪəriəs/', N'nghiêm túc / nghiêm trọng', N'adjective', N'BEGINNER', N'Descriptive', N'He has a serious expression on his face.', N'Anh ấy có vẻ mặt nghiêm túc.'),
(N'comfortable', N'/ˈkʌmftəbəl/', N'thoải mái', N'adjective', N'BEGINNER', N'Descriptive', N'This sofa is very comfortable.', N'Cái ghế sofa này rất thoải mái.'),
(N'wonderful', N'/ˈwʌndərfəl/', N'tuyệt vời', N'adjective', N'BEGINNER', N'Descriptive', N'We had a wonderful time at the beach.', N'Chúng tôi có một khoảng thời gian tuyệt vời ở bãi biển.'),
(N'amazing', N'/əˈmeɪzɪŋ/', N'tuyệt vời / đáng kinh ngạc', N'adjective', N'BEGINNER', N'Descriptive', N'The view from the top is amazing.', N'Cảnh nhìn từ trên đỉnh thật tuyệt vời.'),
(N'exciting', N'/ɪkˈsaɪtɪŋ/', N'thú vị / hồi hộp', N'adjective', N'BEGINNER', N'Descriptive', N'The game was very exciting to watch.', N'Trận đấu rất thú vị khi xem.'),
(N'terrible', N'/ˈterɪbəl/', N'khủng khiếp / tệ hại', N'adjective', N'BEGINNER', N'Descriptive', N'The food at that restaurant was terrible.', N'Đồ ăn ở nhà hàng đó thật tệ.'),
(N'pleasant', N'/ˈplezənt/', N'dễ chịu / thú vị', N'adjective', N'BEGINNER', N'Descriptive', N'It was a pleasant evening with friends.', N'Đó là một buổi tối dễ chịu bên bạn bè.'),
(N'nervous', N'/ˈnɜːrvəs/', N'hồi hộp / lo lắng', N'adjective', N'BEGINNER', N'Descriptive', N'She felt nervous before the exam.', N'Cô ấy cảm thấy hồi hộp trước kỳ thi.'),
(N'recent', N'/ˈriːsənt/', N'gần đây / mới đây', N'adjective', N'BEGINNER', N'Descriptive', N'Have you seen his recent work?', N'Bạn có xem công việc gần đây của anh ấy chưa?'),
(N'useful', N'/ˈjuːsfəl/', N'hữu ích', N'adjective', N'BEGINNER', N'Descriptive', N'This tool is very useful in the kitchen.', N'Dụng cụ này rất hữu ích trong bếp.'),
(N'perfect', N'/ˈpɜːrfɪkt/', N'hoàn hảo', N'adjective', N'BEGINNER', N'Descriptive', N'Nobody is perfect.', N'Không ai là hoàn hảo.'),
(N'strange', N'/streɪndʒ/', N'kỳ lạ / xa lạ', N'adjective', N'BEGINNER', N'Descriptive', N'That is a strange sound.', N'Đó là một âm thanh kỳ lạ.'),
-- General nouns
(N'mistake', N'/mɪˈsteɪk/', N'lỗi lầm / sai lầm', N'noun', N'BEGINNER', N'General', N'Everyone makes mistakes sometimes.', N'Ai cũng mắc lỗi đôi khi.'),
(N'result', N'/rɪˈzʌlt/', N'kết quả', N'noun', N'BEGINNER', N'General', N'The result of the test will be out tomorrow.', N'Kết quả bài kiểm tra sẽ có vào ngày mai.'),
(N'reason', N'/ˈriːzən/', N'lý do', N'noun', N'BEGINNER', N'General', N'Give me a good reason to stay.', N'Cho tôi một lý do tốt để ở lại.'),
(N'condition', N'/kənˈdɪʃən/', N'điều kiện / tình trạng', N'noun', N'INTERMEDIATE', N'General', N'The road is in poor condition.', N'Con đường đang trong tình trạng xấu.'),
(N'demand', N'/dɪˈmɑːnd/', N'nhu cầu / yêu cầu', N'noun', N'INTERMEDIATE', N'General', N'The demand for skilled workers is high.', N'Nhu cầu về lao động có kỹ năng rất cao.'),
(N'topic', N'/ˈtɒpɪk/', N'chủ đề', N'noun', N'BEGINNER', N'General', N'What is the topic of today''s lesson?', N'Chủ đề của bài học hôm nay là gì?'),
(N'detail', N'/ˈdiːteɪl/', N'chi tiết', N'noun', N'BEGINNER', N'General', N'Pay attention to every detail.', N'Chú ý đến từng chi tiết.'),
(N'level', N'/ˈlevəl/', N'cấp độ / mức độ', N'noun', N'BEGINNER', N'General', N'Your English level is improving fast.', N'Trình độ tiếng Anh của bạn đang cải thiện nhanh.'),
(N'member', N'/ˈmembər/', N'thành viên', N'noun', N'BEGINNER', N'General', N'Every member of the team is important.', N'Mỗi thành viên trong nhóm đều quan trọng.'),
(N'method', N'/ˈmeθəd/', N'phương pháp', N'noun', N'INTERMEDIATE', N'General', N'This method is more effective.', N'Phương pháp này hiệu quả hơn.'),
(N'quality', N'/ˈkwɒlɪti/', N'chất lượng', N'noun', N'INTERMEDIATE', N'General', N'Always choose quality over quantity.', N'Luôn chọn chất lượng hơn số lượng.'),
(N'section', N'/ˈsekʃən/', N'phần / mục / khu vực', N'noun', N'INTERMEDIATE', N'General', N'Read the first section carefully.', N'Đọc phần đầu tiên cẩn thận.'),
(N'stage', N'/steɪdʒ/', N'giai đoạn / sân khấu', N'noun', N'INTERMEDIATE', N'General', N'We are in the final stage of the project.', N'Chúng tôi đang ở giai đoạn cuối của dự án.'),
(N'choice', N'/tʃɔɪs/', N'sự lựa chọn', N'noun', N'BEGINNER', N'General', N'Make the right choice for your future.', N'Hãy đưa ra lựa chọn đúng đắn cho tương lai.'),
(N'situation', N'/ˌsɪtʃuˈeɪʃən/', N'tình huống / hoàn cảnh', N'noun', N'INTERMEDIATE', N'General', N'Explain the situation to your manager.', N'Giải thích tình huống cho người quản lý.'),
(N'effect', N'/ɪˈfekt/', N'tác động / hiệu ứng', N'noun', N'INTERMEDIATE', N'General', N'Pollution has a bad effect on health.', N'Ô nhiễm có tác động xấu đến sức khỏe.'),
(N'amount', N'/əˈmaʊnt/', N'số lượng / khối lượng', N'noun', N'BEGINNER', N'General', N'A small amount of sugar is enough.', N'Một lượng nhỏ đường là đủ.'),
(N'type', N'/taɪp/', N'loại / kiểu', N'noun', N'BEGINNER', N'General', N'What type of music do you like?', N'Bạn thích loại nhạc nào?'),
(N'piece', N'/piːs/', N'mảnh / tác phẩm', N'noun', N'BEGINNER', N'General', N'Give me a piece of paper.', N'Cho tôi một tờ giấy.'),
(N'point', N'/pɔɪnt/', N'điểm / ý / mũi nhọn', N'noun', N'BEGINNER', N'General', N'Get to the point quickly.', N'Đi thẳng vào vấn đề nhanh lên.'),
(N'rule', N'/ruːl/', N'quy tắc / luật lệ', N'noun', N'BEGINNER', N'General', N'Follow the rules of the game.', N'Làm theo quy tắc của trò chơi.'),
-- Actions / Verbs
(N'allow', N'/əˈlaʊ/', N'cho phép', N'verb', N'BEGINNER', N'Actions', N'Allow me to explain.', N'Hãy để tôi giải thích.'),
(N'apply', N'/əˈplaɪ/', N'ứng tuyển / áp dụng', N'verb', N'INTERMEDIATE', N'Actions', N'Apply for the job before the deadline.', N'Nộp đơn xin việc trước thời hạn.'),
(N'attend', N'/əˈtend/', N'tham dự / tham gia', N'verb', N'BEGINNER', N'Actions', N'Attend the meeting on time.', N'Tham dự cuộc họp đúng giờ.'),
(N'consider', N'/kənˈsɪdər/', N'cân nhắc / xem xét', N'verb', N'INTERMEDIATE', N'Actions', N'Consider all options before deciding.', N'Cân nhắc tất cả các lựa chọn trước khi quyết định.'),
(N'contain', N'/kənˈteɪn/', N'chứa đựng / bao gồm', N'verb', N'INTERMEDIATE', N'Actions', N'This box contains fragile items.', N'Hộp này chứa các vật dễ vỡ.'),
(N'continue', N'/kənˈtɪnjuː/', N'tiếp tục', N'verb', N'BEGINNER', N'Actions', N'Continue reading until the end.', N'Tiếp tục đọc cho đến hết.'),
(N'create', N'/kriˈeɪt/', N'tạo ra / sáng tạo', N'verb', N'BEGINNER', N'Actions', N'Create something new every day.', N'Tạo ra điều gì đó mới mỗi ngày.'),
(N'describe', N'/dɪˈskraɪb/', N'mô tả', N'verb', N'BEGINNER', N'Actions', N'Describe what you see in the picture.', N'Mô tả những gì bạn thấy trong bức tranh.'),
(N'discover', N'/dɪˈskʌvər/', N'khám phá / phát hiện', N'verb', N'BEGINNER', N'Actions', N'Discover new places when you travel.', N'Khám phá những nơi mới khi bạn đi du lịch.'),
(N'expect', N'/ɪkˈspekt/', N'mong đợi / kỳ vọng', N'verb', N'INTERMEDIATE', N'Actions', N'I expect a reply by tomorrow.', N'Tôi mong nhận được phản hồi vào ngày mai.'),
(N'include', N'/ɪnˈkluːd/', N'bao gồm', N'verb', N'BEGINNER', N'Actions', N'The price includes breakfast.', N'Giá bao gồm bữa sáng.'),
(N'increase', N'/ɪnˈkriːs/', N'tăng lên / tăng cường', N'verb', N'INTERMEDIATE', N'Actions', N'Exercise helps increase your energy.', N'Tập thể dục giúp tăng cường năng lượng.'),
(N'introduce', N'/ˌɪntrəˈdjuːs/', N'giới thiệu', N'verb', N'BEGINNER', N'Actions', N'Let me introduce myself.', N'Hãy để tôi tự giới thiệu.'),
(N'involve', N'/ɪnˈvɒlv/', N'liên quan / bao gồm', N'verb', N'INTERMEDIATE', N'Actions', N'The project involves a lot of research.', N'Dự án liên quan đến nhiều nghiên cứu.'),
(N'prepare', N'/prɪˈpɛər/', N'chuẩn bị', N'verb', N'BEGINNER', N'Actions', N'Prepare for the interview in advance.', N'Chuẩn bị cho buổi phỏng vấn trước.'),
(N'prevent', N'/prɪˈvent/', N'ngăn chặn / phòng ngừa', N'verb', N'INTERMEDIATE', N'Actions', N'Wash your hands to prevent illness.', N'Rửa tay để phòng ngừa bệnh tật.'),
(N'protect', N'/prəˈtekt/', N'bảo vệ', N'verb', N'BEGINNER', N'Actions', N'Protect the environment for future generations.', N'Bảo vệ môi trường cho các thế hệ tương lai.'),
(N'provide', N'/prəˈvaɪd/', N'cung cấp', N'verb', N'INTERMEDIATE', N'Actions', N'The company provides free training.', N'Công ty cung cấp đào tạo miễn phí.'),
(N'reduce', N'/rɪˈdjuːs/', N'giảm / cắt giảm', N'verb', N'INTERMEDIATE', N'Actions', N'Reduce your sugar intake for better health.', N'Giảm lượng đường nạp vào để có sức khỏe tốt hơn.'),
(N'require', N'/rɪˈkwaɪər/', N'yêu cầu / đòi hỏi', N'verb', N'INTERMEDIATE', N'Actions', N'This job requires strong communication skills.', N'Công việc này đòi hỏi kỹ năng giao tiếp tốt.'),
(N'support', N'/səˈpɔːrt/', N'ủng hộ / hỗ trợ', N'verb', N'BEGINNER', N'Actions', N'Support your friends when they need help.', N'Ủng hộ bạn bè khi họ cần giúp đỡ.'),
(N'survive', N'/səˈvaɪv/', N'sống sót / vượt qua', N'verb', N'INTERMEDIATE', N'Actions', N'How do people survive in extreme cold?', N'Làm thế nào mọi người sống sót trong cái lạnh khắc nghiệt?'),
(N'achieve', N'/əˈtʃiːv/', N'đạt được / thành đạt', N'verb', N'INTERMEDIATE', N'Actions', N'Work hard to achieve your goals.', N'Làm việc chăm chỉ để đạt được mục tiêu.'),
(N'attract', N'/əˈtrækt/', N'thu hút', N'verb', N'INTERMEDIATE', N'Actions', N'Beautiful flowers attract bees.', N'Hoa đẹp thu hút ong.'),
(N'combine', N'/kəmˈbaɪn/', N'kết hợp', N'verb', N'INTERMEDIATE', N'Actions', N'Combine work and play for balance.', N'Kết hợp công việc và vui chơi để cân bằng.'),
(N'complete', N'/kəmˈpliːt/', N'hoàn thành', N'verb', N'BEGINNER', N'Actions', N'Complete the task before the deadline.', N'Hoàn thành nhiệm vụ trước thời hạn.'),
(N'connect', N'/kəˈnekt/', N'kết nối', N'verb', N'BEGINNER', N'Actions', N'Connect with people around the world.', N'Kết nối với mọi người trên khắp thế giới.'),
(N'escape', N'/ɪˈskeɪp/', N'thoát khỏi / trốn thoát', N'verb', N'INTERMEDIATE', N'Actions', N'He managed to escape from the burning building.', N'Anh ấy đã thoát khỏi tòa nhà đang cháy.'),
(N'hide', N'/haɪd/', N'ẩn nấp / giấu', N'verb', N'BEGINNER', N'Actions', N'Do not hide your feelings.', N'Đừng giấu cảm xúc của bạn.'),
(N'improve', N'/ɪmˈpruːv/', N'cải thiện / tiến bộ', N'verb', N'INTERMEDIATE', N'Actions', N'Practice daily to improve your skills.', N'Luyện tập hàng ngày để cải thiện kỹ năng.'),
(N'push', N'/pʊʃ/', N'đẩy / thúc đẩy', N'verb', N'BEGINNER', N'Actions', N'Push the door to open it.', N'Đẩy cửa để mở.'),
(N'pull', N'/pʊl/', N'kéo', N'verb', N'BEGINNER', N'Actions', N'Pull the rope as hard as you can.', N'Kéo sợi dây hết sức bạn có thể.'),
(N'reach', N'/riːtʃ/', N'với tới / đạt đến', N'verb', N'BEGINNER', N'Actions', N'Reach for the stars.', N'Vươn tới những vì sao.'),
(N'realize', N'/ˈriːəlaɪz/', N'nhận ra / thực hiện', N'verb', N'INTERMEDIATE', N'Actions', N'I realized my mistake too late.', N'Tôi nhận ra lỗi của mình quá muộn.'),
(N'remain', N'/rɪˈmeɪn/', N'ở lại / vẫn còn', N'verb', N'INTERMEDIATE', N'Actions', N'Please remain seated during the flight.', N'Vui lòng ngồi yên trong suốt chuyến bay.'),
(N'solve', N'/sɒlv/', N'giải quyết', N'verb', N'INTERMEDIATE', N'Actions', N'Solve the problem step by step.', N'Giải quyết vấn đề từng bước một.'),
(N'spread', N'/spred/', N'lan rộng / trải ra', N'verb', N'INTERMEDIATE', N'Actions', N'Good news spreads fast.', N'Tin tốt lan nhanh.'),
(N'succeed', N'/səkˈsiːd/', N'thành công', N'verb', N'INTERMEDIATE', N'Actions', N'Work hard and you will succeed.', N'Làm việc chăm chỉ và bạn sẽ thành công.'),
(N'throw', N'/θroʊ/', N'ném / quăng', N'verb', N'BEGINNER', N'Actions', N'Throw the ball to your teammate.', N'Ném bóng cho đồng đội của bạn.'),
-- Health
(N'stress', N'/stres/', N'căng thẳng', N'noun', N'BEGINNER', N'Health', N'Too much stress is bad for your health.', N'Quá nhiều căng thẳng có hại cho sức khỏe.'),
(N'wound', N'/wuːnd/', N'vết thương', N'noun', N'BEGINNER', N'Health', N'Clean the wound before bandaging it.', N'Làm sạch vết thương trước khi băng.'),
(N'dose', N'/doʊs/', N'liều lượng', N'noun', N'INTERMEDIATE', N'Health', N'Take one dose of the medicine twice a day.', N'Uống một liều thuốc hai lần mỗi ngày.'),
(N'mental', N'/ˈmentəl/', N'tinh thần / tâm lý', N'adjective', N'INTERMEDIATE', N'Health', N'Mental health is as important as physical health.', N'Sức khỏe tinh thần quan trọng không kém sức khỏe thể chất.'),
(N'cure', N'/kjʊər/', N'chữa trị / cách chữa', N'verb', N'INTERMEDIATE', N'Health', N'Scientists are working to cure the disease.', N'Các nhà khoa học đang nghiên cứu để chữa căn bệnh này.'),
-- Home / Daily life
(N'routine', N'/ruːˈtiːn/', N'thói quen hàng ngày / thường lệ', N'noun', N'BEGINNER', N'Home', N'Stick to a healthy morning routine.', N'Duy trì thói quen buổi sáng lành mạnh.'),
(N'meal', N'/miːl/', N'bữa ăn', N'noun', N'BEGINNER', N'Home', N'Eat three meals a day regularly.', N'Ăn ba bữa một ngày đều đặn.'),
(N'snack', N'/snæk/', N'đồ ăn nhẹ', N'noun', N'BEGINNER', N'Home', N'She had a snack between classes.', N'Cô ấy ăn nhẹ giữa các tiết học.'),
(N'grocery', N'/ˈɡroʊsəri/', N'thực phẩm / cửa hàng tạp hóa', N'noun', N'BEGINNER', N'Home', N'I need to buy some groceries after work.', N'Tôi cần mua thực phẩm sau giờ làm.'),
-- Travel
(N'flight', N'/flaɪt/', N'chuyến bay', N'noun', N'BEGINNER', N'Travel', N'Our flight departs at 8 AM.', N'Chuyến bay của chúng tôi khởi hành lúc 8 giờ sáng.'),
(N'ticket', N'/ˈtɪkɪt/', N'vé', N'noun', N'BEGINNER', N'Travel', N'Buy your ticket early to get a discount.', N'Mua vé sớm để được giảm giá.'),
(N'customs', N'/ˈkʌstəmz/', N'hải quan', N'noun', N'INTERMEDIATE', N'Travel', N'Declare all goods at customs.', N'Khai báo tất cả hàng hóa tại hải quan.'),
-- Work
(N'training', N'/ˈtreɪnɪŋ/', N'đào tạo / huấn luyện', N'noun', N'INTERMEDIATE', N'Work', N'New employees undergo training for two weeks.', N'Nhân viên mới trải qua đào tạo trong hai tuần.'),
(N'career', N'/kəˈrɪər/', N'sự nghiệp / nghề nghiệp', N'noun', N'INTERMEDIATE', N'Work', N'Choose a career that matches your passion.', N'Chọn sự nghiệp phù hợp với đam mê của bạn.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('cart','checkout','discount','bargain','purchase','browse','delivery','exchange','refund','cashier','warranty','wallet','sale','concert','festival','episode','cast','trailer','subtitle','podcast','album','lyrics','animation','scene','modern','traditional','ordinary','serious','comfortable','wonderful','amazing','exciting','terrible','pleasant','nervous','recent','useful','perfect','strange','mistake','result','reason','condition','demand','topic','detail','level','member','method','quality','section','stage','choice','situation','effect','amount','type','piece','point','rule','allow','apply','attend','consider','contain','continue','create','describe','discover','expect','include','increase','introduce','involve','prepare','prevent','protect','provide','reduce','require','support','survive','achieve','attract','combine','complete','connect','escape','hide','improve','push','pull','reach','realize','remain','solve','spread','succeed','throw','stress','wound','dose','mental','cure','routine','meal','snack','grocery','flight','ticket','customs','training','career');
