--liquibase formatted sql

--changeset vocab:057-seed-words-batch49
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.category, v.example_sentence, v.example_translation
FROM (VALUES
-- Animals (thêm)
(N'puppy', N'/ˈpʌpi/', N'chó con', N'noun', N'BEGINNER', N'Animals', N'The puppy is playing in the yard.', N'Chú chó con đang chơi trong sân.'),
(N'kitten', N'/ˈkɪtən/', N'mèo con', N'noun', N'BEGINNER', N'Animals', N'The kitten curled up on the sofa.', N'Chú mèo con cuộn tròn trên ghế sofa.'),
(N'chick', N'/tʃɪk/', N'gà con', N'noun', N'BEGINNER', N'Animals', N'The chick followed its mother closely.', N'Gà con đi theo mẹ sát nút.'),
(N'lamb', N'/læm/', N'cừu non', N'noun', N'BEGINNER', N'Animals', N'The lamb jumped happily in the field.', N'Con cừu non nhảy vui vẻ trên cánh đồng.'),
(N'cub', N'/kʌb/', N'gấu con / thú con', N'noun', N'BEGINNER', N'Animals', N'The bear cub stayed close to its mother.', N'Gấu con ở gần bên mẹ.'),
(N'pigeon', N'/ˈpɪdʒɪn/', N'chim bồ câu', N'noun', N'BEGINNER', N'Animals', N'Pigeons gather in the city square.', N'Chim bồ câu tập trung ở quảng trường thành phố.'),
(N'crow', N'/kroʊ/', N'con quạ', N'noun', N'BEGINNER', N'Animals', N'The crow is a very intelligent bird.', N'Con quạ là loài chim rất thông minh.'),
(N'swan', N'/swɒn/', N'con thiên nga', N'noun', N'BEGINNER', N'Animals', N'Swans glide gracefully on the lake.', N'Thiên nga lướt nhẹ nhàng trên mặt hồ.'),
(N'turtle', N'/ˈtɜːrtəl/', N'con rùa biển', N'noun', N'BEGINNER', N'Animals', N'Sea turtles swim thousands of miles.', N'Rùa biển bơi hàng nghìn dặm.'),
(N'hamster', N'/ˈhæmstər/', N'chuột hamster', N'noun', N'BEGINNER', N'Animals', N'My sister keeps a hamster as a pet.', N'Em gái tôi nuôi một con hamster làm thú cưng.'),
(N'peacock', N'/ˈpiːkɒk/', N'chim công', N'noun', N'BEGINNER', N'Animals', N'The peacock spread its beautiful tail feathers.', N'Con công xoè những chiếc lông đuôi đẹp.'),
(N'beetle', N'/ˈbiːtəl/', N'con bọ cánh cứng', N'noun', N'BEGINNER', N'Animals', N'A small beetle landed on the leaf.', N'Một con bọ cánh cứng nhỏ đậu trên lá.'),
(N'ant', N'/ænt/', N'con kiến', N'noun', N'BEGINNER', N'Animals', N'Ants work together in large colonies.', N'Kiến làm việc cùng nhau trong các đàn lớn.'),
(N'starfish', N'/ˈstɑːrfɪʃ/', N'con sao biển', N'noun', N'BEGINNER', N'Animals', N'A starfish has five arms.', N'Con sao biển có năm cánh.'),
-- Body (bổ sung)
(N'throat', N'/θroʊt/', N'cổ họng', N'noun', N'BEGINNER', N'Body', N'I have a sore throat this morning.', N'Tôi bị đau cổ họng sáng nay.'),
(N'tongue', N'/tʌŋ/', N'lưỡi', N'noun', N'BEGINNER', N'Body', N'The tongue helps us taste food.', N'Lưỡi giúp chúng ta nếm thức ăn.'),
(N'lip', N'/lɪp/', N'môi', N'noun', N'BEGINNER', N'Body', N'She put on lip balm before going out.', N'Cô ấy thoa son dưỡng môi trước khi ra ngoài.'),
(N'chin', N'/tʃɪn/', N'cằm', N'noun', N'BEGINNER', N'Body', N'He stroked his chin while thinking.', N'Anh ấy vuốt cằm khi đang suy nghĩ.'),
(N'cheek', N'/tʃiːk/', N'má', N'noun', N'BEGINNER', N'Body', N'The baby has chubby cheeks.', N'Em bé có đôi má bầu bĩnh.'),
(N'chest', N'/tʃest/', N'ngực', N'noun', N'BEGINNER', N'Body', N'He felt pain in his chest.', N'Anh ấy cảm thấy đau ở ngực.'),
(N'knee', N'/niː/', N'đầu gối', N'noun', N'BEGINNER', N'Body', N'She hurt her knee during the race.', N'Cô ấy bị đau đầu gối trong cuộc đua.'),
(N'toe', N'/toʊ/', N'ngón chân', N'noun', N'BEGINNER', N'Body', N'He stubbed his toe on the table.', N'Anh ấy bị vấp ngón chân vào bàn.'),
(N'sneeze', N'/sniːz/', N'hắt hơi', N'verb', N'BEGINNER', N'Body', N'Cover your mouth when you sneeze.', N'Che miệng khi bạn hắt hơi.'),
(N'cough', N'/kɒf/', N'ho', N'verb', N'BEGINNER', N'Health', N'He has been coughing all morning.', N'Anh ấy ho suốt cả buổi sáng.'),
(N'breathe', N'/briːð/', N'thở', N'verb', N'BEGINNER', N'Health', N'Breathe deeply to calm yourself.', N'Hít thở sâu để bình tĩnh lại.'),
(N'bleed', N'/bliːd/', N'chảy máu', N'verb', N'INTERMEDIATE', N'Health', N'The cut on his hand started to bleed.', N'Vết cắt trên tay anh ấy bắt đầu chảy máu.'),
(N'sprain', N'/spreɪn/', N'bong gân', N'verb', N'INTERMEDIATE', N'Health', N'She sprained her ankle playing tennis.', N'Cô ấy bị bong gân khi chơi tennis.'),
-- Clothing (bổ sung)
(N'tie', N'/taɪ/', N'cà vạt / buộc', N'noun', N'BEGINNER', N'Clothing', N'He wore a blue tie to the interview.', N'Anh ấy đeo cà vạt xanh trong buổi phỏng vấn.'),
(N'belt', N'/belt/', N'thắt lưng / dây nịt', N'noun', N'BEGINNER', N'Clothing', N'Fasten your belt before driving.', N'Thắt dây lưng trước khi lái xe.'),
(N'boots', N'/buːts/', N'ủng / giày cao cổ', N'noun', N'BEGINNER', N'Clothing', N'Wear boots when it rains.', N'Đi ủng khi trời mưa.'),
(N'sneakers', N'/ˈsniːkərz/', N'giày thể thao', N'noun', N'BEGINNER', N'Clothing', N'He bought a new pair of sneakers.', N'Anh ấy mua một đôi giày thể thao mới.'),
(N'hoodie', N'/ˈhʊdi/', N'áo hoodie / áo nỉ có mũ', N'noun', N'BEGINNER', N'Clothing', N'She wore a hoodie to the gym.', N'Cô ấy mặc áo hoodie đến phòng gym.'),
(N'jeans', N'/dʒiːnz/', N'quần jean', N'noun', N'BEGINNER', N'Clothing', N'Jeans are comfortable and stylish.', N'Quần jean thoải mái và thời trang.'),
(N'pocket', N'/ˈpɒkɪt/', N'túi áo / túi quần', N'noun', N'BEGINNER', N'Clothing', N'He kept his keys in his pocket.', N'Anh ấy để chìa khóa trong túi.'),
(N'wool', N'/wʊl/', N'len / vải len', N'noun', N'BEGINNER', N'Clothing', N'This sweater is made of wool.', N'Chiếc áo len này được làm từ len.'),
(N'cotton', N'/ˈkɒtən/', N'bông / vải cotton', N'noun', N'BEGINNER', N'Clothing', N'Cotton clothes are soft and breathable.', N'Quần áo cotton mềm mại và thoáng khí.'),
(N'silk', N'/sɪlk/', N'lụa / vải lụa', N'noun', N'INTERMEDIATE', N'Clothing', N'She wore a beautiful silk dress.', N'Cô ấy mặc một chiếc váy lụa đẹp.'),
-- Entertainment / Music
(N'guitar', N'/ɡɪˈtɑːr/', N'đàn guitar', N'noun', N'BEGINNER', N'Entertainment', N'He plays guitar every evening.', N'Anh ấy chơi guitar mỗi buổi tối.'),
(N'piano', N'/piˈænoʊ/', N'đàn piano', N'noun', N'BEGINNER', N'Entertainment', N'She has been learning piano since age five.', N'Cô ấy học đàn piano từ năm năm tuổi.'),
(N'violin', N'/ˌvaɪəˈlɪn/', N'đàn violin', N'noun', N'BEGINNER', N'Entertainment', N'The violin produces a beautiful sound.', N'Đàn violin tạo ra âm thanh tuyệt đẹp.'),
(N'drum', N'/drʌm/', N'trống', N'noun', N'BEGINNER', N'Entertainment', N'He plays the drum in the school band.', N'Anh ấy chơi trống trong ban nhạc trường.'),
(N'comedy', N'/ˈkɒmədi/', N'phim hài / thể loại hài', N'noun', N'BEGINNER', N'Entertainment', N'I enjoy watching comedy films.', N'Tôi thích xem phim hài.'),
(N'drama', N'/ˈdrɑːmə/', N'kịch / phim tâm lý xã hội', N'noun', N'BEGINNER', N'Entertainment', N'This drama series has amazing acting.', N'Bộ phim kịch tính này có diễn xuất tuyệt vời.'),
(N'horror', N'/ˈhɒrər/', N'kinh dị / nỗi kinh hoàng', N'noun', N'BEGINNER', N'Entertainment', N'I get scared watching horror films.', N'Tôi sợ khi xem phim kinh dị.'),
(N'romance', N'/ˈroʊmæns/', N'tình cảm / lãng mạn', N'noun', N'BEGINNER', N'Entertainment', N'She loves reading romance novels.', N'Cô ấy thích đọc tiểu thuyết tình cảm.'),
(N'thriller', N'/ˈθrɪlər/', N'phim gay cấn / hồi hộp', N'noun', N'INTERMEDIATE', N'Entertainment', N'The thriller kept me on the edge of my seat.', N'Bộ phim gay cấn khiến tôi hồi hộp đến phút chót.'),
(N'fiction', N'/ˈfɪkʃən/', N'văn học hư cấu / tiểu thuyết', N'noun', N'INTERMEDIATE', N'Entertainment', N'Science fiction imagines life in the future.', N'Khoa học viễn tưởng tưởng tượng về cuộc sống trong tương lai.'),
(N'biography', N'/baɪˈɒɡrəfi/', N'tiểu sử', N'noun', N'INTERMEDIATE', N'Entertainment', N'She read a biography of Einstein.', N'Cô ấy đọc tiểu sử của Einstein.'),
(N'hobby', N'/ˈhɒbi/', N'sở thích / thú vui', N'noun', N'BEGINNER', N'Entertainment', N'Reading is my favourite hobby.', N'Đọc sách là sở thích yêu thích của tôi.'),
-- Food (hương vị / kết cấu)
(N'salty', N'/ˈsɔːlti/', N'mặn', N'adjective', N'BEGINNER', N'Food', N'The soup is too salty for me.', N'Tô canh quá mặn đối với tôi.'),
(N'bland', N'/blænd/', N'nhạt / vô vị', N'adjective', N'INTERMEDIATE', N'Food', N'The food was bland and tasteless.', N'Món ăn nhạt nhẽo và vô vị.'),
(N'crispy', N'/ˈkrɪspi/', N'giòn', N'adjective', N'BEGINNER', N'Food', N'I love crispy fried chicken.', N'Tôi thích gà chiên giòn.'),
(N'juicy', N'/ˈdʒuːsi/', N'nhiều nước / mọng nước', N'adjective', N'BEGINNER', N'Food', N'The mango was sweet and juicy.', N'Quả xoài ngọt và mọng nước.'),
(N'tender', N'/ˈtendər/', N'mềm / thịt mềm', N'adjective', N'INTERMEDIATE', N'Food', N'The steak was cooked to tender perfection.', N'Miếng bít tết được nấu mềm hoàn hảo.'),
(N'dessert', N'/dɪˈzɜːrt/', N'tráng miệng', N'noun', N'BEGINNER', N'Food', N'We had ice cream for dessert.', N'Chúng tôi ăn kem tráng miệng.'),
(N'pour', N'/pɔːr/', N'rót / đổ', N'verb', N'BEGINNER', N'Food', N'Pour the juice into the glass.', N'Rót nước trái cây vào ly.'),
(N'stir', N'/stɜːr/', N'khuấy / đảo', N'verb', N'BEGINNER', N'Food', N'Stir the sauce until it is smooth.', N'Khuấy nước sốt cho đến khi mịn.'),
-- Nature / Environment
(N'sunrise', N'/ˈsʌnraɪz/', N'bình minh / lúc mặt trời mọc', N'noun', N'BEGINNER', N'Nature', N'We watched the sunrise from the hilltop.', N'Chúng tôi ngắm bình minh từ đỉnh đồi.'),
(N'sunset', N'/ˈsʌnset/', N'hoàng hôn / lúc mặt trời lặn', N'noun', N'BEGINNER', N'Nature', N'The sunset painted the sky orange.', N'Hoàng hôn nhuộm bầu trời màu cam.'),
(N'rainbow', N'/ˈreɪnboʊ/', N'cầu vồng', N'noun', N'BEGINNER', N'Nature', N'A rainbow appeared after the rain.', N'Cầu vồng xuất hiện sau cơn mưa.'),
(N'mud', N'/mʌd/', N'bùn đất', N'noun', N'BEGINNER', N'Nature', N'The children got mud all over their boots.', N'Bọn trẻ dính bùn khắp ủng.'),
(N'rock', N'/rɒk/', N'đá / tảng đá', N'noun', N'BEGINNER', N'Nature', N'He sat on a large flat rock.', N'Anh ấy ngồi trên một tảng đá phẳng lớn.'),
(N'shore', N'/ʃɔːr/', N'bờ biển / bờ sông', N'noun', N'BEGINNER', N'Nature', N'We walked along the rocky shore.', N'Chúng tôi đi dọc theo bờ đá.'),
(N'horizon', N'/həˈraɪzən/', N'đường chân trời', N'noun', N'INTERMEDIATE', N'Nature', N'The ship disappeared over the horizon.', N'Con tàu biến mất sau đường chân trời.'),
(N'stream', N'/striːm/', N'suối / dòng chảy nhỏ', N'noun', N'BEGINNER', N'Nature', N'A clear stream ran through the forest.', N'Một dòng suối trong vắt chảy qua khu rừng.'),
(N'cave', N'/keɪv/', N'hang động', N'noun', N'BEGINNER', N'Nature', N'Explorers found ancient paintings inside the cave.', N'Các nhà thám hiểm tìm thấy tranh cổ đại bên trong hang động.'),
(N'oxygen', N'/ˈɒksɪdʒən/', N'khí ôxy', N'noun', N'INTERMEDIATE', N'Nature', N'Plants produce oxygen through photosynthesis.', N'Thực vật tạo ra ôxy thông qua quá trình quang hợp.'),
-- Places (bổ sung)
(N'pharmacy', N'/ˈfɑːrməsi/', N'nhà thuốc / hiệu thuốc', N'noun', N'BEGINNER', N'Places', N'Buy the medicine at the pharmacy.', N'Mua thuốc tại nhà thuốc.'),
(N'supermarket', N'/ˈsuːpərmɑːrkɪt/', N'siêu thị', N'noun', N'BEGINNER', N'Places', N'I do my weekly shopping at the supermarket.', N'Tôi đi mua sắm hàng tuần tại siêu thị.'),
(N'mall', N'/mɔːl/', N'trung tâm thương mại', N'noun', N'BEGINNER', N'Places', N'The new mall has over two hundred shops.', N'Trung tâm thương mại mới có hơn hai trăm cửa hàng.'),
(N'capital', N'/ˈkæpɪtəl/', N'thủ đô', N'noun', N'BEGINNER', N'Places', N'Hanoi is the capital of Vietnam.', N'Hà Nội là thủ đô của Việt Nam.'),
(N'border', N'/ˈbɔːrdər/', N'biên giới', N'noun', N'INTERMEDIATE', N'Places', N'The two countries share a long border.', N'Hai nước có chung một đường biên giới dài.'),
(N'coast', N'/koʊst/', N'bờ biển / vùng duyên hải', N'noun', N'BEGINNER', N'Places', N'We drove along the coast for hours.', N'Chúng tôi lái xe dọc theo bờ biển nhiều giờ.'),
(N'alley', N'/ˈæli/', N'con ngõ / hẻm', N'noun', N'BEGINNER', N'Places', N'The cat ran into a narrow alley.', N'Con mèo chạy vào một con hẻm hẹp.'),
(N'avenue', N'/ˈævənjuː/', N'đại lộ / phố lớn', N'noun', N'INTERMEDIATE', N'Places', N'The parade went down the main avenue.', N'Đoàn diễu hành đi xuống đại lộ chính.'),
(N'highway', N'/ˈhaɪweɪ/', N'đường cao tốc', N'noun', N'BEGINNER', N'Places', N'Traffic on the highway is heavy today.', N'Giao thông trên đường cao tốc hôm nay rất đông.'),
-- Transport (bổ sung)
(N'traffic', N'/ˈtræfɪk/', N'giao thông / ùn tắc', N'noun', N'BEGINNER', N'Transport', N'There is heavy traffic in the city center.', N'Giao thông rất đông ở trung tâm thành phố.'),
(N'tunnel', N'/ˈtʌnəl/', N'đường hầm', N'noun', N'BEGINNER', N'Transport', N'The train passed through a long tunnel.', N'Đoàn tàu đi qua một đường hầm dài.'),
(N'lane', N'/leɪn/', N'làn đường', N'noun', N'INTERMEDIATE', N'Transport', N'Stay in your lane and drive carefully.', N'Đi trong làn đường của bạn và lái xe cẩn thận.'),
(N'fuel', N'/fjuːəl/', N'nhiên liệu / xăng dầu', N'noun', N'INTERMEDIATE', N'Transport', N'The car ran out of fuel on the highway.', N'Xe hết nhiên liệu trên đường cao tốc.'),
(N'brake', N'/breɪk/', N'phanh / thắng', N'noun', N'INTERMEDIATE', N'Transport', N'Press the brake to slow the car down.', N'Nhấn phanh để làm chậm xe.'),
(N'engine', N'/ˈendʒɪn/', N'động cơ / máy', N'noun', N'INTERMEDIATE', N'Transport', N'The engine made a strange noise.', N'Động cơ phát ra tiếng ồn lạ.'),
(N'harbor', N'/ˈhɑːrbər/', N'bến cảng / vũng tàu', N'noun', N'INTERMEDIATE', N'Transport', N'The fishing boats returned to the harbor.', N'Những chiếc thuyền đánh cá trở về bến cảng.'),
-- People / Relationships
(N'couple', N'/ˈkʌpəl/', N'cặp đôi / cặp vợ chồng', N'noun', N'BEGINNER', N'People', N'The couple got married last spring.', N'Cặp đôi kết hôn vào mùa xuân năm ngoái.'),
(N'sibling', N'/ˈsɪblɪŋ/', N'anh chị em ruột', N'noun', N'INTERMEDIATE', N'People', N'She has two siblings, a brother and a sister.', N'Cô ấy có hai anh chị em, một anh trai và một em gái.'),
(N'relative', N'/ˈrelətɪv/', N'họ hàng / người thân', N'noun', N'BEGINNER', N'People', N'All our relatives came to the celebration.', N'Tất cả họ hàng chúng tôi đến dự lễ.'),
(N'colleague', N'/ˈkɒliːɡ/', N'đồng nghiệp', N'noun', N'INTERMEDIATE', N'People', N'She gets along well with her colleagues.', N'Cô ấy hòa thuận tốt với các đồng nghiệp.'),
(N'staff', N'/stɑːf/', N'nhân viên / đội ngũ', N'noun', N'INTERMEDIATE', N'Work', N'The hotel staff was very helpful.', N'Nhân viên khách sạn rất nhiệt tình.'),
(N'rival', N'/ˈraɪvəl/', N'đối thủ / kình địch', N'noun', N'INTERMEDIATE', N'People', N'He beat his main rival in the final.', N'Anh ấy đánh bại đối thủ chính trong trận chung kết.'),
(N'opponent', N'/əˈpoʊnənt/', N'đối thủ / người phản đối', N'noun', N'INTERMEDIATE', N'People', N'Respect your opponent in competition.', N'Hãy tôn trọng đối thủ trong cuộc thi.'),
(N'ancestor', N'/ˈænsestər/', N'tổ tiên', N'noun', N'INTERMEDIATE', N'People', N'We honor our ancestors during the festival.', N'Chúng tôi tôn vinh tổ tiên trong dịp lễ hội.'),
-- Time (bổ sung)
(N'century', N'/ˈsentʃʊri/', N'thế kỷ', N'noun', N'INTERMEDIATE', N'Time', N'This building is two centuries old.', N'Tòa nhà này đã hai thế kỷ tuổi.'),
(N'decade', N'/ˈdekeɪd/', N'thập kỷ / mười năm', N'noun', N'INTERMEDIATE', N'Time', N'A lot has changed in the past decade.', N'Rất nhiều thứ đã thay đổi trong thập kỷ qua.'),
(N'era', N'/ˈɪərə/', N'thời đại / kỷ nguyên', N'noun', N'INTERMEDIATE', N'Time', N'We live in the digital era.', N'Chúng ta đang sống trong kỷ nguyên số.'),
(N'moment', N'/ˈmoʊmənt/', N'khoảnh khắc / thời điểm', N'noun', N'BEGINNER', N'Time', N'Enjoy every moment of your life.', N'Hãy tận hưởng từng khoảnh khắc của cuộc đời.'),
(N'period', N'/ˈpɪəriəd/', N'giai đoạn / thời kỳ', N'noun', N'INTERMEDIATE', N'Time', N'This was a difficult period in history.', N'Đây là giai đoạn khó khăn trong lịch sử.'),
(N'annual', N'/ˈænjuəl/', N'hàng năm / thường niên', N'adjective', N'INTERMEDIATE', N'Time', N'The annual report is ready for review.', N'Báo cáo thường niên đã sẵn sàng để xem xét.'),
(N'temporary', N'/ˈtempəreri/', N'tạm thời', N'adjective', N'INTERMEDIATE', N'Time', N'This is just a temporary solution.', N'Đây chỉ là một giải pháp tạm thời.'),
(N'permanent', N'/ˈpɜːrmənənt/', N'vĩnh viễn / lâu dài', N'adjective', N'INTERMEDIATE', N'Time', N'She got a permanent job at the company.', N'Cô ấy có được việc làm lâu dài tại công ty.'),
-- Work / Career (bổ sung)
(N'supervisor', N'/ˈsuːpərvaɪzər/', N'người giám sát / quản lý trực tiếp', N'noun', N'INTERMEDIATE', N'Work', N'Report any issues to your supervisor.', N'Báo cáo mọi vấn đề cho người giám sát của bạn.'),
(N'intern', N'/ˈɪntɜːrn/', N'thực tập sinh', N'noun', N'INTERMEDIATE', N'Work', N'He is working as an intern this summer.', N'Anh ấy đang làm thực tập sinh mùa hè này.'),
(N'resign', N'/rɪˈzaɪn/', N'từ chức / nghỉ việc', N'verb', N'INTERMEDIATE', N'Work', N'She decided to resign from her position.', N'Cô ấy quyết định từ chức.'),
(N'evaluate', N'/ɪˈvæljueɪt/', N'đánh giá / thẩm định', N'verb', N'INTERMEDIATE', N'Work', N'We evaluate employee performance each quarter.', N'Chúng tôi đánh giá hiệu suất nhân viên mỗi quý.'),
(N'promote', N'/prəˈmoʊt/', N'thăng chức / quảng bá', N'verb', N'INTERMEDIATE', N'Work', N'She was promoted to senior manager.', N'Cô ấy được thăng chức lên quản lý cấp cao.'),
-- Actions (bổ sung)
(N'apologize', N'/əˈpɒlədʒaɪz/', N'xin lỗi', N'verb', N'BEGINNER', N'Actions', N'Always apologize when you make a mistake.', N'Hãy luôn xin lỗi khi bạn mắc lỗi.'),
(N'forgive', N'/fərˈɡɪv/', N'tha thứ', N'verb', N'INTERMEDIATE', N'Actions', N'It is hard but important to forgive others.', N'Tha thứ cho người khác khó nhưng quan trọng.'),
(N'greet', N'/ɡriːt/', N'chào hỏi / đón tiếp', N'verb', N'BEGINNER', N'Actions', N'He greeted every guest at the door.', N'Anh ấy chào đón từng vị khách tại cửa.'),
(N'complain', N'/kəmˈpleɪn/', N'phàn nàn / than thở', N'verb', N'INTERMEDIATE', N'Actions', N'She complained about the slow service.', N'Cô ấy phàn nàn về dịch vụ chậm.'),
(N'argue', N'/ˈɑːrɡjuː/', N'tranh luận / cãi nhau', N'verb', N'INTERMEDIATE', N'Actions', N'They often argue but always make up quickly.', N'Họ thường cãi nhau nhưng luôn làm lành nhanh.'),
(N'praise', N'/preɪz/', N'khen ngợi / ca ngợi', N'verb', N'INTERMEDIATE', N'Actions', N'The teacher praised the student''s hard work.', N'Giáo viên khen ngợi sự nỗ lực của học sinh.'),
(N'promise', N'/ˈprɒmɪs/', N'hứa / lời hứa', N'verb', N'BEGINNER', N'Actions', N'Promise me you will be careful.', N'Hứa với tôi là bạn sẽ cẩn thận.'),
(N'refuse', N'/rɪˈfjuːz/', N'từ chối', N'verb', N'INTERMEDIATE', N'Actions', N'He refused to accept the unfair offer.', N'Anh ấy từ chối chấp nhận đề nghị không công bằng.'),
(N'challenge', N'/ˈtʃælɪndʒ/', N'thách thức', N'verb', N'INTERMEDIATE', N'Actions', N'Challenge yourself to learn something new daily.', N'Thách thức bản thân học điều gì đó mới mỗi ngày.'),
(N'measure', N'/ˈmeʒər/', N'đo / đo lường', N'verb', N'BEGINNER', N'Actions', N'Measure the room before buying furniture.', N'Đo phòng trước khi mua nội thất.'),
(N'replace', N'/rɪˈpleɪs/', N'thay thế', N'verb', N'INTERMEDIATE', N'Actions', N'Replace old batteries with new ones.', N'Thay pin cũ bằng pin mới.'),
(N'select', N'/sɪˈlekt/', N'lựa chọn / chọn lọc', N'verb', N'INTERMEDIATE', N'Actions', N'Select the best answer from the list.', N'Chọn câu trả lời tốt nhất trong danh sách.'),
(N'upload', N'/ˈʌploʊd/', N'tải lên', N'verb', N'BEGINNER', N'Technology', N'Upload the photo to the website.', N'Tải ảnh lên trang web.'),
(N'download', N'/ˈdaʊnloʊd/', N'tải xuống', N'verb', N'BEGINNER', N'Technology', N'Download the app for free from the store.', N'Tải ứng dụng miễn phí từ cửa hàng.'),
-- Descriptive (bổ sung)
(N'ancient', N'/ˈeɪnʃənt/', N'cổ đại / xa xưa', N'adjective', N'INTERMEDIATE', N'Descriptive', N'The ancient temple is over a thousand years old.', N'Ngôi đền cổ đã hơn một nghìn năm tuổi.'),
(N'modern', N'/ˈmɒdərn/', N'hiện đại', N'adjective', N'BEGINNER', N'Descriptive', N'The city has a very modern skyline.', N'Thành phố có đường chân trời rất hiện đại.'),
(N'global', N'/ˈɡloʊbəl/', N'toàn cầu', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Climate change is a global problem.', N'Biến đổi khí hậu là vấn đề toàn cầu.'),
(N'national', N'/ˈnæʃənəl/', N'quốc gia / toàn quốc', N'adjective', N'INTERMEDIATE', N'Descriptive', N'It is a national holiday tomorrow.', N'Ngày mai là ngày lễ quốc gia.'),
(N'physical', N'/ˈfɪzɪkəl/', N'thể chất / vật lý', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Physical exercise keeps you fit.', N'Tập thể dục thể chất giúp bạn khỏe mạnh.'),
(N'digital', N'/ˈdɪdʒɪtəl/', N'kỹ thuật số', N'adjective', N'BEGINNER', N'Technology', N'We live in a digital world now.', N'Chúng ta đang sống trong một thế giới kỹ thuật số.'),
(N'original', N'/əˈrɪdʒɪnəl/', N'nguyên bản / độc đáo', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Keep the original copy of the document.', N'Giữ bản gốc của tài liệu.'),
(N'previous', N'/ˈpriːviəs/', N'trước đó / trước đây', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Compare this with the previous version.', N'So sánh cái này với phiên bản trước.'),
(N'current', N'/ˈkɜːrənt/', N'hiện tại / hiện nay', N'adjective', N'BEGINNER', N'Descriptive', N'What is your current job?', N'Công việc hiện tại của bạn là gì?'),
(N'entire', N'/ɪnˈtaɪər/', N'toàn bộ / cả', N'adjective', N'INTERMEDIATE', N'Descriptive', N'She read the entire book in one day.', N'Cô ấy đọc cả quyển sách trong một ngày.'),
(N'specific', N'/spəˈsɪfɪk/', N'cụ thể / đặc biệt', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Give me a specific example.', N'Hãy cho tôi một ví dụ cụ thể.'),
(N'particular', N'/pəˈtɪkjʊlər/', N'đặc biệt / cụ thể', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Is there any particular reason for this?', N'Có lý do cụ thể nào cho điều này không?'),
-- General (bổ sung)
(N'system', N'/ˈsɪstəm/', N'hệ thống', N'noun', N'BEGINNER', N'General', N'The education system needs reform.', N'Hệ thống giáo dục cần cải cách.'),
(N'process', N'/ˈprɒses/', N'quá trình / quy trình', N'noun', N'INTERMEDIATE', N'General', N'The hiring process takes about two weeks.', N'Quy trình tuyển dụng mất khoảng hai tuần.'),
(N'issue', N'/ˈɪʃuː/', N'vấn đề / số báo', N'noun', N'INTERMEDIATE', N'General', N'We need to address this issue quickly.', N'Chúng ta cần giải quyết vấn đề này nhanh chóng.'),
(N'matter', N'/ˈmætər/', N'vấn đề / quan trọng', N'noun', N'BEGINNER', N'General', N'It is a matter of time.', N'Đó chỉ là vấn đề thời gian.'),
(N'factor', N'/ˈfæktər/', N'yếu tố', N'noun', N'INTERMEDIATE', N'General', N'Price is a key factor in this decision.', N'Giá cả là yếu tố quan trọng trong quyết định này.'),
(N'standard', N'/ˈstændərd/', N'tiêu chuẩn', N'noun', N'INTERMEDIATE', N'General', N'Set high standards for your work.', N'Đặt tiêu chuẩn cao cho công việc của bạn.'),
(N'feature', N'/ˈfiːtʃər/', N'tính năng / đặc điểm', N'noun', N'INTERMEDIATE', N'General', N'This phone has many useful features.', N'Chiếc điện thoại này có nhiều tính năng hữu ích.'),
(N'position', N'/pəˈzɪʃən/', N'vị trí / chức vụ', N'noun', N'INTERMEDIATE', N'General', N'Apply for the open position online.', N'Nộp đơn ứng tuyển vị trí còn trống trực tuyến.'),
(N'structure', N'/ˈstrʌktʃər/', N'cấu trúc / kết cấu', N'noun', N'INTERMEDIATE', N'General', N'The sentence structure is easy to understand.', N'Cấu trúc câu dễ hiểu.'),
(N'network', N'/ˈnetwɜːrk/', N'mạng lưới', N'noun', N'INTERMEDIATE', N'General', N'Build a strong professional network.', N'Xây dựng mạng lưới chuyên nghiệp vững chắc.'),
(N'pattern', N'/ˈpætərn/', N'mẫu / quy luật', N'noun', N'INTERMEDIATE', N'General', N'I noticed a pattern in her behaviour.', N'Tôi nhận thấy một quy luật trong hành vi của cô ấy.'),
(N'resource', N'/ˈriːsɔːrs/', N'tài nguyên / nguồn lực', N'noun', N'INTERMEDIATE', N'General', N'Use available resources wisely.', N'Sử dụng các nguồn lực sẵn có một cách khôn ngoan.'),
(N'category', N'/ˈkætəɡəri/', N'danh mục / loại', N'noun', N'INTERMEDIATE', N'General', N'Which category does this word belong to?', N'Từ này thuộc danh mục nào?'),
(N'version', N'/ˈvɜːrʒən/', N'phiên bản', N'noun', N'BEGINNER', N'General', N'Download the latest version of the app.', N'Tải xuống phiên bản mới nhất của ứng dụng.'),
(N'content', N'/ˈkɒntent/', N'nội dung', N'noun', N'INTERMEDIATE', N'General', N'The content of the course is very useful.', N'Nội dung khóa học rất hữu ích.'),
(N'purpose', N'/ˈpɜːrpəs/', N'mục đích', N'noun', N'INTERMEDIATE', N'General', N'What is the purpose of this meeting?', N'Mục đích của cuộc họp này là gì?'),
(N'message', N'/ˈmesɪdʒ/', N'tin nhắn / thông điệp', N'noun', N'BEGINNER', N'General', N'Send me a message when you arrive.', N'Nhắn tin cho tôi khi bạn đến nơi.'),
(N'report', N'/ˈrɪpɔːrt/', N'báo cáo', N'noun', N'INTERMEDIATE', N'General', N'Submit the report by Friday.', N'Nộp báo cáo trước thứ Sáu.'),
(N'interview', N'/ˈɪntərvjuː/', N'phỏng vấn', N'noun', N'BEGINNER', N'Work', N'Prepare well for your job interview.', N'Chuẩn bị kỹ cho buổi phỏng vấn xin việc.'),
(N'presentation', N'/ˌprezənˈteɪʃən/', N'bài thuyết trình', N'noun', N'INTERMEDIATE', N'Work', N'She gave an impressive presentation.', N'Cô ấy có bài thuyết trình ấn tượng.'),
-- Health (bổ sung)
(N'pill', N'/pɪl/', N'viên thuốc', N'noun', N'BEGINNER', N'Health', N'Take one pill after every meal.', N'Uống một viên thuốc sau mỗi bữa ăn.'),
(N'ache', N'/eɪk/', N'đau âm ỉ / cơn đau', N'noun', N'BEGINNER', N'Health', N'I have an ache in my lower back.', N'Tôi bị đau âm ỉ ở lưng dưới.'),
(N'sore', N'/sɔːr/', N'đau / bị tổn thương', N'adjective', N'BEGINNER', N'Health', N'My legs are sore after the long run.', N'Chân tôi đau sau buổi chạy dài.'),
(N'relax', N'/rɪˈlæks/', N'thư giãn / nghỉ ngơi', N'verb', N'BEGINNER', N'Health', N'Relax and take a deep breath.', N'Thư giãn và hít thở sâu.'),
(N'checkup', N'/ˈtʃekʌp/', N'kiểm tra sức khỏe', N'noun', N'INTERMEDIATE', N'Health', N'Go for a regular health checkup.', N'Đi khám sức khỏe định kỳ.'),
(N'weight', N'/weɪt/', N'cân nặng / trọng lượng', N'noun', N'BEGINNER', N'Health', N'Maintain a healthy weight through exercise.', N'Duy trì cân nặng lành mạnh qua tập thể dục.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('puppy','kitten','chick','lamb','cub','pigeon','crow','swan','turtle','hamster','peacock','beetle','ant','starfish','throat','tongue','lip','chin','cheek','chest','knee','toe','sneeze','cough','breathe','bleed','sprain','tie','belt','boots','sneakers','hoodie','jeans','pocket','wool','cotton','silk','guitar','piano','violin','drum','comedy','drama','horror','romance','thriller','fiction','biography','hobby','salty','bland','crispy','juicy','tender','dessert','pour','stir','sunrise','sunset','rainbow','mud','rock','shore','horizon','stream','cave','oxygen','pharmacy','supermarket','mall','capital','border','coast','alley','avenue','highway','traffic','tunnel','lane','fuel','brake','engine','harbor','couple','sibling','relative','colleague','staff','rival','opponent','ancestor','century','decade','era','moment','period','annual','temporary','permanent','supervisor','intern','resign','evaluate','promote','apologize','forgive','greet','complain','argue','praise','promise','refuse','challenge','measure','replace','select','upload','download','ancient','global','national','physical','digital','original','previous','current','entire','specific','particular','system','process','issue','matter','factor','standard','feature','position','structure','network','pattern','resource','category','version','content','purpose','message','report','interview','presentation','pill','ache','sore','relax','checkup','weight');
