--liquibase formatted sql

--changeset vocab:058-seed-words-batch50
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.category, v.example_sentence, v.example_translation
FROM (VALUES
-- Animals (chi tiết hơn)
(N'nest', N'/nest/', N'tổ chim / tổ', N'noun', N'BEGINNER', N'Animals', N'The bird built a nest in the tree.', N'Con chim xây tổ trên cây.'),
(N'feather', N'/ˈfeðər/', N'lông chim / lông vũ', N'noun', N'BEGINNER', N'Animals', N'The peacock has beautiful coloured feathers.', N'Con công có những chiếc lông màu sắc đẹp.'),
(N'fur', N'/fɜːr/', N'lông thú / bộ lông mịn', N'noun', N'BEGINNER', N'Animals', N'The cat''s fur is very soft.', N'Bộ lông của con mèo rất mềm.'),
(N'claw', N'/klɔː/', N'móng vuốt', N'noun', N'BEGINNER', N'Animals', N'The eagle gripped the branch with its claws.', N'Con đại bàng bám vào cành bằng móng vuốt.'),
(N'beak', N'/biːk/', N'mỏ chim', N'noun', N'BEGINNER', N'Animals', N'The parrot cracked the nut with its beak.', N'Con vẹt dùng mỏ bẻ vỡ hạt.'),
(N'wing', N'/wɪŋ/', N'cánh', N'noun', N'BEGINNER', N'Animals', N'The bird spread its wings and flew away.', N'Con chim xòe cánh và bay đi.'),
(N'chirp', N'/tʃɜːrp/', N'tiếng chim hót / kêu chíp chíp', N'verb', N'BEGINNER', N'Animals', N'Birds chirp loudly in the morning.', N'Chim hót rộn ràng vào buổi sáng.'),
(N'roar', N'/rɔːr/', N'gầm rú / tiếng gầm', N'verb', N'BEGINNER', N'Animals', N'The lion roared across the savanna.', N'Sư tử gầm vang khắp đồng cỏ.'),
(N'hibernate', N'/ˈhaɪbərneɪt/', N'ngủ đông', N'verb', N'INTERMEDIATE', N'Animals', N'Bears hibernate throughout the winter.', N'Gấu ngủ đông suốt mùa đông.'),
(N'migrate', N'/ˈmaɪɡreɪt/', N'di cư', N'verb', N'INTERMEDIATE', N'Animals', N'Swallows migrate south every autumn.', N'Chim én di cư về phía nam mỗi mùa thu.'),
(N'prey', N'/preɪ/', N'con mồi', N'noun', N'INTERMEDIATE', N'Animals', N'The hawk spotted its prey from above.', N'Con diều hâu nhìn thấy con mồi từ trên cao.'),
(N'predator', N'/ˈpredətər/', N'thú săn mồi / kẻ săn mồi', N'noun', N'INTERMEDIATE', N'Animals', N'The deer ran away from the predator.', N'Con hươu chạy trốn khỏi kẻ săn mồi.'),
-- Body (bổ sung)
(N'bone', N'/boʊn/', N'xương', N'noun', N'BEGINNER', N'Body', N'He broke a bone in his left arm.', N'Anh ấy gãy xương ở cánh tay trái.'),
(N'joint', N'/dʒɔɪnt/', N'khớp / khớp nối', N'noun', N'BEGINNER', N'Body', N'My knee joint hurts after running.', N'Khớp gối của tôi đau sau khi chạy.'),
(N'nerve', N'/nɜːrv/', N'dây thần kinh / bình tĩnh', N'noun', N'INTERMEDIATE', N'Body', N'The dentist hit a nerve by accident.', N'Nha sĩ vô tình chạm vào dây thần kinh.'),
(N'vein', N'/veɪn/', N'tĩnh mạch / gân lá', N'noun', N'INTERMEDIATE', N'Body', N'The nurse found a vein for the injection.', N'Y tá tìm tĩnh mạch để tiêm.'),
(N'appetite', N'/ˈæpɪtaɪt/', N'cảm giác thèm ăn / khẩu vị', N'noun', N'INTERMEDIATE', N'Health', N'Exercise increases your appetite.', N'Tập thể dục làm tăng cảm giác thèm ăn.'),
(N'stretch', N'/stretʃ/', N'giãn cơ / duỗi người', N'verb', N'BEGINNER', N'Health', N'Stretch before and after every workout.', N'Giãn cơ trước và sau mỗi buổi tập.'),
(N'pregnant', N'/ˈpreɡnənt/', N'mang thai / có thai', N'adjective', N'INTERMEDIATE', N'Health', N'She is six months pregnant.', N'Cô ấy đang mang thai sáu tháng.'),
(N'massage', N'/məˈsɑːʒ/', N'xoa bóp / massage', N'noun', N'BEGINNER', N'Health', N'A good massage helps relieve stress.', N'Massage tốt giúp giảm căng thẳng.'),
-- Technology (bổ sung)
(N'keyboard', N'/ˈkiːbɔːrd/', N'bàn phím', N'noun', N'BEGINNER', N'Technology', N'Clean your keyboard regularly.', N'Vệ sinh bàn phím thường xuyên.'),
(N'monitor', N'/ˈmɒnɪtər/', N'màn hình máy tính', N'noun', N'BEGINNER', N'Technology', N'The monitor is too bright in a dark room.', N'Màn hình quá sáng trong phòng tối.'),
(N'printer', N'/ˈprɪntər/', N'máy in', N'noun', N'BEGINNER', N'Technology', N'The printer ran out of ink.', N'Máy in hết mực.'),
(N'folder', N'/ˈfoʊldər/', N'thư mục', N'noun', N'BEGINNER', N'Technology', N'Save the file in the correct folder.', N'Lưu tệp vào thư mục đúng.'),
(N'file', N'/faɪl/', N'tập tin / hồ sơ', N'noun', N'BEGINNER', N'Technology', N'Attach the file before sending the email.', N'Đính kèm tệp trước khi gửi email.'),
(N'wifi', N'/ˈwaɪfaɪ/', N'wifi / mạng không dây', N'noun', N'BEGINNER', N'Technology', N'Connect to the wifi to access the internet.', N'Kết nối wifi để truy cập internet.'),
(N'bluetooth', N'/ˈbluːtuːθ/', N'bluetooth / kết nối không dây', N'noun', N'BEGINNER', N'Technology', N'Turn on bluetooth to pair your headphones.', N'Bật bluetooth để ghép nối tai nghe.'),
(N'signal', N'/ˈsɪɡnəl/', N'tín hiệu', N'noun', N'BEGINNER', N'Technology', N'The phone signal is very weak here.', N'Tín hiệu điện thoại rất yếu ở đây.'),
(N'crash', N'/kræʃ/', N'sập / treo máy / tai nạn', N'verb', N'INTERMEDIATE', N'Technology', N'My computer crashed while I was working.', N'Máy tính của tôi bị treo khi tôi đang làm việc.'),
(N'bug', N'/bʌɡ/', N'lỗi phần mềm', N'noun', N'BEGINNER', N'Technology', N'The developer fixed the bug overnight.', N'Nhà phát triển sửa lỗi trong đêm.'),
(N'glitch', N'/ɡlɪtʃ/', N'trục trặc kỹ thuật', N'noun', N'INTERMEDIATE', N'Technology', N'There was a glitch in the system.', N'Có một trục trặc trong hệ thống.'),
(N'inbox', N'/ˈɪnbɒks/', N'hộp thư đến', N'noun', N'BEGINNER', N'Technology', N'Check your inbox for new messages.', N'Kiểm tra hộp thư đến để xem tin nhắn mới.'),
(N'spam', N'/spæm/', N'thư rác / spam', N'noun', N'BEGINNER', N'Technology', N'Mark suspicious emails as spam.', N'Đánh dấu các email đáng ngờ là thư rác.'),
(N'attachment', N'/əˈtætʃmənt/', N'tệp đính kèm', N'noun', N'INTERMEDIATE', N'Technology', N'The email has a large attachment.', N'Email có tệp đính kèm dung lượng lớn.'),
(N'account', N'/əˈkaʊnt/', N'tài khoản', N'noun', N'BEGINNER', N'Technology', N'Create an account to use the service.', N'Tạo tài khoản để sử dụng dịch vụ.'),
(N'profile', N'/ˈproʊfaɪl/', N'hồ sơ / trang cá nhân', N'noun', N'BEGINNER', N'Technology', N'Update your profile with a recent photo.', N'Cập nhật hồ sơ với ảnh gần đây.'),
-- Sports (bổ sung)
(N'sprint', N'/sprɪnt/', N'chạy nước rút', N'verb', N'INTERMEDIATE', N'General', N'She sprinted to the finish line.', N'Cô ấy chạy nước rút về đích.'),
(N'jog', N'/dʒɒɡ/', N'chạy bộ nhẹ nhàng', N'verb', N'BEGINNER', N'Health', N'He jogs for thirty minutes every morning.', N'Anh ấy chạy bộ ba mươi phút mỗi sáng.'),
(N'foul', N'/faʊl/', N'lỗi / phạm lỗi', N'noun', N'INTERMEDIATE', N'General', N'The referee called a foul on the defender.', N'Trọng tài phạt lỗi cầu thủ phòng thủ.'),
(N'equipment', N'/ɪˈkwɪpmənt/', N'thiết bị / dụng cụ', N'noun', N'BEGINNER', N'General', N'Make sure all equipment is working before the game.', N'Đảm bảo tất cả thiết bị hoạt động trước trận đấu.'),
(N'gear', N'/ɡɪər/', N'đồ nghề / thiết bị', N'noun', N'BEGINNER', N'General', N'Pack your camping gear the night before.', N'Đóng gói đồ cắm trại vào đêm trước.'),
(N'teammate', N'/ˈtiːmmeɪt/', N'đồng đội', N'noun', N'BEGINNER', N'People', N'Pass the ball to your teammate.', N'Chuyền bóng cho đồng đội của bạn.'),
(N'stadium', N'/ˈsteɪdiəm/', N'sân vận động', N'noun', N'BEGINNER', N'Places', N'The stadium was full of cheering fans.', N'Sân vận động đầy những người hâm mộ cổ vũ.'),
(N'medal', N'/ˈmedəl/', N'huy chương', N'noun', N'BEGINNER', N'General', N'She won a gold medal at the Olympics.', N'Cô ấy giành huy chương vàng tại Olympics.'),
-- Food (bổ sung)
(N'peel', N'/piːl/', N'gọt vỏ / lột vỏ', N'verb', N'BEGINNER', N'Food', N'Peel the apple before eating it.', N'Gọt vỏ táo trước khi ăn.'),
(N'slice', N'/slaɪs/', N'cắt lát / miếng cắt', N'verb', N'BEGINNER', N'Food', N'Slice the bread into thin pieces.', N'Cắt bánh mì thành những lát mỏng.'),
(N'appetizer', N'/ˈæpɪtaɪzər/', N'món khai vị', N'noun', N'INTERMEDIATE', N'Food', N'We ordered soup as an appetizer.', N'Chúng tôi gọi súp làm món khai vị.'),
(N'vegan', N'/ˈviːɡən/', N'người ăn thuần chay / thuần chay', N'noun', N'INTERMEDIATE', N'Food', N'She has been vegan for three years.', N'Cô ấy ăn thuần chay được ba năm.'),
(N'buffet', N'/ˈbʌfeɪ/', N'tiệc tự chọn / buffet', N'noun', N'BEGINNER', N'Food', N'The hotel offers a breakfast buffet.', N'Khách sạn cung cấp buffet bữa sáng.'),
(N'tray', N'/treɪ/', N'khay đựng đồ ăn', N'noun', N'BEGINNER', N'Food', N'Carry the tray carefully to avoid spilling.', N'Mang khay cẩn thận để tránh đổ.'),
(N'napkin', N'/ˈnæpkɪn/', N'khăn ăn', N'noun', N'BEGINNER', N'Food', N'Use a napkin to wipe your mouth.', N'Dùng khăn ăn để lau miệng.'),
(N'hunger', N'/ˈhʌŋɡər/', N'cơn đói / nạn đói', N'noun', N'INTERMEDIATE', N'General', N'World hunger remains a serious problem.', N'Nạn đói thế giới vẫn là vấn đề nghiêm trọng.'),
(N'thirst', N'/θɜːrst/', N'cơn khát', N'noun', N'INTERMEDIATE', N'Health', N'Drink water to quench your thirst.', N'Uống nước để giải khát.'),
-- Science / Nature
(N'biology', N'/baɪˈɒlədʒi/', N'sinh học', N'noun', N'INTERMEDIATE', N'Education', N'Biology is the study of living things.', N'Sinh học là môn nghiên cứu về sinh vật sống.'),
(N'chemistry', N'/ˈkemɪstri/', N'hóa học', N'noun', N'INTERMEDIATE', N'Education', N'Chemistry explains how substances react.', N'Hóa học giải thích cách các chất phản ứng.'),
(N'physics', N'/ˈfɪzɪks/', N'vật lý', N'noun', N'INTERMEDIATE', N'Education', N'Physics helps us understand the universe.', N'Vật lý giúp chúng ta hiểu vũ trụ.'),
(N'solid', N'/ˈsɒlɪd/', N'chất rắn / vững chắc', N'noun', N'BEGINNER', N'General', N'Ice is a solid form of water.', N'Đá là dạng rắn của nước.'),
(N'liquid', N'/ˈlɪkwɪd/', N'chất lỏng', N'noun', N'BEGINNER', N'General', N'Water is the most common liquid on Earth.', N'Nước là chất lỏng phổ biến nhất trên Trái Đất.'),
(N'gas', N'/ɡæs/', N'khí / xăng', N'noun', N'BEGINNER', N'General', N'Carbon dioxide is a greenhouse gas.', N'Carbon dioxide là một loại khí nhà kính.'),
(N'force', N'/fɔːrs/', N'lực / sức mạnh', N'noun', N'INTERMEDIATE', N'General', N'Gravity is a natural force.', N'Lực hấp dẫn là một lực tự nhiên.'),
(N'energy', N'/ˈenərdʒi/', N'năng lượng', N'noun', N'BEGINNER', N'General', N'Solar energy is clean and renewable.', N'Năng lượng mặt trời sạch và tái tạo được.'),
(N'electric', N'/ɪˈlektrɪk/', N'điện / chạy điện', N'adjective', N'BEGINNER', N'Technology', N'The electric car is quiet and efficient.', N'Xe điện yên tĩnh và hiệu quả.'),
(N'universe', N'/ˈjuːnɪvɜːrs/', N'vũ trụ', N'noun', N'BEGINNER', N'General', N'The universe is vast and mysterious.', N'Vũ trụ bao la và huyền bí.'),
(N'galaxy', N'/ˈɡæləksi/', N'thiên hà', N'noun', N'INTERMEDIATE', N'General', N'The Milky Way is our galaxy.', N'Dải Ngân Hà là thiên hà của chúng ta.'),
(N'planet', N'/ˈplænɪt/', N'hành tinh', N'noun', N'BEGINNER', N'General', N'Earth is the only planet known to support life.', N'Trái Đất là hành tinh duy nhất được biết là có sự sống.'),
-- Actions / Verbs (bổ sung)
(N'burn', N'/bɜːrn/', N'đốt cháy / bỏng', N'verb', N'BEGINNER', N'Actions', N'Be careful not to burn yourself while cooking.', N'Cẩn thận đừng để bỏng khi nấu ăn.'),
(N'melt', N'/melt/', N'tan chảy / làm chảy', N'verb', N'BEGINNER', N'Actions', N'The ice began to melt in the sun.', N'Băng bắt đầu tan chảy dưới nắng.'),
(N'freeze', N'/friːz/', N'đóng băng / đóng cứng', N'verb', N'BEGINNER', N'Actions', N'Water freezes at zero degrees Celsius.', N'Nước đóng băng ở không độ Celsius.'),
(N'build', N'/bɪld/', N'xây dựng / tạo dựng', N'verb', N'BEGINNER', N'Actions', N'They plan to build a new bridge.', N'Họ có kế hoạch xây một cây cầu mới.'),
(N'fold', N'/foʊld/', N'gấp / xếp', N'verb', N'BEGINNER', N'Actions', N'Fold the paper in half.', N'Gấp tờ giấy làm đôi.'),
(N'wrap', N'/ræp/', N'bọc / gói', N'verb', N'BEGINNER', N'Actions', N'Wrap the gift with colourful paper.', N'Bọc quà bằng giấy màu sắc.'),
(N'compare', N'/kəmˈpɛər/', N'so sánh', N'verb', N'BEGINNER', N'Actions', N'Compare the two prices before buying.', N'So sánh hai mức giá trước khi mua.'),
(N'contrast', N'/ˈkɒntræst/', N'đối chiếu / tương phản', N'verb', N'INTERMEDIATE', N'Actions', N'Contrast the two poems in your essay.', N'Đối chiếu hai bài thơ trong bài luận của bạn.'),
(N'predict', N'/prɪˈdɪkt/', N'dự đoán', N'verb', N'INTERMEDIATE', N'Actions', N'It is hard to predict the weather accurately.', N'Khó dự đoán thời tiết chính xác.'),
(N'estimate', N'/ˈestɪmeɪt/', N'ước tính', N'verb', N'INTERMEDIATE', N'Actions', N'Can you estimate the total cost?', N'Bạn có thể ước tính tổng chi phí không?'),
(N'announce', N'/əˈnaʊns/', N'thông báo / công bố', N'verb', N'INTERMEDIATE', N'Actions', N'The CEO announced the new policy.', N'Giám đốc điều hành thông báo chính sách mới.'),
(N'declare', N'/dɪˈklɛər/', N'tuyên bố / khai báo', N'verb', N'INTERMEDIATE', N'Actions', N'He declared his intention to run for office.', N'Anh ấy tuyên bố ý định tranh cử.'),
(N'lift', N'/lɪft/', N'nâng lên / thang máy', N'verb', N'BEGINNER', N'Actions', N'Lift heavy objects with your legs, not your back.', N'Nâng vật nặng bằng chân, không phải lưng.'),
(N'float', N'/floʊt/', N'nổi / trôi nổi', N'verb', N'BEGINNER', N'Actions', N'Wood floats on water.', N'Gỗ nổi trên mặt nước.'),
(N'guard', N'/ɡɑːrd/', N'canh gác / bảo vệ', N'verb', N'INTERMEDIATE', N'Actions', N'Guard the entrance carefully.', N'Canh gác lối vào cẩn thận.'),
(N'defend', N'/dɪˈfend/', N'bảo vệ / phòng thủ', N'verb', N'INTERMEDIATE', N'Actions', N'We must defend our rights.', N'Chúng ta phải bảo vệ quyền lợi của mình.'),
(N'attack', N'/əˈtæk/', N'tấn công', N'verb', N'INTERMEDIATE', N'Actions', N'The team attacked early in the match.', N'Đội bóng tấn công sớm trong trận đấu.'),
(N'construct', N'/kənˈstrʌkt/', N'xây dựng / kiến tạo', N'verb', N'INTERMEDIATE', N'Actions', N'They will construct a new school next year.', N'Họ sẽ xây dựng một trường học mới vào năm tới.'),
(N'inspect', N'/ɪnˈspekt/', N'kiểm tra / thanh tra', N'verb', N'INTERMEDIATE', N'Actions', N'Inspect the product for any defects.', N'Kiểm tra sản phẩm để phát hiện lỗi.'),
(N'organize', N'/ˈɔːrɡənaɪz/', N'tổ chức / sắp xếp', N'verb', N'INTERMEDIATE', N'Actions', N'Organize your files into folders.', N'Sắp xếp tệp của bạn vào thư mục.'),
(N'publish', N'/ˈpʌblɪʃ/', N'xuất bản / đăng tải', N'verb', N'INTERMEDIATE', N'Actions', N'She published her first novel last year.', N'Cô ấy xuất bản cuốn tiểu thuyết đầu tiên năm ngoái.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('nest','feather','fur','claw','beak','wing','chirp','roar','hibernate','migrate','prey','predator','bone','joint','nerve','vein','appetite','stretch','pregnant','massage','keyboard','monitor','printer','folder','file','wifi','bluetooth','signal','crash','bug','glitch','inbox','spam','attachment','account','profile','sprint','jog','foul','equipment','gear','teammate','stadium','medal','peel','slice','appetizer','vegan','buffet','tray','napkin','hunger','thirst','biology','chemistry','physics','solid','liquid','gas','force','energy','electric','universe','galaxy','planet','burn','melt','freeze','build','fold','wrap','compare','contrast','predict','estimate','announce','declare','lift','float','guard','defend','attack','construct','inspect','organize','publish');
