--liquibase formatted sql

--changeset vocab:059-seed-words-batch51
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.category, v.example_sentence, v.example_translation
FROM (VALUES
-- Social / Relationships
(N'wedding', N'/ˈwedɪŋ/', N'đám cưới', N'noun', N'BEGINNER', N'Social', N'Their wedding was a beautiful ceremony.', N'Đám cưới của họ là một buổi lễ đẹp.'),
(N'marriage', N'/ˈmærɪdʒ/', N'hôn nhân', N'noun', N'INTERMEDIATE', N'Social', N'A happy marriage requires trust and respect.', N'Một cuộc hôn nhân hạnh phúc cần sự tin tưởng và tôn trọng.'),
(N'divorce', N'/dɪˈvɔːrs/', N'ly hôn', N'noun', N'INTERMEDIATE', N'Social', N'The divorce process can be emotionally difficult.', N'Quá trình ly hôn có thể rất khó khăn về mặt cảm xúc.'),
(N'friendship', N'/ˈfrendʃɪp/', N'tình bạn', N'noun', N'BEGINNER', N'Social', N'True friendship lasts a lifetime.', N'Tình bạn thật sự kéo dài suốt đời.'),
(N'polite', N'/pəˈlaɪt/', N'lịch sự', N'adjective', N'BEGINNER', N'Character', N'Always be polite when speaking to others.', N'Hãy luôn lịch sự khi nói chuyện với người khác.'),
(N'rude', N'/ruːd/', N'thô lỗ / bất lịch sự', N'adjective', N'BEGINNER', N'Character', N'It is rude to interrupt someone while they are talking.', N'Ngắt lời người khác khi họ đang nói là thô lỗ.'),
(N'loyal', N'/ˈlɔɪəl/', N'trung thành / trung thực', N'adjective', N'INTERMEDIATE', N'Character', N'A loyal friend stays with you through hard times.', N'Một người bạn trung thành ở bên bạn qua giai đoạn khó khăn.'),
(N'honest', N'/ˈɒnɪst/', N'trung thực / thành thật', N'adjective', N'BEGINNER', N'Character', N'Always be honest with yourself and others.', N'Hãy luôn trung thực với bản thân và người khác.'),
(N'gossip', N'/ˈɡɒsɪp/', N'tin đồn / tán gẫu', N'noun', N'INTERMEDIATE', N'Social', N'Try not to spread gossip at work.', N'Cố gắng không lan truyền tin đồn ở nơi làm việc.'),
(N'rumor', N'/ˈruːmər/', N'tin đồn', N'noun', N'INTERMEDIATE', N'Social', N'Do not believe every rumor you hear.', N'Đừng tin vào mọi tin đồn bạn nghe.'),
(N'trust', N'/trʌst/', N'sự tin tưởng / tin tưởng', N'noun', N'BEGINNER', N'Character', N'Trust is the foundation of every relationship.', N'Sự tin tưởng là nền tảng của mọi mối quan hệ.'),
(N'respect', N'/rɪˈspekt/', N'tôn trọng', N'noun', N'BEGINNER', N'Character', N'Show respect to people of all ages.', N'Tôn trọng mọi người ở mọi lứa tuổi.'),
(N'support', N'/səˈpɔːrt/', N'sự ủng hộ / hỗ trợ', N'noun', N'BEGINNER', N'Social', N'The community showed great support.', N'Cộng đồng thể hiện sự ủng hộ lớn.'),
-- Arts / Music
(N'paint', N'/peɪnt/', N'vẽ / sơn / màu sơn', N'verb', N'BEGINNER', N'Entertainment', N'She loves to paint landscapes.', N'Cô ấy thích vẽ phong cảnh.'),
(N'sketch', N'/sketʃ/', N'phác thảo / vẽ phác', N'verb', N'INTERMEDIATE', N'Entertainment', N'He quickly sketched a portrait of her.', N'Anh ấy phác thảo nhanh một bức chân dung của cô ấy.'),
(N'sculpt', N'/skʌlpt/', N'điêu khắc / tạc', N'verb', N'INTERMEDIATE', N'Entertainment', N'The artist sculpted the statue from marble.', N'Nghệ sĩ điêu khắc tượng từ đá cẩm thạch.'),
(N'palette', N'/ˈpælɪt/', N'bảng màu', N'noun', N'INTERMEDIATE', N'Entertainment', N'The artist mixed colours on the palette.', N'Nghệ sĩ trộn màu trên bảng màu.'),
(N'rehearsal', N'/rɪˈhɜːrsəl/', N'buổi tập dượt / diễn tập', N'noun', N'INTERMEDIATE', N'Entertainment', N'The final rehearsal is tomorrow evening.', N'Buổi tập dượt cuối cùng là tối mai.'),
(N'spotlight', N'/ˈspɒtlaɪt/', N'đèn sân khấu / tiêu điểm', N'noun', N'INTERMEDIATE', N'Entertainment', N'The singer stepped into the spotlight.', N'Ca sĩ bước vào ánh đèn sân khấu.'),
(N'rhythm', N'/ˈrɪðəm/', N'nhịp điệu', N'noun', N'INTERMEDIATE', N'Entertainment', N'The rhythm of the drum is infectious.', N'Nhịp trống rất cuốn hút.'),
(N'beat', N'/biːt/', N'nhịp / đánh / đánh bại', N'noun', N'BEGINNER', N'Entertainment', N'Tap your foot to the beat of the music.', N'Gõ chân theo nhịp nhạc.'),
(N'tempo', N'/ˈtempoʊ/', N'nhịp độ / tốc độ âm nhạc', N'noun', N'INTERMEDIATE', N'Entertainment', N'The orchestra increased the tempo.', N'Dàn nhạc tăng nhịp độ.'),
(N'perform', N'/pərˈfɔːrm/', N'biểu diễn / thực hiện', N'verb', N'INTERMEDIATE', N'Entertainment', N'She performs on stage every weekend.', N'Cô ấy biểu diễn trên sân khấu mỗi cuối tuần.'),
(N'exhibit', N'/ɪɡˈzɪbɪt/', N'triển lãm / trưng bày', N'verb', N'INTERMEDIATE', N'Entertainment', N'The museum exhibits ancient artefacts.', N'Bảo tàng trưng bày các cổ vật.'),
-- Culture / Tradition
(N'tradition', N'/trəˈdɪʃən/', N'truyền thống', N'noun', N'BEGINNER', N'Culture', N'Respect the traditions of other cultures.', N'Tôn trọng truyền thống của các nền văn hóa khác.'),
(N'custom', N'/ˈkʌstəm/', N'phong tục / tập quán', N'noun', N'INTERMEDIATE', N'Culture', N'It is a local custom to bow when greeting.', N'Đây là phong tục địa phương để cúi chào khi gặp mặt.'),
(N'ceremony', N'/ˈserɪməni/', N'lễ nghi / buổi lễ', N'noun', N'INTERMEDIATE', N'Culture', N'The opening ceremony was spectacular.', N'Lễ khai mạc rất hoành tráng.'),
(N'ritual', N'/ˈrɪtʃuəl/', N'nghi lễ / nghi thức', N'noun', N'INTERMEDIATE', N'Culture', N'Morning coffee has become my daily ritual.', N'Uống cà phê sáng đã trở thành nghi lễ hàng ngày của tôi.'),
(N'monument', N'/ˈmɒnjʊmənt/', N'đài tưởng niệm / công trình lịch sử', N'noun', N'INTERMEDIATE', N'Places', N'The monument was built to honor the war heroes.', N'Đài tưởng niệm được xây dựng để tôn vinh các anh hùng chiến tranh.'),
(N'myth', N'/mɪθ/', N'thần thoại / huyền thoại', N'noun', N'INTERMEDIATE', N'Culture', N'The myth of dragons exists in many cultures.', N'Thần thoại về rồng tồn tại trong nhiều nền văn hóa.'),
(N'legend', N'/ˈledʒənd/', N'truyền thuyết / huyền thoại', N'noun', N'INTERMEDIATE', N'Culture', N'The legend of the sword has been passed down.', N'Truyền thuyết về thanh kiếm đã được truyền lại.'),
(N'artifact', N'/ˈɑːrtɪfækt/', N'cổ vật / hiện vật', N'noun', N'INTERMEDIATE', N'Culture', N'The museum displayed rare ancient artifacts.', N'Bảo tàng trưng bày các cổ vật hiếm thấy.'),
-- Business / Finance
(N'deal', N'/diːl/', N'thỏa thuận / giao dịch', N'noun', N'INTERMEDIATE', N'Business', N'We closed the deal yesterday.', N'Chúng tôi chốt thỏa thuận hôm qua.'),
(N'competition', N'/ˌkɒmpɪˈtɪʃən/', N'sự cạnh tranh / cuộc thi', N'noun', N'INTERMEDIATE', N'Business', N'The competition in the market is fierce.', N'Sự cạnh tranh trên thị trường rất khốc liệt.'),
(N'competitor', N'/kəmˈpetɪtər/', N'đối thủ cạnh tranh', N'noun', N'INTERMEDIATE', N'Business', N'Study your competitors carefully.', N'Nghiên cứu kỹ các đối thủ cạnh tranh của bạn.'),
(N'import', N'/ˈɪmpɔːrt/', N'nhập khẩu', N'verb', N'INTERMEDIATE', N'Business', N'Vietnam imports a lot of machinery.', N'Việt Nam nhập khẩu nhiều máy móc.'),
(N'export', N'/ˈekspɔːrt/', N'xuất khẩu', N'verb', N'INTERMEDIATE', N'Business', N'Vietnam exports rice to many countries.', N'Việt Nam xuất khẩu gạo sang nhiều nước.'),
(N'supply', N'/səˈplaɪ/', N'cung cấp / nguồn cung', N'verb', N'INTERMEDIATE', N'Business', N'We supply fresh produce to restaurants.', N'Chúng tôi cung cấp thực phẩm tươi cho nhà hàng.'),
(N'shortage', N'/ˈʃɔːrtɪdʒ/', N'sự thiếu hụt', N'noun', N'INTERMEDIATE', N'Business', N'There is a shortage of skilled workers.', N'Có sự thiếu hụt lao động có kỹ năng.'),
(N'manufacture', N'/ˌmænjʊˈfæktʃər/', N'sản xuất / chế tạo', N'verb', N'INTERMEDIATE', N'Business', N'This company manufactures car parts.', N'Công ty này sản xuất phụ tùng ô tô.'),
(N'retail', N'/ˈriːteɪl/', N'bán lẻ', N'noun', N'INTERMEDIATE', N'Business', N'Retail sales increased during the holidays.', N'Doanh số bán lẻ tăng trong dịp lễ.'),
(N'wholesale', N'/ˈhoʊlseɪl/', N'bán buôn / bán sỉ', N'noun', N'INTERMEDIATE', N'Business', N'We buy products at wholesale prices.', N'Chúng tôi mua sản phẩm với giá bán sỉ.'),
(N'expense', N'/ɪkˈspens/', N'chi phí / khoản chi', N'noun', N'INTERMEDIATE', N'Business', N'Keep track of all business expenses.', N'Theo dõi tất cả chi phí kinh doanh.'),
-- Adjectives (bổ sung)
(N'loud', N'/laʊd/', N'ồn ào / to tiếng', N'adjective', N'BEGINNER', N'Descriptive', N'The music was too loud at the party.', N'Âm nhạc quá ồn ào ở bữa tiệc.'),
(N'quiet', N'/ˈkwaɪɪt/', N'yên tĩnh / im lặng', N'adjective', N'BEGINNER', N'Descriptive', N'Please keep quiet in the library.', N'Vui lòng giữ im lặng trong thư viện.'),
(N'silent', N'/ˈsaɪlənt/', N'im lặng / không phát ra tiếng', N'adjective', N'BEGINNER', N'Descriptive', N'The forest was completely silent at night.', N'Khu rừng hoàn toàn im lặng vào ban đêm.'),
(N'bright', N'/braɪt/', N'sáng / thông minh', N'adjective', N'BEGINNER', N'Descriptive', N'The bright sunlight hurt his eyes.', N'Ánh nắng chói chang làm đau mắt anh ấy.'),
(N'dim', N'/dɪm/', N'mờ tối / lờ mờ', N'adjective', N'INTERMEDIATE', N'Descriptive', N'The room was lit by a dim lamp.', N'Căn phòng được chiếu sáng bằng một ngọn đèn mờ.'),
(N'thick', N'/θɪk/', N'dày / đặc', N'adjective', N'BEGINNER', N'Descriptive', N'Put on a thick coat in winter.', N'Mặc áo dày vào mùa đông.'),
(N'thin', N'/θɪn/', N'mỏng / gầy', N'adjective', N'BEGINNER', N'Descriptive', N'Use a thin layer of butter.', N'Dùng một lớp bơ mỏng.'),
(N'deep', N'/diːp/', N'sâu / thẳm', N'adjective', N'BEGINNER', N'Descriptive', N'The lake is very deep in the centre.', N'Hồ rất sâu ở trung tâm.'),
(N'shallow', N'/ˈʃæloʊ/', N'nông cạn / thiếu sâu sắc', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Children can play in the shallow end.', N'Trẻ em có thể chơi ở phần nông.'),
(N'tight', N'/taɪt/', N'chặt / bó sát', N'adjective', N'BEGINNER', N'Descriptive', N'These shoes are a bit tight.', N'Đôi giày này hơi chật.'),
(N'loose', N'/luːs/', N'lỏng / không chặt', N'adjective', N'BEGINNER', N'Descriptive', N'The screw is loose and needs tightening.', N'Con vít bị lỏng và cần siết chặt.'),
(N'fragile', N'/ˈfrædʒaɪl/', N'dễ vỡ / mỏng manh', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Handle the fragile glass with care.', N'Cẩn thận khi cầm ly thủy tinh dễ vỡ.'),
(N'sturdy', N'/ˈstɜːrdi/', N'chắc chắn / bền vững', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Buy a sturdy bag for travelling.', N'Mua một chiếc túi chắc chắn để đi du lịch.'),
(N'urgent', N'/ˈɜːrdʒənt/', N'khẩn cấp', N'adjective', N'INTERMEDIATE', N'Descriptive', N'This is an urgent matter.', N'Đây là vấn đề khẩn cấp.'),
(N'essential', N'/ɪˈsenʃəl/', N'thiết yếu / quan trọng', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Water is essential for all living things.', N'Nước là thiết yếu cho mọi sinh vật sống.'),
(N'vital', N'/ˈvaɪtəl/', N'sống còn / cực kỳ quan trọng', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Exercise is vital for a healthy life.', N'Tập thể dục là điều sống còn cho sức khỏe.'),
(N'plain', N'/pleɪn/', N'đơn giản / bình thường / không trang trí', N'adjective', N'BEGINNER', N'Descriptive', N'She wore a plain white shirt.', N'Cô ấy mặc một chiếc áo trắng đơn giản.'),
(N'sharp', N'/ʃɑːrp/', N'sắc / nhọn / thông minh', N'adjective', N'BEGINNER', N'Descriptive', N'Use a sharp knife to cut vegetables.', N'Dùng dao sắc để cắt rau.'),
(N'smooth', N'/smuːð/', N'mượt mà / trơn tru', N'adjective', N'BEGINNER', N'Descriptive', N'The road is smooth after repair.', N'Con đường mượt mà sau khi sửa chữa.'),
(N'rough', N'/rʌf/', N'thô ráp / gồ ghề', N'adjective', N'BEGINNER', N'Descriptive', N'The rough surface scratched his hand.', N'Bề mặt thô ráp làm xước tay anh ấy.'),
-- General nouns (bổ sung)
(N'summary', N'/ˈsʌməri/', N'tóm tắt / bản tóm lược', N'noun', N'INTERMEDIATE', N'General', N'Write a short summary of the article.', N'Viết một bản tóm tắt ngắn về bài báo.'),
(N'outline', N'/ˈaʊtlaɪn/', N'đại cương / phác thảo', N'noun', N'INTERMEDIATE', N'General', N'Create an outline before writing your essay.', N'Lập đề cương trước khi viết bài luận.'),
(N'draft', N'/drɑːft/', N'bản thảo', N'noun', N'INTERMEDIATE', N'General', N'Send me the draft by Monday.', N'Gửi cho tôi bản thảo trước thứ Hai.'),
(N'template', N'/ˈtemplɪt/', N'mẫu / khuôn mẫu', N'noun', N'INTERMEDIATE', N'General', N'Use this template to write your report.', N'Dùng mẫu này để viết báo cáo của bạn.'),
(N'format', N'/ˈfɔːrmæt/', N'định dạng / hình thức', N'noun', N'INTERMEDIATE', N'General', N'Please follow the correct file format.', N'Vui lòng tuân theo định dạng tệp chính xác.'),
(N'boundary', N'/ˈbaʊndri/', N'ranh giới / giới hạn', N'noun', N'INTERMEDIATE', N'General', N'Set clear boundaries in your relationships.', N'Thiết lập ranh giới rõ ràng trong các mối quan hệ.'),
(N'limit', N'/ˈlɪmɪt/', N'giới hạn', N'noun', N'BEGINNER', N'General', N'Know your limits and do not overwork.', N'Biết giới hạn của bạn và không làm việc quá sức.'),
(N'priority', N'/praɪˈɒrɪti/', N'ưu tiên / điều quan trọng nhất', N'noun', N'INTERMEDIATE', N'General', N'Health should be your top priority.', N'Sức khỏe nên là ưu tiên hàng đầu của bạn.'),
(N'benefit', N'/ˈbenɪfɪt/', N'lợi ích / phúc lợi', N'noun', N'INTERMEDIATE', N'General', N'Exercise has many health benefits.', N'Tập thể dục có nhiều lợi ích cho sức khỏe.'),
(N'risk', N'/rɪsk/', N'rủi ro / nguy cơ', N'noun', N'INTERMEDIATE', N'General', N'Every investment carries some risk.', N'Mọi khoản đầu tư đều mang theo rủi ro.'),
(N'challenge', N'/ˈtʃælɪndʒ/', N'thách thức / khó khăn', N'noun', N'INTERMEDIATE', N'General', N'Every challenge is an opportunity to grow.', N'Mỗi thách thức là cơ hội để phát triển.'),
(N'opportunity', N'/ˌɒpəˈtjuːnɪti/', N'cơ hội', N'noun', N'INTERMEDIATE', N'General', N'Do not miss this great opportunity.', N'Đừng bỏ lỡ cơ hội tốt này.'),
(N'community', N'/kəˈmjuːnɪti/', N'cộng đồng', N'noun', N'BEGINNER', N'Social', N'The community came together to help.', N'Cộng đồng đã đoàn kết để giúp đỡ.'),
(N'environment', N'/ɪnˈvaɪrənmənt/', N'môi trường', N'noun', N'BEGINNER', N'Nature', N'We must protect the environment.', N'Chúng ta phải bảo vệ môi trường.'),
(N'condition', N'/kənˈdɪʃən/', N'điều kiện / tình trạng', N'noun', N'INTERMEDIATE', N'General', N'The working conditions have improved.', N'Điều kiện làm việc đã được cải thiện.'),
(N'detail', N'/ˈdiːteɪl/', N'chi tiết', N'noun', N'BEGINNER', N'General', N'Pay attention to every detail.', N'Chú ý đến từng chi tiết.'),
(N'location', N'/loʊˈkeɪʃən/', N'vị trí / địa điểm', N'noun', N'BEGINNER', N'General', N'Share your location with your friend.', N'Chia sẻ vị trí của bạn với bạn bè.'),
(N'direction', N'/daɪˈrekʃən/', N'hướng / chỉ dẫn đường', N'noun', N'BEGINNER', N'General', N'Ask for directions if you get lost.', N'Hỏi đường nếu bạn bị lạc.'),
(N'generation', N'/ˌdʒenəˈreɪʃən/', N'thế hệ', N'noun', N'INTERMEDIATE', N'Social', N'Each generation faces different challenges.', N'Mỗi thế hệ đối mặt với các thách thức khác nhau.'),
(N'society', N'/səˈsaɪɪti/', N'xã hội', N'noun', N'INTERMEDIATE', N'Social', N'Education is vital for a healthy society.', N'Giáo dục rất quan trọng cho một xã hội lành mạnh.'),
-- More useful verbs
(N'invest', N'/ɪnˈvest/', N'đầu tư', N'verb', N'INTERMEDIATE', N'Business', N'Invest your savings wisely.', N'Đầu tư tiền tiết kiệm một cách khôn ngoan.'),
(N'achieve', N'/əˈtʃiːv/', N'đạt được / thành đạt', N'verb', N'INTERMEDIATE', N'Actions', N'Hard work helps you achieve your goals.', N'Làm việc chăm chỉ giúp bạn đạt được mục tiêu.'),
(N'expand', N'/ɪkˈspænd/', N'mở rộng', N'verb', N'INTERMEDIATE', N'Actions', N'The company plans to expand overseas.', N'Công ty có kế hoạch mở rộng ra nước ngoài.'),
(N'express', N'/ɪkˈspres/', N'thể hiện / bày tỏ', N'verb', N'INTERMEDIATE', N'Actions', N'Express your feelings openly and clearly.', N'Bày tỏ cảm xúc của bạn một cách cởi mở và rõ ràng.'),
(N'display', N'/dɪˈspleɪ/', N'trưng bày / hiển thị', N'verb', N'INTERMEDIATE', N'Actions', N'The store displays its products in the window.', N'Cửa hàng trưng bày sản phẩm trong tủ kính.'),
(N'establish', N'/ɪˈstæblɪʃ/', N'thành lập / thiết lập', N'verb', N'INTERMEDIATE', N'Actions', N'The company was established in 2005.', N'Công ty được thành lập vào năm 2005.'),
(N'transfer', N'/trænsˈfɜːr/', N'chuyển / chuyển khoản', N'verb', N'INTERMEDIATE', N'Actions', N'Transfer the file to the new computer.', N'Chuyển tệp sang máy tính mới.'),
(N'confirm', N'/kənˈfɜːrm/', N'xác nhận', N'verb', N'INTERMEDIATE', N'Actions', N'Please confirm your appointment by email.', N'Vui lòng xác nhận cuộc hẹn qua email.'),
(N'approve', N'/əˈpruːv/', N'phê duyệt / chấp thuận', N'verb', N'INTERMEDIATE', N'Actions', N'The manager approved the new budget.', N'Người quản lý phê duyệt ngân sách mới.'),
(N'recommend', N'/ˌrekəˈmend/', N'đề xuất / giới thiệu', N'verb', N'INTERMEDIATE', N'Actions', N'I highly recommend this restaurant.', N'Tôi rất giới thiệu nhà hàng này.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('wedding','marriage','divorce','friendship','polite','rude','loyal','honest','gossip','rumor','trust','respect','support','paint','sketch','sculpt','palette','rehearsal','spotlight','rhythm','beat','tempo','perform','exhibit','tradition','custom','ceremony','ritual','monument','myth','legend','artifact','deal','competition','competitor','import','export','supply','shortage','manufacture','retail','wholesale','expense','loud','quiet','silent','bright','dim','thick','thin','deep','shallow','tight','loose','fragile','sturdy','urgent','essential','vital','plain','sharp','smooth','rough','summary','outline','draft','template','format','boundary','limit','priority','benefit','risk','challenge','opportunity','community','environment','condition','detail','location','direction','generation','society','invest','achieve','expand','express','display','establish','transfer','confirm','approve','recommend');
