--liquibase formatted sql

--changeset vocab:060-seed-words-batch52
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.category, v.example_sentence, v.example_translation
FROM (VALUES
(N'abandon', N'/əˈbændən/', N'từ bỏ', N'verb', N'INTERMEDIATE', N'Actions', N'He decided to abandon the plan.', N'Anh ấy quyết định từ bỏ kế hoạch.'),
(N'ability', N'/əˈbɪləti/', N'khả năng', N'noun', N'BEGINNER', N'General', N'She has the ability to solve problems.', N'Cô ấy có khả năng giải quyết vấn đề.'),
(N'accurate', N'/ˈækjərət/', N'chính xác', N'adjective', N'BEGINNER', N'Descriptive', N'The report is accurate.', N'Báo cáo rất chính xác.'),
(N'achieve', N'/əˈtʃiːv/', N'đạt được', N'verb', N'BEGINNER', N'Actions', N'They want to achieve success.', N'Họ muốn đạt được thành công.'),
(N'advice', N'/ədˈvaɪs/', N'lời khuyên', N'noun', N'BEGINNER', N'Social', N'He gave me useful advice.', N'Anh ấy cho tôi lời khuyên hữu ích.'),
(N'afford', N'/əˈfɔːrd/', N'có khả năng chi trả', N'verb', N'BEGINNER', N'Shopping', N'I cannot afford this jacket.', N'Tôi không đủ tiền mua áo khoác này.'),
(N'agree', N'/əˈɡriː/', N'đồng ý', N'verb', N'BEGINNER', N'Social', N'I agree with your idea.', N'Tôi đồng ý với ý tưởng của bạn.'),
(N'allow', N'/əˈlaʊ/', N'cho phép', N'verb', N'BEGINNER', N'General', N'They allow pets here.', N'Họ cho phép nuôi thú cưng ở đây.'),
(N'amazing', N'/əˈmeɪzɪŋ/', N'tuyệt vời', N'adjective', N'BEGINNER', N'Emotions', N'The view is amazing.', N'Khung cảnh thật tuyệt vời.'),
(N'ancient', N'/ˈeɪnʃənt/', N'cổ xưa', N'adjective', N'INTERMEDIATE', N'Places', N'This temple is ancient.', N'Ngôi đền này rất cổ xưa.'),
(N'anxious', N'/ˈæŋkʃəs/', N'lo lắng', N'adjective', N'INTERMEDIATE', N'Emotions', N'She feels anxious before exams.', N'Cô ấy cảm thấy lo lắng trước kỳ thi.'),
(N'arrive', N'/əˈraɪv/', N'đến nơi', N'verb', N'BEGINNER', N'Travel', N'They arrive at noon.', N'Họ đến vào buổi trưa.'),
(N'assist', N'/əˈsɪst/', N'hỗ trợ', N'verb', N'INTERMEDIATE', N'Work', N'He will assist the manager.', N'Anh ấy sẽ hỗ trợ quản lý.'),
(N'attract', N'/əˈtrækt/', N'thu hút', N'verb', N'INTERMEDIATE', N'General', N'This place attracts tourists.', N'Nơi này thu hút khách du lịch.'),
(N'available', N'/əˈveɪləbl/', N'có sẵn', N'adjective', N'BEGINNER', N'Shopping', N'The product is available online.', N'Sản phẩm có sẵn trên mạng.'),
(N'balance', N'/ˈbæləns/', N'sự cân bằng', N'noun', N'BEGINNER', N'Health', N'Keep a balance in life.', N'Giữ sự cân bằng trong cuộc sống.'),
(N'barely', N'/ˈberli/', N'hầu như không', N'adverb', N'INTERMEDIATE', N'General', N'He barely finished on time.', N'Anh ấy gần như không kịp hoàn thành.'),
(N'benefit', N'/ˈbenɪfɪt/', N'lợi ích', N'noun', N'BEGINNER', N'Health', N'Exercise has many benefits.', N'Tập thể dục có nhiều lợi ích.'),
(N'breathe', N'/briːð/', N'hít thở', N'verb', N'BEGINNER', N'Body', N'Remember to breathe slowly.', N'Hãy nhớ hít thở chậm.'),
(N'brief', N'/briːf/', N'ngắn gọn', N'adjective', N'BEGINNER', N'Work', N'Give a brief explanation.', N'Hãy giải thích ngắn gọn.'),
(N'budget', N'/ˈbʌdʒɪt/', N'ngân sách', N'noun', N'BEGINNER', N'Shopping', N'We have a small budget.', N'Chúng tôi có ngân sách nhỏ.'),
(N'capture', N'/ˈkæptʃər/', N'bắt giữ / ghi lại', N'verb', N'INTERMEDIATE', N'Technology', N'The camera captures images clearly.', N'Máy ảnh ghi lại hình ảnh rõ ràng.'),
(N'careful', N'/ˈkerfl/', N'cẩn thận', N'adjective', N'BEGINNER', N'Descriptive', N'Be careful on the road.', N'Hãy cẩn thận trên đường.'),
(N'celebrate', N'/ˈselɪbreɪt/', N'kỷ niệm / ăn mừng', N'verb', N'BEGINNER', N'Social', N'They celebrate the holiday.', N'Họ ăn mừng ngày lễ.'),
(N'challenge', N'/ˈtʃælɪndʒ/', N'thử thách', N'noun', N'BEGINNER', N'General', N'This task is a challenge.', N'Nhiệm vụ này là một thử thách.'),
(N'choice', N'/tʃɔɪs/', N'sự lựa chọn', N'noun', N'BEGINNER', N'General', N'You have a choice.', N'Bạn có một sự lựa chọn.'),
(N'climate', N'/ˈklaɪmət/', N'khí hậu', N'noun', N'BEGINNER', N'Nature', N'The climate is warm here.', N'Khí hậu ở đây ấm áp.'),
(N'combine', N'/kəmˈbaɪn/', N'kết hợp', N'verb', N'INTERMEDIATE', N'General', N'Combine these ideas.', N'Kết hợp những ý tưởng này.'),
(N'comfort', N'/ˈkʌmfərt/', N'sự thoải mái', N'noun', N'BEGINNER', N'Home', N'This sofa gives great comfort.', N'Chiếc ghế sofa này rất thoải mái.'),
(N'compare', N'/kəmˈper/', N'so sánh', N'verb', N'BEGINNER', N'Education', N'Compare the two results.', N'So sánh hai kết quả.'),
(N'complete', N'/kəmˈpliːt/', N'hoàn thành', N'verb', N'BEGINNER', N'Work', N'She completes her tasks on time.', N'Cô ấy hoàn thành công việc đúng giờ.'),
(N'complex', N'/ˈkɑːmpleks/', N'phức tạp', N'adjective', N'INTERMEDIATE', N'Descriptive', N'The problem is complex.', N'Vấn đề rất phức tạp.'),
(N'concern', N'/kənˈsɜːrn/', N'sự quan tâm / lo ngại', N'noun', N'INTERMEDIATE', N'Emotions', N'He shows great concern.', N'Anh ấy thể hiện sự quan tâm lớn.'),
(N'confirm', N'/kənˈfɜːrm/', N'xác nhận', N'verb', N'BEGINNER', N'Work', N'Please confirm your booking.', N'Vui lòng xác nhận đặt chỗ.'),
(N'connect', N'/kəˈnekt/', N'kết nối', N'verb', N'BEGINNER', N'Technology', N'Connect the device to the wifi.', N'Kết nối thiết bị với wifi.'),
(N'consider', N'/kənˈsɪdər/', N'xem xét / cân nhắc', N'verb', N'BEGINNER', N'General', N'Consider this option carefully.', N'Hãy xem xét lựa chọn này cẩn thận.'),
(N'constant', N'/ˈkɑːnstənt/', N'liên tục / không đổi', N'adjective', N'INTERMEDIATE', N'Time', N'There is constant noise outside.', N'Có tiếng ồn liên tục bên ngoài.'),
(N'contribute', N'/kənˈtrɪbjuːt/', N'đóng góp', N'verb', N'INTERMEDIATE', N'Work', N'She contributes new ideas every week.', N'Cô ấy đóng góp ý tưởng mới mỗi tuần.'),
(N'convenient', N'/kənˈviːniənt/', N'tiện lợi', N'adjective', N'BEGINNER', N'General', N'This app is very convenient.', N'Ứng dụng này rất tiện lợi.'),
(N'creative', N'/kriˈeɪtɪv/', N'sáng tạo', N'adjective', N'BEGINNER', N'Work', N'He is very creative.', N'Anh ấy rất sáng tạo.'),
(N'crowded', N'/ˈkraʊdɪd/', N'đông đúc', N'adjective', N'BEGINNER', N'Places', N'The market is very crowded today.', N'Chợ rất đông đúc hôm nay.'),
(N'curious', N'/ˈkjʊriəs/', N'tò mò', N'adjective', N'BEGINNER', N'Emotions', N'Children are naturally curious.', N'Trẻ em tự nhiên rất tò mò.'),
(N'damage', N'/ˈdæmɪdʒ/', N'thiệt hại / hư hỏng', N'noun', N'BEGINNER', N'General', N'The storm caused serious damage.', N'Cơn bão gây thiệt hại nghiêm trọng.'),
(N'decide', N'/dɪˈsaɪd/', N'quyết định', N'verb', N'BEGINNER', N'General', N'They decide quickly in difficult situations.', N'Họ quyết định nhanh trong tình huống khó.'),
(N'delay', N'/dɪˈleɪ/', N'trì hoãn', N'verb', N'BEGINNER', N'Time', N'The flight is delayed by two hours.', N'Chuyến bay bị trì hoãn hai tiếng.'),
(N'deliver', N'/dɪˈlɪvər/', N'giao hàng', N'verb', N'BEGINNER', N'Shopping', N'They deliver packages to your door.', N'Họ giao hàng đến tận cửa nhà bạn.'),
(N'depend', N'/dɪˈpend/', N'phụ thuộc vào', N'verb', N'BEGINNER', N'General', N'Success depends on your effort.', N'Thành công phụ thuộc vào nỗ lực của bạn.'),
(N'describe', N'/dɪˈskraɪb/', N'mô tả', N'verb', N'BEGINNER', N'Education', N'Describe the picture in detail.', N'Mô tả bức tranh một cách chi tiết.'),
(N'develop', N'/dɪˈveləp/', N'phát triển', N'verb', N'BEGINNER', N'Work', N'They develop new software every year.', N'Họ phát triển phần mềm mới mỗi năm.'),
(N'device', N'/dɪˈvaɪs/', N'thiết bị', N'noun', N'BEGINNER', N'Technology', N'This device is very useful.', N'Thiết bị này rất hữu ích.'),
(N'discover', N'/dɪˈskʌvər/', N'khám phá / phát hiện', N'verb', N'BEGINNER', N'Travel', N'They discover new places every trip.', N'Họ khám phá nơi mới trong mỗi chuyến đi.'),
(N'distance', N'/ˈdɪstəns/', N'khoảng cách', N'noun', N'BEGINNER', N'Transport', N'The distance between the two cities is short.', N'Khoảng cách giữa hai thành phố khá ngắn.'),
(N'efficient', N'/ɪˈfɪʃənt/', N'hiệu quả', N'adjective', N'INTERMEDIATE', N'Work', N'She is an efficient worker.', N'Cô ấy là người làm việc hiệu quả.'),
(N'effort', N'/ˈefərt/', N'nỗ lực', N'noun', N'BEGINNER', N'Work', N'He puts in a lot of effort.', N'Anh ấy bỏ ra rất nhiều nỗ lực.'),
(N'encourage', N'/ɪnˈkɜːrɪdʒ/', N'khuyến khích', N'verb', N'BEGINNER', N'Social', N'Teachers encourage students to read.', N'Giáo viên khuyến khích học sinh đọc sách.'),
(N'energy', N'/ˈenərdʒi/', N'năng lượng', N'noun', N'BEGINNER', N'Health', N'We need more energy to finish.', N'Chúng ta cần thêm năng lượng để hoàn thành.'),
(N'environment', N'/ɪnˈvaɪrənmənt/', N'môi trường', N'noun', N'BEGINNER', N'Nature', N'We must protect the environment.', N'Chúng ta phải bảo vệ môi trường.'),
(N'escape', N'/ɪˈskeɪp/', N'thoát khỏi', N'verb', N'INTERMEDIATE', N'Actions', N'He manages to escape the danger.', N'Anh ấy thoát khỏi nguy hiểm.'),
(N'essential', N'/ɪˈsenʃl/', N'thiết yếu', N'adjective', N'BEGINNER', N'Health', N'Water is essential for life.', N'Nước là thiết yếu cho sự sống.'),
(N'evaluate', N'/ɪˈvæljueɪt/', N'đánh giá', N'verb', N'INTERMEDIATE', N'Work', N'They evaluate performance quarterly.', N'Họ đánh giá hiệu suất theo quý.'),
(N'event', N'/ɪˈvent/', N'sự kiện', N'noun', N'BEGINNER', N'Social', N'The event attracted many people.', N'Sự kiện thu hút nhiều người.'),
(N'exact', N'/ɪɡˈzækt/', N'chính xác / đúng', N'adjective', N'BEGINNER', N'Descriptive', N'Give me the exact number please.', N'Vui lòng cho tôi con số chính xác.'),
(N'exist', N'/ɪɡˈzɪst/', N'tồn tại', N'verb', N'BEGINNER', N'General', N'Does this problem still exist?', N'Vấn đề này vẫn còn tồn tại không?'),
(N'expand', N'/ɪkˈspænd/', N'mở rộng', N'verb', N'INTERMEDIATE', N'Work', N'They plan to expand the business.', N'Họ có kế hoạch mở rộng kinh doanh.'),
(N'expect', N'/ɪkˈspekt/', N'mong đợi / kỳ vọng', N'verb', N'BEGINNER', N'Emotions', N'I expect good results this time.', N'Tôi mong đợi kết quả tốt lần này.'),
(N'experience', N'/ɪkˈspɪriəns/', N'kinh nghiệm', N'noun', N'BEGINNER', N'Work', N'She has years of experience.', N'Cô ấy có nhiều năm kinh nghiệm.'),
(N'explore', N'/ɪkˈsplɔːr/', N'khám phá', N'verb', N'BEGINNER', N'Travel', N'They love to explore new areas.', N'Họ thích khám phá những khu vực mới.'),
(N'express', N'/ɪkˈspres/', N'bày tỏ / thể hiện', N'verb', N'BEGINNER', N'Social', N'Express your feelings openly.', N'Hãy bày tỏ cảm xúc một cách cởi mở.'),
(N'extreme', N'/ɪkˈstriːm/', N'cực đoan / khắc nghiệt', N'adjective', N'INTERMEDIATE', N'Descriptive', N'The weather was extreme last winter.', N'Thời tiết rất khắc nghiệt mùa đông vừa rồi.'),
(N'familiar', N'/fəˈmɪliər/', N'quen thuộc', N'adjective', N'BEGINNER', N'General', N'This place looks familiar to me.', N'Nơi này trông quen thuộc với tôi.'),
(N'feature', N'/ˈfiːtʃər/', N'tính năng / đặc điểm', N'noun', N'BEGINNER', N'Technology', N'This phone has many useful features.', N'Điện thoại này có nhiều tính năng hữu ích.'),
(N'focus', N'/ˈfoʊkəs/', N'tập trung', N'verb', N'BEGINNER', N'Education', N'Focus on your task and finish it.', N'Hãy tập trung vào nhiệm vụ và hoàn thành nó.'),
(N'frequent', N'/ˈfriːkwənt/', N'thường xuyên', N'adjective', N'INTERMEDIATE', N'Time', N'He makes frequent visits to the library.', N'Anh ấy thường xuyên đến thư viện.'),
(N'generate', N'/ˈdʒenəreɪt/', N'tạo ra / sinh ra', N'verb', N'INTERMEDIATE', N'Technology', N'The system generates detailed reports.', N'Hệ thống tạo ra các báo cáo chi tiết.'),
(N'global', N'/ˈɡloʊbl/', N'toàn cầu', N'adjective', N'BEGINNER', N'General', N'This is a global issue we must face.', N'Đây là vấn đề toàn cầu chúng ta phải đối mặt.'),
(N'gradual', N'/ˈɡrædʒuəl/', N'dần dần / từng bước', N'adjective', N'INTERMEDIATE', N'Time', N'There has been a gradual change.', N'Đã có sự thay đổi dần dần.'),
(N'handle', N'/ˈhændl/', N'xử lý / đối phó', N'verb', N'BEGINNER', N'Work', N'She handles problems with calm.', N'Cô ấy xử lý vấn đề một cách bình tĩnh.'),
(N'healthy', N'/ˈhelθi/', N'khỏe mạnh', N'adjective', N'BEGINNER', N'Health', N'Eat well and stay healthy.', N'Ăn uống tốt và giữ sức khỏe.'),
(N'improve', N'/ɪmˈpruːv/', N'cải thiện', N'verb', N'BEGINNER', N'General', N'Practice daily to improve your skills.', N'Luyện tập hàng ngày để cải thiện kỹ năng.'),
(N'include', N'/ɪnˈkluːd/', N'bao gồm', N'verb', N'BEGINNER', N'General', N'The price includes tax and delivery.', N'Giá bao gồm thuế và phí giao hàng.'),
(N'increase', N'/ɪnˈkriːs/', N'tăng lên', N'verb', N'BEGINNER', N'General', N'Prices increase every year.', N'Giá cả tăng lên mỗi năm.'),
(N'indicate', N'/ˈɪndɪkeɪt/', N'chỉ ra / cho thấy', N'verb', N'INTERMEDIATE', N'Education', N'The signs indicate the right direction.', N'Các biển báo chỉ ra hướng đúng.'),
(N'influence', N'/ˈɪnfluəns/', N'sự ảnh hưởng', N'noun', N'INTERMEDIATE', N'Social', N'Parents have great influence on children.', N'Cha mẹ có ảnh hưởng lớn đến con cái.'),
(N'inform', N'/ɪnˈfɔːrm/', N'thông báo', N'verb', N'BEGINNER', N'Work', N'Please inform me of any changes.', N'Vui lòng thông báo cho tôi về bất kỳ thay đổi nào.'),
(N'initial', N'/ɪˈnɪʃl/', N'ban đầu', N'adjective', N'INTERMEDIATE', N'Time', N'The initial plan did not work.', N'Kế hoạch ban đầu không hiệu quả.'),
(N'innovative', N'/ˈɪnəveɪtɪv/', N'đổi mới / sáng tạo', N'adjective', N'INTERMEDIATE', N'Technology', N'They create innovative products every year.', N'Họ tạo ra sản phẩm đổi mới mỗi năm.'),
(N'inspire', N'/ɪnˈspaɪər/', N'truyền cảm hứng', N'verb', N'BEGINNER', N'Emotions', N'Her story inspires many people.', N'Câu chuyện của cô ấy truyền cảm hứng cho nhiều người.'),
(N'install', N'/ɪnˈstɔːl/', N'cài đặt', N'verb', N'BEGINNER', N'Technology', N'Install the app on your phone.', N'Cài đặt ứng dụng trên điện thoại của bạn.'),
(N'instant', N'/ˈɪnstənt/', N'ngay lập tức', N'adjective', N'BEGINNER', N'Time', N'The app gives instant results.', N'Ứng dụng cho kết quả ngay lập tức.'),
(N'interaction', N'/ˌɪntərˈækʃn/', N'sự tương tác', N'noun', N'INTERMEDIATE', N'Social', N'Good interaction builds strong teams.', N'Sự tương tác tốt xây dựng đội nhóm vững mạnh.'),
(N'introduce', N'/ˌɪntrəˈduːs/', N'giới thiệu', N'verb', N'BEGINNER', N'Social', N'Let me introduce myself.', N'Hãy để tôi tự giới thiệu bản thân.'),
(N'involve', N'/ɪnˈvɑːlv/', N'liên quan đến', N'verb', N'BEGINNER', N'General', N'This project involves a lot of effort.', N'Dự án này liên quan đến rất nhiều nỗ lực.'),
(N'journey', N'/ˈdʒɜːrni/', N'hành trình', N'noun', N'BEGINNER', N'Travel', N'The journey took three hours by train.', N'Hành trình mất ba tiếng bằng tàu.'),
(N'knowledge', N'/ˈnɑːlɪdʒ/', N'kiến thức', N'noun', N'BEGINNER', N'Education', N'Knowledge is the key to success.', N'Kiến thức là chìa khóa dẫn đến thành công.'),
(N'limit', N'/ˈlɪmɪt/', N'giới hạn', N'noun', N'BEGINNER', N'General', N'Know your limit and do not overwork.', N'Biết giới hạn và đừng làm việc quá sức.'),
(N'maintain', N'/meɪnˈteɪn/', N'duy trì', N'verb', N'INTERMEDIATE', N'Health', N'Maintain a healthy daily routine.', N'Duy trì thói quen hàng ngày lành mạnh.'),
(N'measure', N'/ˈmeʒər/', N'đo lường', N'verb', N'BEGINNER', N'General', N'Measure the length of the table.', N'Đo chiều dài của cái bàn.'),
(N'mental', N'/ˈmentl/', N'tinh thần / tâm lý', N'adjective', N'BEGINNER', N'Health', N'Mental health is as important as physical health.', N'Sức khỏe tinh thần quan trọng không kém sức khỏe thể chất.'),
(N'method', N'/ˈmeθəd/', N'phương pháp', N'noun', N'BEGINNER', N'Education', N'Use this method to solve the problem.', N'Dùng phương pháp này để giải quyết vấn đề.'),
(N'modern', N'/ˈmɑːdərn/', N'hiện đại', N'adjective', N'BEGINNER', N'Places', N'The building has a very modern design.', N'Tòa nhà có thiết kế rất hiện đại.'),
(N'motivate', N'/ˈmoʊtɪveɪt/', N'tạo động lực', N'verb', N'BEGINNER', N'Emotions', N'Good teachers motivate their students.', N'Giáo viên giỏi tạo động lực cho học sinh.'),
(N'network', N'/ˈnetwɜːrk/', N'mạng lưới', N'noun', N'BEGINNER', N'Technology', N'The network connection is very fast.', N'Kết nối mạng rất nhanh.'),
(N'notice', N'/ˈnoʊtɪs/', N'chú ý / nhận ra', N'verb', N'BEGINNER', N'General', N'I notice small changes every day.', N'Tôi nhận thấy những thay đổi nhỏ mỗi ngày.'),
(N'obvious', N'/ˈɑːbviəs/', N'rõ ràng / hiển nhiên', N'adjective', N'BEGINNER', N'Descriptive', N'The answer is obvious to everyone.', N'Câu trả lời rõ ràng với tất cả mọi người.'),
(N'opportunity', N'/ˌɑːpərˈtuːnəti/', N'cơ hội', N'noun', N'BEGINNER', N'Work', N'This is a great opportunity for growth.', N'Đây là cơ hội tuyệt vời để phát triển.'),
(N'organize', N'/ˈɔːrɡənaɪz/', N'tổ chức / sắp xếp', N'verb', N'BEGINNER', N'Work', N'Organize your files into folders.', N'Sắp xếp tài liệu vào các thư mục.'),
(N'outcome', N'/ˈaʊtkʌm/', N'kết quả / kết cục', N'noun', N'INTERMEDIATE', N'General', N'The outcome of the meeting was positive.', N'Kết quả của cuộc họp rất tích cực.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('abandon','ability','accurate','achieve','advice','afford','agree','allow','amazing','ancient','anxious','arrive','assist','attract','available','balance','barely','benefit','breathe','brief','budget','capture','careful','celebrate','challenge','choice','climate','combine','comfort','compare','complete','complex','concern','confirm','connect','consider','constant','contribute','convenient','creative','crowded','curious','damage','decide','delay','deliver','depend','describe','develop','device','discover','distance','efficient','effort','encourage','energy','environment','escape','essential','evaluate','event','exact','exist','expand','expect','experience','explore','express','extreme','familiar','feature','focus','frequent','generate','global','gradual','handle','healthy','improve','include','increase','indicate','influence','inform','initial','innovative','inspire','install','instant','interaction','introduce','involve','journey','knowledge','limit','maintain','measure','mental','method','modern','motivate','network','notice','obvious','opportunity','organize','outcome');
