--liquibase formatted sql

--changeset vocab:062-seed-words-batch54
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.category, v.example_sentence, v.example_translation
FROM (VALUES
-- Business / Commerce
(N'merger', N'/ˈmɜːrdʒər/', N'sự sáp nhập', N'noun', N'ADVANCED', N'Business', N'The two banks agreed to a merger.', N'Hai ngân hàng đã đồng ý sáp nhập.'),
(N'acquisition', N'/ˌækwɪˈzɪʃən/', N'sự mua lại', N'noun', N'ADVANCED', N'Business', N'The acquisition doubled the company size.', N'Việc mua lại đã tăng gấp đôi quy mô công ty.'),
(N'entrepreneur', N'/ˌɑːntrəprəˈnɜːr/', N'doanh nhân', N'noun', N'INTERMEDIATE', N'Business', N'She is a young and successful entrepreneur.', N'Cô ấy là một doanh nhân trẻ và thành công.'),
(N'franchise', N'/ˈfrænʃaɪz/', N'nhượng quyền thương mại', N'noun', N'ADVANCED', N'Business', N'He opened a coffee shop franchise.', N'Anh ấy mở một quán cà phê nhượng quyền.'),
(N'turnover', N'/ˈtɜːrnoʊvər/', N'doanh thu / tỷ lệ thay thế nhân viên', N'noun', N'ADVANCED', N'Business', N'The store has a high annual turnover.', N'Cửa hàng có doanh thu hàng năm cao.'),
(N'warranty', N'/ˈwɔːrənti/', N'sự bảo hành', N'noun', N'INTERMEDIATE', N'Business', N'The laptop comes with a two-year warranty.', N'Chiếc laptop có bảo hành hai năm.'),
(N'refund', N'/ˈriːfʌnd/', N'sự hoàn tiền', N'noun', N'BEGINNER', N'Business', N'I asked for a refund on the broken item.', N'Tôi yêu cầu hoàn tiền cho món hàng bị hỏng.'),
(N'wholesale', N'/ˈhoʊlseɪl/', N'bán sỉ', N'adjective', N'INTERMEDIATE', N'Business', N'They buy goods at wholesale prices.', N'Họ mua hàng với giá bán sỉ.'),
(N'retail', N'/ˈriːteɪl/', N'bán lẻ', N'adjective', N'INTERMEDIATE', N'Business', N'The retail price is higher than wholesale.', N'Giá bán lẻ cao hơn giá bán sỉ.'),
(N'procurement', N'/prəˈkjʊrmənt/', N'việc thu mua', N'noun', N'ADVANCED', N'Business', N'The procurement team negotiates with suppliers.', N'Bộ phận thu mua đàm phán với nhà cung cấp.'),
(N'logistics', N'/ləˈdʒɪstɪks/', N'hậu cần / logistics', N'noun', N'ADVANCED', N'Business', N'Logistics is essential for global trade.', N'Logistics rất quan trọng đối với thương mại toàn cầu.'),
(N'inventory', N'/ˈɪnvəntɔːri/', N'hàng tồn kho', N'noun', N'INTERMEDIATE', N'Business', N'We need to check the inventory levels.', N'Chúng ta cần kiểm tra mức hàng tồn kho.'),
(N'startup', N'/ˈstɑːrtʌp/', N'công ty khởi nghiệp', N'noun', N'BEGINNER', N'Business', N'The startup raised a lot of funding.', N'Công ty khởi nghiệp đã gọi được nhiều vốn.'),
(N'lucrative', N'/ˈluːkrətɪv/', N'có lợi nhuận cao', N'adjective', N'ADVANCED', N'Business', N'They signed a lucrative deal with the client.', N'Họ đã ký một hợp đồng có lợi nhuận cao với khách hàng.'),
-- Technology
(N'chatbot', N'/ˈtʃætbɑːt/', N'trợ lý ảo trò chuyện', N'noun', N'INTERMEDIATE', N'Technology', N'The website uses a chatbot for support.', N'Trang web sử dụng trợ lý ảo để hỗ trợ.'),
(N'biometric', N'/ˌbaɪoʊˈmetrɪk/', N'sinh trắc học', N'adjective', N'ADVANCED', N'Technology', N'The phone unlocks with biometric data.', N'Điện thoại mở khóa bằng dữ liệu sinh trắc học.'),
(N'wearable', N'/ˈwerəbl/', N'thiết bị đeo được', N'noun', N'INTERMEDIATE', N'Technology', N'Wearable devices track your daily steps.', N'Thiết bị đeo được theo dõi số bước đi hàng ngày.'),
(N'streaming', N'/ˈstriːmɪŋ/', N'phát trực tuyến', N'noun', N'BEGINNER', N'Technology', N'Streaming services offer many movies.', N'Các dịch vụ phát trực tuyến cung cấp nhiều bộ phim.'),
(N'subscription', N'/səbˈskrɪpʃən/', N'gói đăng ký thuê bao', N'noun', N'INTERMEDIATE', N'Technology', N'I canceled my monthly subscription.', N'Tôi đã hủy gói đăng ký hàng tháng của mình.'),
(N'firmware', N'/ˈfɜːrmwer/', N'phần mềm hệ thống', N'noun', N'ADVANCED', N'Technology', N'Update the firmware to fix the bug.', N'Cập nhật firmware để khắc phục lỗi.'),
(N'glitch', N'/ɡlɪtʃ/', N'lỗi nhỏ / trục trặc', N'noun', N'INTERMEDIATE', N'Technology', N'A glitch caused the app to freeze.', N'Một trục trặc khiến ứng dụng bị treo.'),
(N'crash', N'/kræʃ/', N'treo máy / sập hệ thống', N'verb', N'BEGINNER', N'Technology', N'The computer crashed during the update.', N'Máy tính bị treo trong lúc cập nhật.'),
(N'backup', N'/ˈbækʌp/', N'bản sao lưu', N'noun', N'BEGINNER', N'Technology', N'Always keep a backup of your files.', N'Luôn giữ một bản sao lưu cho các tập tin của bạn.'),
(N'synchronize', N'/ˈsɪŋkrənaɪz/', N'đồng bộ hóa', N'verb', N'INTERMEDIATE', N'Technology', N'The app synchronizes data across devices.', N'Ứng dụng đồng bộ hóa dữ liệu trên các thiết bị.'),
(N'cloud storage', N'/klaʊd ˈstɔːrɪdʒ/', N'lưu trữ đám mây', N'noun', N'INTERMEDIATE', N'Technology', N'Photos are saved in cloud storage.', N'Ảnh được lưu trong bộ nhớ đám mây.'),
(N'phishing', N'/ˈfɪʃɪŋ/', N'lừa đảo trực tuyến', N'noun', N'ADVANCED', N'Technology', N'Do not click links in phishing emails.', N'Đừng nhấp vào liên kết trong email lừa đảo.'),
(N'spyware', N'/ˈspaɪwer/', N'phần mềm gián điệp', N'noun', N'ADVANCED', N'Technology', N'The antivirus removed the spyware.', N'Phần mềm diệt virus đã xóa phần mềm gián điệp.'),
-- Science
(N'enzyme', N'/ˈenzaɪm/', N'enzyme / men', N'noun', N'ADVANCED', N'Science', N'Enzymes speed up chemical reactions.', N'Enzyme làm tăng tốc các phản ứng hóa học.'),
(N'hormone', N'/ˈhɔːrmoʊn/', N'hoóc-môn', N'noun', N'INTERMEDIATE', N'Science', N'Hormones regulate growth in the body.', N'Hoóc-môn điều hòa sự phát triển của cơ thể.'),
(N'microorganism', N'/ˌmaɪkroʊˈɔːrɡənɪzəm/', N'vi sinh vật', N'noun', N'ADVANCED', N'Science', N'Microorganisms are found everywhere.', N'Vi sinh vật có mặt ở mọi nơi.'),
(N'mutation', N'/mjuːˈteɪʃən/', N'sự đột biến', N'noun', N'ADVANCED', N'Science', N'A genetic mutation can change traits.', N'Một đột biến gen có thể làm thay đổi đặc điểm.'),
(N'precipitation', N'/prɪˌsɪpɪˈteɪʃən/', N'lượng mưa / sự kết tủa', N'noun', N'ADVANCED', N'Science', N'The region gets heavy precipitation in June.', N'Khu vực này có lượng mưa lớn vào tháng Sáu.'),
(N'condensation', N'/ˌkɑːndenˈseɪʃən/', N'sự ngưng tụ', N'noun', N'INTERMEDIATE', N'Science', N'Condensation formed on the cold glass.', N'Sự ngưng tụ xuất hiện trên chiếc ly lạnh.'),
(N'evaporation', N'/ɪˌvæpəˈreɪʃən/', N'sự bốc hơi', N'noun', N'INTERMEDIATE', N'Science', N'Evaporation turns water into vapor.', N'Sự bốc hơi biến nước thành hơi.'),
(N'sediment', N'/ˈsedɪmənt/', N'cặn / trầm tích', N'noun', N'ADVANCED', N'Science', N'Sediment collected at the bottom of the river.', N'Trầm tích tích tụ ở đáy sông.'),
(N'electron', N'/ɪˈlektrɑːn/', N'điện tử', N'noun', N'INTERMEDIATE', N'Science', N'An electron carries a negative charge.', N'Điện tử mang điện tích âm.'),
(N'isotope', N'/ˈaɪsətoʊp/', N'đồng vị', N'noun', N'ADVANCED', N'Science', N'Carbon has several isotopes.', N'Carbon có nhiều đồng vị.'),
(N'spectrum', N'/ˈspektrəm/', N'quang phổ / dải', N'noun', N'ADVANCED', N'Science', N'A rainbow shows the visible spectrum of light.', N'Cầu vồng cho thấy quang phổ ánh sáng nhìn thấy được.'),
-- Health / Medicine
(N'antidote', N'/ˈæntɪdoʊt/', N'thuốc giải độc', N'noun', N'ADVANCED', N'Health', N'Doctors gave him an antidote for the poison.', N'Các bác sĩ đã cho anh ấy thuốc giải độc.'),
(N'sedative', N'/ˈsedətɪv/', N'thuốc an thần', N'noun', N'ADVANCED', N'Health', N'The nurse gave a mild sedative before surgery.', N'Y tá đã cho một loại thuốc an thần nhẹ trước phẫu thuật.'),
(N'inflammation', N'/ˌɪnfləˈmeɪʃən/', N'viêm / sưng', N'noun', N'INTERMEDIATE', N'Health', N'Ice reduces inflammation and pain.', N'Đá giúp giảm viêm và đau.'),
(N'immunity', N'/ɪˈmjuːnəti/', N'khả năng miễn dịch', N'noun', N'INTERMEDIATE', N'Health', N'Vaccines help build immunity.', N'Vắc-xin giúp xây dựng khả năng miễn dịch.'),
(N'cholesterol', N'/kəˈlestərɒl/', N'cholesterol', N'noun', N'INTERMEDIATE', N'Health', N'A healthy diet lowers cholesterol.', N'Chế độ ăn lành mạnh giúp giảm cholesterol.'),
(N'dehydration', N'/ˌdiːhaɪˈdreɪʃən/', N'sự mất nước', N'noun', N'INTERMEDIATE', N'Health', N'Drink water to avoid dehydration.', N'Uống nước để tránh mất nước.'),
(N'malnutrition', N'/ˌmælnuːˈtrɪʃən/', N'suy dinh dưỡng', N'noun', N'ADVANCED', N'Health', N'Malnutrition affects children severely.', N'Suy dinh dưỡng ảnh hưởng nghiêm trọng đến trẻ em.'),
(N'relapse', N'/ˈriːlæps/', N'sự tái phát', N'noun', N'ADVANCED', N'Health', N'The patient suffered a sudden relapse.', N'Bệnh nhân bất ngờ bị tái phát bệnh.'),
(N'remission', N'/rɪˈmɪʃən/', N'sự thuyên giảm', N'noun', N'ADVANCED', N'Health', N'The cancer has gone into remission.', N'Bệnh ung thư đã thuyên giảm.'),
(N'checkup', N'/ˈtʃekʌp/', N'khám sức khỏe tổng quát', N'noun', N'BEGINNER', N'Health', N'She goes for a checkup every year.', N'Cô ấy đi khám sức khỏe tổng quát mỗi năm.'),
-- Nature / Environment
(N'wildfire', N'/ˈwaɪldfaɪər/', N'cháy rừng', N'noun', N'INTERMEDIATE', N'Nature', N'The wildfire spread quickly in the dry heat.', N'Cháy rừng lan nhanh trong không khí khô nóng.'),
(N'sinkhole', N'/ˈsɪŋkhoʊl/', N'hố sụt', N'noun', N'ADVANCED', N'Nature', N'A sinkhole appeared in the middle of the road.', N'Một hố sụt xuất hiện giữa đường.'),
(N'permafrost', N'/ˈpɜːrməfrɒst/', N'lớp đất đóng băng vĩnh cửu', N'noun', N'ADVANCED', N'Nature', N'Permafrost is melting due to warming.', N'Lớp đất đóng băng vĩnh cửu đang tan do nóng lên toàn cầu.'),
(N'canopy', N'/ˈkænəpi/', N'tầng lá rừng', N'noun', N'ADVANCED', N'Nature', N'Sunlight barely reaches under the canopy.', N'Ánh sáng mặt trời hầu như không chiếu tới dưới tầng lá rừng.'),
(N'undergrowth', N'/ˈʌndərɡroʊθ/', N'cây bụi rậm dưới rừng', N'noun', N'ADVANCED', N'Nature', N'They cut through the thick undergrowth.', N'Họ chặt xuyên qua bụi cây rậm rạp.'),
(N'thaw', N'/θɔː/', N'sự tan (băng, tuyết)', N'verb', N'INTERMEDIATE', N'Nature', N'The snow began to thaw in spring.', N'Tuyết bắt đầu tan vào mùa xuân.'),
(N'migratory', N'/ˈmaɪɡrətɔːri/', N'(loài) di cư', N'adjective', N'ADVANCED', N'Nature', N'Migratory birds fly south in winter.', N'Các loài chim di cư bay về phía nam vào mùa đông.'),
(N'predator', N'/ˈpredətər/', N'động vật săn mồi', N'noun', N'INTERMEDIATE', N'Nature', N'The lion is a powerful predator.', N'Sư tử là một loài săn mồi mạnh mẽ.'),
(N'prey', N'/preɪ/', N'con mồi', N'noun', N'INTERMEDIATE', N'Nature', N'The eagle spotted its prey from the sky.', N'Đại bàng phát hiện con mồi từ trên không.'),
-- Character / Personality
(N'tactful', N'/ˈtæktfl/', N'khéo léo, tế nhị', N'adjective', N'ADVANCED', N'Character', N'She gave tactful feedback to her coworker.', N'Cô ấy đưa ra nhận xét khéo léo cho đồng nghiệp.'),
(N'blunt', N'/blʌnt/', N'thẳng thắn / cụt lủn', N'adjective', N'INTERMEDIATE', N'Character', N'He is blunt about his opinions.', N'Anh ấy rất thẳng thắn khi nêu ý kiến của mình.'),
(N'eccentric', N'/ɪkˈsentrɪk/', N'lập dị', N'adjective', N'ADVANCED', N'Character', N'The artist is known for his eccentric behavior.', N'Người nghệ sĩ nổi tiếng với hành vi lập dị.'),
(N'gullible', N'/ˈɡʌləbl/', N'dễ bị lừa / cả tin', N'adjective', N'ADVANCED', N'Character', N'He is gullible and believes anything he hears.', N'Anh ấy cả tin và tin vào bất cứ điều gì nghe được.'),
(N'assertive', N'/əˈsɜːrtɪv/', N'quyết đoán', N'adjective', N'INTERMEDIATE', N'Character', N'Being assertive helps you set boundaries.', N'Tính quyết đoán giúp bạn đặt ra giới hạn.'),
(N'timid', N'/ˈtɪmɪd/', N'nhút nhát, rụt rè', N'adjective', N'BEGINNER', N'Character', N'The timid boy hid behind his mother.', N'Cậu bé nhút nhát trốn sau lưng mẹ.'),
(N'arrogant', N'/ˈærəɡənt/', N'kiêu ngạo', N'adjective', N'INTERMEDIATE', N'Character', N'Nobody likes his arrogant attitude.', N'Không ai thích thái độ kiêu ngạo của anh ấy.'),
(N'humorous', N'/ˈhjuːmərəs/', N'hài hước', N'adjective', N'BEGINNER', N'Character', N'His humorous stories made everyone smile.', N'Những câu chuyện hài hước của anh ấy khiến mọi người mỉm cười.'),
(N'stingy', N'/ˈstɪndʒi/', N'keo kiệt', N'adjective', N'INTERMEDIATE', N'Character', N'He is too stingy to buy anyone a gift.', N'Anh ấy quá keo kiệt để mua quà cho ai đó.'),
(N'considerate', N'/kənˈsɪdərət/', N'biết quan tâm người khác', N'adjective', N'INTERMEDIATE', N'Character', N'She is always considerate of others feelings.', N'Cô ấy luôn quan tâm đến cảm xúc của người khác.'),
-- Emotions
(N'relief', N'/rɪˈliːf/', N'sự nhẹ nhõm', N'noun', N'BEGINNER', N'Emotions', N'She felt relief when the exam ended.', N'Cô ấy cảm thấy nhẹ nhõm khi kỳ thi kết thúc.'),
(N'dread', N'/dred/', N'nỗi sợ hãi, lo sợ', N'noun', N'ADVANCED', N'Emotions', N'He felt dread before the interview.', N'Anh ấy cảm thấy lo sợ trước buổi phỏng vấn.'),
(N'bliss', N'/blɪs/', N'hạnh phúc tột độ', N'noun', N'ADVANCED', N'Emotions', N'Their wedding day was pure bliss.', N'Ngày cưới của họ là niềm hạnh phúc tột độ.'),
(N'irritation', N'/ˌɪrɪˈteɪʃən/', N'sự bực bội', N'noun', N'INTERMEDIATE', N'Emotions', N'The noise caused a lot of irritation.', N'Tiếng ồn gây ra rất nhiều sự bực bội.'),
(N'longing', N'/ˈlɔːŋɪŋ/', N'sự khao khát / nhớ mong', N'noun', N'ADVANCED', N'Emotions', N'She felt a longing for her hometown.', N'Cô ấy cảm thấy nhớ mong quê nhà.'),
(N'remorse', N'/rɪˈmɔːrs/', N'sự hối hận', N'noun', N'ADVANCED', N'Emotions', N'He showed remorse for his mistake.', N'Anh ấy thể hiện sự hối hận về lỗi lầm của mình.'),
(N'serenity', N'/səˈrenəti/', N'sự thanh thản, yên bình', N'noun', N'ADVANCED', N'Emotions', N'The lake gave a sense of serenity.', N'Hồ nước mang lại cảm giác thanh thản.'),
-- Food / Cooking
(N'dice', N'/daɪs/', N'cắt thành hạt lựu', N'verb', N'INTERMEDIATE', N'Food', N'Dice the onion before frying it.', N'Cắt hành thành hạt lựu trước khi chiên.'),
(N'mince', N'/mɪns/', N'băm nhỏ', N'verb', N'INTERMEDIATE', N'Food', N'Mince the garlic finely.', N'Băm nhỏ tỏi.'),
(N'whisk', N'/wɪsk/', N'đánh (trứng, kem)', N'verb', N'INTERMEDIATE', N'Food', N'Whisk the eggs until fluffy.', N'Đánh trứng cho đến khi bông xốp.'),
(N'drizzle', N'/ˈdrɪzl/', N'rưới nhẹ (nước sốt, dầu)', N'verb', N'ADVANCED', N'Food', N'Drizzle olive oil over the salad.', N'Rưới nhẹ dầu ô liu lên món salad.'),
(N'crispy', N'/ˈkrɪspi/', N'giòn', N'adjective', N'BEGINNER', N'Food', N'The fried chicken is very crispy.', N'Gà chiên rất giòn.'),
(N'bland', N'/blænd/', N'nhạt nhẽo (vị)', N'adjective', N'INTERMEDIATE', N'Food', N'The soup tastes a bit bland.', N'Món súp có vị hơi nhạt.'),
(N'savory', N'/ˈseɪvəri/', N'đậm đà, mặn', N'adjective', N'INTERMEDIATE', N'Food', N'I prefer savory snacks over sweet ones.', N'Tôi thích món ăn vặt mặn hơn là ngọt.'),
(N'appetizer', N'/ˈæpɪtaɪzər/', N'món khai vị', N'noun', N'BEGINNER', N'Food', N'We ordered spring rolls as an appetizer.', N'Chúng tôi gọi chả giò làm món khai vị.'),
(N'entree', N'/ˈɑːntreɪ/', N'món chính', N'noun', N'INTERMEDIATE', N'Food', N'The entree included grilled salmon.', N'Món chính bao gồm cá hồi nướng.'),
(N'beverage', N'/ˈbevərɪdʒ/', N'đồ uống', N'noun', N'BEGINNER', N'Food', N'Choose a beverage from the menu.', N'Hãy chọn một loại đồ uống trong thực đơn.'),
-- Travel
(N'stopover', N'/ˈstɑːpoʊvər/', N'điểm dừng chân giữa chuyến', N'noun', N'INTERMEDIATE', N'Travel', N'We had a stopover in Tokyo.', N'Chúng tôi có điểm dừng chân ở Tokyo.'),
(N'checkpoint', N'/ˈtʃekpɔɪnt/', N'trạm kiểm soát', N'noun', N'INTERMEDIATE', N'Travel', N'The bus stopped at a security checkpoint.', N'Xe buýt dừng lại tại một trạm kiểm soát an ninh.'),
(N'customs', N'/ˈkʌstəmz/', N'hải quan', N'noun', N'INTERMEDIATE', N'Travel', N'We went through customs quickly.', N'Chúng tôi qua hải quan rất nhanh.'),
(N'boarding pass', N'/ˈbɔːrdɪŋ pæs/', N'thẻ lên máy bay', N'noun', N'BEGINNER', N'Travel', N'Please show your boarding pass.', N'Vui lòng cho xem thẻ lên máy bay của bạn.'),
(N'jet lag', N'/dʒet læɡ/', N'hội chứng lệch giờ khi bay', N'noun', N'INTERMEDIATE', N'Travel', N'He felt tired from jet lag.', N'Anh ấy cảm thấy mệt vì lệch giờ khi bay.'),
(N'sightseeing', N'/ˈsaɪtsiːɪŋ/', N'tham quan ngắm cảnh', N'noun', N'BEGINNER', N'Travel', N'We spent the day sightseeing in the old town.', N'Chúng tôi dành cả ngày tham quan phố cổ.'),
(N'hitchhike', N'/ˈhɪtʃhaɪk/', N'đi nhờ xe', N'verb', N'ADVANCED', N'Travel', N'They hitchhiked across the country.', N'Họ đi nhờ xe khắp cả nước.'),
-- Language / Idioms
(N'break the ice', N'/breɪk ðə aɪs/', N'làm quen, xóa bỏ sự ngượng ngùng ban đầu', N'phrase', N'INTERMEDIATE', N'Language', N'He told a joke to break the ice.', N'Anh ấy kể một câu chuyện đùa để làm quen.'),
(N'hit the sack', N'/hɪt ðə sæk/', N'đi ngủ', N'phrase', N'INTERMEDIATE', N'Language', N'I am exhausted, time to hit the sack.', N'Tôi mệt quá rồi, đến giờ đi ngủ.'),
(N'under the weather', N'/ˈʌndər ðə ˈweðər/', N'cảm thấy không khỏe', N'phrase', N'INTERMEDIATE', N'Language', N'She felt under the weather this morning.', N'Sáng nay cô ấy cảm thấy không khỏe.'),
(N'spill the beans', N'/spɪl ðə biːnz/', N'tiết lộ bí mật', N'phrase', N'INTERMEDIATE', N'Language', N'He accidentally spilled the beans about the party.', N'Anh ấy vô tình làm lộ bí mật về buổi tiệc.'),
(N'piece of cake', N'/piːs əv keɪk/', N'việc dễ như ăn kẹo', N'phrase', N'BEGINNER', N'Language', N'The test was a piece of cake.', N'Bài kiểm tra dễ như ăn kẹo.'),
(N'cost an arm and a leg', N'/kɒst ən ɑːrm ənd ə leɡ/', N'rất đắt đỏ', N'phrase', N'ADVANCED', N'Language', N'That new phone cost an arm and a leg.', N'Chiếc điện thoại mới đó rất đắt đỏ.'),
(N'call it a day', N'/kɔːl ɪt ə deɪ/', N'dừng công việc lại vì hôm nay', N'phrase', N'INTERMEDIATE', N'Language', N'Let us call it a day and finish tomorrow.', N'Hãy dừng lại hôm nay và hoàn thành vào ngày mai.'),
(N'bite the bullet', N'/baɪt ðə ˈbʊlɪt/', N'chấp nhận điều khó khăn', N'phrase', N'ADVANCED', N'Language', N'She had to bite the bullet and accept the loss.', N'Cô ấy phải chấp nhận điều khó khăn và chịu mất mát.'),
-- Home
(N'thermostat', N'/ˈθɜːrməstæt/', N'bộ điều nhiệt', N'noun', N'INTERMEDIATE', N'Home', N'Adjust the thermostat to save energy.', N'Điều chỉnh bộ điều nhiệt để tiết kiệm năng lượng.'),
(N'skylight', N'/ˈskaɪlaɪt/', N'cửa sổ trên mái', N'noun', N'ADVANCED', N'Home', N'The skylight lets in natural light.', N'Cửa sổ trên mái cho ánh sáng tự nhiên chiếu vào.'),
(N'veranda', N'/vəˈrændə/', N'hiên nhà', N'noun', N'INTERMEDIATE', N'Home', N'They relaxed on the veranda in the evening.', N'Họ nghỉ ngơi trên hiên nhà vào buổi tối.'),
(N'utensil', N'/juːˈtensl/', N'dụng cụ nhà bếp', N'noun', N'INTERMEDIATE', N'Home', N'Wash the kitchen utensils after cooking.', N'Rửa các dụng cụ nhà bếp sau khi nấu ăn.'),
(N'detergent', N'/dɪˈtɜːrdʒənt/', N'chất tẩy rửa', N'noun', N'INTERMEDIATE', N'Home', N'Use detergent to clean the dishes.', N'Dùng chất tẩy rửa để rửa bát đĩa.'),
(N'clutter', N'/ˈklʌtər/', N'sự lộn xộn, đồ đạc bừa bãi', N'noun', N'INTERMEDIATE', N'Home', N'She cleared the clutter from her desk.', N'Cô ấy dọn sạch đồ đạc lộn xộn trên bàn làm việc.'),
-- Time
(N'punctual', N'/ˈpʌŋktʃuəl/', N'đúng giờ', N'adjective', N'INTERMEDIATE', N'Time', N'He is always punctual for meetings.', N'Anh ấy luôn đúng giờ trong các cuộc họp.'),
(N'overdue', N'/ˌoʊvərˈduː/', N'quá hạn', N'adjective', N'INTERMEDIATE', N'Time', N'The library book is overdue.', N'Cuốn sách thư viện đã quá hạn.'),
(N'interim', N'/ˈɪntərɪm/', N'tạm thời', N'adjective', N'ADVANCED', N'Time', N'She was appointed as the interim manager.', N'Cô ấy được bổ nhiệm làm quản lý tạm thời.'),
(N'simultaneous', N'/ˌsaɪmlˈteɪniəs/', N'đồng thời', N'adjective', N'ADVANCED', N'Time', N'The two events happened simultaneously.', N'Hai sự kiện xảy ra đồng thời.'),
-- Social / Law
(N'custody', N'/ˈkʌstədi/', N'quyền nuôi con / sự giam giữ', N'noun', N'ADVANCED', N'Social', N'The mother was granted custody of the children.', N'Người mẹ được trao quyền nuôi con.'),
(N'felony', N'/ˈfeləni/', N'trọng tội', N'noun', N'ADVANCED', N'Social', N'He was charged with a felony.', N'Anh ta bị buộc tội trọng tội.'),
(N'misdemeanor', N'/ˌmɪsdɪˈmiːnər/', N'tội nhẹ', N'noun', N'ADVANCED', N'Social', N'She was fined for a minor misdemeanor.', N'Cô ấy bị phạt vì một tội nhẹ.'),
(N'eyewitness', N'/ˈaɪwɪtnəs/', N'người làm chứng', N'noun', N'INTERMEDIATE', N'Social', N'The eyewitness described the accident clearly.', N'Người làm chứng mô tả vụ tai nạn rõ ràng.'),
(N'curfew', N'/ˈkɜːrfjuː/', N'lệnh giới nghiêm', N'noun', N'ADVANCED', N'Social', N'A curfew was imposed after the storm.', N'Lệnh giới nghiêm được áp đặt sau cơn bão.'),
-- Entertainment / Arts
(N'plot', N'/plɒt/', N'cốt truyện', N'noun', N'BEGINNER', N'Entertainment', N'The movie has an exciting plot.', N'Bộ phim có cốt truyện hấp dẫn.'),
(N'cliffhanger', N'/ˈklɪfhæŋər/', N'tình huống gay cấn treo lơ lửng', N'noun', N'ADVANCED', N'Entertainment', N'The episode ended with a cliffhanger.', N'Tập phim kết thúc với một tình huống gay cấn.'),
(N'blockbuster', N'/ˈblɑːkbʌstər/', N'tác phẩm ăn khách', N'noun', N'INTERMEDIATE', N'Entertainment', N'The film became a summer blockbuster.', N'Bộ phim trở thành tác phẩm ăn khách của mùa hè.'),
(N'soundtrack', N'/ˈsaʊndtræk/', N'nhạc phim', N'noun', N'BEGINNER', N'Entertainment', N'The soundtrack made the scene more emotional.', N'Nhạc phim khiến cảnh quay xúc động hơn.'),
(N'improvise', N'/ˈɪmprəvaɪz/', N'biểu diễn ngẫu hứng', N'verb', N'ADVANCED', N'Entertainment', N'The actors improvised the whole scene.', N'Các diễn viên diễn ngẫu hứng toàn bộ cảnh đó.'),
(N'rehearsal', N'/rɪˈhɜːrsəl/', N'buổi tập diễn', N'noun', N'INTERMEDIATE', N'Entertainment', N'The band has rehearsal every Friday.', N'Ban nhạc có buổi tập diễn vào mỗi thứ Sáu.'),
-- General / Abstract
(N'versatility', N'/ˌvɜːrsəˈtɪləti/', N'tính linh hoạt, đa năng', N'noun', N'ADVANCED', N'General', N'His versatility makes him valuable to the team.', N'Tính đa năng của anh ấy khiến anh trở nên giá trị với cả nhóm.'),
(N'scrutiny', N'/ˈskruːtəni/', N'sự xem xét kỹ lưỡng', N'noun', N'ADVANCED', N'General', N'The proposal is under close scrutiny.', N'Đề xuất đang được xem xét kỹ lưỡng.'),
(N'discrepancy', N'/dɪˈskrepənsi/', N'sự khác biệt / mâu thuẫn', N'noun', N'ADVANCED', N'General', N'There is a discrepancy in the report.', N'Có sự mâu thuẫn trong báo cáo.'),
(N'leeway', N'/ˈliːweɪ/', N'khoảng linh động, dư địa', N'noun', N'ADVANCED', N'General', N'The manager gave some leeway on deadlines.', N'Người quản lý cho phép một chút linh động về thời hạn.'),
(N'loophole', N'/ˈluːphoʊl/', N'lỗ hổng (luật, quy định)', N'noun', N'ADVANCED', N'General', N'They found a loophole in the contract.', N'Họ tìm ra lỗ hổng trong hợp đồng.'),
(N'milestone', N'/ˈmaɪlstoʊn/', N'cột mốc quan trọng', N'noun', N'INTERMEDIATE', N'General', N'Graduating was a major milestone for her.', N'Tốt nghiệp là một cột mốc quan trọng đối với cô ấy.'),
(N'threshold', N'/ˈθreʃhoʊld/', N'ngưỡng', N'noun', N'ADVANCED', N'General', N'The pain threshold varies from person to person.', N'Ngưỡng chịu đau khác nhau ở mỗi người.'),
(N'incentive', N'/ɪnˈsentɪv/', N'động lực khuyến khích', N'noun', N'INTERMEDIATE', N'General', N'The company offers incentives for good performance.', N'Công ty đưa ra động lực khuyến khích cho hiệu suất tốt.'),
(N'drawback', N'/ˈdrɔːbæk/', N'hạn chế / nhược điểm', N'noun', N'INTERMEDIATE', N'General', N'The plan has one major drawback.', N'Kế hoạch có một nhược điểm lớn.'),
(N'mundane', N'/mʌnˈdeɪn/', N'tầm thường, nhàm chán', N'adjective', N'ADVANCED', N'General', N'He was tired of the mundane routine.', N'Anh ấy chán ngán với thói quen nhàm chán.'),
(N'exquisite', N'/ɪkˈskwɪzɪt/', N'tinh tế, tuyệt đẹp', N'adjective', N'ADVANCED', N'Descriptive', N'The dress was made of exquisite silk.', N'Chiếc váy được làm từ lụa tinh tế.'),
(N'immaculate', N'/ɪˈmækjələt/', N'hoàn hảo, sạch sẽ tuyệt đối', N'adjective', N'ADVANCED', N'Descriptive', N'The house was kept immaculate.', N'Ngôi nhà được giữ sạch sẽ hoàn hảo.'),
(N'pristine', N'/ˈprɪstiːn/', N'nguyên sơ, sạch đẹp như mới', N'adjective', N'ADVANCED', N'Descriptive', N'The beach was pristine and untouched.', N'Bãi biển nguyên sơ và chưa bị tác động.'),
(N'vibrant', N'/ˈvaɪbrənt/', N'sống động, rực rỡ', N'adjective', N'INTERMEDIATE', N'Descriptive', N'The market was full of vibrant colors.', N'Chợ tràn ngập những màu sắc sống động.'),
(N'dreary', N'/ˈdrɪri/', N'buồn tẻ, ảm đạm', N'adjective', N'ADVANCED', N'Descriptive', N'It was a dreary, rainy afternoon.', N'Đó là một buổi chiều mưa buồn tẻ.'),
-- People
(N'sibling', N'/ˈsɪblɪŋ/', N'anh chị em ruột', N'noun', N'BEGINNER', N'People', N'She has two siblings.', N'Cô ấy có hai anh chị em.'),
(N'widow', N'/ˈwɪdoʊ/', N'người phụ nữ có chồng đã mất', N'noun', N'INTERMEDIATE', N'People', N'The widow raised her children alone.', N'Người phụ nữ đó nuôi con một mình sau khi chồng mất.'),
(N'widower', N'/ˈwɪdoʊər/', N'người đàn ông có vợ đã mất', N'noun', N'INTERMEDIATE', N'People', N'He became a widower last year.', N'Anh ấy trở thành người mất vợ vào năm ngoái.'),
(N'toddler', N'/ˈtɑːdlər/', N'trẻ mới biết đi', N'noun', N'BEGINNER', N'People', N'The toddler took her first steps.', N'Đứa trẻ mới biết đi đã đi những bước đầu tiên.'),
(N'newborn', N'/ˈnuːbɔːrn/', N'trẻ sơ sinh', N'noun', N'BEGINNER', N'People', N'The newborn slept most of the day.', N'Trẻ sơ sinh ngủ hầu hết cả ngày.'),
(N'stepmother', N'/ˈstepmʌðər/', N'mẹ kế', N'noun', N'BEGINNER', N'People', N'His stepmother is very kind to him.', N'Mẹ kế của anh ấy rất tốt với anh.'),
(N'stepfather', N'/ˈstepfɑːðər/', N'cha dượng', N'noun', N'BEGINNER', N'People', N'Her stepfather taught her how to drive.', N'Cha dượng dạy cô ấy lái xe.'),
-- Animals
(N'herbivore', N'/ˈhɜːrbɪvɔːr/', N'động vật ăn cỏ', N'noun', N'ADVANCED', N'Animals', N'Cows are herbivores.', N'Bò là động vật ăn cỏ.'),
(N'carnivore', N'/ˈkɑːrnɪvɔːr/', N'động vật ăn thịt', N'noun', N'ADVANCED', N'Animals', N'Lions are carnivores.', N'Sư tử là động vật ăn thịt.'),
(N'omnivore', N'/ˈɑːmnɪvɔːr/', N'động vật ăn tạp', N'noun', N'ADVANCED', N'Animals', N'Bears are omnivores that eat both plants and meat.', N'Gấu là động vật ăn tạp, ăn cả thực vật và thịt.'),
(N'mammal', N'/ˈmæml/', N'động vật có vú', N'noun', N'INTERMEDIATE', N'Animals', N'Whales are the largest mammals.', N'Cá voi là loài động vật có vú lớn nhất.'),
(N'reptile', N'/ˈreptaɪl/', N'động vật bò sát', N'noun', N'INTERMEDIATE', N'Animals', N'Snakes and lizards are reptiles.', N'Rắn và thằn lằn là động vật bò sát.'),
(N'hibernate', N'/ˈhaɪbərneɪt/', N'ngủ đông', N'verb', N'ADVANCED', N'Animals', N'Bears hibernate during the winter.', N'Gấu ngủ đông vào mùa đông.'),
(N'herd', N'/hɜːrd/', N'bầy (gia súc)', N'noun', N'INTERMEDIATE', N'Animals', N'A herd of elephants crossed the river.', N'Một bầy voi vượt qua sông.'),
(N'flock', N'/flɒk/', N'bầy (chim, cừu)', N'noun', N'INTERMEDIATE', N'Animals', N'A flock of sheep grazed on the hill.', N'Một bầy cừu ăn cỏ trên đồi.'),
-- Body
(N'pupil', N'/ˈpjuːpl/', N'con ngươi (mắt)', N'noun', N'INTERMEDIATE', N'Body', N'The pupil widens in dim light.', N'Con ngươi giãn ra trong ánh sáng yếu.'),
(N'joint', N'/dʒɔɪnt/', N'khớp xương', N'noun', N'INTERMEDIATE', N'Body', N'Her knee joint hurts when she runs.', N'Khớp gối của cô ấy bị đau khi chạy.'),
(N'tendon', N'/ˈtendən/', N'gân', N'noun', N'ADVANCED', N'Body', N'He injured a tendon while playing football.', N'Anh ấy bị chấn thương gân khi chơi bóng đá.'),
(N'nerve', N'/nɜːrv/', N'dây thần kinh', N'noun', N'INTERMEDIATE', N'Body', N'The nerve sends signals to the brain.', N'Dây thần kinh gửi tín hiệu đến não.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('merger','acquisition','entrepreneur','franchise','turnover','warranty','refund','wholesale','retail','procurement','logistics','inventory','startup','lucrative','chatbot','biometric','wearable','streaming','subscription','firmware','glitch','crash','backup','synchronize','cloud storage','phishing','spyware','enzyme','hormone','microorganism','mutation','precipitation','condensation','evaporation','sediment','electron','isotope','spectrum','antidote','sedative','inflammation','immunity','cholesterol','dehydration','malnutrition','relapse','remission','checkup','wildfire','sinkhole','permafrost','canopy','undergrowth','thaw','migratory','predator','prey','tactful','blunt','eccentric','gullible','assertive','timid','arrogant','humorous','stingy','considerate','relief','dread','bliss','irritation','longing','remorse','serenity','dice','mince','whisk','drizzle','crispy','bland','savory','appetizer','entree','beverage','stopover','checkpoint','customs','boarding pass','jet lag','sightseeing','hitchhike','break the ice','hit the sack','under the weather','spill the beans','piece of cake','cost an arm and a leg','call it a day','bite the bullet','thermostat','skylight','veranda','utensil','detergent','clutter','punctual','overdue','interim','simultaneous','custody','felony','misdemeanor','eyewitness','curfew','plot','cliffhanger','blockbuster','soundtrack','improvise','rehearsal','versatility','scrutiny','discrepancy','leeway','loophole','milestone','threshold','incentive','drawback','mundane','exquisite','immaculate','pristine','vibrant','dreary','sibling','widow','widower','toddler','newborn','stepmother','stepfather','herbivore','carnivore','omnivore','mammal','reptile','hibernate','herd','flock','pupil','joint','tendon','nerve');
