--liquibase formatted sql

--changeset vocab:063-seed-words-batch55
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.category, v.example_sentence, v.example_translation
FROM (VALUES
-- Geography / Nature
(N'gale', N'/ɡeɪl/', N'gió mạnh', N'noun', N'ADVANCED', N'Nature', N'A gale knocked down several trees.', N'Một trận gió mạnh đã làm đổ nhiều cây.'),
(N'hailstorm', N'/ˈheɪlstɔːrm/', N'mưa đá', N'noun', N'ADVANCED', N'Nature', N'The hailstorm damaged the crops.', N'Trận mưa đá đã làm hỏng vụ mùa.'),
(N'overcast', N'/ˈoʊvərkæst/', N'nhiều mây, âm u', N'adjective', N'INTERMEDIATE', N'Nature', N'The sky was overcast all morning.', N'Trời nhiều mây suốt cả buổi sáng.'),
(N'barometer', N'/bəˈrɑːmɪtər/', N'áp kế', N'noun', N'ADVANCED', N'Science', N'The barometer shows falling pressure.', N'Áp kế cho thấy áp suất đang giảm.'),
(N'altitude', N'/ˈæltɪtuːd/', N'độ cao', N'noun', N'INTERMEDIATE', N'Nature', N'The plane is flying at high altitude.', N'Máy bay đang bay ở độ cao lớn.'),
(N'archipelago', N'/ˌɑːrkəˈpeləɡoʊ/', N'quần đảo', N'noun', N'ADVANCED', N'Places', N'Indonesia is a vast archipelago.', N'Indonesia là một quần đảo rộng lớn.'),
(N'topography', N'/təˈpɑːɡrəfi/', N'địa hình', N'noun', N'ADVANCED', N'Places', N'The map shows the topography of the region.', N'Bản đồ cho thấy địa hình của khu vực.'),
(N'floodplain', N'/ˈflʌdpleɪn/', N'đồng bằng ngập lũ', N'noun', N'ADVANCED', N'Nature', N'Houses on the floodplain often flood.', N'Nhà trên đồng bằng ngập lũ thường bị ngập nước.'),
(N'humidity', N'/hjuːˈmɪdəti/', N'độ ẩm', N'noun', N'INTERMEDIATE', N'Nature', N'The humidity is very high in summer.', N'Độ ẩm rất cao vào mùa hè.'),
(N'shoreline', N'/ˈʃɔːrlaɪn/', N'đường bờ biển', N'noun', N'INTERMEDIATE', N'Places', N'They walked along the shoreline.', N'Họ đi bộ dọc theo đường bờ biển.'),
(N'headland', N'/ˈhedlænd/', N'mũi đất nhô ra biển', N'noun', N'ADVANCED', N'Places', N'A lighthouse stands on the headland.', N'Một ngọn hải đăng đứng trên mũi đất.'),
(N'lagoon', N'/ləˈɡuːn/', N'đầm phá', N'noun', N'INTERMEDIATE', N'Places', N'The lagoon is calm and shallow.', N'Đầm phá yên tĩnh và nông.'),
(N'dune', N'/duːn/', N'đồi cát', N'noun', N'INTERMEDIATE', N'Nature', N'Children played on the sand dunes.', N'Trẻ em chơi trên những đồi cát.'),
(N'crater', N'/ˈkreɪtər/', N'miệng núi lửa / hố lớn', N'noun', N'INTERMEDIATE', N'Nature', N'The volcano has a deep crater.', N'Núi lửa có một miệng hố sâu.'),
(N'bedrock', N'/ˈbedrɑːk/', N'đá nền', N'noun', N'ADVANCED', N'Science', N'The building is anchored to the bedrock.', N'Tòa nhà được cố định vào lớp đá nền.'),
-- Music / Arts
(N'lyrics', N'/ˈlɪrɪks/', N'lời bài hát', N'noun', N'BEGINNER', N'Entertainment', N'She wrote the lyrics for the song.', N'Cô ấy viết lời cho bài hát.'),
(N'ballad', N'/ˈbæləd/', N'bản ballad, bài hát trữ tình', N'noun', N'INTERMEDIATE', N'Entertainment', N'He sang a slow, romantic ballad.', N'Anh ấy hát một bản ballad lãng mạn, chậm rãi.'),
(N'ensemble', N'/ɑːnˈsɑːmbl/', N'nhóm nhạc, hòa tấu', N'noun', N'ADVANCED', N'Entertainment', N'The ensemble performed beautifully together.', N'Nhóm nhạc trình diễn cùng nhau rất tuyệt.'),
(N'percussion', N'/pərˈkʌʃən/', N'bộ gõ (nhạc cụ)', N'noun', N'INTERMEDIATE', N'Entertainment', N'Drums belong to the percussion family.', N'Trống thuộc nhóm nhạc cụ bộ gõ.'),
(N'tempo', N'/ˈtempoʊ/', N'nhịp độ (âm nhạc)', N'noun', N'INTERMEDIATE', N'Entertainment', N'The song has a fast tempo.', N'Bài hát có nhịp độ nhanh.'),
(N'choir', N'/ˈkwaɪər/', N'ban hợp xướng', N'noun', N'INTERMEDIATE', N'Entertainment', N'She sings in the church choir.', N'Cô ấy hát trong ban hợp xướng nhà thờ.'),
(N'album', N'/ˈælbəm/', N'album nhạc', N'noun', N'BEGINNER', N'Entertainment', N'The band released a new album.', N'Ban nhạc đã phát hành một album mới.'),
(N'masterpiece', N'/ˈmæstərpiːs/', N'tác phẩm kiệt xuất', N'noun', N'INTERMEDIATE', N'Entertainment', N'This painting is considered a masterpiece.', N'Bức tranh này được xem là một kiệt tác.'),
(N'sketch', N'/sketʃ/', N'bản vẽ nhanh, phác thảo', N'noun', N'INTERMEDIATE', N'Entertainment', N'He made a quick sketch of the building.', N'Anh ấy phác thảo nhanh tòa nhà.'),
(N'calligraphy', N'/kəˈlɪɡrəfi/', N'thư pháp', N'noun', N'ADVANCED', N'Entertainment', N'She practices Chinese calligraphy every day.', N'Cô ấy luyện thư pháp Trung Hoa mỗi ngày.'),
-- Sports
(N'sprint', N'/sprɪnt/', N'chạy nước rút', N'verb', N'INTERMEDIATE', N'General', N'He sprinted to catch the bus.', N'Anh ấy chạy nước rút để bắt kịp xe buýt.'),
(N'tackle', N'/ˈtækl/', N'tranh bóng / xử lý', N'verb', N'INTERMEDIATE', N'General', N'The defender tackled the striker.', N'Cầu thủ hậu vệ tranh bóng với tiền đạo.'),
(N'dribble', N'/ˈdrɪbl/', N'dẫn bóng', N'verb', N'INTERMEDIATE', N'General', N'He dribbled past two defenders.', N'Anh ấy dẫn bóng qua hai hậu vệ.'),
(N'penalty', N'/ˈpenəlti/', N'quả phạt, hình phạt', N'noun', N'INTERMEDIATE', N'General', N'The team scored from a penalty.', N'Đội bóng ghi điểm từ quả phạt.'),
(N'spectator', N'/spekˈteɪtər/', N'khán giả', N'noun', N'INTERMEDIATE', N'General', N'Thousands of spectators filled the stadium.', N'Hàng nghìn khán giả lấp đầy sân vận động.'),
(N'undefeated', N'/ˌʌndɪˈfiːtɪd/', N'bất bại', N'adjective', N'ADVANCED', N'General', N'The team remained undefeated all season.', N'Đội bóng vẫn bất bại suốt cả mùa giải.'),
(N'underdog', N'/ˈʌndərdɔːɡ/', N'kẻ yếu thế', N'noun', N'ADVANCED', N'General', N'The underdog surprised everyone with the win.', N'Kẻ yếu thế đã khiến mọi người bất ngờ với chiến thắng.'),
(N'substitute', N'/ˈsʌbstɪtuːt/', N'người/vật thay thế', N'noun', N'INTERMEDIATE', N'General', N'The coach sent in a substitute player.', N'Huấn luyện viên đưa vào một cầu thủ dự bị.'),
(N'qualify', N'/ˈkwɑːlɪfaɪ/', N'đủ điều kiện, vượt qua vòng loại', N'verb', N'INTERMEDIATE', N'General', N'The team qualified for the final round.', N'Đội bóng đã vượt qua vòng loại vào vòng chung kết.'),
(N'medalist', N'/ˈmedəlɪst/', N'người đạt huy chương', N'noun', N'INTERMEDIATE', N'General', N'She is an Olympic gold medalist.', N'Cô ấy là người đạt huy chương vàng Olympic.'),
-- Politics / Law
(N'constituency', N'/kənˈstɪtʃuənsi/', N'khu vực cử tri', N'noun', N'ADVANCED', N'Politics', N'The senator represents a large constituency.', N'Thượng nghị sĩ đại diện cho một khu vực cử tri lớn.'),
(N'referendum', N'/ˌrefəˈrendəm/', N'trưng cầu dân ý', N'noun', N'ADVANCED', N'Politics', N'The country held a referendum on independence.', N'Đất nước đã tổ chức trưng cầu dân ý về độc lập.'),
(N'legislature', N'/ˈledʒɪsleɪtʃər/', N'cơ quan lập pháp', N'noun', N'ADVANCED', N'Politics', N'The legislature passed the new law.', N'Cơ quan lập pháp đã thông qua luật mới.'),
(N'incumbent', N'/ɪnˈkʌmbənt/', N'người đang tại vị', N'noun', N'ADVANCED', N'Politics', N'The incumbent lost the election.', N'Người đang tại vị đã thất bại trong cuộc bầu cử.'),
(N'autocracy', N'/ɔːˈtɑːkrəsi/', N'chế độ chuyên quyền', N'noun', N'ADVANCED', N'Politics', N'The country slowly became an autocracy.', N'Đất nước dần trở thành một chế độ chuyên quyền.'),
(N'lobbying', N'/ˈlɑːbiɪŋ/', N'vận động hành lang', N'noun', N'ADVANCED', N'Politics', N'Lobbying influences many government decisions.', N'Vận động hành lang ảnh hưởng đến nhiều quyết định của chính phủ.'),
(N'manifesto', N'/ˌmænɪˈfestoʊ/', N'tuyên ngôn, cương lĩnh', N'noun', N'ADVANCED', N'Politics', N'The party released its election manifesto.', N'Đảng đã công bố cương lĩnh bầu cử của mình.'),
(N'subpoena', N'/səˈpiːnə/', N'lệnh triệu tập ra tòa', N'noun', N'ADVANCED', N'Social', N'The witness received a subpoena.', N'Người làm chứng đã nhận được lệnh triệu tập ra tòa.'),
(N'acquittal', N'/əˈkwɪtl/', N'sự tuyên bố vô tội', N'noun', N'ADVANCED', N'Social', N'The jury reached an acquittal.', N'Bồi thẩm đoàn đã tuyên bố vô tội.'),
(N'indictment', N'/ɪnˈdaɪtmənt/', N'bản cáo trạng', N'noun', N'ADVANCED', N'Social', N'He faces a serious indictment.', N'Anh ta đối mặt với một bản cáo trạng nghiêm trọng.'),
(N'litigant', N'/ˈlɪtɪɡənt/', N'bên tham gia tố tụng', N'noun', N'ADVANCED', N'Social', N'Both litigants presented their evidence.', N'Cả hai bên tố tụng đã trình bày chứng cứ của mình.'),
(N'statute', N'/ˈstætʃuːt/', N'đạo luật', N'noun', N'ADVANCED', N'Social', N'The statute was amended last year.', N'Đạo luật đã được sửa đổi vào năm ngoái.'),
(N'embezzlement', N'/ɪmˈbezlmənt/', N'tội tham ô', N'noun', N'ADVANCED', N'Social', N'He was arrested for embezzlement.', N'Anh ta bị bắt vì tội tham ô.'),
(N'perjury', N'/ˈpɜːrdʒəri/', N'tội khai man', N'noun', N'ADVANCED', N'Social', N'She was charged with perjury.', N'Cô ấy bị buộc tội khai man.'),
(N'arbitrator', N'/ˈɑːrbɪtreɪtər/', N'người trọng tài phân xử', N'noun', N'ADVANCED', N'Social', N'An arbitrator settled the dispute.', N'Một người trọng tài đã giải quyết tranh chấp.'),
-- Finance
(N'installment', N'/ɪnˈstɔːlmənt/', N'khoản trả góp', N'noun', N'INTERMEDIATE', N'Business', N'She pays for the car in monthly installments.', N'Cô ấy trả góp tiền mua xe hàng tháng.'),
(N'premium', N'/ˈpriːmiəm/', N'phí bảo hiểm / khoản phụ thêm', N'noun', N'INTERMEDIATE', N'Business', N'The insurance premium increased this year.', N'Phí bảo hiểm đã tăng trong năm nay.'),
(N'overdraft', N'/ˈoʊvərdræft/', N'sự thấu chi', N'noun', N'ADVANCED', N'Business', N'He had to pay an overdraft fee.', N'Anh ấy phải trả phí thấu chi.'),
(N'remittance', N'/rɪˈmɪtəns/', N'tiền gửi về, chuyển khoản', N'noun', N'ADVANCED', N'Business', N'She sends a remittance to her family monthly.', N'Cô ấy gửi tiền về cho gia đình mỗi tháng.'),
(N'escrow', N'/ˈeskroʊ/', N'tài khoản ký quỹ', N'noun', N'ADVANCED', N'Business', N'The deposit is held in escrow.', N'Tiền đặt cọc được giữ trong tài khoản ký quỹ.'),
(N'depreciate', N'/dɪˈpriːʃieɪt/', N'mất giá, khấu hao', N'verb', N'ADVANCED', N'Business', N'Cars depreciate quickly after purchase.', N'Xe hơi mất giá nhanh sau khi mua.'),
(N'principal', N'/ˈprɪnsəpəl/', N'vốn gốc (tài chính)', N'noun', N'ADVANCED', N'Business', N'You must repay the principal plus interest.', N'Bạn phải trả cả vốn gốc và tiền lãi.'),
(N'yield', N'/jiːld/', N'lợi suất, sản lượng', N'noun', N'ADVANCED', N'Business', N'The bond offers a high yield.', N'Trái phiếu này có lợi suất cao.'),
(N'arrears', N'/əˈrɪrz/', N'nợ quá hạn', N'noun', N'ADVANCED', N'Business', N'The tenant is in arrears on rent.', N'Người thuê nhà đang nợ tiền thuê quá hạn.'),
(N'solvency', N'/ˈsɑːlvənsi/', N'khả năng thanh toán nợ', N'noun', N'ADVANCED', N'Business', N'The audit confirmed the company solvency.', N'Cuộc kiểm toán xác nhận khả năng thanh toán nợ của công ty.'),
(N'underwrite', N'/ˈʌndəraɪt/', N'bảo lãnh phát hành', N'verb', N'ADVANCED', N'Business', N'The bank agreed to underwrite the loan.', N'Ngân hàng đồng ý bảo lãnh khoản vay.'),
(N'windfall', N'/ˈwɪndfɔːl/', N'khoản lợi bất ngờ', N'noun', N'ADVANCED', N'Business', N'The inheritance was a financial windfall.', N'Khoản thừa kế là một món lợi tài chính bất ngờ.'),
(N'nest egg', N'/nest eɡ/', N'tiền tiết kiệm dự phòng', N'noun', N'INTERMEDIATE', N'Business', N'They saved a nest egg for retirement.', N'Họ tiết kiệm một khoản dự phòng cho lúc nghỉ hưu.'),
(N'paycheck', N'/ˈpeɪtʃek/', N'tiền lương', N'noun', N'BEGINNER', N'Business', N'He spends his paycheck carefully.', N'Anh ấy chi tiêu tiền lương một cách cẩn thận.'),
-- Relationships / Communication
(N'rapport', N'/ræˈpɔːr/', N'sự gắn kết, thiện cảm', N'noun', N'ADVANCED', N'Social', N'The teacher built rapport with her students.', N'Giáo viên đã xây dựng sự gắn kết với học sinh.'),
(N'reconcile', N'/ˈrekənsaɪl/', N'hòa giải', N'verb', N'ADVANCED', N'Social', N'The two brothers finally reconciled.', N'Hai anh em cuối cùng đã hòa giải.'),
(N'estranged', N'/ɪˈstreɪndʒd/', N'xa cách, ly thân', N'adjective', N'ADVANCED', N'Social', N'She is estranged from her father.', N'Cô ấy đã xa cách với cha mình.'),
(N'confide', N'/kənˈfaɪd/', N'tâm sự, chia sẻ tin tưởng', N'verb', N'INTERMEDIATE', N'Social', N'She confided her secret to a friend.', N'Cô ấy tâm sự bí mật của mình với một người bạn.'),
(N'betray', N'/bɪˈtreɪ/', N'phản bội', N'verb', N'INTERMEDIATE', N'Social', N'He felt betrayed by his best friend.', N'Anh ấy cảm thấy bị bạn thân phản bội.'),
(N'loyalty', N'/ˈlɔɪəlti/', N'sự trung thành', N'noun', N'INTERMEDIATE', N'Social', N'Loyalty is important in friendship.', N'Sự trung thành rất quan trọng trong tình bạn.'),
(N'intimacy', N'/ˈɪntɪməsi/', N'sự thân mật, gần gũi', N'noun', N'ADVANCED', N'Social', N'They shared a deep intimacy.', N'Họ có một sự gần gũi sâu sắc.'),
(N'mutual', N'/ˈmjuːtʃuəl/', N'qua lại, lẫn nhau', N'adjective', N'INTERMEDIATE', N'Social', N'They have mutual respect for each other.', N'Họ có sự tôn trọng lẫn nhau.'),
(N'bond', N'/bɑːnd/', N'mối liên kết', N'noun', N'INTERMEDIATE', N'Social', N'They formed a strong bond over the years.', N'Họ đã tạo dựng một mối liên kết chặt chẽ qua nhiều năm.'),
(N'courtship', N'/ˈkɔːrtʃɪp/', N'thời gian tìm hiểu trước hôn nhân', N'noun', N'ADVANCED', N'Social', N'Their courtship lasted two years.', N'Thời gian tìm hiểu của họ kéo dài hai năm.'),
(N'reunion', N'/riˈjuːnjən/', N'buổi họp mặt lại', N'noun', N'INTERMEDIATE', N'Social', N'The family reunion was held every summer.', N'Buổi họp mặt gia đình được tổ chức mỗi mùa hè.'),
(N'condolence', N'/kənˈdoʊləns/', N'lời chia buồn', N'noun', N'ADVANCED', N'Social', N'He offered his condolences to the family.', N'Anh ấy gửi lời chia buồn đến gia đình.'),
(N'eloquence', N'/ˈeləkwəns/', N'tài hùng biện, ăn nói', N'noun', N'ADVANCED', N'Language', N'Her eloquence impressed the audience.', N'Tài hùng biện của cô ấy đã gây ấn tượng với khán giả.'),
(N'paraphrase', N'/ˈpærəfreɪz/', N'diễn giải lại bằng lời khác', N'verb', N'ADVANCED', N'Language', N'Please paraphrase the passage in your own words.', N'Hãy diễn giải lại đoạn văn bằng lời của bạn.'),
(N'concise', N'/kənˈsaɪs/', N'ngắn gọn, súc tích', N'adjective', N'INTERMEDIATE', N'Language', N'Keep your answer clear and concise.', N'Hãy giữ câu trả lời rõ ràng và ngắn gọn.'),
-- Food / Cooking
(N'baste', N'/beɪst/', N'rưới nước sốt khi nướng', N'verb', N'ADVANCED', N'Food', N'Baste the turkey every twenty minutes.', N'Rưới nước sốt lên gà tây mỗi hai mươi phút.'),
(N'knead', N'/niːd/', N'nhào (bột)', N'verb', N'INTERMEDIATE', N'Food', N'Knead the dough until it is smooth.', N'Nhào bột cho đến khi mịn.'),
(N'marinate', N'/ˈmærɪneɪt/', N'ướp gia vị', N'verb', N'INTERMEDIATE', N'Food', N'Marinate the chicken overnight.', N'Ướp gà qua đêm.'),
(N'saute', N'/soʊˈteɪ/', N'xào với ít dầu', N'verb', N'INTERMEDIATE', N'Food', N'Saute the onions until golden.', N'Xào hành đến khi vàng.'),
(N'poach', N'/poʊtʃ/', N'chần, luộc nhẹ', N'verb', N'ADVANCED', N'Food', N'Poach the eggs for three minutes.', N'Chần trứng trong ba phút.'),
(N'tender', N'/ˈtendər/', N'mềm (thịt)', N'adjective', N'INTERMEDIATE', N'Food', N'The meat was tender and juicy.', N'Thịt mềm và mọng nước.'),
(N'stale', N'/steɪl/', N'để lâu, không còn tươi', N'adjective', N'INTERMEDIATE', N'Food', N'The bread has gone stale.', N'Bánh mì đã bị cứng và không còn tươi.'),
(N'rancid', N'/ˈrænsɪd/', N'bị ôi, có mùi hôi', N'adjective', N'ADVANCED', N'Food', N'The oil smelled rancid.', N'Dầu có mùi hôi khó chịu.'),
(N'wholesome', N'/ˈhoʊlsəm/', N'bổ dưỡng, lành mạnh', N'adjective', N'INTERMEDIATE', N'Food', N'They eat wholesome home-cooked meals.', N'Họ ăn những bữa ăn tự nấu lành mạnh.'),
(N'delicacy', N'/ˈdelɪkəsi/', N'món ăn đặc sản, cao cấp', N'noun', N'ADVANCED', N'Food', N'Caviar is considered a rare delicacy.', N'Trứng cá tầm được xem là món đặc sản hiếm.'),
(N'condiment', N'/ˈkɑːndɪmənt/', N'gia vị kèm theo', N'noun', N'INTERMEDIATE', N'Food', N'Ketchup is a popular condiment.', N'Tương cà là một loại gia vị kèm phổ biến.'),
(N'staple food', N'/ˈsteɪpl fuːd/', N'lương thực chính', N'noun', N'INTERMEDIATE', N'Food', N'Rice is the staple food in Vietnam.', N'Gạo là lương thực chính ở Việt Nam.'),
(N'palate', N'/ˈpælət/', N'vị giác, khẩu vị', N'noun', N'ADVANCED', N'Food', N'The chef has a refined palate.', N'Người bếp trưởng có khẩu vị tinh tế.'),
(N'crumb', N'/krʌm/', N'vụn bánh mì', N'noun', N'BEGINNER', N'Food', N'There were crumbs all over the table.', N'Có vụn bánh mì trên khắp bàn.'),
(N'batter', N'/ˈbætər/', N'hỗn hợp bột nhão', N'noun', N'INTERMEDIATE', N'Food', N'Dip the fish in batter before frying.', N'Nhúng cá vào bột nhão trước khi chiên.'),
-- Housing / Home
(N'tenant', N'/ˈtenənt/', N'người thuê nhà', N'noun', N'INTERMEDIATE', N'Home', N'The tenant pays rent every month.', N'Người thuê nhà trả tiền thuê mỗi tháng.'),
(N'landlord', N'/ˈlændlɔːrd/', N'chủ nhà cho thuê', N'noun', N'INTERMEDIATE', N'Home', N'The landlord fixed the broken pipe.', N'Chủ nhà đã sửa ống nước bị hỏng.'),
(N'lease', N'/liːs/', N'hợp đồng thuê', N'noun', N'INTERMEDIATE', N'Home', N'They signed a one-year lease.', N'Họ đã ký hợp đồng thuê một năm.'),
(N'eviction', N'/ɪˈvɪkʃən/', N'sự đuổi khỏi nhà thuê', N'noun', N'ADVANCED', N'Home', N'The eviction notice arrived last week.', N'Thông báo đuổi nhà đến vào tuần trước.'),
(N'deposit', N'/dɪˈpɑːzɪt/', N'tiền đặt cọc', N'noun', N'INTERMEDIATE', N'Home', N'We paid a deposit before moving in.', N'Chúng tôi đã trả tiền đặt cọc trước khi vào ở.'),
(N'duplex', N'/ˈduːpleks/', N'nhà đôi hai tầng', N'noun', N'ADVANCED', N'Home', N'They live in a duplex near the park.', N'Họ sống trong một căn nhà đôi gần công viên.'),
(N'studio apartment', N'/ˈstuːdioʊ əˈpɑːrtmənt/', N'căn hộ studio', N'noun', N'INTERMEDIATE', N'Home', N'He rents a small studio apartment downtown.', N'Anh ấy thuê một căn hộ studio nhỏ ở trung tâm thành phố.'),
(N'renovate', N'/ˈrenəveɪt/', N'cải tạo, sửa sang', N'verb', N'INTERMEDIATE', N'Home', N'They plan to renovate the old kitchen.', N'Họ có kế hoạch cải tạo nhà bếp cũ.'),
(N'dilapidated', N'/dɪˈlæpɪdeɪtɪd/', N'cũ nát, xuống cấp', N'adjective', N'ADVANCED', N'Home', N'The dilapidated house was finally torn down.', N'Ngôi nhà cũ nát cuối cùng đã bị phá bỏ.'),
(N'cozy', N'/ˈkoʊzi/', N'ấm cúng, thoải mái', N'adjective', N'BEGINNER', N'Home', N'The cabin felt warm and cozy.', N'Căn nhà gỗ cảm giác ấm áp và cozy.'),
-- General / Abstract
(N'hindsight', N'/ˈhaɪndsaɪt/', N'khả năng nhận ra sau khi việc đã xảy ra', N'noun', N'ADVANCED', N'General', N'In hindsight, we should have left earlier.', N'Nhìn lại, chúng ta nên rời đi sớm hơn.'),
(N'foresight', N'/ˈfɔːrsaɪt/', N'khả năng nhìn xa, dự đoán trước', N'noun', N'ADVANCED', N'General', N'Her foresight saved the company money.', N'Khả năng nhìn xa của cô ấy đã giúp công ty tiết kiệm tiền.'),
(N'autonomy', N'/ɔːˈtɑːnəmi/', N'quyền tự chủ', N'noun', N'ADVANCED', N'General', N'The region was granted more autonomy.', N'Khu vực được trao nhiều quyền tự chủ hơn.'),
(N'legitimacy', N'/lɪˈdʒɪtɪməsi/', N'tính hợp pháp, chính đáng', N'noun', N'ADVANCED', N'General', N'The election result lacked legitimacy.', N'Kết quả bầu cử thiếu tính chính đáng.'),
(N'redundant', N'/rɪˈdʌndənt/', N'dư thừa, thừa thãi', N'adjective', N'ADVANCED', N'General', N'The sentence had a redundant phrase.', N'Câu văn có một cụm từ thừa.'),
(N'plausible', N'/ˈplɔːzəbl/', N'có vẻ hợp lý, đáng tin', N'adjective', N'ADVANCED', N'General', N'His excuse sounded plausible.', N'Lời bào chữa của anh ấy nghe có vẻ hợp lý.'),
(N'arbitrary', N'/ˈɑːrbɪtreri/', N'tùy tiện, độc đoán', N'adjective', N'ADVANCED', N'General', N'The decision seemed arbitrary and unfair.', N'Quyết định có vẻ tùy tiện và không công bằng.'),
(N'inevitable', N'/ɪnˈevɪtəbl/', N'không thể tránh khỏi', N'adjective', N'ADVANCED', N'General', N'Change is inevitable in life.', N'Sự thay đổi là không thể tránh khỏi trong cuộc sống.'),
(N'tangible', N'/ˈtændʒəbl/', N'hữu hình, cụ thể', N'adjective', N'ADVANCED', N'General', N'We need tangible proof of progress.', N'Chúng ta cần bằng chứng cụ thể về tiến độ.'),
(N'intangible', N'/ɪnˈtændʒəbl/', N'vô hình', N'adjective', N'ADVANCED', N'General', N'Trust is an intangible but vital asset.', N'Niềm tin là một tài sản vô hình nhưng thiết yếu.'),
(N'sporadic', N'/spəˈrædɪk/', N'lác đác, không liên tục', N'adjective', N'ADVANCED', N'General', N'There was sporadic rain throughout the day.', N'Có những cơn mưa lác đác suốt cả ngày.'),
(N'rampant', N'/ˈræmpənt/', N'lan rộng không kiểm soát', N'adjective', N'ADVANCED', N'General', N'Corruption was rampant in the region.', N'Tham nhũng lan rộng không kiểm soát trong khu vực.'),
(N'dormant', N'/ˈdɔːrmənt/', N'ngủ yên, không hoạt động', N'adjective', N'ADVANCED', N'General', N'The volcano has been dormant for centuries.', N'Núi lửa đã ngủ yên hàng thế kỷ.'),
(N'imminent', N'/ˈɪmɪnənt/', N'sắp xảy ra, cận kề', N'adjective', N'ADVANCED', N'General', N'A storm is imminent according to the forecast.', N'Một cơn bão sắp xảy ra theo dự báo.'),
(N'inherent', N'/ɪnˈhɪrənt/', N'vốn có, cố hữu', N'adjective', N'ADVANCED', N'General', N'There is an inherent risk in this plan.', N'Có một rủi ro cố hữu trong kế hoạch này.'),
(N'credible', N'/ˈkredəbl/', N'đáng tin cậy', N'adjective', N'INTERMEDIATE', N'General', N'She gave a credible explanation.', N'Cô ấy đưa ra một lời giải thích đáng tin cậy.'),
(N'feasible', N'/ˈfiːzəbl/', N'khả thi', N'adjective', N'ADVANCED', N'General', N'Is this plan financially feasible?', N'Kế hoạch này có khả thi về tài chính không?'),
(N'viable', N'/ˈvaɪəbl/', N'khả thi, có thể tồn tại được', N'adjective', N'ADVANCED', N'General', N'They need a viable business model.', N'Họ cần một mô hình kinh doanh khả thi.'),
(N'futile', N'/ˈfjuːtl/', N'vô ích, vô vọng', N'adjective', N'ADVANCED', N'General', N'His attempts to fix it were futile.', N'Những nỗ lực sửa chữa của anh ấy đều vô ích.'),
(N'relentless', N'/rɪˈlentləs/', N'không ngừng, kiên trì đến cùng', N'adjective', N'ADVANCED', N'General', N'She showed relentless determination.', N'Cô ấy thể hiện sự quyết tâm không ngừng nghỉ.'),
(N'meager', N'/ˈmiːɡər/', N'ít, nghèo nàn', N'adjective', N'ADVANCED', N'General', N'He survives on a meager salary.', N'Anh ấy sống với mức lương ít.'),
(N'abundant', N'/əˈbʌndənt/', N'dồi dào, phong phú', N'adjective', N'INTERMEDIATE', N'General', N'The region has abundant natural resources.', N'Khu vực này có nguồn tài nguyên thiên nhiên dồi dào.'),
(N'scarce', N'/skers/', N'khan hiếm', N'adjective', N'INTERMEDIATE', N'General', N'Clean water is scarce in the desert.', N'Nước sạch khan hiếm ở vùng sa mạc.'),
(N'ubiquitous', N'/juːˈbɪkwɪtəs/', N'có mặt ở khắp mọi nơi', N'adjective', N'ADVANCED', N'General', N'Smartphones are ubiquitous nowadays.', N'Điện thoại thông minh có mặt ở khắp mọi nơi ngày nay.'),
(N'innate', N'/ɪˈneɪt/', N'bẩm sinh, vốn có', N'adjective', N'ADVANCED', N'General', N'She has an innate talent for music.', N'Cô ấy có tài năng âm nhạc bẩm sinh.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('gale','hailstorm','overcast','barometer','altitude','archipelago','topography','floodplain','humidity','shoreline','headland','lagoon','dune','crater','bedrock','lyrics','ballad','ensemble','percussion','tempo','choir','album','masterpiece','sketch','calligraphy','sprint','tackle','dribble','penalty','spectator','undefeated','underdog','substitute','qualify','medalist','constituency','referendum','legislature','incumbent','autocracy','lobbying','manifesto','subpoena','acquittal','indictment','litigant','statute','embezzlement','perjury','arbitrator','installment','premium','overdraft','remittance','escrow','depreciate','principal','yield','arrears','solvency','underwrite','windfall','nest egg','paycheck','rapport','reconcile','estranged','confide','betray','loyalty','intimacy','mutual','bond','courtship','reunion','condolence','eloquence','paraphrase','concise','baste','knead','marinate','saute','poach','tender','stale','rancid','wholesome','delicacy','condiment','staple food','palate','crumb','batter','tenant','landlord','lease','eviction','deposit','duplex','studio apartment','renovate','dilapidated','cozy','hindsight','foresight','autonomy','legitimacy','redundant','plausible','arbitrary','inevitable','tangible','intangible','sporadic','rampant','dormant','imminent','inherent','credible','feasible','viable','futile','relentless','meager','abundant','scarce','ubiquitous','innate');
