--liquibase formatted sql

--changeset vocab:065-seed-words-batch57
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.category, v.example_sentence, v.example_translation
FROM (VALUES
-- Character / Personality
(N'diplomatic', N'/ˌdɪpləˈmætɪk/', N'khéo léo trong ứng xử, ngoại giao', N'adjective', N'ADVANCED', N'Character', N'She handled the conflict in a diplomatic way.', N'Cô ấy xử lý mâu thuẫn một cách khéo léo.'),
(N'impulsive', N'/ɪmˈpʌlsɪv/', N'bốc đồng', N'adjective', N'INTERMEDIATE', N'Character', N'He made an impulsive decision to quit.', N'Anh ấy đã đưa ra quyết định bốc đồng để nghỉ việc.'),
(N'self-centered', N'/self ˈsentərd/', N'chỉ nghĩ đến bản thân', N'adjective', N'ADVANCED', N'Character', N'His self-centered attitude annoyed his friends.', N'Thái độ chỉ nghĩ đến bản thân của anh ấy khiến bạn bè khó chịu.'),
(N'easygoing', N'/ˈiːzɪɡoʊɪŋ/', N'dễ tính, thoải mái', N'adjective', N'INTERMEDIATE', N'Character', N'She has an easygoing personality.', N'Cô ấy có tính cách dễ tính.'),
(N'hot-tempered', N'/hɑːt ˈtempərd/', N'nóng tính', N'adjective', N'INTERMEDIATE', N'Character', N'He is hot-tempered and shouts easily.', N'Anh ấy nóng tính và dễ nổi giận.'),
(N'level-headed', N'/ˈlevl ˈhedɪd/', N'bình tĩnh, sáng suốt', N'adjective', N'ADVANCED', N'Character', N'She stayed level-headed during the crisis.', N'Cô ấy vẫn bình tĩnh trong lúc khủng hoảng.'),
(N'overbearing', N'/ˌoʊvərˈberɪŋ/', N'hống hách, áp đặt', N'adjective', N'ADVANCED', N'Character', N'His overbearing manner upset the team.', N'Cách áp đặt của anh ấy làm cả nhóm khó chịu.'),
(N'submissive', N'/səbˈmɪsɪv/', N'phục tùng, cam chịu', N'adjective', N'ADVANCED', N'Character', N'She refused to be submissive at work.', N'Cô ấy từ chối trở nên cam chịu ở nơi làm việc.'),
(N'audacious', N'/ɔːˈdeɪʃəs/', N'táo bạo, dám nghĩ dám làm', N'adjective', N'ADVANCED', N'Character', N'He made an audacious business move.', N'Anh ấy thực hiện một bước đi kinh doanh táo bạo.'),
(N'candid', N'/ˈkændɪd/', N'thẳng thắn, chân thật', N'adjective', N'ADVANCED', N'Character', N'She gave a candid opinion about the plan.', N'Cô ấy đưa ra ý kiến thẳng thắn về kế hoạch.'),
(N'hypocritical', N'/ˌhɪpəˈkrɪtɪkl/', N'giả dối, đạo đức giả', N'adjective', N'ADVANCED', N'Character', N'It was hypocritical of him to criticize others.', N'Việc anh ấy chỉ trích người khác thật giả dối.'),
(N'steadfast', N'/ˈstedfæst/', N'kiên định, trung thành', N'adjective', N'ADVANCED', N'Character', N'She remained steadfast in her beliefs.', N'Cô ấy vẫn kiên định với niềm tin của mình.'),
(N'vindictive', N'/vɪnˈdɪktɪv/', N'hay trả thù, thù hằn', N'adjective', N'ADVANCED', N'Character', N'He became vindictive after losing the case.', N'Anh ấy trở nên thù hằn sau khi thua kiện.'),
(N'nonchalant', N'/ˌnɑːnʃəˈlɑːnt/', N'thản nhiên, hờ hững', N'adjective', N'ADVANCED', N'Character', N'She stayed nonchalant about the bad news.', N'Cô ấy vẫn thản nhiên trước tin xấu.'),
(N'meddlesome', N'/ˈmedlsəm/', N'hay xen vào việc người khác', N'adjective', N'ADVANCED', N'Character', N'Their meddlesome neighbor caused problems.', N'Người hàng xóm hay xen vào việc người khác đã gây ra vấn đề.'),
-- Emotions
(N'elated', N'/ɪˈleɪtɪd/', N'vui sướng, hân hoan', N'adjective', N'ADVANCED', N'Emotions', N'She was elated about her promotion.', N'Cô ấy vui sướng về việc được thăng chức.'),
(N'apprehensive', N'/ˌæprɪˈhensɪv/', N'lo lắng, e sợ điều sắp xảy ra', N'adjective', N'ADVANCED', N'Emotions', N'He felt apprehensive before the surgery.', N'Anh ấy cảm thấy lo lắng trước ca phẫu thuật.'),
(N'overwhelmed', N'/ˌoʊvərˈwelmd/', N'choáng ngợp, quá tải cảm xúc', N'adjective', N'INTERMEDIATE', N'Emotions', N'She felt overwhelmed by the workload.', N'Cô ấy cảm thấy choáng ngợp vì lượng công việc.'),
(N'indifferent', N'/ɪnˈdɪfrənt/', N'dửng dưng, không quan tâm', N'adjective', N'INTERMEDIATE', N'Emotions', N'He seemed indifferent to the result.', N'Anh ấy có vẻ dửng dưng với kết quả.'),
(N'resentful', N'/rɪˈzentfl/', N'bất bình, oán giận', N'adjective', N'ADVANCED', N'Emotions', N'She felt resentful about the unfair decision.', N'Cô ấy cảm thấy bất bình về quyết định không công bằng.'),
(N'heartbroken', N'/ˈhɑːrtbroʊkən/', N'đau khổ, tan vỡ trái tim', N'adjective', N'INTERMEDIATE', N'Emotions', N'He was heartbroken after the breakup.', N'Anh ấy đau khổ sau khi chia tay.'),
(N'jubilant', N'/ˈdʒuːbɪlənt/', N'hớn hở, vui mừng tột độ', N'adjective', N'ADVANCED', N'Emotions', N'The fans were jubilant after the win.', N'Các cổ động viên hớn hở sau chiến thắng.'),
(N'disheartened', N'/dɪsˈhɑːrtənd/', N'nản lòng, thất vọng', N'adjective', N'ADVANCED', N'Emotions', N'He felt disheartened by the rejection.', N'Anh ấy cảm thấy nản lòng vì bị từ chối.'),
(N'content', N'/kənˈtent/', N'hài lòng, mãn nguyện', N'adjective', N'INTERMEDIATE', N'Emotions', N'She feels content with her simple life.', N'Cô ấy cảm thấy hài lòng với cuộc sống đơn giản của mình.'),
(N'restless', N'/ˈrestləs/', N'bồn chồn, không yên', N'adjective', N'INTERMEDIATE', N'Emotions', N'He felt restless waiting for the results.', N'Anh ấy cảm thấy bồn chồn khi chờ kết quả.'),
(N'petrified', N'/ˈpetrɪfaɪd/', N'sợ hãi đến mức tê cứng', N'adjective', N'ADVANCED', N'Emotions', N'She was petrified during the earthquake.', N'Cô ấy sợ hãi tê cứng trong lúc động đất.'),
(N'relieved', N'/rɪˈliːvd/', N'cảm thấy nhẹ nhõm', N'adjective', N'BEGINNER', N'Emotions', N'He was relieved to hear the good news.', N'Anh ấy cảm thấy nhẹ nhõm khi nghe tin tốt.'),
(N'infatuated', N'/ɪnˈfætʃueɪtɪd/', N'say mê, mê muội', N'adjective', N'ADVANCED', N'Emotions', N'She became infatuated with the singer.', N'Cô ấy trở nên say mê ca sĩ đó.'),
(N'remorseful', N'/rɪˈmɔːrsfl/', N'hối lỗi, ăn năn', N'adjective', N'ADVANCED', N'Emotions', N'He seemed remorseful about his behavior.', N'Anh ấy có vẻ hối lỗi về hành vi của mình.'),
(N'euphoric', N'/juːˈfɔːrɪk/', N'hưng phấn tột độ', N'adjective', N'ADVANCED', N'Emotions', N'She felt euphoric after finishing the marathon.', N'Cô ấy cảm thấy hưng phấn tột độ sau khi hoàn thành marathon.'),
-- Education
(N'transcript', N'/ˈtrænskrɪpt/', N'bảng điểm', N'noun', N'INTERMEDIATE', N'Education', N'Request your transcript from the office.', N'Hãy yêu cầu bảng điểm từ văn phòng.'),
(N'valedictorian', N'/ˌvælɪdɪkˈtɔːriən/', N'học sinh đứng đầu tốt nghiệp', N'noun', N'ADVANCED', N'Education', N'She was chosen as the class valedictorian.', N'Cô ấy được chọn là học sinh đứng đầu của lớp.'),
(N'homeroom', N'/ˈhoʊmruːm/', N'lớp chủ nhiệm', N'noun', N'BEGINNER', N'Education', N'Students meet in homeroom every morning.', N'Học sinh gặp nhau ở lớp chủ nhiệm mỗi sáng.'),
(N'extracurricular', N'/ˌekstrəkəˈrɪkjələr/', N'ngoại khóa', N'adjective', N'ADVANCED', N'Education', N'She joins many extracurricular activities.', N'Cô ấy tham gia nhiều hoạt động ngoại khóa.'),
(N'proctor', N'/ˈprɑːktər/', N'giám thị coi thi', N'noun', N'ADVANCED', N'Education', N'The proctor watched the exam closely.', N'Giám thị theo dõi kỳ thi rất sát sao.'),
(N'semester', N'/səˈmestər/', N'học kỳ', N'noun', N'BEGINNER', N'Education', N'The new semester starts in September.', N'Học kỳ mới bắt đầu vào tháng Chín.'),
(N'tutor', N'/ˈtuːtər/', N'gia sư', N'noun', N'BEGINNER', N'Education', N'He hired a tutor to help with math.', N'Anh ấy thuê một gia sư để giúp học toán.'),
(N'literate', N'/ˈlɪtərət/', N'biết đọc biết viết', N'adjective', N'INTERMEDIATE', N'Education', N'The program helps adults become literate.', N'Chương trình giúp người lớn biết đọc biết viết.'),
(N'illiterate', N'/ɪˈlɪtərət/', N'mù chữ', N'adjective', N'INTERMEDIATE', N'Education', N'Many people were illiterate in the past.', N'Nhiều người mù chữ trong quá khứ.'),
(N'dropout', N'/ˈdrɑːpaʊt/', N'người bỏ học', N'noun', N'INTERMEDIATE', N'Education', N'He was a high school dropout.', N'Anh ấy là người bỏ học trung học.'),
(N'alumnus', N'/əˈlʌmnəs/', N'cựu học sinh, sinh viên', N'noun', N'ADVANCED', N'Education', N'She is a proud alumnus of this university.', N'Cô ấy tự hào là cựu sinh viên của trường này.'),
(N'commencement', N'/kəˈmensmənt/', N'lễ tốt nghiệp', N'noun', N'ADVANCED', N'Education', N'The commencement ceremony was held in June.', N'Lễ tốt nghiệp được tổ chức vào tháng Sáu.'),
(N'pop quiz', N'/pɑːp kwɪz/', N'bài kiểm tra bất ngờ nhỏ', N'noun', N'BEGINNER', N'Education', N'The teacher gave a pop quiz today.', N'Giáo viên cho một bài kiểm tra bất ngờ hôm nay.'),
(N'detention', N'/dɪˈtenʃən/', N'hình thức phạt ở lại lớp', N'noun', N'INTERMEDIATE', N'Education', N'He got detention for being late.', N'Anh ấy bị phạt ở lại lớp vì đến muộn.'),
(N'gpa', N'/dʒiː piː eɪ/', N'điểm trung bình học tập', N'noun', N'INTERMEDIATE', N'Education', N'Her GPA is very high this semester.', N'Điểm trung bình học tập của cô ấy rất cao trong học kỳ này.'),
-- Work / Office
(N'workload', N'/ˈwɜːrkloʊd/', N'khối lượng công việc', N'noun', N'INTERMEDIATE', N'Work', N'The workload increased before the deadline.', N'Khối lượng công việc tăng lên trước hạn nộp.'),
(N'onboarding', N'/ˈɒnbɔːrdɪŋ/', N'quá trình hội nhập nhân viên mới', N'noun', N'ADVANCED', N'Work', N'The onboarding process takes one week.', N'Quá trình hội nhập nhân viên mới kéo dài một tuần.'),
(N'telecommute', N'/ˈtelikəmjuːt/', N'làm việc từ xa', N'verb', N'ADVANCED', N'Work', N'Many employees telecommute now.', N'Nhiều nhân viên hiện làm việc từ xa.'),
(N'micromanage', N'/ˌmaɪkroʊˈmænɪdʒ/', N'quản lý quá chi tiết', N'verb', N'ADVANCED', N'Work', N'She tends to micromanage her team.', N'Cô ấy có xu hướng quản lý quá chi tiết nhóm của mình.'),
(N'burnout', N'/ˈbɜːrnaʊt/', N'kiệt sức vì công việc', N'noun', N'ADVANCED', N'Work', N'He suffered from burnout after long hours.', N'Anh ấy bị kiệt sức sau nhiều giờ làm việc.'),
(N'workplace', N'/ˈwɜːrkpleɪs/', N'nơi làm việc', N'noun', N'BEGINNER', N'Work', N'Safety is important in the workplace.', N'An toàn rất quan trọng ở nơi làm việc.'),
(N'supervisor', N'/ˈsuːpərvaɪzər/', N'người giám sát', N'noun', N'INTERMEDIATE', N'Work', N'Report any issues to your supervisor.', N'Hãy báo cáo vấn đề với người giám sát của bạn.'),
(N'severance', N'/ˈsevərəns/', N'trợ cấp thôi việc', N'noun', N'ADVANCED', N'Work', N'He received a severance package.', N'Anh ấy nhận được trợ cấp thôi việc.'),
(N'headhunter', N'/ˈhedhʌntər/', N'người săn đầu người', N'noun', N'ADVANCED', N'Work', N'A headhunter contacted her about a new job.', N'Một người săn đầu người đã liên hệ với cô ấy về công việc mới.'),
(N'downsizing', N'/ˈdaʊnsaɪzɪŋ/', N'việc cắt giảm nhân sự', N'noun', N'ADVANCED', N'Work', N'The company announced downsizing plans.', N'Công ty thông báo kế hoạch cắt giảm nhân sự.'),
(N'paperwork', N'/ˈpeɪpərwɜːrk/', N'công việc giấy tờ, thủ tục', N'noun', N'INTERMEDIATE', N'Work', N'She spent the day doing paperwork.', N'Cô ấy dành cả ngày làm giấy tờ.'),
(N'workflow', N'/ˈwɜːrkfloʊ/', N'quy trình làm việc', N'noun', N'INTERMEDIATE', N'Work', N'The new tool improves our workflow.', N'Công cụ mới cải thiện quy trình làm việc của chúng tôi.'),
(N'clock in', N'/klɑːk ɪn/', N'chấm công vào', N'phrase', N'INTERMEDIATE', N'Work', N'Employees must clock in by nine.', N'Nhân viên phải chấm công vào trước chín giờ.'),
(N'clock out', N'/klɑːk aʊt/', N'chấm công ra', N'phrase', N'INTERMEDIATE', N'Work', N'Do not forget to clock out before leaving.', N'Đừng quên chấm công ra trước khi ra về.'),
(N'moonlight', N'/ˈmuːnlaɪt/', N'làm thêm nghề tay trái', N'verb', N'ADVANCED', N'Work', N'He moonlights as a musician on weekends.', N'Anh ấy làm thêm nghề nhạc sĩ vào cuối tuần.'),
-- Time
(N'bygone', N'/ˈbaɪɡɒn/', N'thuộc quá khứ, đã qua', N'adjective', N'ADVANCED', N'Time', N'These traditions belong to a bygone era.', N'Những truyền thống này thuộc về một thời đại đã qua.'),
(N'forthcoming', N'/ˌfɔːrθˈkʌmɪŋ/', N'sắp tới, sắp diễn ra', N'adjective', N'ADVANCED', N'Time', N'Details about the forthcoming event will be shared soon.', N'Chi tiết về sự kiện sắp tới sẽ được chia sẻ sớm.'),
(N'perpetual', N'/pərˈpetʃuəl/', N'vĩnh viễn, liên tục không ngừng', N'adjective', N'ADVANCED', N'Time', N'The city seems to be in perpetual motion.', N'Thành phố dường như luôn trong trạng thái vận động không ngừng.'),
(N'fleeting', N'/ˈfliːtɪŋ/', N'thoáng qua, chóng vánh', N'adjective', N'ADVANCED', N'Time', N'Fame can be fleeting.', N'Sự nổi tiếng có thể chỉ là thoáng qua.'),
(N'timeless', N'/ˈtaɪmləs/', N'vĩnh cửu, không lỗi thời', N'adjective', N'INTERMEDIATE', N'Time', N'This song has a timeless melody.', N'Bài hát này có giai điệu vĩnh cửu.'),
(N'belated', N'/bɪˈleɪtɪd/', N'muộn, chậm trễ', N'adjective', N'ADVANCED', N'Time', N'She sent a belated birthday card.', N'Cô ấy gửi một tấm thẻ sinh nhật muộn.'),
(N'premature', N'/ˌpriːməˈtʃʊr/', N'non, sớm hơn dự kiến', N'adjective', N'ADVANCED', N'Time', N'It is premature to celebrate yet.', N'Vẫn còn quá sớm để ăn mừng.'),
(N'concurrent', N'/kənˈkɜːrənt/', N'đồng thời, cùng lúc', N'adjective', N'ADVANCED', N'Time', N'He is running two concurrent projects.', N'Anh ấy đang chạy hai dự án đồng thời.'),
(N'everlasting', N'/ˌevərˈlæstɪŋ/', N'vĩnh cửu, mãi mãi', N'adjective', N'ADVANCED', N'Time', N'They promised everlasting friendship.', N'Họ hứa hẹn một tình bạn vĩnh cửu.'),
(N'century', N'/ˈsentʃəri/', N'thế kỷ', N'noun', N'BEGINNER', N'Time', N'This building is over a century old.', N'Tòa nhà này đã hơn một thế kỷ tuổi.'),
-- Descriptive
(N'luminous', N'/ˈluːmɪnəs/', N'sáng chói, phát sáng', N'adjective', N'ADVANCED', N'Descriptive', N'The luminous stars lit up the sky.', N'Những vì sao sáng chói làm rực sáng bầu trời.'),
(N'murky', N'/ˈmɜːrki/', N'mờ đục, u ám', N'adjective', N'ADVANCED', N'Descriptive', N'The river water looked murky.', N'Nước sông trông mờ đục.'),
(N'rugged', N'/ˈrʌɡɪd/', N'gồ ghề, thô ráp', N'adjective', N'ADVANCED', N'Descriptive', N'They hiked through rugged terrain.', N'Họ đi bộ qua địa hình gồ ghề.'),
(N'sleek', N'/sliːk/', N'mượt mà, bóng bẩy', N'adjective', N'ADVANCED', N'Descriptive', N'The car has a sleek design.', N'Chiếc xe có thiết kế bóng bẩy.'),
(N'shabby', N'/ˈʃæbi/', N'tồi tàn, cũ rách', N'adjective', N'ADVANCED', N'Descriptive', N'He wore a shabby old coat.', N'Anh ấy mặc một chiếc áo khoác cũ rách.'),
(N'sturdy', N'/ˈstɜːrdi/', N'chắc chắn, khỏe khoắn', N'adjective', N'INTERMEDIATE', N'Descriptive', N'This table is sturdy and reliable.', N'Cái bàn này chắc chắn và bền.'),
(N'flimsy', N'/ˈflɪmzi/', N'mỏng manh, không chắc chắn', N'adjective', N'ADVANCED', N'Descriptive', N'The umbrella felt flimsy in the wind.', N'Cái ô có cảm giác mỏng manh trong gió.'),
(N'hollow', N'/ˈhɑːloʊ/', N'rỗng', N'adjective', N'INTERMEDIATE', N'Descriptive', N'The tree trunk was hollow inside.', N'Thân cây bị rỗng bên trong.'),
(N'jagged', N'/ˈdʒæɡɪd/', N'lởm chởm, răng cưa', N'adjective', N'ADVANCED', N'Descriptive', N'The jagged rocks made climbing hard.', N'Những tảng đá lởm chởm khiến việc leo núi khó khăn.'),
(N'glossy', N'/ˈɡlɑːsi/', N'bóng, láng', N'adjective', N'INTERMEDIATE', N'Descriptive', N'The magazine has glossy pages.', N'Tạp chí có những trang giấy bóng.'),
(N'matte', N'/mæt/', N'mờ, không bóng', N'adjective', N'INTERMEDIATE', N'Descriptive', N'She prefers a matte finish for her makeup.', N'Cô ấy thích lớp trang điểm mờ, không bóng.'),
(N'translucent', N'/trænsˈluːsnt/', N'trong mờ, bán trong suốt', N'adjective', N'ADVANCED', N'Descriptive', N'The curtain is thin and translucent.', N'Tấm màn mỏng và trong mờ.'),
(N'opaque', N'/oʊˈpeɪk/', N'mờ đục, không xuyên sáng', N'adjective', N'ADVANCED', N'Descriptive', N'The glass was frosted and opaque.', N'Kính bị làm mờ và không xuyên sáng.'),
(N'weathered', N'/ˈweðərd/', N'bị bào mòn bởi thời tiết', N'adjective', N'ADVANCED', N'Descriptive', N'The weathered fence needs repainting.', N'Hàng rào bị bào mòn bởi thời tiết cần sơn lại.'),
(N'pungent', N'/ˈpʌndʒənt/', N'nồng, hắc (mùi)', N'adjective', N'ADVANCED', N'Descriptive', N'The pungent smell filled the kitchen.', N'Mùi hắc lan tỏa khắp nhà bếp.'),
(N'fragrant', N'/ˈfreɪɡrənt/', N'thơm', N'adjective', N'INTERMEDIATE', N'Descriptive', N'The garden was full of fragrant flowers.', N'Khu vườn đầy hoa thơm.'),
(N'musty', N'/ˈmʌsti/', N'có mùi ẩm mốc', N'adjective', N'ADVANCED', N'Descriptive', N'The old book had a musty smell.', N'Cuốn sách cũ có mùi ẩm mốc.'),
(N'brittle', N'/ˈbrɪtl/', N'dễ vỡ, giòn', N'adjective', N'ADVANCED', N'Descriptive', N'The dry leaves were brittle.', N'Những chiếc lá khô rất dễ vỡ.'),
(N'lush', N'/lʌʃ/', N'xanh tươi, sum suê', N'adjective', N'ADVANCED', N'Descriptive', N'The valley was covered in lush greenery.', N'Thung lũng được che phủ bởi cây xanh tươi sum suê.'),
(N'barren', N'/ˈbærən/', N'khô cằn, cằn cỗi', N'adjective', N'ADVANCED', N'Descriptive', N'Nothing grows in this barren land.', N'Không có gì mọc được trên vùng đất khô cằn này.'),
-- Numbers / Math
(N'multiple', N'/ˈmʌltɪpl/', N'số bội, nhiều', N'noun', N'INTERMEDIATE', N'General', N'Twelve is a multiple of four.', N'Mười hai là số bội của bốn.'),
(N'average', N'/ˈævərɪdʒ/', N'trung bình', N'noun', N'BEGINNER', N'General', N'The average score was seven out of ten.', N'Điểm trung bình là bảy trên mười.'),
(N'ratio', N'/ˈreɪʃioʊ/', N'tỉ số', N'noun', N'INTERMEDIATE', N'General', N'The ratio of boys to girls is two to one.', N'Tỉ số giữa nam và nữ là hai trên một.'),
(N'sum', N'/sʌm/', N'tổng', N'noun', N'BEGINNER', N'General', N'Find the sum of these two numbers.', N'Tìm tổng của hai số này.'),
(N'square root', N'/skwer ruːt/', N'căn bậc hai', N'noun', N'INTERMEDIATE', N'General', N'The square root of nine is three.', N'Căn bậc hai của chín là ba.'),
(N'estimate', N'/ˈestɪmət/', N'sự ước lượng', N'noun', N'BEGINNER', N'General', N'Give me a rough estimate of the cost.', N'Hãy cho tôi một ước lượng sơ bộ về chi phí.'),
(N'approximate', N'/əˈprɑːksɪmət/', N'gần đúng, xấp xỉ', N'adjective', N'INTERMEDIATE', N'General', N'This is the approximate distance.', N'Đây là khoảng cách gần đúng.'),
(N'digit', N'/ˈdɪdʒɪt/', N'chữ số', N'noun', N'INTERMEDIATE', N'General', N'Enter a four-digit code.', N'Nhập một mã bốn chữ số.'),
(N'infinite', N'/ˈɪnfɪnət/', N'vô hạn', N'adjective', N'ADVANCED', N'General', N'Space seems infinite.', N'Không gian có vẻ vô hạn.'),
(N'finite', N'/ˈfaɪnaɪt/', N'hữu hạn', N'adjective', N'ADVANCED', N'General', N'Resources on earth are finite.', N'Tài nguyên trên trái đất là hữu hạn.'),
-- Clothing
(N'cardigan', N'/ˈkɑːrdɪɡən/', N'áo khoác len', N'noun', N'INTERMEDIATE', N'Clothing', N'She wore a gray cardigan over her dress.', N'Cô ấy mặc áo khoác len xám bên ngoài váy.'),
(N'trousers', N'/ˈtraʊzərz/', N'quần dài', N'noun', N'BEGINNER', N'Clothing', N'He bought a new pair of trousers.', N'Anh ấy mua một chiếc quần dài mới.'),
(N'hem', N'/hem/', N'đường viền gấu áo, quần', N'noun', N'ADVANCED', N'Clothing', N'The tailor shortened the hem of the dress.', N'Người thợ may đã cắt ngắn đường viền gấu váy.'),
(N'tailor', N'/ˈteɪlər/', N'thợ may', N'noun', N'INTERMEDIATE', N'Clothing', N'The tailor made a perfect fit suit.', N'Người thợ may đã làm bộ vest vừa vặn hoàn hảo.'),
(N'garment', N'/ˈɡɑːrmənt/', N'trang phục, quần áo', N'noun', N'INTERMEDIATE', N'Clothing', N'Each garment is made by hand.', N'Mỗi trang phục đều được làm bằng tay.'),
(N'outfit', N'/ˈaʊtfɪt/', N'bộ trang phục', N'noun', N'BEGINNER', N'Clothing', N'She picked a nice outfit for the party.', N'Cô ấy chọn một bộ trang phục đẹp cho buổi tiệc.'),
(N'lace', N'/leɪs/', N'vải ren, dây giày', N'noun', N'INTERMEDIATE', N'Clothing', N'The dress was decorated with lace.', N'Chiếc váy được trang trí bằng vải ren.'),
(N'denim', N'/ˈdenɪm/', N'vải denim, vải bò', N'noun', N'BEGINNER', N'Clothing', N'He always wears denim jeans.', N'Anh ấy luôn mặc quần jean vải bò.'),
(N'embroidery', N'/ɪmˈbrɔɪdəri/', N'đồ thêu', N'noun', N'ADVANCED', N'Clothing', N'The shirt has beautiful embroidery.', N'Chiếc áo có đường thêu đẹp.'),
(N'loose-fitting', N'/luːs ˈfɪtɪŋ/', N'rộng, thoải mái (quần áo)', N'adjective', N'INTERMEDIATE', N'Clothing', N'She prefers loose-fitting clothes in summer.', N'Cô ấy thích quần áo rộng vào mùa hè.'),
-- Body
(N'rib', N'/rɪb/', N'xương sườn', N'noun', N'INTERMEDIATE', N'Body', N'He broke a rib in the accident.', N'Anh ấy bị gãy một xương sườn trong vụ tai nạn.'),
(N'bladder', N'/ˈblædər/', N'bàng quang', N'noun', N'ADVANCED', N'Body', N'Drink less water to avoid a full bladder at night.', N'Uống ít nước hơn để tránh bàng quang đầy vào ban đêm.'),
(N'kidney', N'/ˈkɪdni/', N'quả thận', N'noun', N'INTERMEDIATE', N'Body', N'The kidney filters waste from the blood.', N'Thận lọc chất thải khỏi máu.'),
(N'liver', N'/ˈlɪvər/', N'gan', N'noun', N'INTERMEDIATE', N'Body', N'The liver helps detoxify the body.', N'Gan giúp giải độc cơ thể.'),
(N'windpipe', N'/ˈwɪndpaɪp/', N'khí quản', N'noun', N'ADVANCED', N'Body', N'Food went down the windpipe by accident.', N'Thức ăn vô tình lọt vào khí quản.'),
(N'eyelid', N'/ˈaɪlɪd/', N'mí mắt', N'noun', N'INTERMEDIATE', N'Body', N'Her eyelids felt heavy from tiredness.', N'Mí mắt của cô ấy nặng trĩu vì mệt mỏi.'),
(N'cheekbone', N'/ˈtʃiːkboʊn/', N'xương gò má', N'noun', N'ADVANCED', N'Body', N'He has high cheekbones.', N'Anh ấy có xương gò má cao.'),
(N'shin', N'/ʃɪn/', N'cẳng chân', N'noun', N'INTERMEDIATE', N'Body', N'She hit her shin on the table.', N'Cô ấy va cẳng chân vào cái bàn.'),
(N'knuckle', N'/ˈnʌkl/', N'khớp ngón tay', N'noun', N'ADVANCED', N'Body', N'He cracked his knuckles before typing.', N'Anh ấy bẻ khớp ngón tay trước khi đánh máy.'),
(N'torso', N'/ˈtɔːrsoʊ/', N'thân người', N'noun', N'ADVANCED', N'Body', N'The statue shows only the torso.', N'Bức tượng chỉ khắc phần thân người.'),
-- Animals
(N'antler', N'/ˈæntlər/', N'gạc (hươu, nai)', N'noun', N'ADVANCED', N'Animals', N'The deer has large antlers.', N'Con hươu có gạc lớn.'),
(N'fin', N'/fɪn/', N'vây (cá)', N'noun', N'INTERMEDIATE', N'Animals', N'The shark fin cut through the water.', N'Vây cá mập cắt qua mặt nước.'),
(N'hoof', N'/huːf/', N'móng guốc', N'noun', N'ADVANCED', N'Animals', N'The horse has strong hooves.', N'Con ngựa có móng guốc chắc khỏe.'),
(N'beak', N'/biːk/', N'mỏ (chim)', N'noun', N'INTERMEDIATE', N'Animals', N'The bird used its beak to crack the seed.', N'Con chim dùng mỏ để tách hạt.'),
(N'talon', N'/ˈtælən/', N'vuốt (chim săn mồi)', N'noun', N'ADVANCED', N'Animals', N'The eagle gripped the branch with its talons.', N'Con đại bàng bám cành cây bằng vuốt của nó.'),
(N'fang', N'/fæŋ/', N'răng nanh', N'noun', N'ADVANCED', N'Animals', N'The snake bared its fangs.', N'Con rắn để lộ răng nanh.'),
(N'scale', N'/skeɪl/', N'vảy (cá, rắn)', N'noun', N'INTERMEDIATE', N'Animals', N'Fish scales shine in the sunlight.', N'Vảy cá sáng lên dưới ánh nắng.'),
(N'gill', N'/ɡɪl/', N'mang (cá)', N'noun', N'ADVANCED', N'Animals', N'Fish breathe through their gills.', N'Cá thở bằng mang.'),
(N'tusk', N'/tʌsk/', N'ngà (voi)', N'noun', N'ADVANCED', N'Animals', N'The elephant tusk is made of ivory.', N'Ngà voi được làm từ chất ngà.'),
(N'pouch', N'/paʊtʃ/', N'túi (của thú có túi)', N'noun', N'ADVANCED', N'Animals', N'The baby kangaroo stayed in its mother pouch.', N'Chuột túi con ở trong túi của mẹ nó.'),
-- Shopping
(N'bargain', N'/ˈbɑːrɡɪn/', N'hàng giá rẻ, món hời', N'noun', N'BEGINNER', N'General', N'I found a great bargain at the market.', N'Tôi tìm được một món hời tuyệt vời ở chợ.'),
(N'haggle', N'/ˈhæɡl/', N'mặc cả, trả giá', N'verb', N'ADVANCED', N'General', N'They haggled over the price for ten minutes.', N'Họ mặc cả giá trong mười phút.'),
(N'checkout', N'/ˈtʃekaʊt/', N'quầy thanh toán', N'noun', N'BEGINNER', N'General', N'There was a long line at checkout.', N'Có một hàng dài ở quầy thanh toán.'),
(N'price tag', N'/praɪs tæɡ/', N'nhãn giá', N'noun', N'BEGINNER', N'General', N'Check the price tag before buying.', N'Kiểm tra nhãn giá trước khi mua.'),
(N'clearance sale', N'/ˈklɪrəns seɪl/', N'đợt giảm giá xả hàng', N'noun', N'INTERMEDIATE', N'General', N'The store is having a clearance sale.', N'Cửa hàng đang có đợt giảm giá xả hàng.'),
(N'loyalty card', N'/ˈlɔɪəlti kɑːrd/', N'thẻ tích điểm khách hàng thân thiết', N'noun', N'INTERMEDIATE', N'General', N'Use your loyalty card to earn points.', N'Dùng thẻ tích điểm để nhận điểm thưởng.'),
(N'impulse buying', N'/ˈɪmpʌls ˈbaɪɪŋ/', N'mua sắm bốc đồng', N'noun', N'ADVANCED', N'General', N'Impulse buying can hurt your budget.', N'Mua sắm bốc đồng có thể ảnh hưởng đến ngân sách của bạn.'),
(N'window shopping', N'/ˈwɪndoʊ ˈʃɑːpɪŋ/', N'đi ngắm hàng không mua', N'noun', N'INTERMEDIATE', N'General', N'We spent the afternoon window shopping.', N'Chúng tôi dành cả chiều để đi ngắm hàng.'),
(N'merchandise', N'/ˈmɜːrtʃəndaɪs/', N'hàng hóa', N'noun', N'INTERMEDIATE', N'Business', N'The store sells a variety of merchandise.', N'Cửa hàng bán nhiều loại hàng hóa.'),
(N'shopper', N'/ˈʃɑːpər/', N'người đi mua sắm', N'noun', N'BEGINNER', N'General', N'Shoppers filled the mall on the weekend.', N'Người mua sắm lấp đầy trung tâm thương mại vào cuối tuần.'),
-- Communication
(N'gossip', N'/ˈɡɑːsɪp/', N'chuyện ngồi lê đôi mách', N'noun', N'INTERMEDIATE', N'Social', N'She does not like to spread gossip.', N'Cô ấy không thích lan truyền chuyện ngồi lê đôi mách.'),
(N'rumor', N'/ˈruːmər/', N'tin đồn', N'noun', N'INTERMEDIATE', N'Social', N'The rumor spread quickly around the office.', N'Tin đồn lan nhanh khắp văn phòng.'),
(N'innuendo', N'/ˌɪnjuˈendoʊ/', N'lời nói ám chỉ, ẩn ý', N'noun', N'ADVANCED', N'Language', N'His comment was full of innuendo.', N'Bình luận của anh ấy đầy ẩn ý.'),
(N'sarcasm', N'/ˈsɑːrkæzəm/', N'sự mỉa mai, châm biếm', N'noun', N'INTERMEDIATE', N'Language', N'His reply was dripping with sarcasm.', N'Câu trả lời của anh ấy đầy mỉa mai.'),
(N'monologue', N'/ˈmɑːnəlɔːɡ/', N'độc thoại', N'noun', N'ADVANCED', N'Language', N'The actor delivered a powerful monologue.', N'Diễn viên thể hiện một đoạn độc thoại mạnh mẽ.'),
(N'dialogue', N'/ˈdaɪəlɔːɡ/', N'đối thoại', N'noun', N'BEGINNER', N'Language', N'The movie has natural dialogue.', N'Bộ phim có đoạn đối thoại tự nhiên.'),
(N'jargon', N'/ˈdʒɑːrɡən/', N'thuật ngữ chuyên ngành', N'noun', N'ADVANCED', N'Language', N'Avoid using too much technical jargon.', N'Tránh dùng quá nhiều thuật ngữ chuyên ngành.'),
(N'anecdote', N'/ˈænɪkdoʊt/', N'giai thoại, chuyện kể ngắn', N'noun', N'ADVANCED', N'Language', N'He shared a funny anecdote from his trip.', N'Anh ấy chia sẻ một giai thoại vui từ chuyến đi.'),
(N'testimonial', N'/ˌtestɪˈmoʊniəl/', N'lời chứng thực, đánh giá', N'noun', N'ADVANCED', N'Language', N'The website features customer testimonials.', N'Trang web có các lời chứng thực từ khách hàng.'),
(N'consensus', N'/kənˈsensəs/', N'sự đồng thuận', N'noun', N'ADVANCED', N'Language', N'The team reached a consensus on the plan.', N'Nhóm đã đạt được sự đồng thuận về kế hoạch.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('diplomatic','impulsive','self-centered','easygoing','hot-tempered','level-headed','overbearing','submissive','audacious','candid','hypocritical','steadfast','vindictive','nonchalant','meddlesome','elated','apprehensive','overwhelmed','indifferent','resentful','heartbroken','jubilant','disheartened','content','restless','petrified','relieved','infatuated','remorseful','euphoric','transcript','valedictorian','homeroom','extracurricular','proctor','semester','tutor','literate','illiterate','dropout','alumnus','commencement','pop quiz','detention','gpa','workload','onboarding','telecommute','micromanage','burnout','workplace','supervisor','severance','headhunter','downsizing','paperwork','workflow','clock in','clock out','moonlight','bygone','forthcoming','perpetual','fleeting','timeless','belated','premature','concurrent','everlasting','century','luminous','murky','rugged','sleek','shabby','sturdy','flimsy','hollow','jagged','glossy','matte','translucent','opaque','weathered','pungent','fragrant','musty','brittle','lush','barren','multiple','average','ratio','sum','square root','estimate','approximate','digit','infinite','finite','cardigan','trousers','hem','tailor','garment','outfit','lace','denim','embroidery','loose-fitting','rib','bladder','kidney','liver','windpipe','eyelid','cheekbone','shin','knuckle','torso','antler','fin','hoof','beak','talon','fang','scale','gill','tusk','pouch','bargain','haggle','checkout','price tag','clearance sale','loyalty card','impulse buying','window shopping','merchandise','shopper','gossip','rumor','innuendo','sarcasm','monologue','dialogue','jargon','anecdote','testimonial','consensus');
