--liquibase formatted sql

--changeset vocab:066-seed-words-batch58
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.category, v.example_sentence, v.example_translation
FROM (VALUES
-- Transportation
(N'commuter', N'/kəˈmjuːtər/', N'người đi làm hàng ngày bằng phương tiện công cộng', N'noun', N'INTERMEDIATE', N'Transport', N'Commuters wait for the train every morning.', N'Những người đi làm chờ tàu mỗi sáng.'),
(N'carpool', N'/ˈkɑːrpuːl/', N'đi chung xe', N'noun', N'INTERMEDIATE', N'Transport', N'They carpool to work to save fuel.', N'Họ đi chung xe đến nơi làm việc để tiết kiệm nhiên liệu.'),
(N'pedestrian', N'/pəˈdestriən/', N'người đi bộ', N'noun', N'INTERMEDIATE', N'Transport', N'Drivers must yield to pedestrians.', N'Người lái xe phải nhường đường cho người đi bộ.'),
(N'intersection', N'/ˌɪntərˈsekʃən/', N'giao lộ', N'noun', N'INTERMEDIATE', N'Transport', N'The accident happened at the intersection.', N'Vụ tai nạn xảy ra tại giao lộ.'),
(N'roundabout', N'/ˈraʊndəbaʊt/', N'bùng binh, vòng xoay', N'noun', N'INTERMEDIATE', N'Transport', N'Turn left at the roundabout.', N'Rẽ trái tại bùng binh.'),
(N'overpass', N'/ˈoʊvərpæs/', N'cầu vượt', N'noun', N'INTERMEDIATE', N'Transport', N'The overpass reduces traffic congestion.', N'Cầu vượt giúp giảm ùn tắc giao thông.'),
(N'detour', N'/ˈdiːtʊr/', N'đường đi vòng, đường tránh', N'noun', N'INTERMEDIATE', N'Transport', N'We had to take a detour due to roadwork.', N'Chúng tôi phải đi đường tránh do công trình đang sửa.'),
(N'traffic jam', N'/ˈtræfɪk dʒæm/', N'tắc đường', N'noun', N'BEGINNER', N'Transport', N'We were stuck in a traffic jam for an hour.', N'Chúng tôi bị kẹt trong cảnh tắc đường suốt một giờ.'),
(N'toll', N'/toʊl/', N'phí đường bộ', N'noun', N'INTERMEDIATE', N'Transport', N'You must pay a toll to use this highway.', N'Bạn phải trả phí đường bộ để sử dụng đường cao tốc này.'),
(N'license plate', N'/ˈlaɪsəns pleɪt/', N'biển số xe', N'noun', N'BEGINNER', N'Transport', N'The police recorded the license plate number.', N'Cảnh sát đã ghi lại số biển số xe.'),
-- Places
(N'skyline', N'/ˈskaɪlaɪn/', N'đường chân trời thành phố', N'noun', N'INTERMEDIATE', N'Places', N'The city skyline looks amazing at night.', N'Đường chân trời thành phố trông tuyệt đẹp vào ban đêm.'),
(N'downtown', N'/ˌdaʊnˈtaʊn/', N'trung tâm thành phố', N'noun', N'BEGINNER', N'Places', N'We are meeting downtown for lunch.', N'Chúng tôi gặp nhau ở trung tâm thành phố để ăn trưa.'),
(N'outskirts', N'/ˈaʊtskɜːrts/', N'vùng ngoại ô', N'noun', N'INTERMEDIATE', N'Places', N'They live on the outskirts of the city.', N'Họ sống ở vùng ngoại ô thành phố.'),
(N'countryside', N'/ˈkʌntrisaɪd/', N'vùng nông thôn', N'noun', N'BEGINNER', N'Places', N'We spent the weekend in the countryside.', N'Chúng tôi dành cuối tuần ở vùng nông thôn.'),
(N'hamlet', N'/ˈhæmlət/', N'làng nhỏ', N'noun', N'ADVANCED', N'Places', N'The hamlet has only fifty residents.', N'Làng nhỏ này chỉ có năm mươi cư dân.'),
(N'metropolis', N'/məˈtrɑːpəlɪs/', N'đô thị lớn', N'noun', N'ADVANCED', N'Places', N'Tokyo is a bustling metropolis.', N'Tokyo là một đô thị lớn nhộn nhịp.'),
(N'slum', N'/slʌm/', N'khu ổ chuột', N'noun', N'ADVANCED', N'Places', N'The government is working to improve the slum area.', N'Chính phủ đang nỗ lực cải thiện khu ổ chuột.'),
(N'district', N'/ˈdɪstrɪkt/', N'quận, khu vực', N'noun', N'INTERMEDIATE', N'Places', N'She works in the financial district.', N'Cô ấy làm việc trong khu tài chính.'),
(N'skyscraper', N'/ˈskaɪskreɪpər/', N'tòa nhà chọc trời', N'noun', N'INTERMEDIATE', N'Places', N'The skyscraper is the tallest building in town.', N'Tòa nhà chọc trời là tòa nhà cao nhất trong thành phố.'),
(N'cul-de-sac', N'/ˈkʌl də sæk/', N'đường cùng', N'noun', N'ADVANCED', N'Places', N'Their house is at the end of a cul-de-sac.', N'Nhà của họ ở cuối đường cùng.'),
-- Social Issues
(N'xenophobia', N'/ˌzenəˈfoʊbiə/', N'chứng sợ người nước ngoài', N'noun', N'ADVANCED', N'Social', N'Xenophobia can lead to discrimination.', N'Chứng sợ người nước ngoài có thể dẫn đến sự phân biệt đối xử.'),
(N'stigma', N'/ˈstɪɡmə/', N'sự kỳ thị, định kiến', N'noun', N'ADVANCED', N'Social', N'There is still stigma around mental illness.', N'Vẫn còn sự kỳ thị đối với bệnh tâm lý.'),
(N'accessibility', N'/əkˌsesəˈbɪləti/', N'khả năng tiếp cận', N'noun', N'ADVANCED', N'Social', N'The building was designed for accessibility.', N'Tòa nhà được thiết kế để dễ tiếp cận.'),
(N'disparity', N'/dɪˈspærəti/', N'sự chênh lệch', N'noun', N'ADVANCED', N'Social', N'There is a wide disparity in income levels.', N'Có sự chênh lệch lớn về mức thu nhập.'),
(N'underprivileged', N'/ˌʌndərˈprɪvəlɪdʒd/', N'thiệt thòi, thiếu thốn', N'adjective', N'ADVANCED', N'Social', N'The charity helps underprivileged children.', N'Tổ chức từ thiện giúp đỡ trẻ em thiệt thòi.'),
(N'welfare', N'/ˈwelfer/', N'phúc lợi xã hội', N'noun', N'INTERMEDIATE', N'Social', N'The government increased welfare spending.', N'Chính phủ đã tăng chi tiêu cho phúc lợi xã hội.'),
(N'grassroots', N'/ˈɡrɑːsruːts/', N'từ cơ sở, quần chúng', N'adjective', N'ADVANCED', N'Social', N'It started as a grassroots movement.', N'Nó bắt đầu như một phong trào từ cơ sở.'),
(N'empower', N'/ɪmˈpaʊər/', N'trao quyền, tiếp sức', N'verb', N'ADVANCED', N'Social', N'Education can empower young women.', N'Giáo dục có thể trao quyền cho phụ nữ trẻ.'),
(N'outreach', N'/ˈaʊtriːtʃ/', N'hoạt động tiếp cận cộng đồng', N'noun', N'ADVANCED', N'Social', N'The clinic runs a community outreach program.', N'Phòng khám thực hiện chương trình tiếp cận cộng đồng.'),
(N'donor', N'/ˈdoʊnər/', N'người quyên góp, hiến tặng', N'noun', N'INTERMEDIATE', N'Social', N'The hospital thanked every blood donor.', N'Bệnh viện đã cảm ơn từng người hiến máu.'),
(N'fundraiser', N'/ˈfʌndreɪzər/', N'sự kiện gây quỹ', N'noun', N'INTERMEDIATE', N'Social', N'They organized a fundraiser for the school.', N'Họ tổ chức một sự kiện gây quỹ cho trường học.'),
(N'petition', N'/pəˈtɪʃən/', N'đơn kiến nghị', N'noun', N'INTERMEDIATE', N'Social', N'Thousands signed the online petition.', N'Hàng nghìn người đã ký đơn kiến nghị trực tuyến.'),
(N'boycott', N'/ˈbɔɪkɑːt/', N'tẩy chay', N'verb', N'ADVANCED', N'Social', N'Consumers decided to boycott the brand.', N'Người tiêu dùng quyết định tẩy chay thương hiệu này.'),
(N'demographic', N'/ˌdeməˈɡræfɪk/', N'thuộc về nhân khẩu học', N'adjective', N'ADVANCED', N'Social', N'The survey targets a young demographic.', N'Cuộc khảo sát nhắm vào nhóm nhân khẩu học trẻ.'),
(N'underrepresented', N'/ˌʌndərrepriˈzentɪd/', N'ít được đại diện', N'adjective', N'ADVANCED', N'Social', N'Women remain underrepresented in the field.', N'Phụ nữ vẫn ít được đại diện trong lĩnh vực này.'),
-- Entertainment / Literature
(N'narrator', N'/nəˈreɪtər/', N'người kể chuyện', N'noun', N'INTERMEDIATE', N'Entertainment', N'The narrator speaks in the first person.', N'Người kể chuyện nói theo ngôi thứ nhất.'),
(N'subplot', N'/ˈsʌbplɑːt/', N'cốt truyện phụ', N'noun', N'ADVANCED', N'Entertainment', N'The subplot added depth to the story.', N'Cốt truyện phụ làm câu chuyện sâu sắc hơn.'),
(N'screenplay', N'/ˈskriːnpleɪ/', N'kịch bản phim', N'noun', N'ADVANCED', N'Entertainment', N'She wrote the screenplay for the film.', N'Cô ấy viết kịch bản cho bộ phim.'),
(N'sequel', N'/ˈsiːkwəl/', N'phần tiếp theo', N'noun', N'INTERMEDIATE', N'Entertainment', N'The sequel was even better than the original.', N'Phần tiếp theo còn hay hơn bản gốc.'),
(N'adaptation', N'/ˌædæpˈteɪʃən/', N'bản chuyển thể', N'noun', N'ADVANCED', N'Entertainment', N'The movie is an adaptation of the novel.', N'Bộ phim là bản chuyển thể từ cuốn tiểu thuyết.'),
(N'box office', N'/bɑːks ˈɒfɪs/', N'doanh thu phòng vé', N'noun', N'INTERMEDIATE', N'Entertainment', N'The film topped the box office this week.', N'Bộ phim đứng đầu doanh thu phòng vé tuần này.'),
(N'premiere', N'/prɪˈmɪr/', N'buổi công chiếu ra mắt', N'noun', N'INTERMEDIATE', N'Entertainment', N'They attended the movie premiere.', N'Họ tham dự buổi công chiếu ra mắt phim.'),
(N'spinoff', N'/ˈspɪnɒf/', N'tác phẩm ăn theo, phần ngoại truyện', N'noun', N'ADVANCED', N'Entertainment', N'The show got a popular spinoff series.', N'Chương trình có một phần ngoại truyện nổi tiếng.'),
(N'autobiography', N'/ˌɔːtəbaɪˈɑːɡrəfi/', N'tự truyện', N'noun', N'ADVANCED', N'Entertainment', N'He is writing his autobiography.', N'Anh ấy đang viết tự truyện của mình.'),
(N'anthology', N'/ænˈθɑːlədʒi/', N'tuyển tập', N'noun', N'ADVANCED', N'Entertainment', N'This anthology contains short stories from many authors.', N'Tuyển tập này gồm truyện ngắn từ nhiều tác giả.'),
-- Phrasal Verbs
(N'look down on', N'/lʊk daʊn ɒn/', N'khinh thường', N'phrase', N'INTERMEDIATE', N'Language', N'He never looks down on anyone.', N'Anh ấy không bao giờ khinh thường ai.'),
(N'come up with', N'/kʌm ʌp wɪð/', N'nghĩ ra, đưa ra', N'phrase', N'INTERMEDIATE', N'Language', N'She came up with a clever solution.', N'Cô ấy đã nghĩ ra một giải pháp thông minh.'),
(N'put up with', N'/pʊt ʌp wɪð/', N'chịu đựng', N'phrase', N'INTERMEDIATE', N'Language', N'I cannot put up with this noise anymore.', N'Tôi không thể chịu đựng tiếng ồn này thêm nữa.'),
(N'get over', N'/ɡet ˈoʊvər/', N'vượt qua, hồi phục', N'phrase', N'INTERMEDIATE', N'Language', N'It took her months to get over the loss.', N'Cô ấy mất nhiều tháng để vượt qua mất mát.'),
(N'give in', N'/ɡɪv ɪn/', N'đầu hàng, nhượng bộ', N'phrase', N'INTERMEDIATE', N'Language', N'He finally gave in to their demands.', N'Cuối cùng anh ấy đã nhượng bộ yêu cầu của họ.'),
(N'hold back', N'/hoʊld bæk/', N'kìm nén, giữ lại', N'phrase', N'INTERMEDIATE', N'Language', N'She held back her tears during the speech.', N'Cô ấy kìm nén nước mắt trong bài phát biểu.'),
(N'run into', N'/rʌn ˈɪntuː/', N'tình cờ gặp', N'phrase', N'INTERMEDIATE', N'Language', N'I ran into an old friend yesterday.', N'Hôm qua tôi tình cờ gặp một người bạn cũ.'),
(N'pull through', N'/pʊl θruː/', N'vượt qua khó khăn, hồi phục', N'phrase', N'ADVANCED', N'Language', N'The doctors are confident he will pull through.', N'Các bác sĩ tin rằng anh ấy sẽ hồi phục.'),
(N'wear off', N'/wer ɒf/', N'mất dần tác dụng', N'phrase', N'ADVANCED', N'Language', N'The painkiller will wear off in a few hours.', N'Thuốc giảm đau sẽ hết tác dụng sau vài giờ.'),
(N'drop out', N'/drɑːp aʊt/', N'bỏ học, bỏ cuộc', N'phrase', N'INTERMEDIATE', N'Language', N'He dropped out of college after one year.', N'Anh ấy bỏ học đại học sau một năm.'),
(N'set off', N'/set ɒf/', N'khởi hành, bắt đầu', N'phrase', N'INTERMEDIATE', N'Language', N'We set off early to avoid traffic.', N'Chúng tôi khởi hành sớm để tránh tắc đường.'),
(N'take after', N'/teɪk ˈæftər/', N'giống (người thân)', N'phrase', N'INTERMEDIATE', N'Language', N'She takes after her mother in many ways.', N'Cô ấy giống mẹ mình ở nhiều điểm.'),
(N'fall behind', N'/fɔːl bɪˈhaɪnd/', N'tụt lại phía sau', N'phrase', N'INTERMEDIATE', N'Language', N'He fell behind on his payments.', N'Anh ấy bị tụt lại phía sau về các khoản thanh toán.'),
(N'break down', N'/breɪk daʊn/', N'hỏng, sụp đổ cảm xúc', N'phrase', N'INTERMEDIATE', N'Language', N'The car broke down on the highway.', N'Chiếc xe bị hỏng trên đường cao tốc.'),
(N'hang in there', N'/hæŋ ɪn ðer/', N'cố gắng chịu đựng, đừng bỏ cuộc', N'phrase', N'ADVANCED', N'Language', N'Just hang in there, things will get better.', N'Hãy cố gắng chịu đựng, mọi thứ sẽ tốt hơn.'),
-- People / Family
(N'offspring', N'/ˈɒfsprɪŋ/', N'con cái, con cháu', N'noun', N'ADVANCED', N'People', N'Animals protect their offspring instinctively.', N'Động vật bảo vệ con cái theo bản năng.'),
(N'descendant', N'/dɪˈsendənt/', N'con cháu, dòng dõi', N'noun', N'ADVANCED', N'People', N'She is a descendant of a royal family.', N'Cô ấy là con cháu của một gia đình hoàng gia.'),
(N'ancestor', N'/ˈænsestər/', N'tổ tiên', N'noun', N'INTERMEDIATE', N'People', N'They honor their ancestors every year.', N'Họ tưởng nhớ tổ tiên mỗi năm.'),
(N'heir', N'/er/', N'người thừa kế', N'noun', N'ADVANCED', N'People', N'He is the sole heir to the fortune.', N'Anh ấy là người thừa kế duy nhất của gia sản.'),
(N'twins', N'/twɪnz/', N'cặp song sinh', N'noun', N'BEGINNER', N'People', N'The twins look almost identical.', N'Cặp song sinh trông gần giống nhau.'),
(N'only child', N'/ˈoʊnli tʃaɪld/', N'con một', N'noun', N'BEGINNER', N'People', N'She is an only child in her family.', N'Cô ấy là con một trong gia đình.'),
(N'relative', N'/ˈrelətɪv/', N'người thân, bà con', N'noun', N'BEGINNER', N'People', N'Many relatives came to the wedding.', N'Nhiều người thân đã đến dự đám cưới.'),
(N'fiance', N'/ˌfiːɑːnˈseɪ/', N'chồng chưa cưới', N'noun', N'INTERMEDIATE', N'People', N'Her fiance proposed at the beach.', N'Chồng chưa cưới của cô ấy đã cầu hôn ở bãi biển.'),
(N'fiancee', N'/ˌfiːɑːnˈseɪ/', N'vợ chưa cưới', N'noun', N'INTERMEDIATE', N'People', N'He introduced his fiancee to the family.', N'Anh ấy giới thiệu vợ chưa cưới với gia đình.'),
(N'godparent', N'/ˈɡɑːdperənt/', N'cha mẹ đỡ đầu', N'noun', N'ADVANCED', N'People', N'She asked her best friend to be the godparent.', N'Cô ấy nhờ người bạn thân làm cha mẹ đỡ đầu.'),
-- Science / Space
(N'satellite', N'/ˈsætəlaɪt/', N'vệ tinh', N'noun', N'INTERMEDIATE', N'Science', N'The satellite orbits the earth.', N'Vệ tinh bay quanh trái đất.'),
(N'galaxy', N'/ˈɡæləksi/', N'dải ngân hà, thiên hà', N'noun', N'INTERMEDIATE', N'Science', N'Our galaxy contains billions of stars.', N'Thiên hà của chúng ta chứa hàng tỷ vì sao.'),
(N'astronaut', N'/ˈæstrənɔːt/', N'nhà du hành vũ trụ', N'noun', N'BEGINNER', N'Science', N'The astronaut floated in zero gravity.', N'Nhà du hành vũ trụ trôi trong môi trường không trọng lực.'),
(N'supernova', N'/ˌsuːpərˈnoʊvə/', N'siêu tân tinh', N'noun', N'ADVANCED', N'Science', N'A supernova is an explosive death of a star.', N'Siêu tân tinh là sự bùng nổ của một ngôi sao khi nó chết.'),
(N'meteor', N'/ˈmiːtiər/', N'sao băng, thiên thạch', N'noun', N'INTERMEDIATE', N'Science', N'We saw a meteor streak across the sky.', N'Chúng tôi thấy một ngôi sao băng lướt qua bầu trời.'),
(N'constellation', N'/ˌkɑːnstəˈleɪʃən/', N'chòm sao', N'noun', N'ADVANCED', N'Science', N'Orion is a famous constellation.', N'Orion là một chòm sao nổi tiếng.'),
(N'lunar', N'/ˈluːnər/', N'thuộc về mặt trăng', N'adjective', N'ADVANCED', N'Science', N'The lunar calendar follows moon phases.', N'Lịch âm dựa theo các tuần trăng.'),
(N'solar eclipse', N'/ˈsoʊlər ɪˈklɪps/', N'nhật thực', N'noun', N'INTERMEDIATE', N'Science', N'A solar eclipse happened last month.', N'Một hiện tượng nhật thực đã xảy ra vào tháng trước.'),
(N'black hole', N'/blæk hoʊl/', N'hố đen', N'noun', N'INTERMEDIATE', N'Science', N'A black hole has extremely strong gravity.', N'Hố đen có lực hấp dẫn cực mạnh.'),
(N'spacecraft', N'/ˈspeɪskræft/', N'tàu vũ trụ', N'noun', N'INTERMEDIATE', N'Science', N'The spacecraft landed safely on the moon.', N'Tàu vũ trụ đã hạ cánh an toàn trên mặt trăng.'),
-- Nature / Weather
(N'downpour', N'/ˈdaʊnpɔːr/', N'mưa lớn, mưa như trút', N'noun', N'ADVANCED', N'Nature', N'A sudden downpour soaked everyone.', N'Một trận mưa lớn bất ngờ làm mọi người ướt sũng.'),
(N'humid', N'/ˈhjuːmɪd/', N'ẩm ướt', N'adjective', N'INTERMEDIATE', N'Nature', N'It feels humid before a storm.', N'Trời cảm giác ẩm ướt trước một trận bão.'),
(N'gust', N'/ɡʌst/', N'luồng gió mạnh', N'noun', N'ADVANCED', N'Nature', N'A gust of wind knocked over the umbrella.', N'Một luồng gió mạnh làm đổ cây dù.'),
(N'mist', N'/mɪst/', N'sương mù nhẹ', N'noun', N'INTERMEDIATE', N'Nature', N'Morning mist covered the valley.', N'Sương mù buổi sáng bao phủ thung lũng.'),
(N'hailstone', N'/ˈheɪlstoʊn/', N'hạt mưa đá', N'noun', N'ADVANCED', N'Nature', N'A hailstone hit the car windshield.', N'Một hạt mưa đá đập vào kính chắn gió xe.'),
(N'thunderstorm', N'/ˈθʌndərstɔːrm/', N'giông bão', N'noun', N'INTERMEDIATE', N'Nature', N'A thunderstorm is expected tonight.', N'Dự báo sẽ có giông bão vào tối nay.'),
(N'climate change', N'/ˈklaɪmət tʃeɪndʒ/', N'biến đổi khí hậu', N'noun', N'INTERMEDIATE', N'Nature', N'Climate change affects sea levels worldwide.', N'Biến đổi khí hậu ảnh hưởng đến mực nước biển toàn cầu.'),
(N'sea level', N'/siː ˈlevl/', N'mực nước biển', N'noun', N'INTERMEDIATE', N'Nature', N'Sea level is rising due to melting ice.', N'Mực nước biển đang tăng do băng tan.'),
(N'equinox', N'/ˈiːkwɪnɑːks/', N'điểm phân', N'noun', N'ADVANCED', N'Nature', N'Day and night are equal during the equinox.', N'Ngày và đêm dài bằng nhau vào ngày điểm phân.'),
(N'solstice', N'/ˈsɑːlstɪs/', N'điểm chí', N'noun', N'ADVANCED', N'Nature', N'The summer solstice is the longest day of the year.', N'Điểm hạ chí là ngày dài nhất trong năm.'),
-- Work / Business Idioms
(N'touch base', N'/tʌtʃ beɪs/', N'liên hệ, trao đổi nhanh', N'phrase', N'INTERMEDIATE', N'Work', N'Let us touch base tomorrow morning.', N'Hãy liên hệ trao đổi vào sáng mai.'),
(N'think outside the box', N'/θɪŋk aʊtˈsaɪd ðə bɑːks/', N'suy nghĩ sáng tạo, khác biệt', N'phrase', N'ADVANCED', N'Work', N'The team was asked to think outside the box.', N'Nhóm được yêu cầu suy nghĩ sáng tạo hơn.'),
(N'in the loop', N'/ɪn ðə luːp/', N'được cập nhật thông tin', N'phrase', N'INTERMEDIATE', N'Work', N'Please keep me in the loop about the project.', N'Hãy cập nhật thông tin cho tôi về dự án.'),
(N'run the numbers', N'/rʌn ðə ˈnʌmbərz/', N'tính toán số liệu', N'phrase', N'ADVANCED', N'Work', N'Let me run the numbers before deciding.', N'Để tôi tính toán số liệu trước khi quyết định.'),
(N'red tape', N'/red teɪp/', N'thủ tục hành chính rườm rà', N'noun', N'ADVANCED', N'Work', N'Red tape delayed the approval process.', N'Thủ tục hành chính rườm rà làm chậm quá trình phê duyệt.'),
(N'bottom line', N'/ˈbɑːtəm laɪn/', N'kết quả cuối cùng, lợi nhuận cốt lõi', N'noun', N'ADVANCED', N'Work', N'The bottom line is we need more funding.', N'Kết quả cuối cùng là chúng ta cần thêm vốn.'),
(N'game changer', N'/ɡeɪm ˈtʃeɪndʒər/', N'yếu tố thay đổi cục diện', N'noun', N'ADVANCED', N'Work', N'This new technology is a real game changer.', N'Công nghệ mới này thực sự thay đổi cục diện.'),
(N'win-win', N'/wɪn wɪn/', N'đôi bên cùng có lợi', N'adjective', N'INTERMEDIATE', N'Work', N'It was a win-win deal for both companies.', N'Đó là một thỏa thuận đôi bên cùng có lợi cho hai công ty.'),
(N'learning curve', N'/ˈlɜːrnɪŋ kɜːrv/', N'quá trình học hỏi ban đầu', N'noun', N'ADVANCED', N'Work', N'There is a steep learning curve for this job.', N'Công việc này có quá trình học hỏi ban đầu khá khó.'),
(N'corner the market', N'/ˈkɔːrnər ðə ˈmɑːrkɪt/', N'chiếm lĩnh thị trường', N'phrase', N'ADVANCED', N'Business', N'The company managed to corner the market.', N'Công ty đã chiếm lĩnh được thị trường.'),
-- General / Abstract
(N'juxtaposition', N'/ˌdʒʌkstəpəˈzɪʃən/', N'sự đặt cạnh nhau để đối chiếu', N'noun', N'ADVANCED', N'General', N'The film uses juxtaposition of past and present.', N'Bộ phim sử dụng cách đặt cạnh nhau giữa quá khứ và hiện tại.'),
(N'dichotomy', N'/daɪˈkɑːtəmi/', N'sự phân chia hai mặt đối lập', N'noun', N'ADVANCED', N'General', N'There is a dichotomy between theory and practice.', N'Có sự phân chia đối lập giữa lý thuyết và thực hành.'),
(N'synergy', N'/ˈsɪnərdʒi/', N'sự hợp lực, cộng hưởng', N'noun', N'ADVANCED', N'General', N'The merger created great synergy between teams.', N'Việc sáp nhập tạo ra sự cộng hưởng lớn giữa các nhóm.'),
(N'precedent', N'/ˈpresɪdənt/', N'tiền lệ', N'noun', N'ADVANCED', N'General', N'This case sets a legal precedent.', N'Vụ án này tạo ra một tiền lệ pháp lý.'),
(N'facet', N'/ˈfæsɪt/', N'khía cạnh, mặt của vấn đề', N'noun', N'ADVANCED', N'General', N'Every facet of the plan was reviewed.', N'Mọi khía cạnh của kế hoạch đều được xem xét.'),
(N'premise', N'/ˈpremɪs/', N'tiền đề, giả định cơ sở', N'noun', N'ADVANCED', N'General', N'The argument is based on a false premise.', N'Lập luận này dựa trên một tiền đề sai.'),
(N'rationale', N'/ˌræʃəˈnæl/', N'lý do căn bản, cơ sở lý luận', N'noun', N'ADVANCED', N'General', N'She explained the rationale behind the decision.', N'Cô ấy giải thích lý do căn bản đằng sau quyết định.'),
(N'stalemate', N'/ˈsteɪlmeɪt/', N'tình trạng bế tắc', N'noun', N'ADVANCED', N'General', N'The negotiations reached a stalemate.', N'Cuộc đàm phán đã rơi vào bế tắc.'),
(N'impasse', N'/ˈɪmpæs/', N'tình trạng bế tắc, ngõ cụt', N'noun', N'ADVANCED', N'General', N'Talks have reached an impasse.', N'Các cuộc thảo luận đã rơi vào ngõ cụt.'),
(N'catharsis', N'/kəˈθɑːrsɪs/', N'sự giải tỏa cảm xúc', N'noun', N'ADVANCED', N'General', N'Writing gave her a sense of catharsis.', N'Viết lách mang lại cho cô ấy sự giải tỏa cảm xúc.'),
(N'epiphany', N'/ɪˈpɪfəni/', N'sự giác ngộ, nhận ra đột ngột', N'noun', N'ADVANCED', N'General', N'He had an epiphany about his career.', N'Anh ấy đã có một sự giác ngộ về sự nghiệp của mình.'),
(N'conundrum', N'/kəˈnʌndrəm/', N'vấn đề khó giải, câu đố hóc búa', N'noun', N'ADVANCED', N'General', N'The puzzle presented a real conundrum.', N'Câu đố này thực sự là một vấn đề hóc búa.'),
(N'quandary', N'/ˈkwɑːndəri/', N'tình trạng khó xử, lưỡng nan', N'noun', N'ADVANCED', N'General', N'She was in a quandary about which job to take.', N'Cô ấy rơi vào tình trạng khó xử về việc chọn công việc nào.'),
(N'tenacity', N'/təˈnæsəti/', N'sự ngoan cường, kiên trì', N'noun', N'ADVANCED', N'General', N'His tenacity helped him succeed.', N'Sự kiên trì của anh ấy đã giúp anh thành công.'),
(N'gravitas', N'/ˈɡrævɪtɑːs/', N'sự trang trọng, uy nghiêm', N'noun', N'ADVANCED', N'General', N'The speaker delivered the news with gravitas.', N'Người phát biểu truyền đạt tin tức với sự trang trọng.'),
-- Descriptive
(N'flamboyant', N'/flæmˈbɔɪənt/', N'phô trương, lòe loẹt', N'adjective', N'ADVANCED', N'Descriptive', N'He has a flamboyant style of dressing.', N'Anh ấy có phong cách ăn mặc phô trương.'),
(N'austere', N'/ɔːˈstɪr/', N'khắc khổ, giản dị nghiêm khắc', N'adjective', N'ADVANCED', N'Descriptive', N'The room had an austere, minimalist look.', N'Căn phòng có vẻ khắc khổ, tối giản.'),
(N'quaint', N'/kweɪnt/', N'cổ kính, có vẻ đẹp xưa cũ', N'adjective', N'ADVANCED', N'Descriptive', N'They stayed in a quaint little village.', N'Họ ở lại một ngôi làng nhỏ cổ kính.'),
(N'idyllic', N'/aɪˈdɪlɪk/', N'đẹp như tranh, thanh bình', N'adjective', N'ADVANCED', N'Descriptive', N'They enjoyed an idyllic vacation by the lake.', N'Họ có một kỳ nghỉ thanh bình như tranh bên hồ.'),
(N'bustling', N'/ˈbʌslɪŋ/', N'nhộn nhịp, tấp nập', N'adjective', N'INTERMEDIATE', N'Descriptive', N'The market was bustling with activity.', N'Chợ tấp nập náo nhiệt.'),
(N'desolate', N'/ˈdesələt/', N'hoang vắng, cô quạnh', N'adjective', N'ADVANCED', N'Descriptive', N'The desert looked desolate and empty.', N'Sa mạc trông hoang vắng và trống trải.'),
(N'secluded', N'/sɪˈkluːdɪd/', N'hẻo lánh, tách biệt', N'adjective', N'ADVANCED', N'Descriptive', N'They found a secluded beach to relax.', N'Họ tìm được một bãi biển hẻo lánh để thư giãn.'),
(N'vast', N'/væst/', N'rộng lớn, bao la', N'adjective', N'INTERMEDIATE', N'Descriptive', N'The desert stretched across a vast area.', N'Sa mạc trải rộng trên một vùng bao la.'),
(N'compact', N'/kəmˈpækt/', N'nhỏ gọn', N'adjective', N'INTERMEDIATE', N'Descriptive', N'The car has a compact design.', N'Chiếc xe có thiết kế nhỏ gọn.'),
(N'spacious', N'/ˈspeɪʃəs/', N'rộng rãi', N'adjective', N'INTERMEDIATE', N'Descriptive', N'They moved into a spacious apartment.', N'Họ chuyển vào một căn hộ rộng rãi.'),
-- Food
(N'succulent', N'/ˈsʌkjələnt/', N'ngon, mọng nước', N'adjective', N'ADVANCED', N'Food', N'The steak was succulent and tender.', N'Miếng bít tết mọng nước và mềm.'),
(N'wholegrain', N'/ˈhoʊlɡreɪn/', N'ngũ cốc nguyên hạt', N'adjective', N'INTERMEDIATE', N'Food', N'She only buys wholegrain bread.', N'Cô ấy chỉ mua bánh mì ngũ cốc nguyên hạt.'),
(N'artisanal', N'/ɑːrˈtɪzənl/', N'làm thủ công tinh xảo', N'adjective', N'ADVANCED', N'Food', N'They sell artisanal cheese at the market.', N'Họ bán phô mai làm thủ công tại chợ.'),
(N'gourmet', N'/ɡʊrˈmeɪ/', N'món ăn cao cấp, sang trọng', N'adjective', N'ADVANCED', N'Food', N'The restaurant serves gourmet dishes.', N'Nhà hàng phục vụ các món ăn cao cấp.'),
(N'leftovers', N'/ˈleftoʊvərz/', N'đồ ăn còn dư', N'noun', N'BEGINNER', N'Food', N'We had leftovers for dinner.', N'Chúng tôi ăn đồ ăn còn dư vào bữa tối.'),
(N'staple diet', N'/ˈsteɪpl ˈdaɪət/', N'chế độ ăn chính, cơ bản', N'noun', N'INTERMEDIATE', N'Food', N'Fish is part of their staple diet.', N'Cá là một phần trong chế độ ăn chính của họ.'),
(N'condensed milk', N'/kənˈdenst mɪlk/', N'sữa đặc', N'noun', N'BEGINNER', N'Food', N'Vietnamese coffee is often served with condensed milk.', N'Cà phê Việt Nam thường được pha kèm sữa đặc.'),
(N'skewer', N'/ˈskjuːər/', N'xiên nướng', N'noun', N'INTERMEDIATE', N'Food', N'They grilled meat on skewers.', N'Họ nướng thịt trên xiên.'),
(N'platter', N'/ˈplætər/', N'đĩa lớn bày món ăn', N'noun', N'INTERMEDIATE', N'Food', N'The waiter brought a seafood platter.', N'Người phục vụ mang ra một đĩa hải sản.'),
(N'zest', N'/zest/', N'vỏ bào chanh, cam / sự hào hứng', N'noun', N'ADVANCED', N'Food', N'Add lemon zest to the batter.', N'Thêm vỏ chanh bào vào hỗn hợp bột.'),
-- Health
(N'outbreak', N'/ˈaʊtbreɪk/', N'sự bùng phát dịch bệnh', N'noun', N'ADVANCED', N'Health', N'The outbreak spread quickly through the city.', N'Sự bùng phát dịch bệnh lan nhanh khắp thành phố.'),
(N'epidemic', N'/ˌepɪˈdemɪk/', N'dịch bệnh', N'noun', N'ADVANCED', N'Health', N'The flu epidemic hit many countries.', N'Dịch cúm đã ảnh hưởng đến nhiều quốc gia.'),
(N'quarantine', N'/ˈkwɔːrəntiːn/', N'cách ly', N'noun', N'INTERMEDIATE', N'Health', N'They were placed in quarantine for two weeks.', N'Họ bị cách ly trong hai tuần.'),
(N'antiseptic', N'/ˌæntɪˈseptɪk/', N'chất khử trùng', N'noun', N'ADVANCED', N'Health', N'Clean the wound with antiseptic.', N'Làm sạch vết thương bằng chất khử trùng.'),
(N'splint', N'/splɪnt/', N'nẹp cố định xương gãy', N'noun', N'ADVANCED', N'Health', N'The doctor put a splint on his broken arm.', N'Bác sĩ đặt nẹp cố định cánh tay bị gãy của anh ấy.'),
-- Technology
(N'artificial', N'/ˌɑːrtɪˈfɪʃəl/', N'nhân tạo', N'adjective', N'INTERMEDIATE', N'Technology', N'Artificial intelligence is changing many industries.', N'Trí tuệ nhân tạo đang thay đổi nhiều ngành công nghiệp.'),
(N'simulation', N'/ˌsɪmjuˈleɪʃən/', N'sự mô phỏng', N'noun', N'ADVANCED', N'Technology', N'The flight simulation felt very realistic.', N'Mô phỏng bay có cảm giác rất thực.'),
(N'render', N'/ˈrendər/', N'hiển thị, kết xuất hình ảnh', N'verb', N'ADVANCED', N'Technology', N'The software takes hours to render the video.', N'Phần mềm mất hàng giờ để kết xuất video.'),
(N'plugin', N'/ˈplʌɡɪn/', N'phần mở rộng, tiện ích bổ sung', N'noun', N'ADVANCED', N'Technology', N'Install this plugin to add new features.', N'Cài đặt tiện ích mở rộng này để thêm tính năng mới.'),
(N'dashboard', N'/ˈdæʃbɔːrd/', N'bảng điều khiển', N'noun', N'INTERMEDIATE', N'Technology', N'The dashboard shows all your statistics.', N'Bảng điều khiển hiển thị tất cả số liệu thống kê của bạn.'),
(N'widget', N'/ˈwɪdʒɪt/', N'tiện ích nhỏ trên màn hình', N'noun', N'ADVANCED', N'Technology', N'Add a weather widget to your home screen.', N'Thêm tiện ích thời tiết vào màn hình chính.'),
(N'bug', N'/bʌɡ/', N'lỗi phần mềm', N'noun', N'BEGINNER', N'Technology', N'The developer fixed the bug quickly.', N'Nhà phát triển đã sửa lỗi phần mềm nhanh chóng.'),
(N'patch', N'/pætʃ/', N'bản vá lỗi', N'noun', N'INTERMEDIATE', N'Technology', N'A new patch fixed the security issue.', N'Một bản vá mới đã khắc phục vấn đề an ninh.'),
(N'token', N'/ˈtoʊkən/', N'mã thông báo', N'noun', N'ADVANCED', N'Technology', N'The app uses a token for secure login.', N'Ứng dụng dùng mã thông báo để đăng nhập an toàn.'),
(N'throughput', N'/ˈθruːpʊt/', N'lưu lượng xử lý', N'noun', N'ADVANCED', N'Technology', N'The new server increased data throughput.', N'Máy chủ mới đã tăng lưu lượng xử lý dữ liệu.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('commuter','carpool','pedestrian','intersection','roundabout','overpass','detour','traffic jam','toll','license plate','skyline','downtown','outskirts','countryside','hamlet','metropolis','slum','district','skyscraper','cul-de-sac','xenophobia','stigma','accessibility','disparity','underprivileged','welfare','grassroots','empower','outreach','donor','fundraiser','petition','boycott','demographic','underrepresented','narrator','subplot','screenplay','sequel','adaptation','box office','premiere','spinoff','autobiography','anthology','look down on','come up with','put up with','get over','give in','hold back','run into','pull through','wear off','drop out','set off','take after','fall behind','break down','hang in there','offspring','descendant','ancestor','heir','twins','only child','relative','fiance','fiancee','godparent','satellite','galaxy','astronaut','supernova','meteor','constellation','lunar','solar eclipse','black hole','spacecraft','downpour','humid','gust','mist','hailstone','thunderstorm','climate change','sea level','equinox','solstice','touch base','think outside the box','in the loop','run the numbers','red tape','bottom line','game changer','win-win','learning curve','corner the market','juxtaposition','dichotomy','synergy','precedent','facet','premise','rationale','stalemate','impasse','catharsis','epiphany','conundrum','quandary','tenacity','gravitas','flamboyant','austere','quaint','idyllic','bustling','desolate','secluded','vast','compact','spacious','succulent','wholegrain','artisanal','gourmet','leftovers','staple diet','condensed milk','skewer','platter','zest','outbreak','epidemic','quarantine','antiseptic','splint','artificial','simulation','render','plugin','dashboard','widget','bug','patch','token','throughput');
