--liquibase formatted sql

--changeset vocab:069-seed-words-batch59
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.category, v.example_sentence, v.example_translation
FROM (VALUES
-- Home / Household tools
(N'bucket', N'/ˈbʌkɪt/', N'cái xô', N'noun', N'BEGINNER', N'Home', N'He filled the bucket with water.', N'Anh ấy đổ đầy nước vào xô.'),
(N'ladder', N'/ˈlædər/', N'cái thang', N'noun', N'BEGINNER', N'Home', N'She climbed the ladder to fix the roof.', N'Cô ấy leo thang để sửa mái nhà.'),
(N'hanger', N'/ˈhæŋər/', N'cái mắc áo', N'noun', N'BEGINNER', N'Home', N'Hang your coat on the hanger.', N'Treo áo khoác của bạn lên mắc áo.'),
(N'doormat', N'/ˈdɔːrmæt/', N'tấm thảm lau chân', N'noun', N'BEGINNER', N'Home', N'Wipe your shoes on the doormat.', N'Lau giày của bạn trên tấm thảm cửa.'),
(N'doorknob', N'/ˈdɔːrnɑːb/', N'nắm cửa', N'noun', N'BEGINNER', N'Home', N'She turned the doorknob slowly.', N'Cô ấy xoay nắm cửa từ từ.'),
(N'hinge', N'/hɪndʒ/', N'bản lề', N'noun', N'INTERMEDIATE', N'Home', N'The door hinge needs oiling.', N'Bản lề cửa cần được bơm dầu.'),
(N'padlock', N'/ˈpædlɑːk/', N'khóa móc', N'noun', N'INTERMEDIATE', N'Home', N'He locked the gate with a padlock.', N'Anh ấy khóa cổng bằng khóa móc.'),
(N'doorbell', N'/ˈdɔːrbel/', N'chuông cửa', N'noun', N'BEGINNER', N'Home', N'Someone rang the doorbell.', N'Có ai đó bấm chuông cửa.'),
(N'peephole', N'/ˈpiːphoʊl/', N'lỗ nhìn trộm ở cửa', N'noun', N'INTERMEDIATE', N'Home', N'She looked through the peephole before opening the door.', N'Cô ấy nhìn qua lỗ cửa trước khi mở cửa.'),
(N'mailbox', N'/ˈmeɪlbɑːks/', N'hộp thư', N'noun', N'BEGINNER', N'Home', N'Check the mailbox for letters.', N'Kiểm tra hộp thư xem có thư không.'),
(N'clothesline', N'/ˈkloʊzlaɪn/', N'dây phơi đồ', N'noun', N'INTERMEDIATE', N'Home', N'She hung the clothes on the clothesline.', N'Cô ấy phơi quần áo trên dây phơi.'),
(N'flowerpot', N'/ˈflaʊərpɑːt/', N'chậu hoa', N'noun', N'BEGINNER', N'Home', N'He planted a rose in the flowerpot.', N'Anh ấy trồng một cây hồng trong chậu hoa.'),
(N'wheelbarrow', N'/ˈwiːlbæroʊ/', N'xe đẩy tay', N'noun', N'INTERMEDIATE', N'Home', N'He carried bricks in a wheelbarrow.', N'Anh ấy chở gạch bằng xe đẩy tay.'),
(N'rake', N'/reɪk/', N'cái cào', N'noun', N'BEGINNER', N'Home', N'She used a rake to gather the leaves.', N'Cô ấy dùng cào để dọn lá.'),
(N'dustpan', N'/ˈdʌstpæn/', N'đồ hót rác', N'noun', N'BEGINNER', N'Home', N'She swept the dust into the dustpan.', N'Cô ấy quét bụi vào đồ hót rác.'),
(N'clothespin', N'/ˈkloʊzpɪn/', N'kẹp phơi đồ', N'noun', N'BEGINNER', N'Home', N'He used a clothespin to hang the shirt.', N'Anh ấy dùng kẹp để phơi áo.'),
(N'watering can', N'/ˈwɔːtərɪŋ kæn/', N'bình tưới nước', N'noun', N'BEGINNER', N'Home', N'She watered the plants with a watering can.', N'Cô ấy tưới cây bằng bình tưới nước.'),
(N'lawnmower', N'/ˈlɔːnmoʊər/', N'máy cắt cỏ', N'noun', N'BEGINNER', N'Home', N'He mowed the grass with a lawnmower.', N'Anh ấy cắt cỏ bằng máy cắt cỏ.'),
-- Travel / Camping gear
(N'suitcase', N'/ˈsuːtkeɪs/', N'vali', N'noun', N'BEGINNER', N'Travel', N'She packed her suitcase for the trip.', N'Cô ấy đóng vali cho chuyến đi.'),
(N'tent', N'/tent/', N'lều', N'noun', N'BEGINNER', N'Travel', N'They set up a tent by the lake.', N'Họ dựng lều bên hồ.'),
(N'sleeping bag', N'/ˈsliːpɪŋ bæɡ/', N'túi ngủ', N'noun', N'BEGINNER', N'Travel', N'He zipped up his sleeping bag.', N'Anh ấy kéo khóa túi ngủ.'),
(N'flashlight', N'/ˈflæʃlaɪt/', N'đèn pin', N'noun', N'BEGINNER', N'Travel', N'She used a flashlight to find her way in the dark.', N'Cô ấy dùng đèn pin để tìm đường trong bóng tối.'),
(N'lighter', N'/ˈlaɪtər/', N'bật lửa', N'noun', N'BEGINNER', N'Travel', N'He lit the campfire with a lighter.', N'Anh ấy đốt lửa trại bằng bật lửa.'),
-- Clothing
(N'raincoat', N'/ˈreɪnkoʊt/', N'áo mưa', N'noun', N'BEGINNER', N'Clothing', N'Wear a raincoat, it might rain.', N'Mặc áo mưa vào, trời có thể mưa.'),
(N'poncho', N'/ˈpɑːntʃoʊ/', N'áo choàng không tay', N'noun', N'INTERMEDIATE', N'Clothing', N'He wore a poncho during the storm.', N'Anh ấy mặc áo poncho trong lúc mưa bão.'),
(N'mitten', N'/ˈmɪtn/', N'bao tay không ngón', N'noun', N'BEGINNER', N'Clothing', N'She wore mittens to keep her hands warm.', N'Cô ấy đeo bao tay để giữ ấm tay.'),
(N'sock', N'/sɑːk/', N'chiếc vớ', N'noun', N'BEGINNER', N'Clothing', N'He put on a clean pair of socks.', N'Anh ấy mang một đôi vớ sạch.'),
(N'slipper', N'/ˈslɪpər/', N'dép đi trong nhà', N'noun', N'BEGINNER', N'Clothing', N'She wears slippers around the house.', N'Cô ấy đi dép trong nhà.'),
(N'sandal', N'/ˈsændl/', N'dép sandal', N'noun', N'BEGINNER', N'Clothing', N'He bought a pair of sandals for summer.', N'Anh ấy mua một đôi dép sandal cho mùa hè.'),
(N'boot', N'/buːt/', N'ủng, giày cao cổ', N'noun', N'BEGINNER', N'Clothing', N'She wore boots in the snow.', N'Cô ấy mang ủng trong tuyết.'),
(N'necktie', N'/ˈnektaɪ/', N'cà vạt', N'noun', N'INTERMEDIATE', N'Clothing', N'He wore a necktie to the interview.', N'Anh ấy đeo cà vạt đi phỏng vấn.'),
(N'purse', N'/pɜːrs/', N'túi xách nhỏ', N'noun', N'BEGINNER', N'Clothing', N'She keeps her keys in her purse.', N'Cô ấy giữ chìa khóa trong túi xách.'),
(N'schoolbag', N'/ˈskuːlbæɡ/', N'túi đi học', N'noun', N'BEGINNER', N'Clothing', N'He packed his schoolbag the night before.', N'Anh ấy soạn túi đi học từ tối trước.'),
(N'shoelace', N'/ˈʃuːleɪs/', N'dây giày', N'noun', N'BEGINNER', N'Clothing', N'Tie your shoelace before you run.', N'Buộc dây giày trước khi chạy.'),
(N'apron', N'/ˈeɪprən/', N'tạp dề', N'noun', N'BEGINNER', N'Clothing', N'She wore an apron while cooking.', N'Cô ấy đeo tạp dề khi nấu ăn.'),
(N'oven mitt', N'/ˈʌvən mɪt/', N'găng tay chống nóng lò', N'noun', N'BEGINNER', N'Clothing', N'Use an oven mitt to take out the hot tray.', N'Dùng găng tay chống nóng để lấy khay ra.'),
-- Body / Appearance
(N'fingernail', N'/ˈfɪŋɡərneɪl/', N'móng tay', N'noun', N'BEGINNER', N'Body', N'She painted her fingernails red.', N'Cô ấy sơn móng tay màu đỏ.'),
(N'heel', N'/hiːl/', N'gót chân', N'noun', N'BEGINNER', N'Body', N'He hurt his heel while running.', N'Anh ấy bị đau gót chân khi chạy.'),
(N'eyelash', N'/ˈaɪlæʃ/', N'lông mi', N'noun', N'BEGINNER', N'Body', N'She has long eyelashes.', N'Cô ấy có lông mi dài.'),
(N'goosebumps', N'/ˈɡuːsbʌmps/', N'da gà, sởn gai ốc', N'noun', N'INTERMEDIATE', N'Body', N'The scary movie gave her goosebumps.', N'Bộ phim đáng sợ làm cô ấy sởn gai ốc.'),
(N'frostbite', N'/ˈfrɔːstbaɪt/', N'tê cứng do lạnh, cước', N'noun', N'INTERMEDIATE', N'Body', N'He suffered frostbite on his fingers.', N'Anh ấy bị cước ở các ngón tay.'),
(N'sunburn', N'/ˈsʌnbɜːrn/', N'bị cháy nắng', N'noun', N'BEGINNER', N'Body', N'She got a sunburn at the beach.', N'Cô ấy bị cháy nắng ở bãi biển.'),
(N'blister', N'/ˈblɪstər/', N'phồng rộp da', N'noun', N'INTERMEDIATE', N'Body', N'The new shoes gave him a blister.', N'Giày mới làm chân anh ấy bị phồng rộp.'),
(N'bruise', N'/bruːz/', N'vết bầm tím', N'noun', N'BEGINNER', N'Body', N'He got a bruise on his knee.', N'Anh ấy bị bầm tím ở đầu gối.'),
(N'scab', N'/skæb/', N'vảy vết thương', N'noun', N'INTERMEDIATE', N'Body', N'The scab fell off after a week.', N'Vảy vết thương rơi ra sau một tuần.'),
(N'splinter', N'/ˈsplɪntər/', N'dằm gỗ đâm vào da', N'noun', N'INTERMEDIATE', N'Body', N'She got a splinter in her finger.', N'Cô ấy bị dằm gỗ đâm vào ngón tay.'),
(N'callus', N'/ˈkæləs/', N'chai da', N'noun', N'ADVANCED', N'Body', N'He has calluses on his hands from working.', N'Anh ấy có chai da ở tay vì làm việc.'),
(N'freckle', N'/ˈfrekl/', N'tàn nhang', N'noun', N'INTERMEDIATE', N'Body', N'She has freckles on her nose.', N'Cô ấy có tàn nhang trên mũi.'),
(N'dimple', N'/ˈdɪmpl/', N'lỗ đồng tiền, má lúm', N'noun', N'INTERMEDIATE', N'Body', N'He has a dimple when he smiles.', N'Anh ấy có má lúm khi cười.'),
(N'wrinkle', N'/ˈrɪŋkl/', N'nếp nhăn', N'noun', N'BEGINNER', N'Body', N'She has a few wrinkles around her eyes.', N'Cô ấy có vài nếp nhăn quanh mắt.'),
(N'bald', N'/bɔːld/', N'hói đầu', N'adjective', N'BEGINNER', N'Body', N'His grandfather is bald.', N'Ông của anh ấy bị hói đầu.'),
(N'ponytail', N'/ˈpoʊniteɪl/', N'tóc đuôi ngựa', N'noun', N'BEGINNER', N'Body', N'She tied her hair into a ponytail.', N'Cô ấy buộc tóc thành kiểu đuôi ngựa.'),
(N'braid', N'/breɪd/', N'tóc bện', N'noun', N'BEGINNER', N'Body', N'Her hair was styled in a braid.', N'Tóc cô ấy được tạo kiểu bện.'),
(N'bangs', N'/bæŋz/', N'tóc mái', N'noun', N'INTERMEDIATE', N'Body', N'She cut her bangs short.', N'Cô ấy cắt tóc mái ngắn.'),
(N'mustache', N'/ˈmʌstæʃ/', N'ria mép', N'noun', N'BEGINNER', N'Body', N'He grew a mustache last winter.', N'Anh ấy để ria mép vào mùa đông trước.'),
(N'beard', N'/bɪrd/', N'râu quai nón', N'noun', N'BEGINNER', N'Body', N'He has a thick beard.', N'Anh ấy có bộ râu dày.'),
(N'sideburns', N'/ˈsaɪdbɜːrnz/', N'tóc mai', N'noun', N'ADVANCED', N'Body', N'He trims his sideburns every week.', N'Anh ấy cắt tóc mai mỗi tuần.'),
-- Accessories / Small items
(N'earring', N'/ˈɪrɪŋ/', N'bông tai', N'noun', N'BEGINNER', N'Clothing', N'She wore silver earrings.', N'Cô ấy đeo bông tai bạc.'),
(N'necklace', N'/ˈnekləs/', N'dây chuyền', N'noun', N'BEGINNER', N'Clothing', N'He gave her a necklace as a gift.', N'Anh ấy tặng cô ấy một chiếc dây chuyền.'),
(N'anklet', N'/ˈæŋklət/', N'vòng đeo mắt cá chân', N'noun', N'INTERMEDIATE', N'Clothing', N'She wore a gold anklet.', N'Cô ấy đeo một chiếc vòng chân bằng vàng.'),
(N'brooch', N'/broʊtʃ/', N'trâm cài áo', N'noun', N'ADVANCED', N'Clothing', N'She pinned a brooch to her coat.', N'Cô ấy gắn một chiếc trâm lên áo khoác.'),
(N'cufflink', N'/ˈkʌflɪŋk/', N'nút áo tay măng sét', N'noun', N'ADVANCED', N'Clothing', N'He wore silver cufflinks to the wedding.', N'Anh ấy đeo nút tay áo bạc trong đám cưới.'),
(N'handkerchief', N'/ˈhæŋkərtʃɪf/', N'khăn tay', N'noun', N'INTERMEDIATE', N'Clothing', N'He wiped his face with a handkerchief.', N'Anh ấy lau mặt bằng khăn tay.'),
(N'tissue', N'/ˈtɪʃuː/', N'khăn giấy', N'noun', N'BEGINNER', N'Home', N'She grabbed a tissue to blow her nose.', N'Cô ấy lấy khăn giấy để xì mũi.'),
-- Household textiles / misc small items
(N'tablecloth', N'/ˈteɪblklɔːθ/', N'khăn trải bàn', N'noun', N'BEGINNER', N'Home', N'She spread a clean tablecloth for dinner.', N'Cô ấy trải khăn bàn sạch cho bữa tối.'),
(N'placemat', N'/ˈpleɪsmæt/', N'khăn lót đĩa ăn', N'noun', N'INTERMEDIATE', N'Home', N'Each seat had a woven placemat.', N'Mỗi chỗ ngồi có một tấm lót đĩa dệt.'),
(N'coaster', N'/ˈkoʊstər/', N'lót ly', N'noun', N'BEGINNER', N'Home', N'Put your cup on the coaster.', N'Đặt cốc của bạn lên miếng lót ly.'),
(N'ashtray', N'/ˈæʃtreɪ/', N'gạt tàn thuốc', N'noun', N'BEGINNER', N'Home', N'He put out the cigarette in the ashtray.', N'Anh ấy dụi thuốc trong gạt tàn.'),
(N'matchbox', N'/ˈmætʃbɑːks/', N'hộp diêm', N'noun', N'BEGINNER', N'Home', N'He kept a matchbox in the kitchen drawer.', N'Anh ấy để hộp diêm trong ngăn kéo bếp.'),
(N'toothpick', N'/ˈtuːθpɪk/', N'que xỉa răng', N'noun', N'BEGINNER', N'Home', N'He used a toothpick after dinner.', N'Anh ấy dùng que xỉa răng sau bữa tối.'),
(N'floss', N'/flɔːs/', N'chỉ nha khoa', N'noun', N'INTERMEDIATE', N'Health', N'She flosses her teeth every night.', N'Cô ấy dùng chỉ nha khoa mỗi tối.'),
(N'mouthwash', N'/ˈmaʊθwɑːʃ/', N'nước súc miệng', N'noun', N'BEGINNER', N'Health', N'He uses mouthwash after brushing his teeth.', N'Anh ấy dùng nước súc miệng sau khi đánh răng.'),
(N'razor', N'/ˈreɪzər/', N'dao cạo', N'noun', N'BEGINNER', N'Health', N'He shaved with a razor this morning.', N'Anh ấy cạo mặt bằng dao cạo sáng nay.'),
-- Personal care / Health items
(N'shaving cream', N'/ˈʃeɪvɪŋ kriːm/', N'kem cạo râu', N'noun', N'BEGINNER', N'Health', N'He applied shaving cream before shaving.', N'Anh ấy bôi kem cạo râu trước khi cạo.'),
(N'lotion', N'/ˈloʊʃən/', N'kem dưỡng da', N'noun', N'BEGINNER', N'Health', N'She applies lotion after a shower.', N'Cô ấy bôi kem dưỡng da sau khi tắm.'),
(N'sunscreen', N'/ˈsʌnskriːn/', N'kem chống nắng', N'noun', N'BEGINNER', N'Health', N'Apply sunscreen before going outside.', N'Bôi kem chống nắng trước khi ra ngoài.'),
(N'insect repellent', N'/ˈɪnsekt rɪˈpelənt/', N'thuốc chống côn trùng', N'noun', N'INTERMEDIATE', N'Health', N'Spray insect repellent before camping.', N'Xịt thuốc chống côn trùng trước khi cắm trại.'),
(N'band-aid', N'/ˈbænd eɪd/', N'băng cá nhân', N'noun', N'BEGINNER', N'Health', N'She put a band-aid on the cut.', N'Cô ấy dán băng cá nhân lên vết cắt.'),
(N'stethoscope', N'/ˈsteθəskoʊp/', N'ống nghe (bác sĩ)', N'noun', N'INTERMEDIATE', N'Health', N'The doctor listened with a stethoscope.', N'Bác sĩ nghe bằng ống nghe.'),
(N'wheelchair', N'/ˈwiːltʃer/', N'xe lăn', N'noun', N'BEGINNER', N'Health', N'He uses a wheelchair to move around.', N'Anh ấy dùng xe lăn để di chuyển.'),
(N'crutches', N'/ˈkrʌtʃɪz/', N'nạng chống', N'noun', N'INTERMEDIATE', N'Health', N'She walked on crutches after the surgery.', N'Cô ấy đi bằng nạng sau ca phẫu thuật.'),
(N'hearing aid', N'/ˈhɪrɪŋ eɪd/', N'máy trợ thính', N'noun', N'INTERMEDIATE', N'Health', N'My grandfather wears a hearing aid.', N'Ông tôi đeo máy trợ thính.'),
(N'contact lens', N'/ˈkɑːntækt lenz/', N'kính áp tròng', N'noun', N'INTERMEDIATE', N'Health', N'She wears contact lenses instead of glasses.', N'Cô ấy đeo kính áp tròng thay vì kính mắt.'),
(N'dentures', N'/ˈdentʃərz/', N'răng giả', N'noun', N'INTERMEDIATE', N'Health', N'He removes his dentures at night.', N'Anh ấy tháo răng giả ra vào ban đêm.'),
(N'earplug', N'/ˈɪrplʌɡ/', N'nút tai', N'noun', N'INTERMEDIATE', N'Health', N'She uses earplugs to sleep better.', N'Cô ấy dùng nút tai để ngủ ngon hơn.'),
-- People / Family
(N'nephew', N'/ˈnefjuː/', N'cháu trai (gọi bằng cô, chú, bác)', N'noun', N'BEGINNER', N'People', N'My nephew visited us last weekend.', N'Cháu trai tôi đến thăm chúng tôi cuối tuần trước.'),
(N'niece', N'/niːs/', N'cháu gái (gọi bằng cô, chú, bác)', N'noun', N'BEGINNER', N'People', N'My niece just started school.', N'Cháu gái tôi vừa bắt đầu đi học.'),
(N'orphan', N'/ˈɔːrfən/', N'trẻ mồ côi', N'noun', N'INTERMEDIATE', N'People', N'The charity supports orphans in the city.', N'Tổ chức từ thiện hỗ trợ trẻ mồ côi trong thành phố.'),
(N'teenager', N'/ˈtiːneɪdʒər/', N'thanh thiếu niên', N'noun', N'BEGINNER', N'People', N'The show is popular among teenagers.', N'Chương trình được yêu thích trong giới thanh thiếu niên.'),
(N'elderly', N'/ˈeldərli/', N'người cao tuổi', N'adjective', N'BEGINNER', N'People', N'They help elderly neighbors with groceries.', N'Họ giúp hàng xóm cao tuổi đi mua đồ.'),
(N'infant', N'/ˈɪnfənt/', N'trẻ sơ sinh', N'noun', N'BEGINNER', N'People', N'The infant slept through the night.', N'Trẻ sơ sinh ngủ suốt đêm.'),
-- Weather / Places
(N'puddle', N'/ˈpʌdl/', N'vũng nước nhỏ', N'noun', N'BEGINNER', N'Nature', N'The children jumped over the puddle.', N'Những đứa trẻ nhảy qua vũng nước.'),
(N'hail', N'/heɪl/', N'mưa đá nhỏ', N'noun', N'BEGINNER', N'Nature', N'Hail damaged the crops last night.', N'Mưa đá làm hỏng vụ mùa đêm qua.'),
(N'sleet', N'/sliːt/', N'mưa tuyết', N'noun', N'INTERMEDIATE', N'Nature', N'Sleet made the roads slippery.', N'Mưa tuyết làm đường trơn trượt.'),
(N'sidewalk', N'/ˈsaɪdwɔːk/', N'lối đi bộ ven đường', N'noun', N'BEGINNER', N'Places', N'They walked along the sidewalk.', N'Họ đi bộ dọc theo lối đi bộ.'),
(N'crosswalk', N'/ˈkrɔːswɔːk/', N'vạch qua đường', N'noun', N'BEGINNER', N'Places', N'Always cross at the crosswalk.', N'Luôn qua đường ở vạch qua đường.'),
-- Time / Education
(N'weekday', N'/ˈwiːkdeɪ/', N'ngày trong tuần (không phải cuối tuần)', N'noun', N'BEGINNER', N'Time', N'The office is open on weekdays.', N'Văn phòng mở cửa vào các ngày trong tuần.'),
(N'timetable', N'/ˈtaɪmteɪbl/', N'thời gian biểu', N'noun', N'BEGINNER', N'Time', N'Check the train timetable before you go.', N'Kiểm tra thời gian biểu tàu trước khi đi.'),
(N'recess', N'/ˈriːses/', N'giờ ra chơi', N'noun', N'BEGINNER', N'Education', N'The kids play outside during recess.', N'Trẻ em chơi bên ngoài trong giờ ra chơi.'),
(N'library card', N'/ˈlaɪbreri kɑːrd/', N'thẻ thư viện', N'noun', N'BEGINNER', N'Education', N'You need a library card to borrow books.', N'Bạn cần thẻ thư viện để mượn sách.'),
(N'bookmark', N'/ˈbʊkmɑːrk/', N'cái đánh dấu sách', N'noun', N'BEGINNER', N'Education', N'She used a bookmark to save her page.', N'Cô ấy dùng cái đánh dấu để giữ trang sách.'),
(N'textbook', N'/ˈtekstbʊk/', N'sách giáo khoa', N'noun', N'BEGINNER', N'Education', N'Bring your textbook to class tomorrow.', N'Mang sách giáo khoa đến lớp ngày mai.'),
(N'compass', N'/ˈkʌmpəs/', N'la bàn / com-pa', N'noun', N'BEGINNER', N'Education', N'He used a compass to draw a circle.', N'Anh ấy dùng com-pa để vẽ hình tròn.'),
(N'protractor', N'/proʊˈtræktər/', N'thước đo góc', N'noun', N'INTERMEDIATE', N'Education', N'Use a protractor to measure the angle.', N'Dùng thước đo góc để đo góc.'),
(N'chalk', N'/tʃɔːk/', N'phấn viết bảng', N'noun', N'BEGINNER', N'Education', N'The teacher wrote with chalk on the board.', N'Giáo viên viết bằng phấn trên bảng.'),
(N'whiteboard', N'/ˈwaɪtbɔːrd/', N'bảng trắng', N'noun', N'BEGINNER', N'Education', N'The answer is written on the whiteboard.', N'Câu trả lời được viết trên bảng trắng.'),
(N'marker', N'/ˈmɑːrkər/', N'bút lông, bút đánh dấu', N'noun', N'BEGINNER', N'Education', N'She wrote her name with a marker.', N'Cô ấy viết tên mình bằng bút lông.'),
(N'highlighter', N'/ˈhaɪlaɪtər/', N'bút đánh dấu màu', N'noun', N'BEGINNER', N'Education', N'He highlighted the key points with a highlighter.', N'Anh ấy đánh dấu các ý chính bằng bút highlight.'),
(N'stapler', N'/ˈsteɪplər/', N'cái bấm kim', N'noun', N'BEGINNER', N'Education', N'She used a stapler to attach the pages.', N'Cô ấy dùng bấm kim để ghép các trang lại.'),
(N'paperclip', N'/ˈpeɪpərklɪp/', N'kẹp giấy', N'noun', N'BEGINNER', N'Education', N'He attached the receipt with a paperclip.', N'Anh ấy kẹp biên lai bằng kẹp giấy.'),
(N'glue stick', N'/ɡluː stɪk/', N'hồ dán dạng thỏi', N'noun', N'BEGINNER', N'Education', N'The students used a glue stick for the craft.', N'Học sinh dùng hồ dán để làm đồ thủ công.'),
-- Transport
(N'motorbike', N'/ˈmoʊtərbaɪk/', N'xe máy', N'noun', N'BEGINNER', N'Transport', N'He rides a motorbike to work.', N'Anh ấy đi xe máy đến chỗ làm.'),
(N'scooter', N'/ˈskuːtər/', N'xe tay ga / xe scooter', N'noun', N'BEGINNER', N'Transport', N'She rents a scooter to explore the city.', N'Cô ấy thuê xe scooter để khám phá thành phố.'),
(N'subway', N'/ˈsʌbweɪ/', N'tàu điện ngầm', N'noun', N'BEGINNER', N'Transport', N'We took the subway downtown.', N'Chúng tôi đi tàu điện ngầm vào trung tâm.'),
(N'tram', N'/træm/', N'xe điện', N'noun', N'INTERMEDIATE', N'Transport', N'The tram stops right outside the station.', N'Xe điện dừng ngay bên ngoài nhà ga.'),
(N'ferry', N'/ˈferi/', N'phà', N'noun', N'BEGINNER', N'Transport', N'They crossed the river by ferry.', N'Họ qua sông bằng phà.'),
(N'seatbelt', N'/ˈsiːtbelt/', N'dây an toàn', N'noun', N'BEGINNER', N'Transport', N'Please fasten your seatbelt.', N'Vui lòng thắt dây an toàn.'),
(N'steering wheel', N'/ˈstɪrɪŋ wiːl/', N'vô lăng', N'noun', N'BEGINNER', N'Transport', N'He gripped the steering wheel tightly.', N'Anh ấy nắm chặt vô lăng.'),
(N'gasoline', N'/ˈɡæsəliːn/', N'xăng', N'noun', N'BEGINNER', N'Transport', N'The car ran out of gasoline.', N'Xe hết xăng.'),
(N'tire', N'/ˈtaɪər/', N'lốp xe', N'noun', N'BEGINNER', N'Transport', N'One of the tires is flat.', N'Một trong các lốp xe bị xì hơi.'),
(N'headlight', N'/ˈhedlaɪt/', N'đèn pha xe', N'noun', N'BEGINNER', N'Transport', N'Turn on your headlights at night.', N'Bật đèn pha xe vào ban đêm.'),
-- Playground / Games
(N'playground', N'/ˈpleɪɡraʊnd/', N'sân chơi', N'noun', N'BEGINNER', N'General', N'The children ran to the playground.', N'Những đứa trẻ chạy đến sân chơi.'),
(N'seesaw', N'/ˈsiːsɔː/', N'bập bênh', N'noun', N'INTERMEDIATE', N'General', N'The kids took turns on the seesaw.', N'Các em nhỏ thay nhau chơi bập bênh.'),
(N'swing set', N'/swɪŋ set/', N'bộ xích đu', N'noun', N'BEGINNER', N'General', N'They installed a swing set in the yard.', N'Họ lắp bộ xích đu trong sân.'),
(N'slide', N'/slaɪd/', N'cầu tuột', N'noun', N'BEGINNER', N'General', N'The child went down the slide.', N'Đứa trẻ trượt xuống cầu tuột.'),
(N'sandbox', N'/ˈsændbɑːks/', N'hố cát chơi đùa', N'noun', N'BEGINNER', N'General', N'The kids built a castle in the sandbox.', N'Các em nhỏ xây một lâu đài trong hố cát.'),
(N'merry-go-round', N'/ˈmeri ɡoʊ raʊnd/', N'ngựa quay / đu quay ngựa gỗ', N'noun', N'INTERMEDIATE', N'General', N'She loves riding the merry-go-round.', N'Cô bé thích cưỡi ngựa quay.'),
(N'kite', N'/kaɪt/', N'diều', N'noun', N'BEGINNER', N'General', N'They flew a kite in the park.', N'Họ thả diều trong công viên.'),
(N'jump rope', N'/dʒʌmp roʊp/', N'dây nhảy', N'noun', N'BEGINNER', N'General', N'She practices jump rope every afternoon.', N'Cô bé tập nhảy dây mỗi buổi chiều.'),
(N'hopscotch', N'/ˈhɑːpskɑːtʃ/', N'trò nhảy ô', N'noun', N'INTERMEDIATE', N'General', N'The girls drew squares to play hopscotch.', N'Các bé gái vẽ ô để chơi nhảy ô.'),
(N'tag', N'/tæɡ/', N'trò rượt bắt', N'noun', N'BEGINNER', N'General', N'The kids played tag in the yard.', N'Các em nhỏ chơi rượt bắt trong sân.'),
(N'hide and seek', N'/haɪd ənd siːk/', N'trò trốn tìm', N'noun', N'BEGINNER', N'General', N'They played hide and seek after dinner.', N'Họ chơi trốn tìm sau bữa tối.'),
(N'board game', N'/bɔːrd ɡeɪm/', N'trò chơi cờ bàn', N'noun', N'BEGINNER', N'Entertainment', N'The family plays a board game every Sunday.', N'Gia đình chơi cờ bàn mỗi Chủ nhật.'),
(N'jigsaw', N'/ˈdʒɪɡsɔː/', N'tranh ghép hình', N'noun', N'INTERMEDIATE', N'Entertainment', N'They spent hours on the jigsaw puzzle.', N'Họ dành nhiều giờ để ghép tranh xếp hình.'),
(N'crossword', N'/ˈkrɔːswɜːrd/', N'ô chữ', N'noun', N'INTERMEDIATE', N'Entertainment', N'She solves a crossword every morning.', N'Cô ấy giải ô chữ mỗi sáng.'),
(N'riddle', N'/ˈrɪdl/', N'câu đố', N'noun', N'INTERMEDIATE', N'Entertainment', N'He asked me a tricky riddle.', N'Anh ấy đố tôi một câu đố khó.'),
(N'tongue twister', N'/tʌŋ ˈtwɪstər/', N'câu nói líu lưỡi', N'noun', N'ADVANCED', N'Language', N'Try saying this tongue twister fast.', N'Hãy thử nói câu líu lưỡi này thật nhanh.'),
(N'knock-knock joke', N'/nɑːk nɑːk dʒoʊk/', N'câu đùa cốc cốc', N'noun', N'INTERMEDIATE', N'Entertainment', N'He told a silly knock-knock joke.', N'Anh ấy kể một câu đùa cốc cốc ngớ ngẩn.'),
(N'prank', N'/præŋk/', N'trò đùa tinh nghịch', N'noun', N'INTERMEDIATE', N'Entertainment', N'They played a prank on their friend.', N'Họ chơi khăm bạn của mình.'),
(N'practical joke', N'/ˈpræktɪkl dʒoʊk/', N'trò chơi khăm', N'noun', N'INTERMEDIATE', N'Entertainment', N'He is famous for his practical jokes.', N'Anh ấy nổi tiếng với những trò chơi khăm.'),
(N'scavenger hunt', N'/ˈskævəndʒər hʌnt/', N'trò săn tìm đồ vật', N'noun', N'ADVANCED', N'Entertainment', N'The class organized a scavenger hunt.', N'Lớp học tổ chức một trò săn tìm đồ vật.'),
(N'treasure hunt', N'/ˈtreʒər hʌnt/', N'trò tìm kho báu', N'noun', N'INTERMEDIATE', N'Entertainment', N'The kids went on a treasure hunt in the garden.', N'Các em nhỏ đi tìm kho báu trong vườn.'),
(N'checkmate', N'/ˈtʃekmeɪt/', N'chiếu hết (cờ vua)', N'noun', N'ADVANCED', N'Entertainment', N'He won the game with a clever checkmate.', N'Anh ấy thắng trận bằng một thế chiếu hết khéo léo.'),
-- Sleep / Daily routine
(N'lullaby', N'/ˈlʌləbaɪ/', N'bài hát ru', N'noun', N'INTERMEDIATE', N'General', N'She sang a lullaby to the baby.', N'Cô ấy hát bài ru cho em bé.'),
(N'nursery rhyme', N'/ˈnɜːrsəri raɪm/', N'bài đồng dao', N'noun', N'INTERMEDIATE', N'General', N'The children sang a nursery rhyme.', N'Các em nhỏ hát một bài đồng dao.'),
(N'bedtime', N'/ˈbedtaɪm/', N'giờ đi ngủ', N'noun', N'BEGINNER', N'Time', N'It is past his bedtime.', N'Đã quá giờ đi ngủ của cậu bé.'),
(N'nightmare', N'/ˈnaɪtmer/', N'ác mộng', N'noun', N'BEGINNER', N'General', N'She woke up from a nightmare.', N'Cô ấy tỉnh giấc sau một cơn ác mộng.'),
(N'daydream', N'/ˈdeɪdriːm/', N'mơ mộng giữa ban ngày', N'verb', N'INTERMEDIATE', N'General', N'He often daydreams during class.', N'Anh ấy thường mơ mộng trong giờ học.'),
(N'nap', N'/næp/', N'ngủ trưa ngắn', N'noun', N'BEGINNER', N'General', N'She took a short nap after lunch.', N'Cô ấy chợp mắt một chút sau bữa trưa.'),
(N'snore', N'/snɔːr/', N'ngáy', N'verb', N'INTERMEDIATE', N'General', N'He snores loudly when he sleeps.', N'Anh ấy ngáy to khi ngủ.'),
(N'yawn', N'/jɔːn/', N'ngáp', N'verb', N'BEGINNER', N'General', N'She yawned because she was tired.', N'Cô ấy ngáp vì mệt.'),
(N'hiccup', N'/ˈhɪkʌp/', N'nấc cụt', N'noun', N'BEGINNER', N'General', N'He got the hiccups after drinking soda fast.', N'Anh ấy bị nấc cụt sau khi uống nước ngọt quá nhanh.'),
(N'burp', N'/bɜːrp/', N'ợ hơi', N'verb', N'BEGINNER', N'General', N'The baby burped after feeding.', N'Em bé ợ hơi sau khi bú.'),
-- Animals / Insects
(N'birdhouse', N'/ˈbɜːrdhaʊs/', N'nhà chim', N'noun', N'BEGINNER', N'Animals', N'They built a birdhouse in the garden.', N'Họ làm một nhà chim trong vườn.'),
(N'beehive', N'/ˈbiːhaɪv/', N'tổ ong', N'noun', N'BEGINNER', N'Animals', N'The beehive was full of honey.', N'Tổ ong chứa đầy mật.'),
(N'anthill', N'/ˈænthɪl/', N'gò kiến, ổ kiến', N'noun', N'BEGINNER', N'Animals', N'The children watched the ants near the anthill.', N'Các em nhỏ xem đàn kiến gần ổ kiến.'),
(N'cobweb', N'/ˈkɑːbweb/', N'mạng nhện', N'noun', N'BEGINNER', N'Animals', N'There was a cobweb in the corner of the room.', N'Có một mạng nhện ở góc phòng.'),
(N'firefly', N'/ˈfaɪərflaɪ/', N'đom đóm', N'noun', N'INTERMEDIATE', N'Animals', N'They caught fireflies in the summer night.', N'Họ bắt đom đóm trong đêm hè.'),
(N'ladybug', N'/ˈleɪdibʌɡ/', N'bọ rùa', N'noun', N'BEGINNER', N'Animals', N'A ladybug landed on the flower.', N'Một con bọ rùa đậu trên hoa.'),
(N'caterpillar', N'/ˈkætərpɪlər/', N'sâu bướm', N'noun', N'BEGINNER', N'Animals', N'The caterpillar turned into a butterfly.', N'Con sâu bướm biến thành bươm bướm.'),
(N'cocoon', N'/kəˈkuːn/', N'cái nhộng', N'noun', N'INTERMEDIATE', N'Animals', N'The moth stayed in its cocoon for weeks.', N'Con ngài ở trong nhộng suốt nhiều tuần.'),
(N'tadpole', N'/ˈtædpoʊl/', N'nòng nọc', N'noun', N'INTERMEDIATE', N'Animals', N'The tadpole will grow into a frog.', N'Con nòng nọc sẽ lớn thành con ếch.'),
-- Beach / Sea
(N'seashell', N'/ˈsiːʃel/', N'vỏ sò', N'noun', N'BEGINNER', N'Nature', N'She collected seashells on the beach.', N'Cô ấy nhặt vỏ sò trên bãi biển.'),
(N'seahorse', N'/ˈsiːhɔːrs/', N'cá ngựa', N'noun', N'BEGINNER', N'Animals', N'They saw a seahorse at the aquarium.', N'Họ nhìn thấy một con cá ngựa ở thủy cung.'),
(N'tide pool', N'/taɪd puːl/', N'vũng nước triều', N'noun', N'INTERMEDIATE', N'Nature', N'They found crabs in the tide pool.', N'Họ tìm thấy cua trong vũng nước triều.'),
(N'sandcastle', N'/ˈsændkæsl/', N'lâu đài cát', N'noun', N'BEGINNER', N'General', N'The kids built a sandcastle on the shore.', N'Các em nhỏ xây lâu đài cát trên bờ biển.'),
(N'beach ball', N'/biːtʃ bɔːl/', N'bóng bãi biển', N'noun', N'BEGINNER', N'General', N'They played with a beach ball in the water.', N'Họ chơi bóng bãi biển dưới nước.'),
(N'sunhat', N'/ˈsʌnhæt/', N'mũ che nắng', N'noun', N'BEGINNER', N'Clothing', N'She wore a sunhat to the beach.', N'Cô ấy đội mũ che nắng ra biển.'),
(N'flip-flop', N'/ˈflɪp flɑːp/', N'dép xỏ ngón', N'noun', N'BEGINNER', N'Clothing', N'He walked on the sand in flip-flops.', N'Anh ấy đi trên cát bằng dép xỏ ngón.'),
(N'snorkel', N'/ˈsnɔːrkl/', N'ống thở lặn', N'noun', N'INTERMEDIATE', N'General', N'She used a snorkel to see the fish.', N'Cô ấy dùng ống thở để xem cá.'),
(N'goggles', N'/ˈɡɑːɡlz/', N'kính bảo hộ / kính bơi', N'noun', N'BEGINNER', N'General', N'He wore goggles while swimming.', N'Anh ấy đeo kính bơi khi bơi.'),
(N'diving board', N'/ˈdaɪvɪŋ bɔːrd/', N'ván nhảy cầu', N'noun', N'INTERMEDIATE', N'General', N'She jumped off the diving board.', N'Cô ấy nhảy khỏi ván nhảy cầu.'),
(N'lifeguard', N'/ˈlaɪfɡɑːrd/', N'nhân viên cứu hộ', N'noun', N'BEGINNER', N'General', N'The lifeguard watched the swimmers closely.', N'Nhân viên cứu hộ quan sát người bơi thật kỹ.'),
-- Sports
(N'scoreboard', N'/ˈskɔːrbɔːrd/', N'bảng tỉ số', N'noun', N'BEGINNER', N'General', N'Everyone checked the scoreboard.', N'Mọi người kiểm tra bảng tỉ số.'),
(N'locker room', N'/ˈlɑːkər ruːm/', N'phòng thay đồ', N'noun', N'INTERMEDIATE', N'General', N'The team met in the locker room.', N'Đội gặp nhau trong phòng thay đồ.'),
(N'gymnasium', N'/dʒɪmˈneɪziəm/', N'nhà thi đấu, phòng gym', N'noun', N'INTERMEDIATE', N'General', N'The school built a new gymnasium.', N'Trường xây một nhà thi đấu mới.'),
(N'treadmill', N'/ˈtredmɪl/', N'máy chạy bộ', N'noun', N'BEGINNER', N'General', N'She runs on the treadmill every morning.', N'Cô ấy chạy trên máy chạy bộ mỗi sáng.'),
(N'dumbbell', N'/ˈdʌmbel/', N'tạ tay', N'noun', N'BEGINNER', N'General', N'He lifts dumbbells at the gym.', N'Anh ấy tập tạ tay ở phòng gym.'),
(N'push-up', N'/ˈpʊʃ ʌp/', N'chống đẩy', N'noun', N'BEGINNER', N'General', N'He does fifty push-ups every day.', N'Anh ấy chống đẩy năm mươi lần mỗi ngày.'),
(N'sit-up', N'/ˈsɪt ʌp/', N'gập bụng', N'noun', N'BEGINNER', N'General', N'She does sit-ups to strengthen her core.', N'Cô ấy gập bụng để tăng cường cơ bụng.'),
(N'stopwatch', N'/ˈstɑːpwɑːtʃ/', N'đồng hồ bấm giờ', N'noun', N'BEGINNER', N'General', N'The coach used a stopwatch to time the race.', N'Huấn luyện viên dùng đồng hồ bấm giờ để đo thời gian.'),
(N'finish line', N'/ˈfɪnɪʃ laɪn/', N'đường đích', N'noun', N'BEGINNER', N'General', N'She crossed the finish line first.', N'Cô ấy về đích đầu tiên.'),
(N'podium', N'/ˈpoʊdiəm/', N'bục nhận giải', N'noun', N'INTERMEDIATE', N'General', N'The winner stood on the podium.', N'Người chiến thắng đứng trên bục nhận giải.'),
(N'mascot', N'/ˈmæskɑːt/', N'linh vật', N'noun', N'INTERMEDIATE', N'General', N'The team mascot cheered the crowd.', N'Linh vật của đội cổ vũ khán giả.'),
(N'cheerleader', N'/ˈtʃɪrliːdər/', N'người cổ vũ', N'noun', N'BEGINNER', N'General', N'The cheerleaders danced during halftime.', N'Các cổ động viên nhảy múa trong giờ nghỉ giữa trận.'),
(N'huddle', N'/ˈhʌdl/', N'túm tụm bàn chiến thuật', N'noun', N'ADVANCED', N'General', N'The players formed a huddle before the play.', N'Các cầu thủ túm tụm lại trước khi vào trận.'),
(N'timeout', N'/ˈtaɪmaʊt/', N'thời gian tạm nghỉ', N'noun', N'BEGINNER', N'General', N'The coach called a timeout.', N'Huấn luyện viên yêu cầu tạm nghỉ.'),
(N'offside', N'/ˈɒfsaɪd/', N'lỗi việt vị', N'noun', N'ADVANCED', N'General', N'The goal was disallowed for offside.', N'Bàn thắng bị hủy vì lỗi việt vị.'),
(N'touchdown', N'/ˈtʌtʃdaʊn/', N'chạm bóng ghi điểm (bóng bầu dục)', N'noun', N'INTERMEDIATE', N'General', N'He scored a touchdown in the final minute.', N'Anh ấy chạm bóng ghi điểm ở phút cuối.'),
(N'home run', N'/hoʊm rʌn/', N'cú đánh về nhà (bóng chày)', N'noun', N'INTERMEDIATE', N'General', N'She hit a home run in the last inning.', N'Cô ấy đánh một cú home run ở lượt cuối.'),
(N'strikeout', N'/ˈstraɪkaʊt/', N'bị loại vì đánh hụt 3 lần (bóng chày)', N'noun', N'ADVANCED', N'General', N'The pitcher got a strikeout to end the inning.', N'Người ném bóng khiến đối thủ bị loại để kết thúc lượt.'),
(N'slam dunk', N'/slæm dʌŋk/', N'úp rổ', N'noun', N'ADVANCED', N'General', N'He finished the game with a slam dunk.', N'Anh ấy kết thúc trận đấu bằng một cú úp rổ.'),
(N'free throw', N'/friː θroʊ/', N'ném phạt (bóng rổ)', N'noun', N'INTERMEDIATE', N'General', N'She made both free throws.', N'Cô ấy ném phạt trúng cả hai lần.'),
(N'volley', N'/ˈvɑːli/', N'đánh bóng trên không', N'noun', N'INTERMEDIATE', N'General', N'He hit a powerful volley at the net.', N'Anh ấy đánh một cú vô-lê mạnh ở lưới.'),
(N'smash', N'/smæʃ/', N'cú đập mạnh (cầu lông/bóng)', N'noun', N'INTERMEDIATE', N'General', N'She won the point with a smash.', N'Cô ấy thắng điểm bằng một cú đập mạnh.'),
(N'rally', N'/ˈræli/', N'đợt đấu qua lại liên tục', N'noun', N'INTERMEDIATE', N'General', N'The rally lasted more than twenty shots.', N'Đợt đấu qua lại kéo dài hơn hai mươi lần đánh.'),
-- Camping / Hiking
(N'hiking trail', N'/ˈhaɪkɪŋ treɪl/', N'đường mòn đi bộ', N'noun', N'INTERMEDIATE', N'Travel', N'They followed the hiking trail to the summit.', N'Họ theo đường mòn đi bộ lên đỉnh núi.'),
(N'trailhead', N'/ˈtreɪlhed/', N'điểm bắt đầu đường mòn', N'noun', N'ADVANCED', N'Travel', N'We parked near the trailhead.', N'Chúng tôi đỗ xe gần điểm bắt đầu đường mòn.'),
(N'backcountry', N'/ˈbækkʌntri/', N'vùng hoang dã hẻo lánh', N'noun', N'ADVANCED', N'Travel', N'They hiked into the backcountry for three days.', N'Họ đi bộ vào vùng hoang dã trong ba ngày.'),
(N'basecamp', N'/ˈbeɪskæmp/', N'trại căn cứ', N'noun', N'ADVANCED', N'Travel', N'Climbers rested at the basecamp before the final push.', N'Các nhà leo núi nghỉ ở trại căn cứ trước chặng cuối.'),
(N'bonfire', N'/ˈbɑːnfaɪər/', N'lửa trại lớn', N'noun', N'BEGINNER', N'General', N'They gathered around the bonfire.', N'Họ quây quần bên đống lửa trại.'),
(N'altitude sickness', N'/ˈæltɪtuːd ˈsɪknəs/', N'chứng say độ cao', N'noun', N'INTERMEDIATE', N'Health', N'He felt dizzy from altitude sickness.', N'Anh ấy cảm thấy choáng do say độ cao.'),
(N'seasickness', N'/ˈsiːsɪknəs/', N'chứng say sóng biển', N'noun', N'INTERMEDIATE', N'Health', N'She took medicine to prevent seasickness.', N'Cô ấy uống thuốc để tránh say sóng biển.'),
(N'motion sickness', N'/ˈmoʊʃən ˈsɪknəs/', N'chứng say tàu xe', N'noun', N'INTERMEDIATE', N'Health', N'The child suffers from motion sickness on long drives.', N'Đứa trẻ bị say xe trong những chuyến đi dài.'),
-- Air travel
(N'jet bridge', N'/dʒet brɪdʒ/', N'cầu ống lên máy bay', N'noun', N'ADVANCED', N'Travel', N'Passengers walked through the jet bridge.', N'Hành khách đi qua cầu ống lên máy bay.'),
(N'carry-on', N'/ˈkæri ɑːn/', N'hành lý xách tay', N'noun', N'INTERMEDIATE', N'Travel', N'She packed light so it fit as a carry-on.', N'Cô ấy đóng gói gọn để làm hành lý xách tay.'),
(N'overhead bin', N'/ˈoʊvərhed bɪn/', N'ngăn để hành lý trên máy bay', N'noun', N'INTERMEDIATE', N'Travel', N'Put your bag in the overhead bin.', N'Để túi của bạn vào ngăn hành lý trên đầu.'),
(N'tray table', N'/treɪ ˈteɪbl/', N'bàn ăn gấp trên máy bay', N'noun', N'INTERMEDIATE', N'Travel', N'Please fold up your tray table.', N'Vui lòng gấp bàn ăn lại.'),
(N'window shade', N'/ˈwɪndoʊ ʃeɪd/', N'màn che cửa sổ máy bay', N'noun', N'INTERMEDIATE', N'Travel', N'Lower the window shade during the movie.', N'Kéo màn che cửa sổ xuống khi xem phim.'),
(N'duty-free', N'/ˈduːti friː/', N'miễn thuế', N'adjective', N'INTERMEDIATE', N'Travel', N'She bought perfume at the duty-free shop.', N'Cô ấy mua nước hoa ở cửa hàng miễn thuế.'),
(N'passport control', N'/ˈpæspɔːrt kənˈtroʊl/', N'khu kiểm soát hộ chiếu', N'noun', N'INTERMEDIATE', N'Travel', N'The line at passport control was long.', N'Hàng chờ ở khu kiểm soát hộ chiếu rất dài.'),
(N'immigration officer', N'/ˌɪmɪˈɡreɪʃən ˈɒfɪsər/', N'nhân viên xuất nhập cảnh', N'noun', N'INTERMEDIATE', N'Travel', N'The immigration officer checked her passport.', N'Nhân viên xuất nhập cảnh kiểm tra hộ chiếu của cô ấy.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('bucket','ladder','hanger','doormat','doorknob','hinge','padlock','doorbell','peephole','mailbox','clothesline','flowerpot','wheelbarrow','rake','dustpan','clothespin','watering can','lawnmower','suitcase','tent','sleeping bag','flashlight','lighter','raincoat','poncho','mitten','sock','slipper','sandal','boot','necktie','purse','schoolbag','shoelace','apron','oven mitt','fingernail','heel','eyelash','goosebumps','frostbite','sunburn','blister','bruise','scab','splinter','callus','freckle','dimple','wrinkle','bald','ponytail','braid','bangs','mustache','beard','sideburns','earring','necklace','anklet','brooch','cufflink','handkerchief','tissue','tablecloth','placemat','coaster','ashtray','matchbox','toothpick','floss','mouthwash','razor','shaving cream','lotion','sunscreen','insect repellent','band-aid','stethoscope','wheelchair','crutches','hearing aid','contact lens','dentures','earplug','nephew','niece','orphan','teenager','elderly','infant','puddle','hail','sleet','sidewalk','crosswalk','weekday','timetable','recess','library card','bookmark','textbook','compass','protractor','chalk','whiteboard','marker','highlighter','stapler','paperclip','glue stick','motorbike','scooter','subway','tram','ferry','seatbelt','steering wheel','gasoline','tire','headlight','playground','seesaw','swing set','slide','sandbox','merry-go-round','kite','jump rope','hopscotch','tag','hide and seek','board game','jigsaw','crossword','riddle','tongue twister','knock-knock joke','prank','practical joke','scavenger hunt','treasure hunt','checkmate','lullaby','nursery rhyme','bedtime','nightmare','daydream','nap','snore','yawn','hiccup','burp','birdhouse','beehive','anthill','cobweb','firefly','ladybug','caterpillar','cocoon','tadpole','seashell','seahorse','tide pool','sandcastle','beach ball','sunhat','flip-flop','snorkel','goggles','diving board','lifeguard','scoreboard','locker room','gymnasium','treadmill','dumbbell','push-up','sit-up','stopwatch','finish line','podium','mascot','cheerleader','huddle','timeout','offside','touchdown','home run','strikeout','slam dunk','free throw','volley','smash','rally','hiking trail','trailhead','backcountry','basecamp','bonfire','altitude sickness','seasickness','motion sickness','jet bridge','carry-on','overhead bin','tray table','window shade','duty-free','passport control','immigration officer');
