--liquibase formatted sql

--changeset vocab:070-seed-words-batch60
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.category, v.example_sentence, v.example_translation
FROM (VALUES
-- Kitchen appliances / tools
(N'kitchen sink', N'/ˈkɪtʃɪn sɪŋk/', N'bồn rửa bát', N'noun', N'BEGINNER', N'Home', N'She washed the dishes in the kitchen sink.', N'Cô ấy rửa bát trong bồn rửa.'),
(N'cutting board', N'/ˈkʌtɪŋ bɔːrd/', N'thớt', N'noun', N'BEGINNER', N'Home', N'He chopped vegetables on the cutting board.', N'Anh ấy cắt rau trên thớt.'),
(N'frying pan', N'/ˈfraɪɪŋ pæn/', N'chảo chiên', N'noun', N'BEGINNER', N'Home', N'She fried the eggs in a frying pan.', N'Cô ấy chiên trứng trong chảo.'),
(N'saucepan', N'/ˈsɔːspæn/', N'nồi nhỏ có tay cầm', N'noun', N'BEGINNER', N'Home', N'He heated the soup in a saucepan.', N'Anh ấy hâm súp trong nồi nhỏ.'),
(N'kettle', N'/ˈketl/', N'ấm nước', N'noun', N'BEGINNER', N'Home', N'She boiled water in the kettle.', N'Cô ấy đun nước trong ấm.'),
(N'toaster', N'/ˈtoʊstər/', N'máy nướng bánh mì', N'noun', N'BEGINNER', N'Home', N'He put the bread in the toaster.', N'Anh ấy cho bánh mì vào máy nướng.'),
(N'blender', N'/ˈblendər/', N'máy xay sinh tố', N'noun', N'BEGINNER', N'Home', N'She made a smoothie with a blender.', N'Cô ấy làm sinh tố bằng máy xay.'),
(N'dishwasher', N'/ˈdɪʃwɑːʃər/', N'máy rửa bát', N'noun', N'BEGINNER', N'Home', N'He loaded the dishwasher after dinner.', N'Anh ấy xếp bát vào máy rửa bát sau bữa tối.'),
(N'refrigerator', N'/rɪˈfrɪdʒəreɪtər/', N'tủ lạnh', N'noun', N'BEGINNER', N'Home', N'Put the milk back in the refrigerator.', N'Cất sữa lại vào tủ lạnh.'),
(N'freezer', N'/ˈfriːzər/', N'tủ đông, ngăn đá', N'noun', N'BEGINNER', N'Home', N'She keeps ice cream in the freezer.', N'Cô ấy để kem trong tủ đông.'),
(N'stove', N'/stoʊv/', N'bếp nấu', N'noun', N'BEGINNER', N'Home', N'He turned on the stove to cook rice.', N'Anh ấy mở bếp để nấu cơm.'),
(N'grill pan', N'/ɡrɪl pæn/', N'chảo nướng', N'noun', N'INTERMEDIATE', N'Home', N'She grilled the chicken on a grill pan.', N'Cô ấy nướng gà trên chảo nướng.'),
(N'colander', N'/ˈkʌləndər/', N'cái rây, giá lọc', N'noun', N'INTERMEDIATE', N'Home', N'He drained the pasta with a colander.', N'Anh ấy để mì ráo nước bằng cái rây.'),
(N'ladle', N'/ˈleɪdl/', N'cái vá canh', N'noun', N'INTERMEDIATE', N'Home', N'She served the soup with a ladle.', N'Cô ấy múc súp bằng cái vá.'),
(N'rolling pin', N'/ˈroʊlɪŋ pɪn/', N'cây cán bột', N'noun', N'INTERMEDIATE', N'Home', N'He rolled the dough with a rolling pin.', N'Anh ấy cán bột bằng cây cán bột.'),
(N'measuring cup', N'/ˈmeʒərɪŋ kʌp/', N'cốc đo lường', N'noun', N'BEGINNER', N'Home', N'She measured the flour with a measuring cup.', N'Cô ấy đo bột bằng cốc đo lường.'),
-- Cleaning / home maintenance
(N'trash can', N'/træʃ kæn/', N'thùng rác', N'noun', N'BEGINNER', N'Home', N'Throw the paper in the trash can.', N'Vứt tờ giấy vào thùng rác.'),
(N'recycling bin', N'/rɪˈsaɪklɪŋ bɪn/', N'thùng tái chế', N'noun', N'BEGINNER', N'Home', N'Put the bottles in the recycling bin.', N'Cho các chai vào thùng tái chế.'),
(N'laundry basket', N'/ˈlɔːndri ˈbæskɪt/', N'giỏ đồ giặt', N'noun', N'BEGINNER', N'Home', N'She carried the laundry basket upstairs.', N'Cô ấy mang giỏ đồ giặt lên gác.'),
(N'iron', N'/ˈaɪərn/', N'bàn ủi', N'noun', N'BEGINNER', N'Home', N'He used an iron to press his shirt.', N'Anh ấy dùng bàn ủi để ủi áo.'),
(N'ironing board', N'/ˈaɪərnɪŋ bɔːrd/', N'bàn ủi đồ', N'noun', N'BEGINNER', N'Home', N'She set up the ironing board in the living room.', N'Cô ấy đặt bàn ủi đồ trong phòng khách.'),
(N'vacuum cleaner', N'/ˈvækjuːm ˈkliːnər/', N'máy hút bụi', N'noun', N'BEGINNER', N'Home', N'He vacuumed the carpet with a vacuum cleaner.', N'Anh ấy hút bụi tấm thảm bằng máy hút bụi.'),
(N'sponge', N'/spʌndʒ/', N'miếng bọt biển rửa bát', N'noun', N'BEGINNER', N'Home', N'She washed the plate with a sponge.', N'Cô ấy rửa đĩa bằng miếng bọt biển.'),
(N'dish soap', N'/dɪʃ soʊp/', N'nước rửa bát', N'noun', N'BEGINNER', N'Home', N'Add some dish soap to the water.', N'Thêm một ít nước rửa bát vào nước.'),
(N'scrub brush', N'/skrʌb brʌʃ/', N'bàn chải cọ rửa', N'noun', N'INTERMEDIATE', N'Home', N'He scrubbed the pot with a scrub brush.', N'Anh ấy cọ nồi bằng bàn chải cọ rửa.'),
(N'air freshener', N'/er ˈfreʃənər/', N'sáp thơm phòng', N'noun', N'INTERMEDIATE', N'Home', N'She sprayed air freshener in the bathroom.', N'Cô ấy xịt sáp thơm trong phòng tắm.'),
-- Electrical / utilities
(N'light bulb', N'/laɪt bʌlb/', N'bóng đèn', N'noun', N'BEGINNER', N'Home', N'The light bulb burned out.', N'Bóng đèn bị cháy.'),
(N'extension cord', N'/ɪkˈstenʃən kɔːrd/', N'dây nối điện', N'noun', N'INTERMEDIATE', N'Home', N'He used an extension cord to reach the outlet.', N'Anh ấy dùng dây nối điện để nối tới ổ điện.'),
(N'power outlet', N'/ˈpaʊər ˈaʊtlet/', N'ổ điện', N'noun', N'INTERMEDIATE', N'Home', N'Plug the charger into the power outlet.', N'Cắm bộ sạc vào ổ điện.'),
(N'remote control', N'/rɪˈmoʊt kənˈtroʊl/', N'điều khiển từ xa', N'noun', N'BEGINNER', N'Home', N'He changed the channel with the remote control.', N'Anh ấy đổi kênh bằng điều khiển từ xa.'),
(N'alarm clock', N'/əˈlɑːrm klɑːk/', N'đồng hồ báo thức', N'noun', N'BEGINNER', N'Home', N'The alarm clock woke her up at six.', N'Đồng hồ báo thức đánh thức cô ấy lúc sáu giờ.'),
(N'wall clock', N'/wɔːl klɑːk/', N'đồng hồ treo tường', N'noun', N'BEGINNER', N'Home', N'A wall clock hung above the door.', N'Một chiếc đồng hồ treo tường được treo trên cửa.'),
(N'ceiling fan', N'/ˈsiːlɪŋ fæn/', N'quạt trần', N'noun', N'BEGINNER', N'Home', N'They turned on the ceiling fan to cool the room.', N'Họ mở quạt trần để làm mát phòng.'),
(N'air conditioner', N'/er kənˈdɪʃənər/', N'máy điều hòa', N'noun', N'BEGINNER', N'Home', N'The air conditioner keeps the room cool.', N'Máy điều hòa giữ phòng mát mẻ.'),
(N'radiator', N'/ˈreɪdieɪtər/', N'máy tỏa nhiệt sưởi', N'noun', N'INTERMEDIATE', N'Home', N'The radiator warmed up the room.', N'Máy tỏa nhiệt làm ấm phòng.'),
-- House structure
(N'staircase', N'/ˈsterkeɪs/', N'cầu thang', N'noun', N'BEGINNER', N'Home', N'She walked up the staircase slowly.', N'Cô ấy đi lên cầu thang một cách chậm rãi.'),
(N'handrail', N'/ˈhændreɪl/', N'tay vịn', N'noun', N'INTERMEDIATE', N'Home', N'Hold the handrail when going down the stairs.', N'Hãy nắm tay vịn khi xuống thang.'),
(N'elevator', N'/ˈelɪveɪtər/', N'thang máy', N'noun', N'BEGINNER', N'Places', N'They took the elevator to the tenth floor.', N'Họ đi thang máy lên tầng mười.'),
(N'escalator', N'/ˈeskəleɪtər/', N'thang cuốn', N'noun', N'BEGINNER', N'Places', N'She rode the escalator to the second floor.', N'Cô ấy đi thang cuốn lên tầng hai.'),
(N'balcony railing', N'/ˈbælkəni ˈreɪlɪŋ/', N'lan can ban công', N'noun', N'INTERMEDIATE', N'Home', N'He leaned against the balcony railing.', N'Anh ấy tựa vào lan can ban công.'),
(N'windowsill', N'/ˈwɪndoʊsɪl/', N'bệ cửa sổ', N'noun', N'INTERMEDIATE', N'Home', N'She placed a plant on the windowsill.', N'Cô ấy để một cây cảnh trên bệ cửa sổ.'),
(N'rooftop garden', N'/ˈruːftɑːp ˈɡɑːrdn/', N'vườn trên sân thượng', N'noun', N'INTERMEDIATE', N'Home', N'They grow vegetables in the rooftop garden.', N'Họ trồng rau trong vườn trên sân thượng.'),
(N'basement stairs', N'/ˈbeɪsmənt sterz/', N'cầu thang xuống hầm', N'noun', N'INTERMEDIATE', N'Home', N'He carried boxes down the basement stairs.', N'Anh ấy mang thùng xuống cầu thang hầm.'),
(N'attic ladder', N'/ˈætɪk ˈlædər/', N'thang lên gác mái', N'noun', N'INTERMEDIATE', N'Home', N'She climbed the attic ladder to store the boxes.', N'Cô ấy leo thang lên gác mái để cất thùng đồ.'),
(N'garage door', N'/ɡəˈrɑːʒ dɔːr/', N'cửa ga-ra', N'noun', N'BEGINNER', N'Home', N'He opened the garage door before driving out.', N'Anh ấy mở cửa ga-ra trước khi lái xe ra.'),
(N'mail slot', N'/meɪl slɑːt/', N'khe nhận thư', N'noun', N'INTERMEDIATE', N'Home', N'The postman pushed the letter through the mail slot.', N'Người đưa thư nhét lá thư qua khe nhận thư.'),
(N'house number', N'/haʊs ˈnʌmbər/', N'số nhà', N'noun', N'BEGINNER', N'Home', N'The house number was hard to see at night.', N'Số nhà khó nhìn thấy vào ban đêm.'),
(N'fireplace mantel', N'/ˈfaɪərpleɪs ˈmæntl/', N'bệ lò sưởi', N'noun', N'INTERMEDIATE', N'Home', N'They placed photos on the fireplace mantel.', N'Họ đặt ảnh lên bệ lò sưởi.'),
-- Street / transport infrastructure
(N'street lamp', N'/striːt læmp/', N'đèn đường', N'noun', N'BEGINNER', N'Places', N'The street lamp lit up the corner.', N'Đèn đường chiếu sáng góc phố.'),
(N'traffic light', N'/ˈtræfɪk laɪt/', N'đèn giao thông', N'noun', N'BEGINNER', N'Places', N'Stop when the traffic light is red.', N'Dừng lại khi đèn giao thông màu đỏ.'),
(N'stop sign', N'/stɑːp saɪn/', N'biển báo dừng', N'noun', N'BEGINNER', N'Places', N'The driver stopped at the stop sign.', N'Người lái xe dừng lại ở biển báo dừng.'),
(N'speed bump', N'/spiːd bʌmp/', N'gờ giảm tốc', N'noun', N'INTERMEDIATE', N'Places', N'Drive slowly over the speed bump.', N'Lái chậm qua gờ giảm tốc.'),
(N'parking meter', N'/ˈpɑːrkɪŋ ˈmiːtər/', N'máy tính giờ đỗ xe', N'noun', N'INTERMEDIATE', N'Places', N'He paid the parking meter for two hours.', N'Anh ấy trả tiền máy tính giờ đỗ xe cho hai giờ.'),
(N'parking lot', N'/ˈpɑːrkɪŋ lɑːt/', N'bãi đỗ xe', N'noun', N'BEGINNER', N'Places', N'She left her car in the parking lot.', N'Cô ấy để xe trong bãi đỗ xe.'),
(N'gas station', N'/ɡæs ˈsteɪʃən/', N'trạm xăng', N'noun', N'BEGINNER', N'Places', N'They stopped at a gas station to refuel.', N'Họ dừng lại ở trạm xăng để đổ nhiên liệu.'),
(N'bus stop', N'/bʌs stɑːp/', N'trạm xe buýt', N'noun', N'BEGINNER', N'Places', N'She waited for the bus at the bus stop.', N'Cô ấy chờ xe buýt ở trạm xe buýt.'),
(N'train platform', N'/treɪn ˈplætfɔːrm/', N'sân ga', N'noun', N'INTERMEDIATE', N'Places', N'He waited on the train platform.', N'Anh ấy chờ ở sân ga.'),
(N'turnstile', N'/ˈtɜːrnstaɪl/', N'cửa xoay kiểm soát vào', N'noun', N'INTERMEDIATE', N'Places', N'She scanned her ticket at the turnstile.', N'Cô ấy quét vé ở cửa xoay.'),
-- Money / Shopping
(N'vending machine', N'/ˈvendɪŋ məˈʃiːn/', N'máy bán hàng tự động', N'noun', N'BEGINNER', N'General', N'He bought a soda from the vending machine.', N'Anh ấy mua nước ngọt từ máy bán hàng tự động.'),
(N'ATM', N'/ˌeɪ tiː ˈem/', N'máy rút tiền tự động', N'noun', N'BEGINNER', N'Business', N'She withdrew cash from the ATM.', N'Cô ấy rút tiền mặt từ máy ATM.'),
(N'bank teller', N'/bæŋk ˈtelər/', N'nhân viên giao dịch ngân hàng', N'noun', N'INTERMEDIATE', N'Business', N'The bank teller helped him deposit the check.', N'Nhân viên ngân hàng giúp anh ấy gửi tiền séc.'),
(N'safe deposit box', N'/seɪf dɪˈpɑːzɪt bɑːks/', N'hộp ký gửi an toàn', N'noun', N'INTERMEDIATE', N'Business', N'She keeps her jewelry in a safe deposit box.', N'Cô ấy giữ trang sức trong hộp ký gửi an toàn.'),
(N'piggy bank', N'/ˈpɪɡi bæŋk/', N'heo đất tiết kiệm', N'noun', N'BEGINNER', N'General', N'The child saved coins in a piggy bank.', N'Đứa trẻ để dành tiền xu trong heo đất.'),
(N'coin purse', N'/kɔɪn pɜːrs/', N'túi đựng tiền xu', N'noun', N'BEGINNER', N'General', N'She keeps her coins in a small coin purse.', N'Cô ấy để tiền xu trong túi nhỏ.'),
(N'shopping cart', N'/ˈʃɑːpɪŋ kɑːrt/', N'xe đẩy siêu thị', N'noun', N'BEGINNER', N'General', N'He pushed the shopping cart down the aisle.', N'Anh ấy đẩy xe siêu thị dọc theo lối đi.'),
(N'shopping bag', N'/ˈʃɑːpɪŋ bæɡ/', N'túi mua hàng', N'noun', N'BEGINNER', N'General', N'She carried two shopping bags home.', N'Cô ấy mang hai túi hàng về nhà.'),
(N'barcode scanner', N'/ˈbɑːrkoʊd ˈskænər/', N'máy quét mã vạch', N'noun', N'INTERMEDIATE', N'Business', N'The cashier used a barcode scanner.', N'Nhân viên thu ngân dùng máy quét mã vạch.'),
(N'cash register', N'/kæʃ ˈredʒɪstər/', N'máy tính tiền', N'noun', N'BEGINNER', N'Business', N'She entered the price into the cash register.', N'Cô ấy nhập giá vào máy tính tiền.'),
(N'fitting room', N'/ˈfɪtɪŋ ruːm/', N'phòng thử đồ', N'noun', N'INTERMEDIATE', N'General', N'He tried on the shirt in the fitting room.', N'Anh ấy thử áo trong phòng thử đồ.'),
(N'mannequin', N'/ˈmænɪkɪn/', N'ma-nơ-canh', N'noun', N'INTERMEDIATE', N'General', N'The dress was displayed on a mannequin.', N'Chiếc váy được trưng bày trên ma-nơ-canh.'),
(N'display window', N'/dɪˈspleɪ ˈwɪndoʊ/', N'cửa kính trưng bày', N'noun', N'INTERMEDIATE', N'General', N'The shoes were shown in the display window.', N'Giày được trưng bày ở cửa kính.'),
(N'grocery aisle', N'/ˈɡroʊsəri aɪl/', N'lối đi trong siêu thị', N'noun', N'INTERMEDIATE', N'General', N'She walked down the grocery aisle looking for rice.', N'Cô ấy đi dọc lối đi siêu thị để tìm gạo.'),
(N'checkout line', N'/ˈtʃekaʊt laɪn/', N'hàng chờ thanh toán', N'noun', N'BEGINNER', N'General', N'The checkout line was very long.', N'Hàng chờ thanh toán rất dài.'),
(N'ticket booth', N'/ˈtɪkɪt buːθ/', N'quầy bán vé', N'noun', N'BEGINNER', N'General', N'They bought tickets at the ticket booth.', N'Họ mua vé ở quầy bán vé.'),
-- Party / Celebration
(N'gift wrap', N'/ɡɪft ræp/', N'giấy gói quà', N'noun', N'BEGINNER', N'General', N'She wrapped the present with colorful gift wrap.', N'Cô ấy gói quà bằng giấy gói nhiều màu.'),
(N'birthday candle', N'/ˈbɜːrθdeɪ ˈkændl/', N'nến sinh nhật', N'noun', N'BEGINNER', N'General', N'He blew out the birthday candles.', N'Anh ấy thổi nến sinh nhật.'),
(N'party hat', N'/ˈpɑːrti hæt/', N'mũ tiệc', N'noun', N'BEGINNER', N'General', N'The children wore party hats.', N'Các em nhỏ đội mũ tiệc.'),
(N'balloon animal', N'/bəˈluːn ˈænɪml/', N'con vật làm từ bóng bay', N'noun', N'INTERMEDIATE', N'General', N'The clown made a balloon animal for the kid.', N'Chú hề làm một con vật bằng bóng bay cho đứa trẻ.'),
(N'confetti', N'/kənˈfeti/', N'giấy vụn tung mừng', N'noun', N'INTERMEDIATE', N'General', N'Confetti fell from the ceiling at midnight.', N'Giấy vụn rơi từ trần nhà lúc nửa đêm.'),
(N'streamers', N'/ˈstriːmərz/', N'dây trang trí giấy', N'noun', N'INTERMEDIATE', N'General', N'They decorated the room with streamers.', N'Họ trang trí phòng bằng dây giấy màu.'),
(N'piñata', N'/piːnˈjɑːtə/', N'con vật giấy đựng kẹo', N'noun', N'INTERMEDIATE', N'General', N'The kids took turns hitting the piñata.', N'Các em nhỏ thay nhau đánh vào piñata.'),
(N'wrapping paper', N'/ˈræpɪŋ ˈpeɪpər/', N'giấy gói quà', N'noun', N'BEGINNER', N'General', N'She bought wrapping paper for the gift.', N'Cô ấy mua giấy gói cho món quà.'),
(N'greeting card', N'/ˈɡriːtɪŋ kɑːrd/', N'thẻ chúc mừng', N'noun', N'BEGINNER', N'General', N'He sent her a greeting card for her birthday.', N'Anh ấy gửi cho cô ấy một thẻ chúc mừng sinh nhật.'),
(N'thank you note', N'/θæŋk juː noʊt/', N'thư cảm ơn', N'noun', N'INTERMEDIATE', N'General', N'She wrote a thank you note to her teacher.', N'Cô ấy viết một thư cảm ơn cho giáo viên.'),
(N'invitation', N'/ˌɪnvɪˈteɪʃən/', N'thư mời', N'noun', N'BEGINNER', N'General', N'They sent invitations to all their friends.', N'Họ gửi thư mời đến tất cả bạn bè.'),
(N'guest list', N'/ɡest lɪst/', N'danh sách khách mời', N'noun', N'INTERMEDIATE', N'General', N'She added ten more names to the guest list.', N'Cô ấy thêm mười tên nữa vào danh sách khách mời.'),
(N'seating chart', N'/ˈsiːtɪŋ tʃɑːrt/', N'sơ đồ chỗ ngồi', N'noun', N'INTERMEDIATE', N'General', N'The seating chart showed who sat where.', N'Sơ đồ chỗ ngồi cho biết ai ngồi ở đâu.'),
-- Wedding / Life events
(N'wedding ring', N'/ˈwedɪŋ rɪŋ/', N'nhẫn cưới', N'noun', N'BEGINNER', N'People', N'He never takes off his wedding ring.', N'Anh ấy không bao giờ tháo nhẫn cưới.'),
(N'engagement ring', N'/ɪnˈɡeɪdʒmənt rɪŋ/', N'nhẫn đính hôn', N'noun', N'BEGINNER', N'People', N'She showed everyone her engagement ring.', N'Cô ấy khoe nhẫn đính hôn với mọi người.'),
(N'bridesmaid', N'/ˈbraɪdzmeɪd/', N'phụ dâu', N'noun', N'INTERMEDIATE', N'People', N'She asked her sister to be her bridesmaid.', N'Cô ấy nhờ em gái làm phụ dâu.'),
(N'groomsman', N'/ˈɡruːmzmən/', N'phụ rể', N'noun', N'INTERMEDIATE', N'People', N'His best friend was a groomsman.', N'Người bạn thân của anh ấy làm phụ rể.'),
(N'best man', N'/best mæn/', N'phụ rể chính', N'noun', N'INTERMEDIATE', N'People', N'His brother was the best man at the wedding.', N'Anh trai của anh ấy là phụ rể chính trong đám cưới.'),
(N'maid of honor', N'/meɪd əv ˈɑːnər/', N'phụ dâu chính', N'noun', N'INTERMEDIATE', N'People', N'She chose her best friend as maid of honor.', N'Cô ấy chọn bạn thân làm phụ dâu chính.'),
(N'flower girl', N'/ˈflaʊər ɡɜːrl/', N'bé gái rải hoa', N'noun', N'INTERMEDIATE', N'People', N'The flower girl walked down the aisle first.', N'Bé gái rải hoa đi đầu tiên xuống lối đi.'),
(N'ring bearer', N'/rɪŋ ˈberər/', N'bé trai mang nhẫn cưới', N'noun', N'INTERMEDIATE', N'People', N'The ring bearer carried the rings carefully.', N'Bé trai mang nhẫn cẩn thận cầm nhẫn cưới.'),
(N'honeymoon', N'/ˈhʌnimuːn/', N'trăng mật', N'noun', N'INTERMEDIATE', N'People', N'They went to Bali for their honeymoon.', N'Họ đi Bali để hưởng trăng mật.'),
(N'anniversary', N'/ˌænɪˈvɜːrsəri/', N'ngày kỷ niệm', N'noun', N'INTERMEDIATE', N'People', N'They celebrated their tenth anniversary.', N'Họ kỷ niệm mười năm ngày cưới.'),
(N'retirement party', N'/rɪˈtaɪərmənt ˈpɑːrti/', N'tiệc nghỉ hưu', N'noun', N'INTERMEDIATE', N'People', N'They threw a retirement party for their manager.', N'Họ tổ chức tiệc nghỉ hưu cho quản lý của mình.'),
(N'graduation cap', N'/ˌɡrædʒuˈeɪʃən kæp/', N'mũ tốt nghiệp', N'noun', N'BEGINNER', N'Education', N'She threw her graduation cap into the air.', N'Cô ấy ném mũ tốt nghiệp lên không.'),
(N'diploma', N'/dɪˈploʊmə/', N'bằng tốt nghiệp', N'noun', N'INTERMEDIATE', N'Education', N'He received his diploma on stage.', N'Anh ấy nhận bằng tốt nghiệp trên sân khấu.'),
(N'report card', N'/rɪˈpɔːrt kɑːrd/', N'sổ liên lạc / bảng điểm', N'noun', N'BEGINNER', N'Education', N'Her report card showed good grades.', N'Sổ liên lạc của cô ấy có điểm tốt.'),
-- School
(N'hall pass', N'/hɔːl pæs/', N'giấy phép ra ngoài lớp', N'noun', N'INTERMEDIATE', N'Education', N'He needed a hall pass to leave the classroom.', N'Anh ấy cần giấy phép để ra khỏi lớp.'),
(N'locker combination', N'/ˈlɑːkər ˌkɑːmbɪˈneɪʃən/', N'mã số khóa tủ đồ', N'noun', N'INTERMEDIATE', N'Education', N'She forgot her locker combination.', N'Cô ấy quên mã số khóa tủ đồ.'),
(N'gym uniform', N'/dʒɪm ˈjuːnɪfɔːrm/', N'đồng phục thể dục', N'noun', N'BEGINNER', N'Education', N'Students must wear a gym uniform for P.E.', N'Học sinh phải mặc đồng phục thể dục cho giờ thể dục.'),
(N'school bus', N'/skuːl bʌs/', N'xe buýt học sinh', N'noun', N'BEGINNER', N'Education', N'The children rode the school bus every morning.', N'Các em nhỏ đi xe buýt học sinh mỗi sáng.'),
(N'crossing guard', N'/ˈkrɔːsɪŋ ɡɑːrd/', N'người hướng dẫn qua đường', N'noun', N'INTERMEDIATE', N'Education', N'The crossing guard helped students cross safely.', N'Người hướng dẫn giúp học sinh qua đường an toàn.'),
(N'principal''s office', N'/ˈprɪnsəplz ˈɑːfɪs/', N'phòng hiệu trưởng', N'noun', N'INTERMEDIATE', N'Education', N'He was sent to the principal''s office.', N'Anh ấy bị gọi lên phòng hiệu trưởng.'),
(N'substitute teacher', N'/ˈsʌbstɪtuːt ˈtiːtʃər/', N'giáo viên dạy thay', N'noun', N'INTERMEDIATE', N'Education', N'A substitute teacher taught the class today.', N'Một giáo viên dạy thay đã dạy lớp hôm nay.'),
(N'field trip', N'/fiːld trɪp/', N'chuyến đi thực tế', N'noun', N'BEGINNER', N'Education', N'The class went on a field trip to the museum.', N'Lớp học đi thực tế đến viện bảo tàng.'),
(N'show and tell', N'/ʃoʊ ənd tel/', N'giờ giới thiệu đồ vật', N'noun', N'INTERMEDIATE', N'Education', N'She brought her toy for show and tell.', N'Cô bé mang đồ chơi đến giờ giới thiệu đồ vật.'),
(N'spelling bee', N'/ˈspelɪŋ biː/', N'cuộc thi đánh vần', N'noun', N'INTERMEDIATE', N'Education', N'He won the school spelling bee.', N'Anh ấy thắng cuộc thi đánh vần của trường.'),
(N'science fair', N'/ˈsaɪəns fer/', N'hội chợ khoa học', N'noun', N'INTERMEDIATE', N'Education', N'She presented her project at the science fair.', N'Cô ấy trình bày dự án tại hội chợ khoa học.'),
(N'art class', N'/ɑːrt klæs/', N'lớp học vẽ', N'noun', N'BEGINNER', N'Education', N'He painted a picture in art class.', N'Anh ấy vẽ một bức tranh trong lớp học vẽ.'),
(N'music class', N'/ˈmjuːzɪk klæs/', N'lớp học nhạc', N'noun', N'BEGINNER', N'Education', N'They sang songs in music class.', N'Họ hát các bài hát trong lớp học nhạc.'),
(N'gym class', N'/dʒɪm klæs/', N'lớp thể dục', N'noun', N'BEGINNER', N'Education', N'We played basketball in gym class.', N'Chúng tôi chơi bóng rổ trong lớp thể dục.'),
(N'fire drill', N'/ˈfaɪər drɪl/', N'diễn tập phòng cháy', N'noun', N'BEGINNER', N'Education', N'The school held a fire drill this morning.', N'Trường tổ chức diễn tập phòng cháy sáng nay.'),
(N'emergency exit', N'/ɪˈmɜːrdʒənsi ˈeksɪt/', N'cửa thoát hiểm', N'noun', N'BEGINNER', N'General', N'Everyone left through the emergency exit.', N'Mọi người đi ra qua cửa thoát hiểm.'),
(N'smoke detector', N'/smoʊk dɪˈtektər/', N'máy báo khói', N'noun', N'INTERMEDIATE', N'General', N'The smoke detector went off during cooking.', N'Máy báo khói kêu lúc đang nấu ăn.'),
(N'fire extinguisher', N'/ˈfaɪər ɪkˈstɪŋɡwɪʃər/', N'bình chữa cháy', N'noun', N'INTERMEDIATE', N'General', N'He used a fire extinguisher to put out the fire.', N'Anh ấy dùng bình chữa cháy để dập lửa.'),
(N'first aid kit', N'/fɜːrst eɪd kɪt/', N'túi cứu thương', N'noun', N'BEGINNER', N'Health', N'She keeps a first aid kit in the car.', N'Cô ấy để túi cứu thương trong xe.'),
-- Stationery / craft
(N'safety pin', N'/ˈseɪfti pɪn/', N'kim băng', N'noun', N'BEGINNER', N'Education', N'She fastened the badge with a safety pin.', N'Cô ấy gài huy hiệu bằng kim băng.'),
(N'rubber band', N'/ˈrʌbər bænd/', N'dây cao su', N'noun', N'BEGINNER', N'Education', N'He wrapped the papers with a rubber band.', N'Anh ấy buộc mấy tờ giấy bằng dây cao su.'),
(N'sticky note', N'/ˈstɪki noʊt/', N'giấy nhớ', N'noun', N'BEGINNER', N'Education', N'She left a sticky note on the fridge.', N'Cô ấy để một tờ giấy nhớ trên tủ lạnh.'),
(N'index card', N'/ˈɪndeks kɑːrd/', N'thẻ ghi chú', N'noun', N'INTERMEDIATE', N'Education', N'He wrote notes on an index card.', N'Anh ấy viết ghi chú trên thẻ ghi chú.'),
(N'binder clip', N'/ˈbaɪndər klɪp/', N'kẹp bướm', N'noun', N'INTERMEDIATE', N'Education', N'She used a binder clip to hold the papers together.', N'Cô ấy dùng kẹp bướm để giữ các tờ giấy lại.'),
(N'hole puncher', N'/hoʊl ˈpʌntʃər/', N'cái đục lỗ giấy', N'noun', N'INTERMEDIATE', N'Education', N'He used a hole puncher before filing the papers.', N'Anh ấy dùng cái đục lỗ trước khi lưu hồ sơ.'),
(N'pencil sharpener', N'/ˈpensl ˈʃɑːrpənər/', N'cái gọt bút chì', N'noun', N'BEGINNER', N'Education', N'She sharpened her pencil with a pencil sharpener.', N'Cô ấy gọt bút chì bằng cái gọt bút chì.'),
(N'crayon', N'/ˈkreɪɑːn/', N'bút sáp màu', N'noun', N'BEGINNER', N'Education', N'The child drew a sun with a crayon.', N'Đứa trẻ vẽ ông mặt trời bằng bút sáp màu.'),
(N'watercolor paint', N'/ˈwɔːtərkʌlər peɪnt/', N'màu nước', N'noun', N'INTERMEDIATE', N'Education', N'She painted the sky with watercolor paint.', N'Cô ấy vẽ bầu trời bằng màu nước.'),
(N'paintbrush', N'/ˈpeɪntbrʌʃ/', N'cọ vẽ', N'noun', N'BEGINNER', N'Education', N'He cleaned the paintbrush after painting.', N'Anh ấy rửa cọ vẽ sau khi vẽ xong.'),
(N'clay sculpture', N'/kleɪ ˈskʌlptʃər/', N'tác phẩm điêu khắc bằng đất sét', N'noun', N'INTERMEDIATE', N'Education', N'She made a clay sculpture in art class.', N'Cô ấy làm một tác phẩm điêu khắc đất sét trong lớp vẽ.'),
(N'origami', N'/ˌɔːrɪˈɡɑːmi/', N'nghệ thuật gấp giấy', N'noun', N'INTERMEDIATE', N'Education', N'He folded a paper crane using origami.', N'Anh ấy gấp một con hạc giấy bằng nghệ thuật origami.'),
(N'scrapbook', N'/ˈskræpbʊk/', N'sổ lưu niệm dán ảnh', N'noun', N'INTERMEDIATE', N'Education', N'She keeps photos in a scrapbook.', N'Cô ấy lưu ảnh trong sổ lưu niệm.'),
(N'photo album', N'/ˈfoʊtoʊ ˈælbəm/', N'album ảnh', N'noun', N'BEGINNER', N'General', N'They looked through the old photo album.', N'Họ xem lại album ảnh cũ.'),
(N'picture frame', N'/ˈpɪktʃər freɪm/', N'khung ảnh', N'noun', N'BEGINNER', N'Home', N'She put the photo in a picture frame.', N'Cô ấy đặt tấm ảnh vào khung ảnh.'),
(N'bulletin board', N'/ˈbʊlətɪn bɔːrd/', N'bảng thông báo', N'noun', N'INTERMEDIATE', N'Education', N'The notice was posted on the bulletin board.', N'Thông báo được dán trên bảng thông báo.'),
-- Security
(N'name tag', N'/neɪm tæɡ/', N'thẻ tên', N'noun', N'BEGINNER', N'General', N'Every employee wears a name tag.', N'Mỗi nhân viên đều đeo thẻ tên.'),
(N'lanyard', N'/ˈlænjərd/', N'dây đeo thẻ', N'noun', N'INTERMEDIATE', N'General', N'She wore her badge on a lanyard.', N'Cô ấy đeo thẻ bằng dây đeo.'),
(N'security guard', N'/sɪˈkjʊrəti ɡɑːrd/', N'nhân viên bảo vệ', N'noun', N'BEGINNER', N'Work', N'The security guard checked everyone''s bag.', N'Nhân viên bảo vệ kiểm tra túi của mọi người.'),
(N'metal detector', N'/ˈmetl dɪˈtektər/', N'máy dò kim loại', N'noun', N'INTERMEDIATE', N'General', N'Passengers walked through the metal detector.', N'Hành khách đi qua máy dò kim loại.'),
(N'surveillance camera', N'/sərˈveɪləns ˈkæmərə/', N'camera giám sát', N'noun', N'INTERMEDIATE', N'General', N'The store installed a surveillance camera.', N'Cửa hàng lắp một camera giám sát.'),
(N'fire alarm', N'/ˈfaɪər əˈlɑːrm/', N'chuông báo cháy', N'noun', N'INTERMEDIATE', N'General', N'The fire alarm rang loudly.', N'Chuông báo cháy kêu rất to.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('kitchen sink','cutting board','frying pan','saucepan','kettle','toaster','blender','dishwasher','refrigerator','freezer','stove','grill pan','colander','ladle','rolling pin','measuring cup','trash can','recycling bin','laundry basket','iron','ironing board','vacuum cleaner','sponge','dish soap','scrub brush','air freshener','light bulb','extension cord','power outlet','remote control','alarm clock','wall clock','ceiling fan','air conditioner','radiator','staircase','handrail','elevator','escalator','balcony railing','windowsill','rooftop garden','basement stairs','attic ladder','garage door','mail slot','house number','fireplace mantel','street lamp','traffic light','stop sign','speed bump','parking meter','parking lot','gas station','bus stop','train platform','turnstile','vending machine','ATM','bank teller','safe deposit box','piggy bank','coin purse','shopping cart','shopping bag','barcode scanner','cash register','fitting room','mannequin','display window','grocery aisle','checkout line','ticket booth','gift wrap','birthday candle','party hat','balloon animal','confetti','streamers','piñata','wrapping paper','greeting card','thank you note','invitation','guest list','seating chart','wedding ring','engagement ring','bridesmaid','groomsman','best man','maid of honor','flower girl','ring bearer','honeymoon','anniversary','retirement party','graduation cap','diploma','report card','hall pass','locker combination','gym uniform','school bus','crossing guard','principal''s office','substitute teacher','field trip','show and tell','spelling bee','science fair','art class','music class','gym class','fire drill','emergency exit','smoke detector','fire extinguisher','first aid kit','safety pin','rubber band','sticky note','index card','binder clip','hole puncher','pencil sharpener','crayon','watercolor paint','paintbrush','clay sculpture','origami','scrapbook','photo album','picture frame','bulletin board','name tag','lanyard','security guard','metal detector','surveillance camera','fire alarm');
