--liquibase formatted sql

--changeset vocab:071-seed-words-batch61
INSERT INTO words (word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
SELECT v.word, v.pronunciation, v.meaning_vi, v.part_of_speech, v.difficulty, v.category, v.example_sentence, v.example_translation
FROM (VALUES
-- Core everyday vocabulary — high frequency gaps
(N'different', N'/ˈdɪfərənt/', N'khác nhau', N'adjective', N'BEGINNER', N'Descriptive', N'They have different opinions about the plan.', N'Họ có những ý kiến khác nhau về kế hoạch.'),
(N'information', N'/ˌɪnfərˈmeɪʃən/', N'thông tin', N'noun', N'BEGINNER', N'General', N'Please give me more information.', N'Vui lòng cho tôi thêm thông tin.'),
(N'danger', N'/ˈdeɪndʒər/', N'sự nguy hiểm', N'noun', N'BEGINNER', N'General', N'The sign warned about the danger ahead.', N'Tấm bảng cảnh báo về sự nguy hiểm phía trước.'),
(N'error', N'/ˈerər/', N'lỗi', N'noun', N'BEGINNER', N'General', N'The computer showed an error message.', N'Máy tính hiện thông báo lỗi.'),
(N'excuse', N'/ɪkˈskjuːs/', N'lời xin lỗi, lý do bào chữa', N'noun', N'BEGINNER', N'General', N'He gave a good excuse for being late.', N'Anh ấy đưa ra một lý do hay cho việc đến muộn.'),
(N'fancy', N'/ˈfænsi/', N'sang trọng, cầu kỳ', N'adjective', N'BEGINNER', N'Descriptive', N'They ate at a fancy restaurant.', N'Họ ăn ở một nhà hàng sang trọng.'),
(N'gentle', N'/ˈdʒentl/', N'nhẹ nhàng, hiền lành', N'adjective', N'BEGINNER', N'Character', N'She has a gentle voice.', N'Cô ấy có giọng nói nhẹ nhàng.'),
(N'growth', N'/ɡroʊθ/', N'sự tăng trưởng', N'noun', N'BEGINNER', N'General', N'The company saw strong growth this year.', N'Công ty có sự tăng trưởng mạnh trong năm nay.'),
(N'improvement', N'/ɪmˈpruːvmənt/', N'sự cải thiện', N'noun', N'BEGINNER', N'General', N'There is a big improvement in his English.', N'Có sự cải thiện lớn trong tiếng Anh của anh ấy.'),
(N'material', N'/məˈtɪriəl/', N'vật liệu, chất liệu', N'noun', N'BEGINNER', N'General', N'This bag is made of strong material.', N'Chiếc túi này được làm từ chất liệu bền.'),
(N'messy', N'/ˈmesi/', N'lộn xộn, bừa bãi', N'adjective', N'BEGINNER', N'Descriptive', N'His room is always messy.', N'Phòng của anh ấy luôn bừa bãi.'),
(N'middle', N'/ˈmɪdl/', N'phần giữa, chính giữa', N'noun', N'BEGINNER', N'General', N'She sat in the middle of the row.', N'Cô ấy ngồi ở giữa hàng ghế.'),
(N'normal', N'/ˈnɔːrml/', N'bình thường', N'adjective', N'BEGINNER', N'Descriptive', N'It is normal to feel nervous before a test.', N'Cảm thấy lo lắng trước kỳ thi là điều bình thường.'),
(N'opinion', N'/əˈpɪnjən/', N'ý kiến', N'noun', N'BEGINNER', N'General', N'What is your opinion on this topic?', N'Ý kiến của bạn về chủ đề này là gì?'),
(N'opposite', N'/ˈɑːpəzɪt/', N'trái ngược, đối diện', N'adjective', N'BEGINNER', N'Descriptive', N'Love and hate are opposite feelings.', N'Yêu và ghét là những cảm xúc trái ngược.'),
(N'power', N'/ˈpaʊər/', N'sức mạnh, quyền lực', N'noun', N'BEGINNER', N'General', N'Knowledge gives you power.', N'Kiến thức mang lại cho bạn sức mạnh.'),
(N'safety', N'/ˈseɪfti/', N'sự an toàn', N'noun', N'BEGINNER', N'General', N'Wear a helmet for your own safety.', N'Đội mũ bảo hiểm để đảm bảo an toàn cho bạn.'),
(N'secret', N'/ˈsiːkrət/', N'bí mật', N'noun', N'BEGINNER', N'General', N'She kept the secret for years.', N'Cô ấy giữ bí mật đó trong nhiều năm.'),
(N'silly', N'/ˈsɪli/', N'ngớ ngẩn', N'adjective', N'BEGINNER', N'Character', N'That was a silly mistake.', N'Đó là một lỗi ngớ ngẩn.'),
(N'smart', N'/smɑːrt/', N'thông minh, khôn ngoan', N'adjective', N'BEGINNER', N'Character', N'She is a smart student.', N'Cô ấy là một học sinh thông minh.'),
(N'special', N'/ˈspeʃl/', N'đặc biệt', N'adjective', N'BEGINNER', N'Descriptive', N'Today is a special day for our family.', N'Hôm nay là một ngày đặc biệt với gia đình chúng tôi.'),
(N'straight', N'/streɪt/', N'thẳng', N'adjective', N'BEGINNER', N'Descriptive', N'Draw a straight line here.', N'Vẽ một đường thẳng ở đây.'),
(N'style', N'/staɪl/', N'phong cách', N'noun', N'BEGINNER', N'General', N'She has her own style of dressing.', N'Cô ấy có phong cách ăn mặc riêng.'),
(N'usual', N'/ˈjuːʒuəl/', N'thường lệ, thông thường', N'adjective', N'BEGINNER', N'Descriptive', N'He arrived at the usual time.', N'Anh ấy đến vào giờ thường lệ.'),
(N'lie', N'/laɪ/', N'lời nói dối', N'noun', N'BEGINNER', N'General', N'He told a lie to avoid trouble.', N'Anh ấy nói dối để tránh rắc rối.'),
-- Intermediate abstract nouns / adjectives
(N'agreement', N'/əˈɡriːmənt/', N'sự đồng ý, thỏa thuận', N'noun', N'INTERMEDIATE', N'General', N'They finally reached an agreement.', N'Cuối cùng họ đã đạt được thỏa thuận.'),
(N'alternative', N'/ɔːlˈtɜːrnətɪv/', N'sự lựa chọn khác', N'noun', N'INTERMEDIATE', N'General', N'We need to find an alternative plan.', N'Chúng ta cần tìm một kế hoạch thay thế.'),
(N'antique', N'/ænˈtiːk/', N'đồ cổ', N'adjective', N'INTERMEDIATE', N'Descriptive', N'She collects antique furniture.', N'Cô ấy sưu tập đồ nội thất cổ.'),
(N'central', N'/ˈsentrəl/', N'trung tâm, chủ chốt', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Trust is central to any relationship.', N'Niềm tin là điều cốt lõi trong mọi mối quan hệ.'),
(N'characteristic', N'/ˌkærəktəˈrɪstɪk/', N'đặc điểm', N'noun', N'INTERMEDIATE', N'General', N'Patience is one of her characteristics.', N'Kiên nhẫn là một trong những đặc điểm của cô ấy.'),
(N'commitment', N'/kəˈmɪtmənt/', N'sự cam kết', N'noun', N'INTERMEDIATE', N'General', N'He showed great commitment to his job.', N'Anh ấy thể hiện sự cam kết lớn với công việc.'),
(N'component', N'/kəmˈpoʊnənt/', N'thành phần, bộ phận', N'noun', N'INTERMEDIATE', N'General', N'Trust is a key component of teamwork.', N'Niềm tin là thành phần quan trọng của làm việc nhóm.'),
(N'concept', N'/ˈkɑːnsept/', N'khái niệm', N'noun', N'INTERMEDIATE', N'General', N'The concept of time is different in physics.', N'Khái niệm thời gian trong vật lý là khác biệt.'),
(N'decline', N'/dɪˈklaɪn/', N'suy giảm, từ chối', N'verb', N'INTERMEDIATE', N'General', N'Sales began to decline last quarter.', N'Doanh số bắt đầu suy giảm vào quý trước.'),
(N'depth', N'/depθ/', N'độ sâu', N'noun', N'INTERMEDIATE', N'General', N'The pool has a depth of two meters.', N'Bể bơi có độ sâu hai mét.'),
(N'development', N'/dɪˈveləpmənt/', N'sự phát triển', N'noun', N'INTERMEDIATE', N'General', N'The city has seen rapid development.', N'Thành phố đã có sự phát triển nhanh chóng.'),
(N'disaster', N'/dɪˈzæstər/', N'thảm họa', N'noun', N'INTERMEDIATE', N'General', N'The flood was a natural disaster.', N'Lũ lụt là một thảm họa tự nhiên.'),
(N'economy', N'/ɪˈkɑːnəmi/', N'nền kinh tế', N'noun', N'INTERMEDIATE', N'Business', N'The economy grew slowly this year.', N'Nền kinh tế tăng trưởng chậm trong năm nay.'),
(N'fault', N'/fɔːlt/', N'lỗi, khuyết điểm', N'noun', N'INTERMEDIATE', N'General', N'It was not her fault.', N'Đó không phải lỗi của cô ấy.'),
(N'finance', N'/ˈfaɪnæns/', N'tài chính', N'noun', N'INTERMEDIATE', N'Business', N'She studies finance at university.', N'Cô ấy học tài chính ở đại học.'),
(N'foolish', N'/ˈfuːlɪʃ/', N'dại dột, ngu ngốc', N'adjective', N'INTERMEDIATE', N'Character', N'It was foolish to ignore the warning.', N'Việc bỏ qua cảnh báo là dại dột.'),
(N'former', N'/ˈfɔːrmər/', N'trước đây, cựu', N'adjective', N'INTERMEDIATE', N'Time', N'He is the former president of the company.', N'Anh ấy là cựu chủ tịch của công ty.'),
(N'incident', N'/ˈɪnsɪdənt/', N'sự việc, vụ việc', N'noun', N'INTERMEDIATE', N'General', N'Police are investigating the incident.', N'Cảnh sát đang điều tra vụ việc.'),
(N'industry', N'/ˈɪndəstri/', N'ngành công nghiệp', N'noun', N'INTERMEDIATE', N'Business', N'He works in the tech industry.', N'Anh ấy làm việc trong ngành công nghệ.'),
(N'limitation', N'/ˌlɪmɪˈteɪʃən/', N'sự hạn chế', N'noun', N'INTERMEDIATE', N'General', N'Everyone has their own limitations.', N'Ai cũng có những hạn chế riêng của mình.'),
(N'miracle', N'/ˈmɪrəkl/', N'phép màu', N'noun', N'INTERMEDIATE', N'General', N'It was a miracle that she survived.', N'Việc cô ấy sống sót là một phép màu.'),
(N'mission', N'/ˈmɪʃən/', N'nhiệm vụ, sứ mệnh', N'noun', N'INTERMEDIATE', N'General', N'The team completed its mission successfully.', N'Nhóm hoàn thành nhiệm vụ một cách thành công.'),
(N'occasion', N'/əˈkeɪʒən/', N'dịp, sự kiện', N'noun', N'INTERMEDIATE', N'General', N'They only meet on special occasions.', N'Họ chỉ gặp nhau vào những dịp đặc biệt.'),
(N'overall', N'/ˌoʊvərˈɔːl/', N'nói chung, tổng thể', N'adjective', N'INTERMEDIATE', N'General', N'The overall result was positive.', N'Kết quả tổng thể là tích cực.'),
(N'pace', N'/peɪs/', N'nhịp độ, tốc độ', N'noun', N'INTERMEDIATE', N'General', N'He walked at a fast pace.', N'Anh ấy đi bộ với nhịp độ nhanh.'),
(N'phase', N'/feɪz/', N'giai đoạn', N'noun', N'INTERMEDIATE', N'General', N'The project is in its final phase.', N'Dự án đang ở giai đoạn cuối.'),
(N'preference', N'/ˈprefərəns/', N'sự ưu tiên, ưa thích', N'noun', N'INTERMEDIATE', N'General', N'She has a preference for quiet places.', N'Cô ấy có sự ưa thích với những nơi yên tĩnh.'),
(N'requirement', N'/rɪˈkwaɪərmənt/', N'yêu cầu', N'noun', N'INTERMEDIATE', N'General', N'The job has strict requirements.', N'Công việc có những yêu cầu nghiêm ngặt.'),
(N'response', N'/rɪˈspɑːns/', N'sự phản hồi, phản ứng', N'noun', N'INTERMEDIATE', N'General', N'We are waiting for their response.', N'Chúng tôi đang chờ phản hồi của họ.'),
(N'restriction', N'/rɪˈstrɪkʃən/', N'sự hạn chế, giới hạn', N'noun', N'INTERMEDIATE', N'General', N'There are restrictions on parking here.', N'Có những hạn chế về việc đỗ xe ở đây.'),
(N'sample', N'/ˈsæmpl/', N'mẫu thử', N'noun', N'INTERMEDIATE', N'General', N'She gave us a free sample of the perfume.', N'Cô ấy cho chúng tôi mẫu thử nước hoa miễn phí.'),
(N'saving', N'/ˈseɪvɪŋ/', N'sự tiết kiệm, tiền để dành', N'noun', N'INTERMEDIATE', N'Business', N'He put his savings into the bank.', N'Anh ấy gửi tiền tiết kiệm vào ngân hàng.'),
(N'spare', N'/sper/', N'dự phòng, dư ra', N'adjective', N'INTERMEDIATE', N'Descriptive', N'Keep a spare key at your neighbor''s house.', N'Giữ một chìa khóa dự phòng ở nhà hàng xóm.'),
(N'status', N'/ˈsteɪtəs/', N'tình trạng, địa vị', N'noun', N'INTERMEDIATE', N'General', N'Check the status of your order online.', N'Kiểm tra tình trạng đơn hàng của bạn trực tuyến.'),
(N'territory', N'/ˈterətɔːri/', N'lãnh thổ', N'noun', N'INTERMEDIATE', N'Places', N'The animal marked its territory.', N'Con vật đánh dấu lãnh thổ của nó.'),
(N'tragedy', N'/ˈtrædʒədi/', N'bi kịch', N'noun', N'INTERMEDIATE', N'General', N'The accident was a real tragedy.', N'Vụ tai nạn là một bi kịch thật sự.'),
(N'weird', N'/wɪrd/', N'kỳ lạ, quái dị', N'adjective', N'INTERMEDIATE', N'Descriptive', N'That noise sounds really weird.', N'Tiếng động đó nghe thật kỳ lạ.'),
-- Advanced / formal vocabulary
(N'latter', N'/ˈlætər/', N'cái sau, phần sau', N'adjective', N'ADVANCED', N'Time', N'Of the two options, I prefer the latter.', N'Trong hai lựa chọn, tôi thích phần sau hơn.'),
(N'obligation', N'/ˌɑːblɪˈɡeɪʃən/', N'nghĩa vụ', N'noun', N'ADVANCED', N'General', N'Parents have an obligation to protect their children.', N'Cha mẹ có nghĩa vụ bảo vệ con cái.'),
(N'regulation', N'/ˌreɡjuˈleɪʃən/', N'quy định', N'noun', N'ADVANCED', N'Business', N'The factory must follow safety regulations.', N'Nhà máy phải tuân theo các quy định an toàn.'),
(N'transformation', N'/ˌtrænsfərˈmeɪʃən/', N'sự biến đổi', N'noun', N'ADVANCED', N'General', N'The city underwent a major transformation.', N'Thành phố đã trải qua một sự biến đổi lớn.'),
(N'transition', N'/trænˈzɪʃən/', N'sự chuyển đổi, giai đoạn chuyển tiếp', N'noun', N'ADVANCED', N'General', N'The transition to adulthood can be difficult.', N'Giai đoạn chuyển tiếp sang tuổi trưởng thành có thể khó khăn.')
) AS v(word, pronunciation, meaning_vi, part_of_speech, difficulty, category, example_sentence, example_translation)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE w.word = v.word);

--rollback DELETE FROM words WHERE word IN ('different','information','danger','error','excuse','fancy','gentle','growth','improvement','material','messy','middle','normal','opinion','opposite','power','safety','secret','silly','smart','special','straight','style','usual','lie','agreement','alternative','antique','central','characteristic','commitment','component','concept','decline','depth','development','disaster','economy','fault','finance','foolish','former','incident','industry','limitation','miracle','mission','occasion','overall','pace','phase','preference','requirement','response','restriction','sample','saving','spare','status','territory','tragedy','weird','latter','obligation','regulation','transformation','transition');
