spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:sqlserver://localhost;databaseName=vocab_db;encrypt=false;trustServerCertificate=true
    username: sa
    password: "123456"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

  liquibase:
    enabled: false

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000  # 24 hours in ms
  gemini:
    api-key: AIzaSyA2f5cKAN7Oz6MXnh--xVwlTNzJhZbP-Ao

server:
  port: 8080

logging:
  level:
    com.vocab: DEBUG
    org.springframework.security: INFO
